### ISSUE TITLE
Refactor update methods to use single DataUpdateCoordinator

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#1]
>Home Assistant provides a DataUpdateCoordinator class to help you manage this as efficiently as possible.

https://developers.home-assistant.io/docs/integration_fetching_data/

- [ ] Use event listener from python-tahoma-api
- [ ] Add RestoreEntity

**Comment by iMicknl** [comment]
Not sure if this is possible, since it looks like it is only possible to retrieve state on a per device basis.

**Comment by vlebourl** [comment]
get_states takes a list of devices that could be retrieved from get_devices, all from the api. Then it's a question of mapping back to the entities.

**Comment by vlebourl** [comment]
`api.get_states(api.get_devices().values())`

**Comment by iMicknl** [comment]
This is currently blocked, until we have a new async API implementation which leverage event listeners as well. This will require a rewrite of the whole state mechanism.

**Comment by iMicknl** [comment]
Unblocked by #160
