### ISSUE TITLE
Add support for internal:PodMiniComponent

### ISSUE THREAD

**Issue by cdeharo** [iMicknl/ha-tahoma#104]
**Device information**
Doesn't having this device doesn't seems to affect my awning or solar sensor. The other device I have is a wind sensor which closes the awning if it detects vibration, but I'm not able to control this device using the Connexoon Terrace Android app, I don't know if it is connected to the Connexoon gateway.

In order to avoid error logs I have this device excluded from the core integration as I stated in [this comment](https://github.com/home-assistant/core/issues/37131#issuecomment-652628733).

**Device details**
Sorry, I can't access the `https://www.tahomalink.com/enduser-mobile-web/steer-html5-client/tahoma/` to get the details of the device. I'm using the same credentials that I use in this platform, but the web reports an error (maybe because I own a Connexoon and not a Tahoma).

**Debug log registered in Home Assistant logs**
```
2020-07-05 10: 50: 01 DEBUG (MainThread) [custom_components.tahoma] Unsupported Tahoma device (internal:PodMiniComponent). Create an issue on Github with the following information. 
```
```JSON
internal:PodMiniComponent - Pod - Pod 
[
    {
        "commandName": "getName",
        "nparams": 0
    },
    {
        "commandName": "update",
        "nparams": 0
    },
    {
        "commandName": "setCountryCode",
        "nparams": 1
    },
    {
        "commandName": "activateCalendar",
        "nparams": 0
    },
    {
        "commandName": "deactivateCalendar",
        "nparams": 0
    },
    {
        "commandName": "refreshPodMode",
        "nparams": 0
    },
    {
        "commandName": "refreshUpdateStatus",
        "nparams": 0
    },
    {
        "commandName": "setCalendar",
        "nparams": 1
    },
    {
        "commandName": "setLightingLedPodMode",
        "nparams": 1
    },
    {
        "commandName": "setPodLedOff",
        "nparams": 0
    },
    {
        "commandName": "setPodLedOn",
        "nparams": 0
    }
],
[
    {
        "values": [
            "offline",
            "online"
        ],
        "type": "DiscreteState",
        "qualifiedName": "core:ConnectivityState"
    },
    {
        "type": "DataState",
        "qualifiedName": "core:CountryCodeState"
    },
    {
        "type": "DataState",
        "qualifiedName": "core:LocalIPv4AddressState"
    },
    {
        "type": "DataState",
        "qualifiedName": "core:NameState"
    },
    {
        "values": [
            "doublePress",
            "longPress",
            "simplePress",
            "triplePress",
            "veryLongPress"
        ],
        "type": "DiscreteState",
        "qualifiedName": "internal:LastActionConfigButtonState"
    },
    {
        "type": "ContinuousState",
        "qualifiedName": "internal:LightingLedPodModeState"
    }
]
``` 

**Environment**
 - **Home Assistant version**: 0.112.2
 - **Platform**: Somfy TaHoma 1.5 (custom component)

**Comment by iMicknl** [comment]
Thanks for reporting, @cdeharo! The `PodMiniComponent` doesn't have any commands that are really useful in Home Assistant. Or do you have a use-case for the `setPodLedOn` / `setPodLedOff`? Or would you like to use the input from a button press of the 'pod'?

The `Unsupported Tahoma device` message will only be shown in debug mode, thus this won't have any consequences for 'normal' users.

**Comment by jensihnow** [comment]
I believe the input of the button press would be good to be implemented. It could call a scenario or scene if available.

**Comment by iMicknl** [comment]
Not sure how realtime `internal:LastActionConfigButtonState` is, but it should have the following possibilities. Should it be mapped to a sensor? Since a `binary_sensor` is just a boolean, and this pod could have multiple options.

```
"doublePress",
"longPress",
"simplePress",
"triplePress",
"veryLongPress"
```

**Comment by vlebourl** [comment]
I would map it to a remote. But I don't think we have that yet in the component.

**Comment by cdeharo** [comment]
>Or do you have a use-case for the setPodLedOn / setPodLedOff?
Sorry, I don't know where I have this `PodMiniComponent` in my awning gadgets... I don't know how I can use this button because I don't know where it is.

My Somfy components are:
* Motor Somfy IO
* Connexoon
* SUNIS IO
* [Eolis 3D](https://www.somfysystems.com/en-us/products/1816081/eolis-3d-wirefree-rts)

**Comment by iMicknl** [comment]
@cdeharo I am not sure about the Connexoon, but the Somfy TaHoma module has a (touch?) button and can show a status led. However, this device is most of the time hidden somewhere, thus I don't see a use-case for this.

![image](https://user-images.githubusercontent.com/1424596/86615141-56d46500-bfb4-11ea-8269-e056eeafd8b2.png)

**Comment by cdeharo** [comment]
Yes, I agree that this device is always hidden. Maybe in the Connexoon module this button is the PROG one and the LED in the right:
![image](https://user-images.githubusercontent.com/12809819/86621356-5771f900-bfbe-11ea-8e40-9f4053fd5e0c.png)

I don't think I'm never going to use this buttons and LED in my HA automations ;-)

**Comment by iMicknl** [comment]
This device has been added to the ignore list in the integration, thus not spamming your debug log anymore.

I will close this issue for now since there is no intention of supporting this device in Home Assistant, as discussed. :-)
