### ISSUE TITLE
Refactor constants and strings

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#110]
- [x] Move constants from `consts.py` to the platform files if they are only used there
- [x] Add constants for all strings, especially in `binary_sensor`, `cover` and `switch`
- [x] Utilise f strings instead of .format() ([core comment](https://github.com/home-assistant/core/pull/36258#issuecomment-637720333))
- [x] Add helper functions for retrieving state and calling commands, eliminating all the if statements

**Comment by tetienne** [comment]
> Add helper functions for retrieving state and calling commands, eliminating all the if statements

IMO it must be done in another issue. Otherwise, it will increase the size of your PR and made difficult to review it.

**Comment by vlebourl** [comment]
Second tick by #126
