### ISSUE TITLE
Remove (or document) offset for covers

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#112]
**Is your feature request related to a problem? Please describe.**
There is an open TODO in `cover.py` related to an offset that will be added to the position. This is coming from the original component and we are not sure why. https://github.com/iMicknl/ha-tahoma/blob/dd3a5c67035e591429071439b818ca991dca6122/custom_components/tahoma/cover.py#L133-L137

**Describe the solution you'd like**
This should be removed or properly documented.

**Comment by vlebourl** [comment]
this might relate to some of the problems mentioned here: #103

**Comment by tetienne** [comment]
I've been removed with https://github.com/iMicknl/ha-tahoma/pull/148
