### ISSUE TITLE
Hcs PROBLEM

### ISSUE THREAD

**Issue by Lupick** [iMicknl/ha-tahoma#130]
**Describe the bug**
 I've just added https://github.com/imicknl/ha-tahoma to my hassio HACCS but in the logs I get:
-07-08 06:25:02 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove
20-07-08 06:31:33 INFO (MainThread) [supervisor.store.git] Clone add-on https://github.com/imicknl/ha-tahoma repository
20-07-08 06:31:36 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/93152bd9/repository.json: [Errno 2] No such file or directory: '/data/addons/git/93152bd9/repository.json'
20-07-08 06:31:36 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/93152bd9/repository.json
20-07-08 06:31:36 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove

Maybe somthings wrong in github repo configurations?

**To Reproduce**
1. add https://github.com/imicknl/ha-tahoma to HACS config
2. check the logs

**Comment by tetienne** [comment]
I just try right now using the latest HACS version (1.1.2) and the latest HA version (0.112.3). I haven't any error in the log. Which version are you using?

**Comment by Lupick** [comment]
I'm on Home Assistant 0.112.3 . Wehere I've to check for HACS version? I'm using hassio:

arch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.11
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7
python_version | 3.7.7
supervisor | 228
timezone | Europe/Rome
version | 0.112.3
virtualenv | false

**Comment by iMicknl** [comment]
If you open the HACS page, you should have an 'About' button, which will show the version of HACS. 

To be sure, I would advise to download the latest HACS version and install it.

**Comment by Lupick** [comment]
I've just reinstalled hacs and now it's working.
