### ISSUE TITLE
io:CyclicGarageOpenerIOComponent not accessible by services, automations, and has status unknown

### ISSUE THREAD

**Issue by francodutch** [iMicknl/ha-tahoma#146]
**Describe the bug**
I have installed the following Somfy [device](Physical device: https://www.somfy.fr/produits/1841229/recepteur-acces-compatible-io) which allows opening and closing of garage door via dry contact. Even if this is IO device, state cannot be fed back because the interface to the garage door motor is via dry contact (up/stop/down/stop/etc).

The device is recognised as a garage door opener and created in HA, but no actions (scropts/automations/status) are possible.

**To Reproduce**
1. Go to '.Configuration / Integration / Tahoma Integration Devices '
2. Click on 'right_garage_door'
3. Click on the plus sign next to "automations"
4. Message:
"Create automation with device
There are no automations available for this device."

**Expected behaviour**
Ability to create automations like with any other Tahoma component. 

**Log entry**
Logger: homeassistant.components.cover.reproduce_state
Source: components/cover/reproduce_state.py:51
Integration: Cover (documentation, issues)
First occurred: 17:06:03 (1 occurrences)
Last logged: 17:06:03
Invalid state specified for cover.right_garage_door: unknown

**Environment (please complete the following information):**
 - **Home Assistant version:** 0.112.4
 - **Platform**: Tahoma

**Device:** Cyclic Garage Door
 - **Model**: dry contact remote, enables to toggle existing garage door opener
 - **Type**: [e.g. `io:DimmableLightIOComponent`, can be gathered from device page in HA looking at Firmware] `/config/devices/dashboard`]
 - **Device details**

```json
{
   "creationTime":1594134595000,
   "lastUpdateTime":1594134595000,
   "label":"Left Garage Door",
   "deviceURL":"###",
   "shortcut":false,
   "controllableName":"io:CyclicGarageOpenerIOComponent",
   "definition":{
      "commands":[
         {
            "commandName":"cycle",
            "nparams":0
         },
         {
            "commandName":"delayedStopIdentify",
            "nparams":1
         },
         {
            "commandName":"getName",
            "nparams":0
         },
         {
            "commandName":"identify",
            "nparams":0
         },
         {
            "commandName":"setName",
            "nparams":1
         },
         {
            "commandName":"startIdentify",
            "nparams":0
         },
         {
            "commandName":"stopIdentify",
            "nparams":0
         },
         {
            "commandName":"wink",
            "nparams":1
         },
         {
            "commandName":"pairOneWayController",
            "nparams":2
         },
         {
            "commandName":"unpairAllOneWayControllers",
            "nparams":0
         },
         {
            "commandName":"unpairOneWayController",
            "nparams":2
         }
      ],
      "states":[
         {
            "values":[
               "good",
               "low",
               "normal",
               "verylow"
            ],
            "type":"DiscreteState",
            "qualifiedName":"core:DiscreteRSSILevelState"
         },
         {
            "type":"DataState",
            "qualifiedName":"core:NameState"
         },
         {
            "type":"ContinuousState",
            "qualifiedName":"core:PriorityLockTimerState"
         },
         {
            "type":"ContinuousState",
            "qualifiedName":"core:RSSILevelState"
         },
         {
            "values":[
               "available",
               "unavailable"
            ],
            "type":"DiscreteState",
            "qualifiedName":"core:StatusState"
         },
         {
            "values":[
               "comfortLevel1",
               "comfortLevel2",
               "comfortLevel3",
               "comfortLevel4",
               "environmentProtection",
               "humanProtection",
               "userLevel1",
               "userLevel2"
            ],
            "type":"DiscreteState",
            "qualifiedName":"io:PriorityLockLevelState"
         },
         {
            "values":[
               "LSC",
               "SAAC",
               "SFC",
               "UPS",
               "externalGateway",
               "localUser",
               "myself",
               "rain",
               "security",
               "temperature",
               "timer",
               "user",
               "wind"
            ],
            "type":"DiscreteState",
            "qualifiedName":"io:PriorityLockOriginatorState"
         }
      ],
      "dataProperties":[
         {
            "value":"500",
            "qualifiedName":"core:identifyInterval"
         }
      ],
      "widgetName":"CyclicGarageDoor",
      "uiClass":"GarageDoor",
      "qualifiedName":"io:CyclicGarageOpenerIOComponent",
      "type":"ACTUATOR"
   },
   "states":[
      {
         "name":"core:NameState",
         "type":3,
         "value":"Left Garage Door"
      },
      {
         "name":"core:PriorityLockTimerState",
         "type":1,
         "value":0
      },
      {
         "name":"core:StatusState",
         "type":3,
         "value":"available"
      },
      {
         "name":"core:DiscreteRSSILevelState",
         "type":3,
         "value":"good"
      },
      {
         "name":"core:RSSILevelState",
         "type":2,
         "value":84.0
      }
   ],
   "available":true,
   "enabled":true,
   "placeOID":"###",
   "widget":"CyclicGarageDoor",
   "type":1,
   "oid":"###",
   "uiClass":"GarageDoor"
}
```

**Additional context**

**Comment by tetienne** [comment]
On the created entity, what's actions are currently available?

**Comment by iMicknl** [comment]
This is due to this device only supporting `cycle`. We currently don't have support for `cycle` in the cover platform, but we have in the switch platform.

I will have a look if this could be supported in cover platform as well, or if your specific device should be remapped to the switch platform.

**Comment by vlebourl** [comment]
as there is no state feedback, I'd say mapping it to a switch would make the most sense.

**Comment by tetienne** [comment]
Or just override the toggle method from the cover entity: https://github.com/home-assistant/core/blob/dev/homeassistant/components/cover/__init__.py#L261

As the ui class is GarageDoor it will avoid to create different use cases.

**Comment by iMicknl** [comment]
Still an issue. Best way would be to make sure `assumed_state` is `True` for cover devices where position is not known. And to map `cycle` to on + off as the last option.

**Comment by francodutch** [comment]
I'm afraid the cover.toggle service still has no effect, neither does any of the other cover related services. Also, in the configuration/entities list, clicking on the entity where it shows device info, scenes, automations, scripts etc, clicking on the plus for a new automation gives the message "There are no automations available for this device."

**Comment by iMicknl** [comment]
@francodutch which version of the integration are you using currently? If you are using the latest master, could you try https://github.com/iMicknl/ha-tahoma/releases/tag/v1.6.4 for now.

**Comment by francodutch** [comment]
> @francodutch which version of the integration are you using currently? If you are using the latest master, could you try https://github.com/iMicknl/ha-tahoma/releases/tag/v1.6.4 for now.
> > I'm on 1.6.4
> And what if you call cover.toggle() directly in your automation, via the service?
> > tried via a script but nothing happens.. I have some entries in the error log that occurred two hours after the last time I tried yesterday, but those seem related to a connection to tahomalink to update the status rather than to the issue with the service. nothing at all in the log after running the script again...am I missing something?

**Comment by francodutch** [comment]
by the way via the service directly nothing happens either.

**Comment by iMicknl** [comment]
@francodutch could you try https://github.com/iMicknl/ha-tahoma/tree/fix/146_2?

**Comment by iMicknl** [comment]
Should be solved in latest master. https://github.com/iMicknl/ha-tahoma/tree/master

In case it still doesn't work, let me know and we can reopen it.
