### ISSUE TITLE
Support for interior_blind_positionable_stateful_roof

### ISSUE THREAD

**Issue by ppenders** [iMicknl/ha-tahoma#149]
Hi,

Could you add support for: interior_blind_positionable_stateful_roof ?

Thanks,

Perry

**Comment by vlebourl** [comment]
Hi, thank you for your report. Could you provide us with details on the device you'd like to see added?

**Device information**
A clear and concise description of the device, together with specific use cases that you would like to see supported.

**Device details**
Please follow the instructions here: https://github.com/totalimmersion/com.somfy.tahoma/files/2755935/Instructions.for.the.TaHoma.devices.pdf to gather more details of the device and post them below_

```json
[PASTE DEVICE DETAILS HERE]
```

**Comment by ppenders** [comment]
Support for open, close, stop and position would be great!

"creationTime":1564554730000,
         "lastUpdateTime":1564554730000,
         "label":"Dakraam Master",
         "deviceURL":"
         "shortcut":false,
         "controllableName":"io:VerticalInteriorBlindVeluxIOComponent",
         "definition":{
            "commands":[
               {
                  "commandName":"close",
                  "nparams":0
               },
               {
                  "commandName":"delayedStopIdentify",
                  "nparams":1
               },
               {
                  "commandName":"down",
                  "nparams":0
               },
               {
                  "commandName":"getName",
                  "nparams":0
               },
               {
                  "commandName":"identify",
                  "nparams":0
               },
               {
                  "commandName":"my",
                  "nparams":0
               },
               {
                  "commandName":"open",
                  "nparams":0
               },
               {
                  "commandName":"refreshMemorized1Position",
                  "nparams":0
               },
               {
                  "commandName":"setClosure",
                  "nparams":1
               },
               {
                  "commandName":"setMemorized1Position",
                  "nparams":1
               },
               {
                  "commandName":"setName",
                  "nparams":1
               },
               {
                  "commandName":"setPosition",
                  "nparams":1
               },
               {
                  "commandName":"setSecuredPosition",
                  "nparams":1
               },
               {
                  "commandName":"startIdentify",
                  "nparams":0
               },
               {
                  "commandName":"stop",
                  "nparams":0
               },
               {
                  "commandName":"stopIdentify",
                  "nparams":0
               },
               {
                  "commandName":"up",
                  "nparams":0
               },
               {
                  "commandName":"wink",
                  "nparams":1
               },
               {
                  "commandName":"pairOneWayController",
                  "nparams":2
               },
               {
                  "commandName":"unpairAllOneWayControllers",
                  "nparams":0
               },
               {
                  "commandName":"unpairOneWayController",
                  "nparams":2
               }
            ],
            "states":[
               {
                  "type":"ContinuousState",
                  "qualifiedName":"core:ClosureState"
               },
               {
                  "values":[
                     "good",
                     "low",
                     "normal",
                     "verylow"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"core:DiscreteRSSILevelState"
               },
               {
                  "type":"ContinuousState",
                  "qualifiedName":"core:Memorized1PositionState"
               },
               {
                  "type":"DataState",
                  "qualifiedName":"core:NameState"
               },
               {
                  "values":[
                     "closed",
                     "open"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"core:OpenClosedState"
               },
               {
                  "type":"ContinuousState",
                  "qualifiedName":"core:PriorityLockTimerState"
               },
               {
                  "type":"ContinuousState",
                  "qualifiedName":"core:RSSILevelState"
               },
               {
                  "type":"ContinuousState",
                  "qualifiedName":"core:SecuredPositionState"
               },
               {
                  "values":[
                     "available",
                     "unavailable"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"core:StatusState"
               },
               {
                  "values":[
                     "comfortLevel1",
                     "comfortLevel2",
                     "comfortLevel3",
                     "comfortLevel4",
                     "environmentProtection",
                     "humanProtection",
                     "userLevel1",
                     "userLevel2"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"io:PriorityLockLevelState"
               },
               {
                  "values":[
                     "LSC",
                     "SAAC",
                     "SFC",
                     "UPS",
                     "externalGateway",
                     "localUser",
                     "myself",
                     "rain",
                     "security",
                     "temperature",
                     "timer",
                     "user",
                     "wind"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"io:PriorityLockOriginatorState"
               }
            ],
            "dataProperties":[
               {
                  "value":"500",
                  "qualifiedName":"core:identifyInterval"
               }
            ],
            "widgetName":"PositionableTiltedScreen",
            "uiClass":"Screen",
            "qualifiedName":"io:VerticalInteriorBlindVeluxIOComponent",
            "type":"ACTUATOR"
         },
         "states":[
            {
               "name":"core:NameState",
               "type":3,
               "value":"Dakraam Master"
            },
            {
               "name":"core:PriorityLockTimerState",
               "type":1,
               "value":0
            },
            {
               "name":"core:StatusState",
               "type":3,
               "value":"available"
            },
            {
               "name":"core:DiscreteRSSILevelState",
               "type":3,
               "value":"normal"
            },
            {
               "name":"core:RSSILevelState",
               "type":2,
               "value":62.0
            },
            {
               "name":"core:ClosureState",
               "type":1,
               "value":93
            },
            {
               "name":"core:OpenClosedState",
               "type":3,
               "value":"open"
            }
         ],
         "available":true,
         "enabled":true,
         "placeOID":"xyz",
         "widget":"PositionableTiltedScreen",
         "type":1,
         "oid":"xyz",
         "uiClass":"Screen"

**Comment by vlebourl** [comment]
Thanks. Could you try this branch? https://github.com/iMicknl/ha-tahoma/tree/fix/fix_149

Download and extract this zip: https://github.com/iMicknl/ha-tahoma/archive/fix/fix_149.zip

Replace your tahoma folder installed with HACS by the one in the zip, restart HA and let us know if that works.

**Comment by ppenders** [comment]
Hi!

Thank you for your swift response. I've tested and it works like a charm :)

Thanks,

Perry
