### ISSUE TITLE
Cover fails to get current_cover_position for device 'rts:GenericRTSComponent' 

### ISSUE THREAD

**Issue by vlebourl** [iMicknl/ha-tahoma#155]
This device is an RTS micro module to command covers, but as it is rts it doesn't have state return, hence the failure...
This device should be mapped as a switch probably...

**Comment by vlebourl** [comment]
uiClass is `Generic`

**Comment by iMicknl** [comment]
I believe this should still be mapped to a cover, since it is a cover device. We already set `assumed_state` to True for RTS devices. It should be possible to have a cover without a position.

How do other components do this?

**Comment by iMicknl** [comment]
https://github.com/iMicknl/ha-tahoma/blob/34b6832f554d02f8455814fbc8e51aa92388ab02/custom_components/tahoma/cover.py#L103

Maybe recent changes have caused this? It should return None when there is no position available?

**Comment by vlebourl** [comment]
yes, it's quite recent, the addition of helper functions

**Comment by tetienne** [comment]
Yes indeed, we forgot to handle the None case.
