### ISSUE TITLE
Add support for Gate - DiscreteGateWithPedestrianPosition (io:DiscreteGateOpenerIOComponent)

### ISSUE THREAD

**Issue by francodutch** [iMicknl/ha-tahoma#18]
Following from [this thread](https://community.home-assistant.io/t/re-additional-supported-device-types-tahoma-plafform/201961?u=luckydutchie):

```json
{
"creationTime":1577640280000,
"lastUpdateTime":1577640280000,
"label":"Gate",
"deviceURL":"####",
"shortcut":false,
"controllableName":"io:DiscreteGateOpenerIOComponent",
"definition":{
"commands":[
{
"commandName":"close",
"nparams":0
},
{
"commandName":"delayedStopIdentify",
"nparams":1
},
{
"commandName":"getName",
"nparams":0
},
{
"commandName":"identify",
"nparams":0
},
{
"commandName":"open",
"nparams":0
},
{
"commandName":"refreshPedestrianPosition",
"nparams":0
},
{
"commandName":"setName",
"nparams":1
},
{
"commandName":"setPedestrianPosition",
"nparams":0
},
{
"commandName":"startIdentify",
"nparams":0
},
{
"commandName":"stop",
"nparams":0
},
{
"commandName":"stopIdentify",
"nparams":0
},
{
"commandName":"wink",
"nparams":1
}
],
"states":[
{
"type":"DataState",
"qualifiedName":"core:NameState"
},
{
"values":[
"closed",
"open",
"pedestrian",
"unknown"
],
"type":"DiscreteState",
"qualifiedName":"core:OpenClosedPedestrianState"
},
{
"type":"ContinuousState",
"qualifiedName":"core:PedestrianPositionState"
},
{
"type":"ContinuousState",
"qualifiedName":"core:PriorityLockTimerState"
},
{
"type":"ContinuousState",
"qualifiedName":"core:RSSILevelState"
},
{
"values":[
"available",
"unavailable"
],
"type":"DiscreteState",
"qualifiedName":"core:StatusState"
},
{
"values":[
"comfortLevel1",
"comfortLevel2",
"comfortLevel3",
"comfortLevel4",
"environmentProtection",
"humanProtection",
"userLevel1",
"userLevel2"
],
"type":"DiscreteState",
"qualifiedName":"io:PriorityLockLevelState"
},
{
"values":[
"LSC",
"SAAC",
"SFC",
"UPS",
"externalGateway",
"localUser",
"myself",
"rain",
"security",
"temperature",
"timer",
"user",
"wind"
],
"type":"DiscreteState",
"qualifiedName":"io:PriorityLockOriginatorState"
}
],
"dataProperties":[
{
"value":"500",
"qualifiedName":"core:identifyInterval"
}
],
"widgetName":"DiscreteGateWithPedestrianPosition",
"uiClass":"Gate",
"qualifiedName":"io:DiscreteGateOpenerIOComponent",
"type":"ACTUATOR"
},
"states":[
{
"name":"core:NameState",
"type":3,
"value":"Gate"
},
{
"name":"core:PriorityLockTimerState",
"type":1,
"value":0
},
{
"name":"core:OpenClosedPedestrianState",
"type":3,
"value":"closed"
},
{
"name":"core:StatusState",
"type":3,
"value":"available"
},
{
"name":"core:RSSILevelState",
"type":2,
"value":50.0
},
{
"name":"core:PedestrianPositionState",
"type":1,
"value":50
}
],
"attributes":[

     ],
     "available":true,
     "enabled":true,
     "placeOID":"####",
     "widget":"DiscreteGateWithPedestrianPosition",
     "type":1,
     "oid":"####",
     "uiClass":"Gate"
  },
```

**Comment by iMicknl** [comment]
Basis support for gates has been added and is pre-published as [1.1-alpha release](https://github.com/iMicknl/ha-tahoma/releases/tag/1.1-alpha) on Github and HACS.

- If you manually want to install the package, download the zip [here](https://github.com/iMicknl/ha-tahoma/releases/tag/1.1-alpha).
- If you use HACS, make sure you enable `Show beta versions` and select `1.1-alpha`. If you have a previous version installed already, press re-install to install the beta.

Could you give it a try and report your findings?

**Comment by iMicknl** [comment]
Current positions needs to be tweaked for some gates. 

>yes. but for a swing gate with two parts...50 makes little sense when it's closed

**Comment by francodutch** [comment]
gate opens initially but errors as follows:
Log Details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection.2806510768
Source: custom_components/tahoma/tahoma_api.py:55
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:27:40 (1 occurrences)
Last logged: 16:27:40

Could not login: Too many requests, try again later : login with ####

**Comment by iMicknl** [comment]
@francodutch this is related to #24. Unfortunately the original implementation has not been super well written in regards to API usage. We are improving this, however for now, sometimes this will mean you get locked out after doing a lot of requests in a short timeframe.

**Comment by vlebourl** [comment]
Bummer... you have to wait 10 to 15 minutes... restart HA once the wait is over.

**Comment by francodutch** [comment]
![image](https://user-images.githubusercontent.com/65336159/83892278-b558ba00-a74e-11ea-9bc5-805f921adb63.png)

**Comment by francodutch** [comment]
other than above gate opens and closes well

**Comment by francodutch** [comment]
Just noticed that if gate opened/closed with remote control, status change is not registered in HA. The automatic closing after having been open for 1 minute isn't either. This looks like a Tahoma problem: seems like Tahoma doesn't get the state changes when initiated outside Tahoma.

**Comment by iMicknl** [comment]
Basic gate support has been added, your bug above has been added as #33 and #40.

**Comment by NicoLeOca** [comment]
Hi @iMicknl 
I would like to control the pedestrian mode of my "DiscreteGareWithPedetrianPosition".
Is it supported already?
Thanks
NicoLeOca

**Comment by NicoLeOca** [comment]
Merci @tetienne 
That would be great definitely!
