### ISSUE TITLE
Add support for OccupancySensor (io:SomfyOccupancyIOSystemSensor)

### ISSUE THREAD

**Issue by francodutch** [iMicknl/ha-tahoma#19]
these sensors are ideal to trigger actions (presence/movement sensor):

```json
{
"creationTime":1544905637000,
"lastUpdateTime":1544905637000,
"label":"Movement Kitchen",
"deviceURL":"io://###",
"shortcut":false,
"controllableName":"io:SomfyOccupancyIOSystemSensor",
"definition":{
"commands":[
],
"states":[
{
"eventBased":true,
"values":[
"noPersonInside",
"personInside"
],
"type":"DiscreteState",
"qualifiedName":"core:OccupancyState"
},
{
"type":"ContinuousState",
"qualifiedName":"core:RSSILevelState"
},
{
"values":[
"dead",
"lowBattery",
"maintenanceRequired",
"noDefect"
],
"type":"DiscreteState",
"qualifiedName":"core:SensorDefectState"
},
{
"values":[
"available",
"unavailable"
],
"type":"DiscreteState",
"qualifiedName":"core:StatusState"
}
],
"dataProperties":[

        ],
        "widgetName":"OccupancySensor",
        "uiClass":"OccupancySensor",
        "qualifiedName":"io:SomfyOccupancyIOSystemSensor",
        "type":"SENSOR"
     },
     "states":[
        {
           "name":"core:OccupancyState",
           "type":3,
           "value":"noPersonInside"
        },
        {
           "name":"core:StatusState",
           "type":3,
           "value":"available"
        },
        {
           "name":"core:RSSILevelState",
           "type":2,
           "value":78.0
        }
     ],
     "attributes":[
        {
           "name":"core:PowerSourceType",
           "type":3,
           "value":"battery"
        }
     ],
     "available":true,
     "enabled":true,
     "placeOID":"####",
     "widget":"OccupancySensor",
     "type":2,
     "oid":"#####",
     "uiClass":"OccupancySensor"
  }

**Comment by iMicknl** [comment]
Support for this `OccupancySensor` has been added and is pre-published as [1.1-alpha release](https://github.com/iMicknl/ha-tahoma/releases/tag/1.1-alpha) on Github and HACS.

- If you manually want to install the package, download the zip [here](https://github.com/iMicknl/ha-tahoma/releases/tag/1.1-alpha).
- If you use HACS, make sure you enable `Show beta versions` and select `1.1-alpha`. If you have a previous version installed already, press re-install to install the beta.

**Comment by francodutch** [comment]
A few log entries:

First:
Logger: custom_components.tahoma
Source: custom_components/tahoma/__init__.py:94
Integration: Tahoma (documentation)
First occurred: 13:14:30 (7 occurrences)
Last logged: 13:14:30

Unsupported Tahoma device (internal:PodV2Component - Pod - Pod)
Unsupported Tahoma device (io:SomfyIndoorSimpleSirenIOComponent - Siren - IOSiren)
Unsupported Tahoma device (jsw:CameraController - Camera - JSWCamera)
Unsupported Tahoma device (rtd:OutdoorSirenRTDComponent - Siren - RTDOutdoorSiren)
Unsupported Tahoma device (rtds:SirenStatusRTDSComponent - Siren - SirenStatus)

Second:
Log Details (ERROR)
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:163
First occurred: 13:14:30 (4 occurrences)
Last logged: 13:14:30

Error setting up entry luchennekens@gmail.com for binary_sensor
Error setting up entry luchennekens@gmail.com for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 139, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 163, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
Connection lost. Reconnecting…

Third:
Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 13:14:31 (1 occurrences)
Last logged: 13:14:31

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for tahoma doing I/O at custom_components/tahoma/tahoma_api.py, line 581: timeout=10)
Connection lost. Reconnecting…

**Comment by iMicknl** [comment]
Thanks!

Is your occupancy sensor working? Your first log entries are by default and are here to show you that possibly more devices could be integrated in the future.

Your second log entry are related to #16.

Your third log entries are related to #2.

**Comment by iMicknl** [comment]
@francodutch can we close this one? It looks like the occopancy sensor is working and that your log entries are related to other issues?

**Comment by francodutch** [comment]
> @francodutch can we close this one? It looks like the occopancy sensor is working and that your log entries are related to other issues?

yes sure sorry for the late reply I have been offline for a while. thanks

**Comment by iMicknl** [comment]
@francodutch no worries. Thank you for testing.
