### ISSUE TITLE
Error fetching TaHoma Event Fetcher data: Error communicating with the TaHoma API: None

### ISSUE THREAD

**Issue by thijsdejong** [iMicknl/ha-tahoma#191]
**Describe the bug**
Error fetching TaHoma Event Fetcher data: Error communicating with the TaHoma API: None

**To Reproduce**

1. Start HomeAssistant

**Expected behavior**
No error :)

**Environment (please complete the following information):**

- **Home Assistant version:** 0.113.2

**Device:** (if your problem is related to a specific device)

Using version 1ef0944

Just reporting this in case it's useful

**Comment by iMicknl** [comment]
Thanks for reporting @thijsdejong. I have faced this as well, and I believe @tetienne and @vlebourl also. In my installation, it only happens once every 15 times approximately. 

https://github.com/iMicknl/ha-tahoma/blob/1ef09448093c917f3bb4f5b1b1e6538519034397/custom_components/tahoma/coordinator.py#L44-L49

However, what I couldn't figure out yet is that the exception is `None`. That would mean that it probably is a general exception, where `message` has an empty value. We would need to add better error messages to the [pyhoma client](https://github.com/iMicknl/python-tahoma-api).

https://github.com/iMicknl/python-tahoma-api/blob/e00b472ac772701bc1573ff5f9c05ab177bb5498/pyhoma/client.py#L223-L228

**Comment by tetienne** [comment]
I'm facing the same issue too. 23 times in less than 1 hours.

First occurred: 22:06:04 (23 occurrences)
Last logged: 22:40:51

**Comment by vlebourl** [comment]
First occurred: 17:09:09 (44 occurrences)
Last logged: 22:52:21

**Comment by iMicknl** [comment]
Using debugpy, I found out that the actual exception is `ServerDisconnectedError(None)`. Could it be that we do multiple concurrent requests using the same session?

**Comment by tetienne** [comment]
This is strange, if we were really disconnected from the server, the next update should fail too. This is not the case.

**Comment by iMicknl** [comment]
@tetienne most of the issues I can find mention that we need to close the connection. Apparently the remote API server closes our request, if we have to many open connections. The next update will start a new connection which will work, until the server does close it again.

We need to see if adding close does something with our performance.

>HTTP keep-alive allows the same connection to be used for multiple requests, which can improve performance, especially over HTTPS, where the connection handshake can be lengthy. But the server may have a limit as to how long it's willing to keep the connection alive or how many requests it will accept on the same connection. When the limit runs out, it closes the connection.

https://github.com/aio-libs/aiohttp/issues/850#issuecomment-471663047

**Comment by tetienne** [comment]
The tahomalink website set the header Connection: keep-alive, I will update our library to do the same. 

```
curl 'https://www.tahomalink.com/enduser-mobile-web/enduserAPI/events/xxxxxxxxx/fetch' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0' -H 'Accept: */*' -H 'Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3' --compressed -H 'X-Requested-With: XMLHttpRequest' -H 'Origin: https://www.tahomalink.com' -H 'Connection: keep-alive' -H 'Referer: https://www.tahomalink.com/enduser-mobile-web/steer-html5-client/tahoma/' -H 'Cookie: JSESSIONID=xxxxxxxxx' --data-raw ''
```

**Comment by tetienne** [comment]
See https://github.com/iMicknl/python-tahoma-api/pull/26 for a potential fix.

**Comment by tetienne** [comment]
I've updated the poll interval to 10 seconds, and for half an hour, still no error.

**Comment by thijsdejong** [comment]
> See [iMicknl/python-tahoma-api#26](https://github.com/iMicknl/python-tahoma-api/pull/26) for a potential fix.

How would I go about testing that version of the dependency on my installation? Do you have any guide that could help me out?

**Comment by tetienne** [comment]
@thijsdejong I think my fix is useless. Try to update this value from 5 to 10: https://github.com/iMicknl/ha-tahoma/blob/master/custom_components/tahoma/__init__.py#L18

**Comment by thijsdejong** [comment]
> @thijsdejong I think my fix is useless. Try to update this value from 5 to 10: https://github.com/iMicknl/ha-tahoma/blob/master/custom_components/tahoma/__init__.py#L18

Hmm I found a way to use a git repo as a dependency and applied your fix. As I responded in the PR it SHOULD not do anything, but I have not had the error since.

Also just want to say amazing job on the updating of states. I have 26 roller shutters / windows connected to tahoma, and there would always be an incredible amount of timeouts. So far on this new version no error messages at all!

**Comment by thijsdejong** [comment]
@tetienne I have done some more research and it seems a workaround for this is actually **disabling** keepalive. It's a workaround that sacrifices some speed but eliminates the problem of connections being closed by the server when they are open too long.

https://github.com/aio-libs/aiohttp/issues/850#issuecomment-471663047

**Comment by tetienne** [comment]
@thijsdejong In fact just increasing the poll interval from 5 to 10 seems enough. For 3 hours, I have 0 error. No need to update our library.
