### ISSUE TITLE
Stop command doesn't work for some cover devices

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#204]
**Describe the bug**
Currently the cover implementation relies on the available commands of a cover device. However, when a `stop` command is present, it doesn't mean that the `stop` command is functional. (thanks Somfy 👍🏻)

https://github.com/iMicknl/ha-tahoma/blob/23eaec1a7f6c9cc776d857ec45bbadca4d206bf0/custom_components/tahoma/cover.py#L217-L221

**To Reproduce**

1. Open or close cover
2. Press stop button
3. Cover device doesn't stop moving

**Additional context**
The integration is not consistent in how it handles a stop command. For example, for the `cover_tilt` mainly used by Pergolas, we first execute `COMMAND_STOP_IDENTIFY` since `STOP` didn't work for my own device...

https://github.com/iMicknl/ha-tahoma/blob/23eaec1a7f6c9cc776d857ec45bbadca4d206bf0/custom_components/tahoma/cover.py#L223-L227

Best would be to:

First use `COMMAND_STOP_IDENTIFY` or `COMMAND_MY` to stop a moving cover. This needs to be thoroughly tested to ensure it doesn't cause problems with covers that are not experiencing this issue.

**OR**

Make sure entities can set their preferred stop method via `customize.yaml`, as a workaround. I am not a fan of having all those device specific if statements in the integration.

**Environment (please complete the following information):**
- **Platform**: cover

**Device:** (if your problem is related to a specific device)
- AwningComponent (io:HorizontalAwningIOComponent) (see #59 
- ExteriorScreen (rts:ExteriorBlindRTSComponent) (see #43)

**Comment by Glenn1986** [comment]
@iMicknl can I help with testing for this problem. I have RTS roller shutters and the stop command doesn't work?

**Comment by iMicknl** [comment]
@Glenn1986 are you familiar with Developer Tools in your browser? Could you capture which XHR requests happen when you open the cover and cancel the command?

**Comment by Glenn1986** [comment]
Oke I will try, do you mean the xhr request in home assistant or in tahomalink? I think the last one but want to be sure ;)

**Comment by vlebourl** [comment]
yes tahomalink!

**Comment by Glenn1986** [comment]
Hope this information helps you guys
`{execution: {eventTime: 1599025157127, owner: "xxxxxx", source: "mobile:mobile",…}}
execution: {eventTime: 1599025157127, owner: "xxxx", source: "mobile:mobile",…}
commands: [,…]
0: {deviceURL: "rts://1222-8124-6958/16745869", command: "close", parameters: [], rank: 0, dynamic: false,…}
command: "close"
deviceURL: "rts://1222-8124-6958/16745869"
dynamic: false
**failureType: "CMDCANCELLED"**
parameters: []
rank: 0
state: "FAILED"
duration: 7825
effectiveStartTime: 1599025157127
endTime: 1599025164952
eventTime: 1599025157127
executionSubType: "MANUAL_CONTROL"
executionType: "Immediate execution"
failureType: "CMDCANCELLED"
id: "4d539405-ac10-3e01-2775-8dbbaf803366"
label: "Slaapkamer 3.1 - Sluiten - TaHoma PC"
owner: "xxxx"
source: "mobile:mobile"
state: "FAILED"
type: "Immediate execution - MANUAL_CONTROL"`

**Comment by iMicknl** [comment]
Thanks @Glenn1986. Could you have a look if the previous request is a `DELETE` request? I will start working on it this weekend probably, so will soon have a version to test.

**Comment by Glenn1986** [comment]
Request URL: https://www.tahomalink.com/enduser-mobile-web/enduserAPI/exec/current/setup/4e440f95-ac10-3e01-2775-8dbb10e9de74
Request Method: DELETE
Status Code: 204 
Remote Address: xxxx
Referrer Policy: no-referrer-when-downgrade

It's indeed a delete request before above information is received. :)

**Comment by iMicknl** [comment]
Great to hear! I have implemented a first try in https://github.com/iMicknl/ha-tahoma/tree/enhancement/improve_stop_functionality, could you give it a try?

You can download this zip https://github.com/iMicknl/ha-tahoma/archive/enhancement/improve_stop_functionality.zip and extract the tahoma folder to your `custom_components` folder. Please delete the old one first to make sure you don't have any left overs.

**Comment by Glenn1986** [comment]
Hi @iMicknl. I did the test with the new version you made but didn't work. Gives me the error: Kan service cover/stop_cover niet aanroepen 'TahomaCover' object has no attribute 'debug'.

**Comment by iMicknl** [comment]
@Glenn1986 oops, I made an obvious mistake. It is fixed in the latest version.
I can try this myself this Sunday the earliest unfortunately.

**Comment by iMicknl** [comment]
@Glenn1986 you could download the zip again and retry :)

**Comment by Glenn1986** [comment]
@iMicknl i tested again and now it worked. The rollershutter stopped but he gives on error: Kan service cover/stop_cover niet aanroepen 'NoneType' object has no attribute 'get'.

**Comment by iMicknl** [comment]
Cool! I will have a look myself and polish it up a bit, but great to know that the stop functionality is finally working for you.

**Comment by iMicknl** [comment]
@Glenn1986 if you could try the latest version and report if this solved your issues, would be appreciated 👍🏻

**Comment by Glenn1986** [comment]
@iMicknl i just tested your new version. Everything worked well and no errors showing up. Nice work!

**Comment by Glenn1986** [comment]
@iMicknl in which release will you're fix for stop command cover released?

**Comment by iMicknl** [comment]
@Glenn1986 it depends a little bit on the code review, I expect it to go out with a release in the next week. I will close this issue once it is merged to master, so you will get a notification :-).

**Comment by Glenn1986** [comment]
Thanks!

**Comment by golles** [comment]
I was about to report this bug, as I noticed it today, now I see a fix has been merged 12 hours ago. It works for my RTS awning, well done!!

**Comment by iMicknl** [comment]
@golles thanks for first looking at closed issues / pr's 😄! This PR took a bit longer to get merged, but I will do a new release soon with some more fixes. 

For now, you could install the latest master via HACS or manually.

**Comment by golles** [comment]
Great to hear that you're so active! I bought the Tahoma box recently and I'm really happy to see that you and the others rewrite this component.
I manually pull the master branch into my custom_components, I try to update all my dependencies a couple of times per week :-) 
Looking forward to what's coming!
