### ISSUE TITLE
Log is not containing all the devices I have.

### ISSUE THREAD

**Issue by larsvinc** [iMicknl/ha-tahoma#207]
First, let me praise the new integration. This is really needed. I want to help any way I can!

I have a Tahoma system with 6 devices - 4 window covers, 1 external cover, and a terrasse heater.
Additionally the Tahoma box came with a remote. You can see all of them here on my home screen in the app:
https://photos.app.goo.gl/zTDpDrQGemzWNNVC7

All of the devices (except the remote) support the same set of buttons: on, off and "My" (see screenshot)

However when I use the integration (version 2.0) I only get the 4 window cover and the external cover, not the terrasse heater and the remote.

I have enabled logging, but I am not seeing the other devices in the log:
2020-08-06 10:48:20 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for tahoma which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-08-06 10:48:31 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.040 seconds
2020-08-06 10:48:41 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.159 seconds
2020-08-06 10:48:51 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.146 seconds

How can I make sure that all the devices are indeed in the log?

**Comment by vlebourl** [comment]
Hi, Thank you for the report. So far we haven't added any remote to the component as most of them don't add any value over directly controlling the device itself. For instance I own a remote that opens or closes the smart lock, but adding the remote to HA is useless as I can directly control the lock through the component. 

Regarding the heater, I suspect it could be detected as something else than a climate device. Can you confirm that you have only 5 devices in the integration page? (sorry if the question seems dumb, sometimes, we do have to go to the very basics)

![image](https://user-images.githubusercontent.com/5701372/89513856-69210900-d7d5-11ea-90a8-338167b547d8.png)

**Comment by vlebourl** [comment]
Can you also have a look at this https://github.com/totalimmersion/com.somfy.tahoma/files/2089039/Instructions.for.the.TaHoma.devices.pdf
and report the details concerning the heating device?

**Comment by iMicknl** [comment]
I made some changes to the debug logging in 2.0.0, so I would need to have a look why it is not printing anything in your case.. I had a look at the code and I can understand why your Heating Device is not visible, however the remote should be visible for sure.

Are you sure they are not present in the list? (/config/devices/dashboard) (see screenshot from above).

@vlebourl regarding the climate device. We should not match `HeatingSystem` and `ExteriorHeatingSystem` to climate, if climate only supports three specific widget classes. This should be matched to those widgets only, or preferably a better fallback in device for generic heating devices.

**Comment by vlebourl** [comment]
Hey back, just to be clear, is that what you call the remote?
![image](https://user-images.githubusercontent.com/5701372/89520068-9b366900-d7dd-11ea-9dc9-da16626c8dfe.png)

**Comment by vlebourl** [comment]
partly fixed by #209.
Can you install master in hacs and restart HA? The climate device should appear in the logs as unsupported.

**Comment by larsvinc** [comment]
Hi! Thanks for the swift comments.

First, 2.0.1 made the climate device appear in the logs:
2020-08-06 18:21:51 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for tahoma which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-08-06 18:22:01 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.042 seconds
2020-08-06 18:22:01 DEBUG (MainThread) [custom_components.tahoma] Unsupported TaHoma device detected (rts:ExteriorHeatingRTSComponent - ExteriorHeatingSystem - StatelessExteriorHeating)

The outdoor heating uses the same remote as the others with arrow down (off), arrow (up) on, and "My" which is less heat. I am curious how this is exposed by tahoma. This is the heater:
https://www.somfy.me/en-gc/products/1810876/heating-modulis-ramp-rts-

"Fjernkontroll" is indeed the remote control. I have two types of remotes:

1. This guy who came with the blinds: https://www.somfysystems.com/en-us/products/1810633/telis-rts
I believe these directly communicate with the blinds / heater, and as such cannot be used for HA.

2. This guy who came with the hub: https://www.somfy.co.uk/products/2401370/tahoma-remote-control
This is the one that shows up in the app. 
I understand why one could argue that it is not worth exposing. At the same time, it is a device with 5 buttons that could be used / programmed to do a variety of things in HA. So if they could natively be exposed as buttons, it would be a plus in my books.

Let me know how I can further contribute.

**Comment by vlebourl** [comment]
Thanks, I'll add the heater to the supported devices, maybe tomorrow, otherwise next week. 
Regarding the remote, indeed the first one isn't exposed. 
I believe the second one isn't the one you mentioned, but the physical button present on the tahoma box. The 5 buttons remote is a remote dedicated to the security part of the tahoma box, and isn't exposed either.

**Comment by vlebourl** [comment]
Mine is called "active button" and only has 1 button
![Screenshot_20200806-193542](https://user-images.githubusercontent.com/5701372/89563677-17e83800-d81c-11ea-92f1-86184459a187.jpg)

**Comment by larsvinc** [comment]
I realized that my button is the same. I fully agree that adding the button on the box makes no sense whatsoever.

Thanks for the swift feedback. Let me know when I should test a new version!

**Comment by iMicknl** [comment]
@larsvinc could you perhaps open a new issue (unsupported device)? In that issue we can track your exterior terrace heater :-).

```
2020-08-06 18:22:01 DEBUG (MainThread) [custom_components.tahoma] Unsupported TaHoma device detected (rts:ExteriorHeatingRTSComponent - ExteriorHeatingSystem - StatelessExteriorHeating)
``

**Comment by larsvinc** [comment]
@iMicknl Done :)
