### ISSUE TITLE
Add support for TSKAlarmController (internal:TSKAlarmComponent)

### ISSUE THREAD

**Issue by Glenn1986** [iMicknl/ha-tahoma#212]
Since the siren has been added, we have the option to build our own alarm system in home assistant with somfy sensors. But why invent hot water if it already exists. Via the TSKAlarmComponent we can use the alarm system from somfy itself. This system is already used with the tahoma version in openHab. Via a selection method we can activate the alarm or monitor certain zones. Somfy will then automatically look at its sensors and sound the alarm in case of movement. Via the api of somfy you can receive alarm signals and generate actions in home assistant.

**Comment by tetienne** [comment]
Hi,thx for this feature request. Using your Tahoma can you manipulate the alarm system?

**Comment by iMicknl** [comment]
@tetienne this Alarm Component is present in all Tahoma installations, however most of the time it is not used / disabled.

I already have a working prototype which I will publish this week. I am looking into disabling this entity by default. But I would like to understand if there is something in the state that reflects the use of this 'device'.

**Comment by tetienne** [comment]
Yes I can see it in my setup response. However I have no idea on how manipulate it through the Tahomalink website.

**Comment by iMicknl** [comment]
```
{
	"commands": [{
		"commandName": "alarmOff",
		"nparams": 0
	}, {
		"commandName": "alarmOn",
		"nparams": 0
	}, {
		"commandName": "getName",
		"nparams": 0
	}, {
		"commandName": "off",
		"nparams": 0
	}, {
		"commandName": "on",
		"nparams": 0
	}, {
		"commandName": "setName",
		"nparams": 1
	}, {
		"commandName": "refreshAlarmDelay",
		"nparams": 0
	}, {
		"commandName": "refreshCurrentAlarmMode",
		"nparams": 0
	}, {
		"commandName": "refreshIntrusionDetected",
		"nparams": 0
	}, {
		"commandName": "setAlarmDelay",
		"nparams": 1
	}, {
		"commandName": "alarmPartial1",
		"nparams": 0
	}, {
		"commandName": "alarmPartial2",
		"nparams": 0
	}, {
		"commandName": "setIntrusionDetected",
		"nparams": 1
	}, {
		"commandName": "setTargetAlarmMode",
		"nparams": 1
	}],
	"states": [{
		"type": "DataState",
		"qualifiedName": "core:NameState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "internal:AlarmDelayState"
	}, {
		"values": ["off", "partial1", "partial2", "total"],
		"type": "DiscreteState",
		"qualifiedName": "internal:CurrentAlarmModeState"
	}, {
		"values": ["detected", "notDetected", "pending", "sos"],
		"type": "DiscreteState",
		"qualifiedName": "internal:IntrusionDetectedState"
	}, {
		"values": ["off", "partial1", "partial2", "sos", "total"],
		"type": "DiscreteState",
		"qualifiedName": "internal:TargetAlarmModeState"
	}],
	"dataProperties": [],
	"widgetName": "TSKAlarmController",
	"uiClass": "Alarm",
	"qualifiedName": "internal:TSKAlarmComponent",
	"type": "ACTUATOR"
}
```

**Comment by iMicknl** [comment]
First version is available via https://github.com/iMicknl/ha-tahoma/archive/enhancement/add_alarm_integration.zip. Please unzip the file and place the `tahoma` folder in your `custom_components` folder to test.

Looking for feedback @PoVPoV29, @WhistleMaster, Glenn1986. :-). In case anything is not working correctly, have a look at the logs and share the state information from `/developer-tools/state`.

**Comment by Glenn1986** [comment]
Hi @iMicknl I just tested the alarm panel and it worked very well for me. My siren gives the tone that the alarm will be activated and when I set it off he asks me if I want to put it off. Everything worked just fine. Thanks men great work!!!
I will use it for a while and do automations with it and let you know if I find a problem.

**Comment by iMicknl** [comment]
Great to hear @Glenn1986! We will probably disable this alarm entity by default, since every Somfy TaHoma user has this alarm, but it is not always used and officially supported. This will prevent confusion by users.

Behavior in my case is:
- I can arm (away, night, home) the alarm
- I can disarm the alarm
- I see the pending status in between

But when I open the security tab on tahomalink.com, it shows a small message with 'deactivating alarm' and it will disarm my alarm. Probably since I don't pay for it / don't have hardware supporting it. It makes more sense for me (and similar users) to have this entity disabled and to create a software defined alarm control panel in HA.

Could you share some of the states you see for this alarm? Would be great to understand if we can see in any way if the security module is enabled.

**Comment by Glenn1986** [comment]
OK, I hope this helps you. In my tahoma app I already setup the time he most wait by before he armed the alarm. That gives me the time to leave the house. When I look to the logs I see that when I activate the alarm by clicking on the away button that he turns on the siren. That because I setup in tahoma app that he most gives a peep sound when the alarm is pending. So he gives a peep not really the alarm sound. This peep sound is activated for 45 sec (my own choise). The alarm changed from disarmed to pending. After the 45 sec the siren turns of and the alarm changed to armed_away. Now the alarm is on and looks to my sensors. When I click the button to set the alarm off he changes the alarm to disarmed immediately.

- 9:35:25: Alarm changed to disarmed

- 9:35:05: Alarm changed to armed_away

- 9:35:05: Siren io turned off

- 9:34:05: Alarm changed to pending

- 9:34:05: Siren io turned on

Sorry for my bad english.
Do you want the logs when he finds movement and activate the alarm to?

**Comment by iMicknl** [comment]
@Glenn1986 thanks! Would be good if you could share your states from `/developer-tools/state` once. I wonder if you have more states than me available. 

```
code_format: null
changed_by: null
code_arm_required: true
ui_class: Alarm
widget: TSKAlarmController
controllable_name: internal:TSKAlarmComponent
core:NameState: alarm name
internal:CurrentAlarmModeState: off
internal:AlarmDelayState: 30
internal:TargetAlarmModeState: off
internal:IntrusionDetectedState: notDetected
friendly_name: Alarm
supported_features: 7
```

And no worries, your English is fine ;-).

**Comment by Glenn1986** [comment]
Ok my alarm is now active and this is the state that I have.
`code_format: null
changed_by: null
code_arm_required: true
ui_class: Alarm
widget: TSKAlarmController
controllable_name: 'internal:TSKAlarmComponent'
'core:NameState': alarm name
'internal:CurrentAlarmModeState': total
'internal:AlarmDelayState': 60
'internal:TargetAlarmModeState': total
'internal:IntrusionDetectedState': notDetected
friendly_name: Alarm
supported_features: 7`

I hope this helped. After the weekend I will try to make automations with the alarm.

**Comment by Glenn1986** [comment]
Hi @iMicknl I did a bit of testing this weekend. I wasn't able to test automations with the alarm because when the alarm goes off he gives no entitie feedback. I know that in the openhab version you had feedback of the state of the alarm and correct me if I'm wrong but I thought that you can see which zone was detected motion. But setting on and off the alarm is working good :) If I can help you with something let me know.

**Comment by iMicknl** [comment]
@Glenn1986 could you share your states when the alarm has been triggered? Currently we check if `core:IntrusionState` is `detected`, but maybe this value will be different when triggered?

**Comment by Glenn1986** [comment]
State when alarm is armed_away:
`code_format: null
changed_by: null
code_arm_required: true
ui_class: Alarm
widget: TSKAlarmController
controllable_name: 'internal:TSKAlarmComponent'
'core:NameState': alarm name
'internal:CurrentAlarmModeState': total
'internal:AlarmDelayState': 60
'internal:TargetAlarmModeState': total
'internal:IntrusionDetectedState': notDetected
friendly_name: Alarm
supported_features: 7`

State when alarm is detected:
`code_format: null
changed_by: null
code_arm_required: true
ui_class: Alarm
widget: TSKAlarmController
controllable_name: 'internal:TSKAlarmComponent'
'core:NameState': alarm name
'internal:CurrentAlarmModeState': total
'internal:AlarmDelayState': 60
'internal:TargetAlarmModeState': total
'internal:IntrusionDetectedState': pending
friendly_name: Alarm
supported_features: 7
`

States when the alarm goes off:
`code_format: null
changed_by: null
code_arm_required: true
ui_class: Alarm
widget: TSKAlarmController
controllable_name: 'internal:TSKAlarmComponent'
'core:NameState': alarm name
'internal:CurrentAlarmModeState': total
'internal:AlarmDelayState': 60
'internal:TargetAlarmModeState': total
'internal:IntrusionDetectedState': detected
friendly_name: Alarm
supported_features: 7
`

Strange if I see the state of the IntrusionDetectedState it is correct but I can't catch this via the automation.
Maybe I most look further for a solution.

Another question, the alarm is operable via the alarm_control_panel.alarm. What is good, but I would like to use a pincode to arm the alarm. That is posible via the manual alarm. I created one but armed the somfy alarm didn't work. Do you know what I do wrong. This is the yaml code that I created:
`# Alarm panel for somfy alarm
alarm_control_panel:
  - platform: manual
    name: Alarmcentrale
    code: 'xxxx'
    arming_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0`

Thanks for you time. I'm a noob, still learning HA :)

**Comment by iMicknl** [comment]
The state for your alarm should be triggered indeed, when it goes off. Are you not able to create an automation to check if alarm == triggered?

You can not use states like `IntrusionDetectedState` directly in automations, since we just show them for debugging purposes. However if the state is `detected` we map it to `triggered` in Home Assistant. And we also support `pending` state in HA.

I am not sure if you can add a code.. The Somfy TaHoma panel doesn't allow a code, thus I am not sure if you can let HA add a code. I haven't used the alarm control panel myself yet.

**Comment by Glenn1986** [comment]
Thanks that was the solution. I'm able to do actions when my alarm goes of with this code:
`device_id: e146cd3c959341b9ad13820c9c2bca63
domain: alarm_control_panel
entity_id: alarm_control_panel.alarm
platform: device
type: triggered`

Thanks for your help. I will try to find more info for the manual alarm so I can use a pincode to arm the alarm. When I find that I will post it later.
Conclusion: everything works fine :)
