### ISSUE TITLE
Add support for MyFoxAlarmController (myfox:SomfyProtectAlarmController)

### ISSUE THREAD

**Issue by lseufer** [iMicknl/ha-tahoma#215]
- Alarm - MyFoxAlarmController

**Device information**
Myfox/SomfyProtect Alarm

**Device details**
myfox:SomfyProtectAlarmController - Alarm - MyFoxAlarmController"

**Comment by iMicknl** [comment]
Thanks @lseufer! It looks like there are multiple Myfox devices that have similar commands available. I will try to support them all at once. 

```
{
	"commands": [{
		"commandName": "arm",
		"nparams": 0
	}, {
		"commandName": "disarm",
		"nparams": 0
	}, {
		"commandName": "partial",
		"nparams": 0
	}, {
		"commandName": "refreshAlarmStatus",
		"nparams": 0
	}, {
		"commandName": "setAlarmStatus",
		"nparams": 1
	}],
	"states": [{
		"values": ["down", "up"],
		"type": "DiscreteState",
		"qualifiedName": "core:PowerSupplyUpDownState"
	}, {
		"values": ["armed", "disarmed", "partial"],
		"type": "DiscreteState",
		"qualifiedName": "myfox:AlarmStatusState"
	}, {
		"type": "DataState",
		"qualifiedName": "myfox:AlertTrespassState"
	}],
	"dataProperties": [],
	"widgetName": "MyFoxAlarmController",
	"uiClass": "Alarm",
	"qualifiedName": "myfox:AlarmController",
	"type": "ACTUATOR"
}
```

```
{
	"commands": [{
		"commandName": "arm",
		"nparams": 0
	}, {
		"commandName": "disarm",
		"nparams": 0
	}, {
		"commandName": "getName",
		"nparams": 0
	}, {
		"commandName": "partial",
		"nparams": 0
	}, {
		"commandName": "setName",
		"nparams": 1
	}, {
		"commandName": "refreshAlarmStatus",
		"nparams": 0
	}, {
		"commandName": "setAlarmStatus",
		"nparams": 1
	}],
	"states": [{
		"values": ["offline", "online", "uninstalled"],
		"type": "DiscreteState",
		"qualifiedName": "core:CloudDeviceStatusState"
	}, {
		"values": ["detected", "notDetected"],
		"type": "DiscreteState",
		"qualifiedName": "core:IntrusionState"
	}, {
		"type": "DataState",
		"qualifiedName": "core:NameState"
	}, {
		"values": ["armed", "disarmed", "partial"],
		"type": "DiscreteState",
		"qualifiedName": "myfox:AlarmStatusState"
	}, {
		"type": "DataState",
		"qualifiedName": "myfox:AlertTrespassState"
	}],
	"dataProperties": [],
	"widgetName": "MyFoxAlarmController",
	"uiClass": "Alarm",
	"qualifiedName": "myfox:HomeKeeperProAlarmController",
	"type": "ACTUATOR"
}
```

```
{
	"commands": [{
		"commandName": "arm",
		"nparams": 0
	}, {
		"commandName": "disarm",
		"nparams": 0
	}, {
		"commandName": "getName",
		"nparams": 0
	}, {
		"commandName": "partial",
		"nparams": 0
	}, {
		"commandName": "setName",
		"nparams": 1
	}, {
		"commandName": "refreshAlarmStatus",
		"nparams": 0
	}, {
		"commandName": "setAlarmStatus",
		"nparams": 1
	}],
	"states": [{
		"values": ["offline", "online", "uninstalled"],
		"type": "DiscreteState",
		"qualifiedName": "core:CloudDeviceStatusState"
	}, {
		"values": ["detected", "notDetected"],
		"type": "DiscreteState",
		"qualifiedName": "core:IntrusionState"
	}, {
		"type": "DataState",
		"qualifiedName": "core:NameState"
	}, {
		"values": ["armed", "disarmed", "partial"],
		"type": "DiscreteState",
		"qualifiedName": "myfox:AlarmStatusState"
	}, {
		"type": "DataState",
		"qualifiedName": "myfox:AlertTrespassState"
	}],
	"dataProperties": [],
	"widgetName": "MyFoxAlarmController",
	"uiClass": "Alarm",
	"qualifiedName": "myfox:SomfyProtectAlarmController",
	"type": "ACTUATOR"
}
```

**Comment by lseufer** [comment]
(I am not patient I know!) I implemented your changes and I have two alarms discovered. One doesn't do anything (named alarm). The other (link) allows me to control the somfy protect alarm (yeah!) but it stays on triggered status. If I force its status to off, it ges back to triggered automatically. I believe it has something to with the "trespass status".
Thanks!

<img width="1162" alt="Screenshot 2020-08-11 at 22 02 25" src="https://user-images.githubusercontent.com/7261297/89943668-de01a200-dc1e-11ea-935e-41cb311a9271.png">

**Comment by iMicknl** [comment]
@lseufer haha, did you use https://github.com/iMicknl/ha-tahoma/pull/214? That branch was far from polished and needs a lot more work. Could you help me out with the available states?

Would be great if you could do all the commands via Tahomalink.com (like arm / home etc.) and note the state change after the commands. Afterwards, I can map those states to the right Home Assistant states.

**Comment by lseufer** [comment]
Yes that's the one I used. I can't get the available states that way. The integration is stuck on triggered. Any idea how to by-pass the TrespassState?

**Comment by iMicknl** [comment]
@lseufer that would probably require an update to the Python code, I will have a look later this week / next week to see if I can rewrite it.

Are you not able to change the alarm positions via the Tahoma app or Tahomalink.com? When you look at the states in Home Assistant, the `triggered` won't change, but the other States you shared will be updated every 10 seconds. It is really helpful to know all the states for every action you take.

**Comment by lseufer** [comment]
The only thing changing is:

myfox:AlarmStatusState: disarmed
myfox:AlarmStatusState: partial
myfox:AlarmStatusState: armed

not sure if it helps.

**Comment by iMicknl** [comment]
Thanks! And partial = home? Or which action did you execute via Tahomalink to receive that state.

**Comment by lseufer** [comment]
Disarmed= off
Partial= night mode
Armed= on

**Comment by iMicknl** [comment]
Could you try the latest version? I fixed the bug where the status is always set to triggered.

**Comment by lseufer** [comment]
Yeay! It's working! The partial mode doesn't work but I am not using it.

**Comment by iMicknl** [comment]
Great to hear! Can you arm / disarm it via Home Assistant? 

I am not sure why the partial mode doesn't work. Could you elaborate a little bit on the action you take in HA and what happens? (log + states + screenshot? :-)). Would be great if we can fix this.

**Comment by lseufer** [comment]
Wow, you never sleep! My bad, I had to delete the Arm Home option and the Arm Night appeared and this one works. Man, you rock. That was the last thing relying on this piece of crap that is IFTTT, I am now free of it!

**Comment by iMicknl** [comment]
@lseufer haha, with a temperature of 28 degrees Celsius inside my house, not yet... 
Neither do you ;-).

How can you delete the arm home option? Or was this something that did appear when you did relogin to the TaHoma integration? Great to hear that it is working correctly now.

**Comment by lseufer** [comment]
The arm home option appears by default. When setting up the alarm panel in HA you can choose which commands you want to be displayed. 
I solely needed to remove the arm home and replace it with arm night.

<img width="967" alt="Screenshot 2020-08-13 at 07 44 16" src="https://user-images.githubusercontent.com/7261297/90098605-e64e0000-dd38-11ea-83c9-9aac2c0bc95a.png">
<img width="982" alt="Screenshot 2020-08-13 at 07 44 31" src="https://user-images.githubusercontent.com/7261297/90098608-e817c380-dd38-11ea-8b61-b081ffdc183e.png">

**Comment by PoVPoV29** [comment]
Hello,
This patch (I past the dectory "Tahoma" in my HACS directory) is working fine for two things : 
- I have now my thermostat in HA !
- I can control the "door" of the "Somfy Outdoor camera" and "Somfy One plus"
I don't have an entity to arm or disarm the alarm sorry.
Do I have to do something else in my configuration?
Thanks !

**Comment by PoVPoV29** [comment]
Hello,
Sorry I made a mistake  I inverse the two package : 
https://github.com/iMicknl/ha-tahoma/archive/enhancement/support_MyFoxSecurityCamera_camera_cover.zip
and 
https://github.com/iMicknl/ha-tahoma/archive/enhancement/add_alarm_integration.zip
With a button i have an error  to change state : 
Échec d'appel du service "alarm_control_panel/turn_off". Service not found.
But with alarm panel it's working fine ! You did an excelent job !

**Comment by iMicknl** [comment]
@PoVPoV29 which alarm model do you have? (you can see the details on the Integrations page in Home Assistant). Do you you have TSKController or the MyFoxAlarmController?

And great to hear it works with the correct branch 👍🏻. They will have a code review soon, be merged to master and published in a new release.

**Comment by PoVPoV29** [comment]
I have got both TSK and Myfox.
I have a lot of somfy equipements ;) 22 equipements for 39 entities.

**Comment by iMicknl** [comment]
@PoVPoV29 do you use both? Or do you only use the Myfox alarm controller? We are still not sure if the TSK is actually used by someone...

If you could share a screenshot of your integrations page (filtered on Somfy TaHoma) with us, would be great! I haven't seen that many devices via this new integration yet.

**Comment by PoVPoV29** [comment]
Hello, 
I use "alarm_control_panel.cuisine" to arm/disarm the alarm (Somfy One plus) I don't know if TSK is involved for that entity or not. (or TSK)

![4](https://user-images.githubusercontent.com/69581008/90236893-afa0e400-de23-11ea-9265-f277001fe45b.JPG)
![1](https://user-images.githubusercontent.com/69581008/90236906-b3cd0180-de23-11ea-9538-1bad7339feed.JPG)
![2](https://user-images.githubusercontent.com/69581008/90236917-b62f5b80-de23-11ea-8489-6d937a5fa08c.JPG)
![3](https://user-images.githubusercontent.com/69581008/90236923-b7f91f00-de23-11ea-9805-6ef1f240b9a4.JPG)

**Comment by iMicknl** [comment]
@PoVPoV29 thanks! Could you also share a screenshot of your Appareils tab? You could also filter only on Somfy by going to Intégrations and then click xx appareils.

**Comment by PoVPoV29** [comment]
![1](https://user-images.githubusercontent.com/69581008/90262970-4e8f0580-de4f-11ea-807b-78e5454ec96d.PNG)
![2](https://user-images.githubusercontent.com/69581008/90262974-4fc03280-de4f-11ea-8aaa-359fb5627eae.PNG)

**Comment by iMicknl** [comment]
@PoVPoV29 wow, you have a lot of devices ;-). You are using the MyFoxAlarmController, looking at the model in your list.

Hopefully this change will be merged and released soon.

**Comment by PoVPoV29** [comment]
Hello,
And I have a lot more Somfy equipements connected to Somfy one plus. But they dont show up in tahomalink :(

**Comment by vlebourl** [comment]
That's sad but unfortunately not surprising from Somfy... Do you have a web interface for the One+ or is it app only?

**Comment by PoVPoV29** [comment]
There is no  web interface. Juste app for Somfy protect equipements. Are you able to retreive the battery state if thé Somfy One Plus?
