### ISSUE TITLE
Expose `my` position for covers via a service

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#220]
**Is your feature request related to a problem? Please describe.**
>for the roller, is it possible to add the favorit position “My” ?
https://community.home-assistant.io/t/somfy-tahoma-official-api/61448/1065?u=imick

**Describe the solution you'd like**
Register a new service for covers that support the `MY` command.

**Service:** `cover.my`

**Service Data:** ```entity_id: cover.living_room```

**Describe alternatives you've considered**
In #204, we are figuring out if we want to call `MY` instead of `STOP` to stop the cover movement. This would mean that the `cover.stop()` service in Home Assistant will move the cover to the my position if there is no movement.

**Comment by tetienne** [comment]
The name of the service will be _tahoma.my_. See https://developers.home-assistant.io/docs/dev_101_services/#entity-services

**Comment by iMicknl** [comment]
@PoVPoV29 we just added support for calling `tahoma.cover_my` to the integration. If you install the latest master integration, you are able to set your covers to the my position.

**Comment by PoVPoV29** [comment]
Hello,
It seems working.(I Don't remember my 'my' position on my covers)
I used the stop button for the my position.
