### ISSUE TITLE
Add support for SomfyOneplusCamera (myfox:SomfyOnePlusCameraController)

### ISSUE THREAD

**Issue by PoVPoV29** [iMicknl/ha-tahoma#221]
2020-08-12 15:14:24 DEBUG (MainThread) [custom_components.tahoma] Unsupported TaHoma device detected (myfox:SomfyOnePlusCameraController - Camera - MyFoxSecurityCamera)

**Device information**
The equipement is a Somy One plus Camera ("plus" is because there is a batery inside)
Can you integrate it with : 
- photo/image support
-on/off alarm (with status)
- activate siren
- detection status
- power status

**Device details**

```
{
	"commands": [{
		"commandName": "close",
		"nparams": 0
	}, {
		"commandName": "getName",
		"nparams": 0
	}, {
		"commandName": "open",
		"nparams": 0
	}, {
		"commandName": "refreshDeviceStatus",
		"nparams": 0
	}, {
		"commandName": "setName",
		"nparams": 1
	}, {
		"commandName": "refreshShutterStatus",
		"nparams": 0
	}],
	"states": [{
		"values": ["offline", "online", "uninstalled"],
		"type": "DiscreteState",
		"qualifiedName": "core:CloudDeviceStatusState"
	}, {
		"type": "DataState",
		"qualifiedName": "core:NameState"
	}, {
		"values": ["down", "up"],
		"type": "DiscreteState",
		"qualifiedName": "core:PowerSupplyUpDownState"
	}, {
		"values": ["closed", "opened"],
		"type": "DiscreteState",
		"qualifiedName": "myfox:ShutterStatusState"
	}],
	"dataProperties": [],
	"widgetName": "MyFoxSecurityCamera",
	"uiClass": "Camera",
	"qualifiedName": "myfox:SomfyOnePlusCameraController",
	"type": "ACTUATOR"
}
```

**Comment by PoVPoV29** [comment]
Maybe it's releated with :
2020-08-12 15:14:24 DEBUG (MainThread) [custom_components.tahoma] Unsupported TaHoma device detected (myfox:SomfyProtectAlarmController - Alarm - MyFoxAlarmController)
2020-08-12 15:14:24 DEBUG (MainThread) [custom_components.tahoma] Unsupported TaHoma device detected (rtds:RTDSRemoteControllerComponent - RemoteController - AlarmRemoteController)

I don't know the meening of these two lines.

**Comment by iMicknl** [comment]
Thanks for the information. I am afraid that retrieving the live streams from the cameras will be hard, since it is not available in the commands that I added to your first post. How do you consume the camera streams? Is there a separate platform to log in, or can you access them via tahomalink.com?

> Maybe it's releated with :
> 2020-08-12 15:14:24 DEBUG (MainThread) [custom_components.tahoma] Unsupported TaHoma device detected (myfox:SomfyProtectAlarmController - Alarm - MyFoxAlarmController)
> 2020-08-12 15:14:24 DEBUG (MainThread) [custom_components.tahoma] Unsupported TaHoma device detected (rtds:RTDSRemoteControllerComponent - RemoteController - AlarmRemoteController)
> 
> I don't know the meening of these two lines.

The alarm controller is the alarm controller component of your Somfy Protect system. We are already working on adding this to Home Assistant, which is tracked in #215. :-)

The Remote Controller is a device that I don't know. It doesn't have any commands, but it does offer information about some parts of the alarm system. 
```
{
	"commands": [],
	"states": [{
		"type": "ContinuousState",
		"qualifiedName": "rtds:ControllerBatteryState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "rtds:ControllerBipState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "rtds:ControllerOrderTypeState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "rtds:ControllerOriginatorState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "rtds:ControllerSensingState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "rtds:ControllerSirenState"
	}],
	"dataProperties": [],
	"widgetName": "AlarmRemoteController",
	"uiClass": "RemoteController",
	"qualifiedName": "rtds:RTDSRemoteControllerComponent",
	"type": "REMOTE_CONTROLLER"
}
```

**Comment by PoVPoV29** [comment]
Hello,
Thanks for the #215 !
Remote controller seems to be a part of the Somfy One Plus : I supose that because the Somfy one plus has a battery and a siren. it does a "bip" sound too when the alarm is turn on or off.)

**Comment by iMicknl** [comment]
I have implemented the open / close functionality of the cover of your camera in #224. Could you give it a try and let me know the result?

You can download the file below, unzip it and place the `tahoma` folder in your `custom_components` folder.

https://github.com/iMicknl/ha-tahoma/archive/enhancement/support_MyFoxSecurityCamera_camera_cover.zip

**Comment by PoVPoV29** [comment]
Hello,
The cover is working fine thanks !
But Can I a merge from : 
https://github.com/iMicknl/ha-tahoma/archive/enhancement/support_MyFoxSecurityCamera_camera_cover.zip
and 
https://github.com/iMicknl/ha-tahoma/archive/enhancement/add_alarm_integration.zip
To have alarm cover and alarm arm working.
Thanks

**Comment by vlebourl** [comment]
Great to hear. You can always do whatever you want on your own directory or fork! We prefer to work on including features separately. But if this is working, it should be merged into master pretty soon.

**Comment by iMicknl** [comment]
Added support for cover in latest master, will be published soon. Tracked the live stream issue in #226.
