### ISSUE TITLE
[Architecture] Allow multiple entities per device

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#223]
**Is your feature request related to a problem? Please describe.**
Currently, we only have one entity per discovered Somfy TaHoma device. However, looking at some of the devices, there are more interesting states and/or actions to take, which we put now in attributes.

Looking at PR's to core, I get the feeling that the attributes part is used less and less and should not be used to store everything. 

For example, looking at some sensors, there are multiple power states and the same for some security devices.

**Describe the solution you'd like**
Rewrite part of the integration to dynamically allow the creation of multiple entities per device.

**Additional context**
Example of a Z-Wave device, with multiple entities. Some less frequent used entities are hidden by default. 
<img width="354" alt="Screenshot 2020-08-12 at 17 44 53" src="https://user-images.githubusercontent.com/1424596/90036612-8b2df600-dcc3-11ea-9fd5-5f99608dc4f0.png">

**Comment by tetienne** [comment]
So you want to convert some Somfy attribute to hass entity_id?

**Comment by iMicknl** [comment]
@tetienne not sure yet how to do it technically. Opened this issue for tracking, since I faced it a few times in my last work on the integration.

Open for any technical architectures.

**Comment by PoVPoV29** [comment]
It should be perfect to manage detectors ! :
![Screenshot_20200813-114556_Somfy Protect](https://user-images.githubusercontent.com/69581008/90120358-f1198c80-dd5a-11ea-8ac6-ab2a257798ae.jpg)

**Comment by PoVPoV29** [comment]
It's should be perfect to manager detector : 
![Capture](https://user-images.githubusercontent.com/69581008/90120899-959bce80-dd5b-11ea-84e9-5b810b883498.PNG)

**Comment by iMicknl** [comment]
I started on this one, however there is a lot of work to be done.

Sneak peek:
<img width="333" alt="Screen Shot 2021-04-18 at 18 31 39" src="https://user-images.githubusercontent.com/1424596/115153078-55bc8200-a074-11eb-95a6-75c9488365ab.png">

**Comment by iMicknl** [comment]
@Hankey71 the version below should add a sensor for the expected number of showers.
@tillstaff the version below should add a sensor for the speed of each motors (inlet and outlet). 

Could you give https://github.com/iMicknl/ha-tahoma/archive/refs/heads/feature/add_secondary_sensors.zip a try? Extract this file and place `custom_components/tahoma` in your `custom_components` folder. Let me know how it works.

**Comment by Hankey71** [comment]
Hi @iMicknl 
Thank you again for all the work you do on this integration!
I just tested this version with the number of showers and it's perfect!
But I think you had already tried with my water heater because on your screen print it looks like my data from my water heater!
Thank you !

**Comment by iMicknl** [comment]
Great to hear, @Hankey71! And the screenshot is from a long time ago, but I guess I took it while developing via your account. 😄

**Comment by Hankey71** [comment]
Yes, no worries for the account! Now I can have my three cards on lovelace, the towel dryer, the three living room radiators (together) and the water heater! Perfect !
![Presse-papiers-1](https://user-images.githubusercontent.com/61835259/125709086-1cc7ef49-c7ee-40bb-b462-cd3cb1f6a70c.png)
