### ISSUE TITLE
Lots of traffic to Tahoma?

### ISSUE THREAD

**Issue by halest** [iMicknl/ha-tahoma#231]
**Describe the bug**
Hey, I don't know if this is connected to the other bug from earlier and possible retries but I'm seeing a lot of traffic talking to TaHoma. Is this the plugin or it this the gateway itself? I had never noticed before.

**Environment (please complete the following information):**

- **ha-tahoma version:** 2.0.1
- **Home Assistant version:** 0.113.3

<img width="250" alt="grafik" src="https://user-images.githubusercontent.com/12716965/90280050-93746580-de6a-11ea-8ae9-a10d52db062b.png">

**Comment by iMicknl** [comment]
This integration is using an event listener, to retrieve the latest updates to the state of devices. Unfortunately, tahomalink.com doesn't offer a push api / webhook, thus we are polling the event endpoint every 10 seconds. 

tahomalink.com is using the same approach, but only when you have the website open. Since Home Assistant is mostly running 24/7 on the background, there will be more requests than normal.

In pull request #227, we are working on making this timing configurable. Especially for users that are only using Home Assistant to control their Somfy TaHoma devices, it doesn't make sense to poll every 10 seconds.

**Comment by halest** [comment]
Hello iMicknl, sorry to bother you twice an evening :) 
Weird that they would even build an API without push interface in 2020 but I guess polling it is for now.
I'm one of these people only using it for my TaHoma covers so I'm looking forward to #227 but thanks for answering! Do you have an example where pulling the state would be important? Just curious.

**Comment by iMicknl** [comment]
> Do you have an example where pulling the state would be important? Just curious.

If you control your devices outside of Home Assistant. For example, if you control your (stateful) cover via the remote or via tahomalink.com, you would like to see this state changed in Home Assistant as well. 

Other examples of events that will be broadcasted, is when a device is (un)available, for example when it is out of the reach of the Tahoma box.

**Comment by halest** [comment]
Sure thing @iMicknl ! I've replaced the current master version with this one and set in the options a pull timeout of 1200 seconds. So far no traffic, I'll update in 20 minutes.

**Comment by halest** [comment]
Alrighty @iMicknl , it jumped from 6 to 8, probably doing two requests per pull I'd assume but other than that, much cleaner than before 👍

**Comment by iMicknl** [comment]
> Alrighty @iMicknl , it jumped from 6 to 8, probably doing two requests per pull I'd assume but other than that, much cleaner than before 👍

The current behaviour is that it will pull the event listener every second, after you executed a command. This will bring more frequent updates / feedback after execution of a command, even when you did configure the timeout to be less frequent.

**Comment by halest** [comment]
Hey @iMicknl , on thing I've noticed with this #227 is that the error from Issue #228 is no happening constantly. I basically get one command free for the covers, after which that error will occur and no more commands will execute until I reboot. Had to reboot four times since yesterday

**Comment by iMicknl** [comment]
What is your timeout? Is it still set to 1200 seconds? I can not reproduce this issue with a timeout of 30 seconds, but perhaps it is due to a long timeout. Good to test that as well! :-)

**Comment by halest** [comment]
It's 1200, but as I understood theres just a general problem regarding the API sending an empty body instead of a JSON?

**Comment by iMicknl** [comment]
The JSON error is a side effect of the original issue where you are Not Authenticated after some inactivity with the event listener. I could reproduce it on the latest version with a timeout of 1200, while calling the event listener endpoint..

**Comment by halest** [comment]
Ah I see, I understood they'd just throw you a 200 without a body. Usually in my own projects I'd kick in a doLoginIfNotAuthenticated kind of function that checks for a valid token and if not does the Login before continuing. I don't really know this framework, is something like that an option here?

**Comment by iMicknl** [comment]
The issue is that they return JSON content, without a valid MIME type, which causes the http client to throw an error. We have an open PR to fix this, and we will implement the next step soon where it will relogin on error.

https://github.com/iMicknl/python-tahoma-api/pull/36

**Comment by halest** [comment]
Ah, also very interesting! I'll set it to 30 and wait for PR 36. Thanks for yout time, I appreciate it.

**Comment by iMicknl** [comment]
@iMicknl you can give #227 a try, it should fix all your problems now.

**Comment by halest** [comment]
I've just deployed the new version. So far no problems. I'll reply if I find something. Thanks!
