### ISSUE TITLE
Detected integration that closes the Home Assistant aiohttp session

### ISSUE THREAD

**Issue by jensihnow** [iMicknl/ha-tahoma#238]
**Describe the bug**

Apparently Home Assistant complains about:

2020-08-27 20:35:08 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that closes the Home Assistant aiohttp session. Please report issue to the custom component author for tahoma using this method at custom_components/tahoma/__init__.py, line 145: await client.close()

**To Reproduce**

Happened on restart or deletion of the integration if I'm not mistaken. Found it in the logs while looking for another issue.

**Expected behavior**

No warning for this topic.

**Screenshots**

**Environment (please complete the following information):**

- **ha-tahoma version:** branch https://github.com/iMicknl/ha-tahoma/pull/227
- **Home Assistant version:** 0.114.4
- **Platform**: -

**Device:** -

- **Model**: -
- **Type**: -

**Additional context**

-

**Comment by tetienne** [comment]
Thx for reporting this. @iMicknl  That's probably due to the fact that now we share the HA aiohttp session. We must not close the session anymore.

**Comment by iMicknl** [comment]
Cool, I wasn't sure about this one, however I didn't see it in my logs yet. Perhaps since I didn't had to close the session yet.

Will fix this in #227.

**Comment by iMicknl** [comment]
Should be fixed in #227!
