### ISSUE TITLE
Camera update after triggering

### ISSUE THREAD

**Issue by dckiller51** [iMicknl/ha-tahoma#240]
Hello, 
When the camera goes into trigger. The state does not return in an armed or disarmed state. Home assistant must be restarted to regain its good condition.

**Comment by iMicknl** [comment]
Thanks for reporting. Could you please use the [issue template](https://github.com/iMicknl/ha-tahoma/issues/new?assignees=&labels=bug&template=bug_report.md&title=) and fill all fields? We need more information to help you and this template covers all required information.

I will close this one, please create a new issue using the template.
