### ISSUE TITLE
Not really a bug: EnergyConsumptionSensor

### ISSUE THREAD

**Issue by lseufer** [iMicknl/ha-tahoma#245]
**Describe the bug**
7 of the 8 power meters discovered by the integration are reporting a measurement in Watt per hour. However, I can't match any of those with the ones in the Tahoma app/website. The measurements are all different.

I don't have any idea what period of time those are supposed to be.

Tahoma displays  Daily, Weekly, Monthly, Yearly in kWh.

**Device:** 
Here are the sensors I have.

io:ElectricityMeterComponent
io:DHWElectricalEnergyConsumptionSensor
io:OtherElectricalEnergyConsumptionSensor
io:TotalElectricalEnergyConsumptionIOSystemSensor
io:HeatingElectricalEnergyConsumptionSensor
io:PlugsElectricalEnergyConsumptionSensor

io:EnergyConsumptionSensorsConfigurationComponent
-> this one doesn't report anything and could be disregarded

**Comment by iMicknl** [comment]
Thanks for reporting @lseufer! We are getting close to a pull request to core, thus it would be great to solve some of the latest bugs.

**io:DHWElectricalEnergyConsumptionSensor**
We read the `core:ElectricEnergyConsumptionState` from the Energy Consumption Sensors. This is probably the realtime value of your energy usage. Is the value that you are looking for present in the other states? (`/developer-tools/state`). Otherwise, you would need to calculate the total values in Home Assistant based on the realtime state.

```
{
	"commands": [{
		"commandName": "getSensorName",
		"nparams": 0
	}, {
		"commandName": "putSensorName",
		"nparams": 1
	}],
	"states": [{
		"type": "ContinuousState",
		"qualifiedName": "core:ConsumptionTariff0State"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "core:ConsumptionTariff1State"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "core:ConsumptionTariff2State"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "core:ConsumptionTariff3State"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "core:ConsumptionTariff4State"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "core:ConsumptionTariff5State"
	}, {
		"values": ["good", "low", "normal", "verylow"],
		"type": "DiscreteState",
		"qualifiedName": "core:DiscreteRSSILevelState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "core:ElectricEnergyConsumptionState"
	}, {
		"type": "DataState",
		"qualifiedName": "core:NameState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "core:RSSILevelState"
	}, {
		"values": ["dead", "lowBattery", "maintenanceRequired", "noDefect"],
		"type": "DiscreteState",
		"qualifiedName": "core:SensorDefectState"
	}, {
		"values": ["available", "unavailable"],
		"type": "DiscreteState",
		"qualifiedName": "core:StatusState"
	}],
	"dataProperties": [],
	"widgetName": "CumulativeElectricPowerConsumptionSensor",
	"uiClass": "ElectricitySensor",
	"qualifiedName": "io:DHWElectricalEnergyConsumptionSensor",
	"type": "SENSOR"
}
```

**io:ElectricityMeterComponent**
Does this show any value currently? I believe this one is not properly mapped yet, since we don't have any of the qualifiedName's below in our repository. Could you have a look at the states in Home Assistant? (`/developer-tools/state`). I wonder which value makes most sense to show in HA front-end.

We currently do not support multiple entities per device, however this is something we would like for the future. (#223)


```
{
	"commands": [{
		"commandName": "setElectricalContractIntensity",
		"nparams": 1
	}],
	"states": [{
		"type": "DataState",
		"qualifiedName": "core:CurrentTariffNumberState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "core:ElectricalContractIntensityState"
	}, {
		"type": "DataState",
		"qualifiedName": "core:ElectricalContractNameState"
	}, {
		"values": ["French blue electronic meter", "French linky meter", "Mechanical meter"],
		"type": "DiscreteState",
		"qualifiedName": "core:ElectricalMeterTypeState"
	}, {
		"values": ["available", "unavailable"],
		"type": "DiscreteState",
		"qualifiedName": "core:StatusState"
	}],
	"dataProperties": [],
	"widgetName": "AtlanticMultiMeterElectricSensor",
	"uiClass": "ElectricitySensor",
	"qualifiedName": "io:ElectricityMeterComponent",
	"type": "ACTUATOR"
}
```

**io:EnergyConsumptionSensorsConfigurationComponent**
Could you have a look at the states in Home Assistant again? (`/developer-tools/state`). I wonder what the value of `io:HeatPumpActiveState` is. 
It looks like there is a command available as well (`activateHeatPumpMode`). Would that not be useful?

```
{
	"commands": [{
		"commandName": "activateHeatPumpMode",
		"nparams": 0
	}],
	"states": [{
		"values": ["available", "unavailable"],
		"type": "DiscreteState",
		"qualifiedName": "core:StatusState"
	}, {
		"type": "DataState",
		"qualifiedName": "io:HeatPumpActiveState"
	}],
	"dataProperties": [],
	"widgetName": "AtlanticMultiMeterElectricConfiguration",
	"uiClass": "ElectricitySensor",
	"qualifiedName": "io:EnergyConsumptionSensorsConfigurationComponent",
	"type": "ACTUATOR"
}
```

**Comment by lseufer** [comment]
The figures displayed in HA match the ones I get if I export the values from the Tahoma web interface but they don't match those displayed in the Tahoma graphs... Somfy at its best.. again...

Some of the values appear to be cumulative consumptions over a monthly period, others are weekly ones. I don't think I'll be able to make any use of those sensors.

In case it helps, here are the values I have in the dev tools tab of HA.

ui_class: ElectricitySensor
widget: CumulativeElectricPowerConsumptionSensor
controllable_name: 'io:HeatingElectricalEnergyConsumptionSensor'
rssi_level: 100
'core:MeasurementCategory': electric/heatingSystem
'core:PowerSourceType': mainSupply
'core:MeasuredValueType': 'core:ElectricalEnergyInWh'
'core:StatusState': available
'core:DiscreteRSSILevelState': good
'core:RSSILevelState': 100
'core:ElectricEnergyConsumptionState': 4161409
'core:ConsumptionTariff0State': 3900163   -> heating system
'core:ConsumptionTariff1State': 119560603 -> electric applian 	
unit_of_measurement: Wh



ui_class: ElectricitySensor
widget: CumulativeElectricPowerConsumptionSensor
controllable_name: 'io:DHWElectricalEnergyConsumptionSensor'
rssi_level: 100
'core:MeasurementCategory': electric/dhw
'core:PowerSourceType': mainSupply
'core:MeasuredValueType': 'core:ElectricalEnergyInWh'
'core:StatusState': available
'core:DiscreteRSSILevelState': good
'core:RSSILevelState': 100
'core:ElectricEnergyConsumptionState': 1336665
'core:ConsumptionTariff0State': 1395706
'core:ConsumptionTariff1State': 94291616
unit_of_measurement: Wh




ui_class: ElectricitySensor
widget: CumulativeElectricPowerConsumptionSensor
controllable_name: 'io:OtherElectricalEnergyConsumptionSensor'
rssi_level: 100
'core:MeasurementCategory': electric/unknown
'core:PowerSourceType': mainSupply
'core:MeasuredValueType': 'core:ElectricalEnergyInWh'
'core:StatusState': available
'core:DiscreteRSSILevelState': good
'core:RSSILevelState': 100
'core:ElectricEnergyConsumptionState': 18687582
'core:ConsumptionTariff0State': 15628944
'core:ConsumptionTariff1State': 112466143
unit_of_measurement: Wh



ui_class: ElectricitySensor
widget: CumulativeElectricPowerConsumptionSensor
controllable_name: 'io:TotalElectricalEnergyConsumptionIOSystemSensor'
rssi_level: 100
'core:MeasurementCategory': electric/overall
'core:PowerSourceType': mainSupply
'core:MeasuredValueType': 'core:ElectricalEnergyInWh'
'core:StatusState': available
'core:DiscreteRSSILevelState': good
'core:RSSILevelState': 100
'core:ElectricEnergyConsumptionState': 24375408
unit_of_measurement: Wh




ui_class: ElectricitySensor
widget: CumulativeElectricPowerConsumptionSensor
controllable_name: 'io:PlugsElectricalEnergyConsumptionSensor'
rssi_level: 100
'core:MeasurementCategory': electric/outlet
'core:PowerSourceType': mainSupply
'core:MeasuredValueType': 'core:ElectricalEnergyInWh'
'core:StatusState': available
'core:DiscreteRSSILevelState': good
'core:RSSILevelState': 100
'core:ElectricEnergyConsumptionState': 189835
'core:ConsumptionTariff0State': 667262
'core:ConsumptionTariff1State': 28695908
unit_of_measurement: Wh

**Comment by iMicknl** [comment]
> The figures displayed in HA match the ones I get if I export the values from the Tahoma web interface but they don't match those displayed in the Tahoma graphs... Somfy at its best.. again...

Unfortunately this is not something we can fix in our integration... So I guess for now the sensors are a bit useless, until Somfy changes the states of the devices. They have a lot of logic in their front-end most of the time, so we can not work around everything.
