### ISSUE TITLE
Add support for DomesticHotWaterTank (io:DomesticHotWaterTankComponent)

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#246]
**Device information**
Unsupported TaHoma device detected (io:DomesticHotWaterTankComponent - WaterHeatingSystem - DomesticHotWaterTank)

> Those commands are not accessible via the Tahoma interface but if they were to work, I can already see how I could make use of them. (if more than X persons detected in the house for more than 2 days then turn Force heating on, no more pressing on the heater button for me!)
> 
> The button is to force the heating to run without stopping for a few days. It’s been set to heat water for a family of 4 but if we have guests, it won’t be enough. The button bypasses the standard heating mode if you will.
@lseufer

**Device details**

```
{
	"commands": [{
		"commandName": "refreshForceHeatingMode",
		"nparams": 0
	}, {
		"commandName": "setForceHeating",
		"nparams": 1
	}],
	"states": [{
		"values": ["available", "unavailable"],
		"type": "DiscreteState",
		"qualifiedName": "core:StatusState"
	}, {
		"values": ["off", "on"],
		"type": "DiscreteState",
		"qualifiedName": "io:AllowForceHeatingState"
	}, {
		"values": ["off", "on"],
		"type": "DiscreteState",
		"qualifiedName": "io:ForceHeatingState"
	}],
	"dataProperties": [],
	"widgetName": "DomesticHotWaterTank",
	"uiClass": "WaterHeatingSystem",
	"qualifiedName": "io:DomesticHotWaterTankComponent",
	"type": "ACTUATOR"
}
```

**Comment by iMicknl** [comment]
@lseufer could you give https://github.com/iMicknl/ha-tahoma/tree/feature/support_DomesticHotWaterTank a try? You can download this zip (https://github.com/iMicknl/ha-tahoma/archive/feature/support_DomesticHotWaterTank.zip) and extract the `tahoma` folder and place it in your `custom_components` folder to try.

It should detect your `DomesticHotWaterTank` as a switch, which will unblock the scenario you mentioned on the Home Assistant Community forum.

**Comment by lseufer** [comment]
Excellent! It's working, now to create my scenario and automate my water heater. Thanks!!!
