### ISSUE TITLE
Add support for EvoHome - HeatingSetPoint (ramses:EvoHomeZoneSetPoint)

### ISSUE THREAD

**Issue by wzwart76** [iMicknl/ha-tahoma#249]
**Device information**
I have a Evohome box (HGI80) connected to the Tahoma via USB and can read the temperature (temperaturesensor) in Home Assitant, but I cannot set the temperature, because the device (thermostat / setpoint) is not supported.

**Device details**

DEBUG (MainThread) [custom_components.tahoma] Unsupported TaHoma device detected (ramses:EvoHomeZoneSetPoint - EvoHome - HeatingSetPoint)

```
{
	"commands": [{
		"commandName": "getName",
		"nparams": 0
	}, {
		"commandName": "setName",
		"nparams": 1
	}, {
		"commandName": "setTargetTemperature",
		"nparams": 1
	}, {
		"commandName": "setSetpointOverride",
		"nparams": 3
	}, {
		"commandName": "setTimeProgram",
		"nparams": 1
	}],
	"states": [{
		"type": "DataState",
		"qualifiedName": "core:NameState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "core:TargetTemperatureState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "core:TemperatureState"
	}, {
		"type": "DataState",
		"qualifiedName": "ramses:RAMSESSetPointOverrideDurationState"
	}, {
		"type": "DataState",
		"qualifiedName": "ramses:RAMSESSetPointOverrideModeState"
	}, {
		"type": "DataState",
		"qualifiedName": "ramses:RAMSESZoneTimeProgramState"
	}],
	"dataProperties": [],
	"widgetName": "HeatingSetPoint",
	"uiClass": "EvoHome",
	"qualifiedName": "ramses:EvoHomeZoneSetPoint",
	"type": "ACTUATOR"
}
```

**Comment by vlebourl** [comment]
Hi, 
I'll start working on this, any idea what the "setSetpointOverride" command is?
cheers

**Comment by wzwart76** [comment]
Hello Vincent,

In Evohome there is a schedule. So I think this is the override of the schedule. For instance, between 23:00 and 18:00 it is always 20 degrees. And between 18:00 and 23:00 the temperature increases to 21 degrees. On the Tahoma I can set a different temperature for the current period, but once a new period begins (18:00 for example) the override disappears.

I hope this is clear? Thanks!

**Comment by iMicknl** [comment]
@wzwart76 do you still own this device and would you like to have it in this integration?

In order to gather more information, you can use the tahoma.get_execution_history service in Home Assistant which will print your execution history to the Home Assistant log. Run the all available commands via the official vendor app (e.g. TaHoma) and capture the commands.
(this service is added in the latest version, so you would need to update this integration).

It would be great if you could also add some screenshots / more information of the official vendor app.

**Comment by wzwart76** [comment]
Yes I do and I would love to have it! How do I enable the tahoma.get_execution_history? No problem to send some screenshots!

**Comment by iMicknl** [comment]
Run the all available commands via the vendor app and write down what you called. Now go to Developer Tools -> Services in Home Assistant and execute tahoma.get_execution_history. This will print the last execution history in your logbook, which you can paste here.

**Comment by wzwart76** [comment]
I just performed the actions. But there is no logging in Home Assistant. Do I have to switch something on? I have attached some screenshots of the Tahoma app of me setting the temperature of my ""Studeerkamer".
![Schermafbeelding 2021-02-04 204958](https://user-images.githubusercontent.com/60143372/106948241-bc93f580-672b-11eb-84bc-604205bc6e5a.png)
![Schermafbeelding 2021-02-04 205026](https://user-images.githubusercontent.com/60143372/106948252-bf8ee600-672b-11eb-9871-07d532d7f3ea.png)

**Comment by wzwart76** [comment]
I only saw these messages:

2021-02-04 20:48:51 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for tahoma which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-04 20:48:51 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-04 20:50:57 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547943531808] Error handling message: expected dict for dictionary value @ data['service_data']. Got 'tahoma.get_execution_history'
expected str for dictionary value @ data['service']. Got None

**Comment by iMicknl** [comment]
@wzwart76 it looks like you are not executing the service in the right way. Could you share a screenshot of how you are calling the service? It should look like this:

```https://xxxxxxx.nl/developer-tools/service```

<img width="588" alt="Screen Shot 2021-02-11 at 23 09 29" src="https://user-images.githubusercontent.com/1424596/107704875-3729bb80-6cbe-11eb-90e6-ce1216bc1dd7.png">

Please make sure you are using the latest version of the integration (2.4.6).

**Comment by wzwart76** [comment]
![image](https://user-images.githubusercontent.com/60143372/107873384-7882bc80-6eb2-11eb-9a8c-c0b546af9b7c.png)

**Comment by iMicknl** [comment]
@wzwart76 have you checked your log? (Configuration -> Logs).

**Comment by wzwart76** [comment]
Yes, but nothing!

**Comment by iMicknl** [comment]
@wzwart76 also no errors in your log? 

Otherwise we could work [via Discord](https://discord.gg/3ssGqebP) (iMick#1903) to see if something else is going wrong. Easiest is if you are able to temporarily change your password, so we can have a quick look, and than change it back.
