### ISSUE TITLE
Can not arm StatelessAlarmController via Lovelace (rtd:AlarmRTDComponent)

### ISSUE THREAD

**Issue by thomasgregg** [iMicknl/ha-tahoma#254]
Hi,

I have a rather complicated setup to connect a Somfy Protexial RTS Alarm system. There is no custom integration etc, for this alarm system as it doesn’t provide a public API. At least i couldn’t find one. The good news is that I also have a Somfy Tahoma which allows me to integrate the Protexial system. HA offers a great integration with Tahoma so I can see and use most of the things Tahoma sees in HA. Via the above explained integration:

Somfy Protexial RTS --> Somfy Tahoma --> Home Assistant

I do now have a “alarm_control_panel.security” entity available in HA which is provided by the Tahoma integration. Which is great. But it all fails when I try to use the the Alarm Panel in lovelace. Whatever I do it doesn’t show me the keypad.

![image](https://user-images.githubusercontent.com/2538782/92308755-5e0df400-efa0-11ea-9cae-4ad87522e2fa.png)

I did some digging and found out that the format for code_format Tahoma provides to HA is null.

![image](https://user-images.githubusercontent.com/2538782/92308758-6bc37980-efa0-11ea-9e38-ca473984451f.png)

I am not 100% sure if this is the only issue why the alarm integration is not working correctly but I assume it would be first step. Thanks so much for the great work and the great custom integration.

I would appreciate some help.

**Comment by iMicknl** [comment]
Thanks for reporting! Can you set a code to arm / disarm your alarm panel via tahomalink.com? Currently the alarm control panel integration in this component doesn't allow you to set a code indeed. 

Are you able to arm / disarm your alarm via Home Assistant? It should work already (without user code), but otherwise we need to have a better look for this as well.

**Comment by thomasgregg** [comment]
Hi,

Thanks for getting back to quickly. You are absolutely right. I can arm / disarm from the Somfy Tahoma App without a code and it works fine. So there should be no reason to have a code in HA.

Nevertheless it still doesn't fully work. When I press the Disarm button (screenshot in my first post) I can hear the alarm system peeping and it disarms when I set armed it manually or via the Somfy app before. All good so far.

What I can't figure  out is how to arm it. The button arm never appears in the alarm control panel.

![image](https://user-images.githubusercontent.com/2538782/92356454-6ff9af00-f0e6-11ea-801a-89f38c0f2b69.png)


Any help would be appreciated.

Thanks,

**Comment by iMicknl** [comment]
Currently, we only support `arm_away` for your device, which is mapped to the `alarmOn` command. Could you try it manually by calling `alarm_control_panel.alarm_arm_away` service?

For now, my guess is that the LoveLace card cannot handle an alarm without state, but that is something we would need to investigate.

**Comment by thomasgregg** [comment]
Ok. Calling the services:

* alarm_control_panel.alarm_disarm
* alarm_control_panel.alarm_arm_away

work fine and do the trick. 

Lovelace card still doesn't work but I assume this is not really related to this integration then. Thanks for your help.

**Comment by iMicknl** [comment]
@thomasgregg I will keep this open for now, until I am sure it is not an issue with the Lovelace card. However, I believe that the current card doesn't support stateless alarm control panel devices. 

Would it make more sense to map your device to a `switch` entity in Home Assistant, where you have a turn on and off button. (both visible, since it is a stateless device).

**Comment by thomasgregg** [comment]
Agree. A switch entity would be a great idea. Would reduce 2 buttons to 1 on lovelace if i understand correctly. The issue I can see here is that there are other ways to arm / disarm the alarm system like badges, the keypad etc. As It seems the alarm system doesn't report a state if it is armed or disarmed HA would always be out of sync.

**Comment by iMicknl** [comment]
@thomasgregg could you share a screenshot of this alarm on tahomalink.com? I would like to understand if they show the current state (and if it is not out of sync when you arm it by the keypad).

**Comment by iMicknl** [comment]
@thomasgregg should I close this issue? Or do you have any suggestions how to solve this. :-)

**Comment by thomasgregg** [comment]
Yes, let's close it. Thanks for your support.
