### ISSUE TITLE
DoorSensor trigger not working in automation (io:SomfyContactIOSystemSensor)

### ISSUE THREAD

**Issue by quibusus** [iMicknl/ha-tahoma#255]
**Describe the bug**

What works:
* I can see io:SomfyContactIOSystemSensor - binary door opened/closed sensor in the UI
* I can see the status being updated in the UI when I close/open the doors
* I can see open/closed in the event log in the UI

What does not work:
* in automation, when I select trigger > type: device > door sensor, automation is not triggered
* also does not work with trigger > type: state, automation is not triggered 

**To Reproduce**
Set the following automation trigger
```
type: not_opened
platform: device
device_id: xxx
entity_id: binary_sensor.door_left
domain: binary_sensor
```

open/close the door to trigger door sensor

**Expected behavior**
Automation is triggered, when I close/open the door

- **ha-tahoma version:** v2.2.0
- **Home Assistant version:** 0.114.4
- **Platform**: binary_sensor

**Device:** https://www.expert-security.de/somfy-tahoma-funk-oeffnungsmelder-io-weiss-1811482.html

- **Model**: [e.g. PositionableScreen, can be gathered from device list in HA]
- **Type**: io:SomfyContactIOSystemSensor

**Additional context**

In logs I see
```
DEBUG (MainThread) [custom_components.tahoma.coordinator] DeviceStateChangedEvent/None (device:io://1209-9218-5268/13179721,state:None->None)
```

**Comment by tetienne** [comment]
Hi, instead of selecting a device can you try with the entity id directly ?

**Comment by quibusus** [comment]
I also tried the following
```
platform: state
entity_id: binary_sensor.esszimmer_linke_tur
to: opened
```

**Comment by quibusus** [comment]
I can see it in the log like this: 
![image](https://user-images.githubusercontent.com/965671/92313471-53695400-efcc-11ea-94a2-bdc1d23ee0b8.png)

**Comment by iMicknl** [comment]
> I also tried the following trigger, no success
> 
> ```
> platform: state
> entity_id: binary_sensor.esszimmer_linke_tur
> to: opened
> ```

Have you tried `on` and `off`? I believe this is the required value for binary sensors. 

This doesn't look like a bug in ha-tahoma since it reports the status correctly in the UI and logbook. Could you have a look at the states (Developer Tools -> States or `/developer-tools/state`) and check if they change from `on` to `off`?

**Comment by quibusus** [comment]
Thank you @iMicknl @tetienne, I started to lose hope 😆 

The `on` and `off` states indeed work as intended 👍

Can I help with documenting this somewhere?

**Comment by tetienne** [comment]
You are welcome. 

About the documentation, what you described is listed on this page: https://www.home-assistant.io/docs/automation/trigger/

Look at state trigger.

**Comment by quibusus** [comment]
> You are welcome.
> 
> About the documentation, what you described is listed on this page: https://www.home-assistant.io/docs/automation/trigger/
> 
> Look at state trigger.

My bad, overlooked that. Thank you for the help!
