### ISSUE TITLE
Don't trigger alarm when state is disarmed for MyFoxAlarmController (myfox:SomfyProtectAlarmController)

### ISSUE THREAD

**Issue by PoVPoV29** [iMicknl/ha-tahoma#258]
Hello,
After a detection the intrusion state stay "detected" beside the alarm status is disarmed.
Can you do something for that ? (It seems that is the Somfy API informations)
Thanks
Alain

code_format: null
changed_by: null
code_arm_required: true
ui_class: Alarm
widget: MyFoxAlarmController
controllable_name: 'myfox:SomfyProtectAlarmController'
'core:IntrusionState': detected
'core:CloudDeviceStatusState': online
'myfox:AlarmStatusState': disarmed
'myfox:AlertTrespassState': >-

**Comment by iMicknl** [comment]
@PoVPoV29 so the status can be `detected`, even when the alarm control panel is set to disarmed? 

Would it make sense if I add a check to set the status to `detected` only if the panel is NOT set to disarmed.

**Comment by PoVPoV29** [comment]
I agree and I am ready to test that. Thanks

**Comment by iMicknl** [comment]
@PoVPoV29 could you give https://github.com/iMicknl/ha-tahoma/archive/fix/only_trigger_alarm_when_armed.zip a try? You could unzip the `custom_components/tahoma` folder to your custom components folder.

**Comment by PoVPoV29** [comment]
It seems the issue is still happening : 
code_format: null
changed_by: null
code_arm_required: true
ui_class: Alarm
widget: MyFoxAlarmController
controllable_name: 'myfox:SomfyProtectAlarmController'
'core:IntrusionState': detected
'core:CloudDeviceStatusState': online
'myfox:AlarmStatusState': disarmed
'myfox:AlertTrespassState': >-
  {"deviceId":"NmZSuim2Wwcttk9NB56B1kdql30fDmDY","sendAt":"2020-09-15T07:27:53.000000Z"}
friendly_name: cuisine
supported_features: 30

So the issue is with the alarm panel : 
![Cuisine](https://user-images.githubusercontent.com/69581008/93179778-71565780-f736-11ea-9b1c-9a7b423dc1b0.PNG)
it don't reflect the alarmstatusstate/

**Comment by iMicknl** [comment]
@PoVPoV29 I am not sure if I understand you correctly. It shows that your alarm is disarmed? That should be the correct status, since intrusion detected should not show for disarmed devices.

**Comment by PoVPoV29** [comment]
Hello @iMicknl In the "'myfox:AlarmStatusState" yes it's diusarmed but no in the web interface (alarm panel)

**Comment by iMicknl** [comment]
> Hello @iMicknl In the "'myfox:AlarmStatusState" yes it's diusarmed but no in the web interface (alarm panel)

Could you give it another try? :) I just updated the branch with a small fix.

**Comment by iMicknl** [comment]
@PoVPoV29 I just uploaded a new version, could you try if this solves your problem? https://github.com/iMicknl/ha-tahoma/archive/fix/only_trigger_alarm_when_armed.zip

**Comment by PoVPoV29** [comment]
Hello,
It's good for me now !

code_format: null
changed_by: null
code_arm_required: true
ui_class: Alarm
widget: MyFoxAlarmController
controllable_name: 'myfox:SomfyProtectAlarmController'
'core:IntrusionState': detected
'core:CloudDeviceStatusState': online
'myfox:AlarmStatusState': disarmed
'myfox:AlertTrespassState': '{"deviceId":"site_alarm","sendAt":"2020-09-22T14:39:16.000000Z"}'
friendly_name: cuisine
supported_features: 30

"Core:intrusionstate" seems to keep the last state in the Somfy API.
Disarmed in the status state, and in the graphical interface widget. 

Nice job again !
Thanks !

**Comment by PoVPoV29** [comment]
Hello,
New issue releated to your modifications : 
after armed the alarm, the status "cuisine déclenché" is active. It shouldn't because there was no intrusion.
![auto](https://user-images.githubusercontent.com/69581008/93912489-20c99600-fd04-11ea-8eba-37fcae615f11.PNG)

**Comment by iMicknl** [comment]
The issue is that the state is still `'core:IntrusionState': detected`. What we could do possibly is that we set the status to undetected after you disarm the alarm, maybe that will solve the first problem as well...

Could you have a look at the state after you disarm the alarm via tahomalink.com. Does it change the `IntrusionState` to `undetected`.

**Comment by PoVPoV29** [comment]
How can I look the state in the Tahomalink? throught API? GUI?

**Comment by PoVPoV29** [comment]
"id": "",
    "type": "camera_protect_somfyone",
    "categories": [
      "camera"
    ],
    "states": [
      {
        "name": "shutter_position",
        "value": "closed",
        "type": "string"
      }
    ],
    "capabilities": [
      {
        "name": "shutter_close",
        "parameters": []
      },
      {
        "name": "shutter_open",
        "parameters": []
      }
    ],
    "site_id": "",
    "last_status": "unknown",
    "name": "Camera cuisine"

**Comment by iMicknl** [comment]
I am looking for the state that you did pull from Home Assistant. They should be updated as well, after you execute an action via tahomalink.com. I would like to understand if they set the status to `notDetected` from tahomalink.com when you disarm.

**Comment by PoVPoV29** [comment]
Hello,
I didn't understand what do you want from me. Can you explain me ?
Thanks

**Comment by iMicknl** [comment]
No worries. Hereby the steps in a bit more detail:

1. Arm alarm panel via tahomalink.com

3. Make sure you trigger the alarm (status should move to detected)

2. Wait for a minute (or wait for the time that you configured in Integrations -> Tahoma -> Options -> Update Interval)

2. Copy all states from Developer Tools -> States for the MyFoxAlarmController.

3. Disarm alarm panel via tahomalink.com

2. Wait for a minute (or wait for the time that you configured in Integrations -> Tahoma -> Options -> Update Interval)

4. Copy all states from Developer Tools -> States for the MyFoxAlarmController.

3. Make sure you trigger the alarm

2. Wait for a minute (or wait for the time that you configured in Integrations -> Tahoma -> Options -> Update Interval)

2. Copy all states from Developer Tools -> States for the MyFoxAlarmController.

**Comment by PoVPoV29** [comment]
code_format: null
changed_by: null
code_arm_required: true
ui_class: Alarm
widget: MyFoxAlarmController
controllable_name: 'myfox:SomfyProtectAlarmController'
'core:IntrusionState': detected
'core:CloudDeviceStatusState': online
'myfox:AlarmStatusState': armed
'myfox:AlertTrespassState': '{"deviceId":"site_alarm","sendAt":"2020-11-03T08:00:33.000000Z"}'
friendly_name: cuisine
supported_features: 30

code_format: null
changed_by: null
code_arm_required: true
ui_class: Alarm
widget: MyFoxAlarmController
controllable_name: 'myfox:SomfyProtectAlarmController'
'core:IntrusionState': detected
'core:CloudDeviceStatusState': online
'myfox:AlarmStatusState': disarmed
'myfox:AlertTrespassState': '{"deviceId":"site_alarm","sendAt":"2020-11-03T08:00:33.000000Z"}'
friendly_name: cuisine
supported_features: 30


Here the point 4 and 7 for the 10, I suppose the alarm has to be armed ?

The issue is that the state is still 'core:IntrusionState': detected. What we could do possibly is that we set the status to undetected after you disarm the alarm, maybe that will solve the first problem as well...
Could you have a look at the state after you disarm the alarm via tahomalink.com. Does it change the IntrusionState to undetected.
It's seems to be a solution for me. Can you modify the script ? I agree to test that.

**Comment by iMicknl** [comment]
Hi @PoVPoV29, could you test the latest version? 
https://github.com/iMicknl/ha-tahoma/archive/fix/only_trigger_alarm_when_armed.zip

**Comment by PoVPoV29** [comment]
Not yet I will try to do that this week. Sorry

**Comment by iMicknl** [comment]
No worries, I just made the modification. So no hurry. :-)

**Comment by PoVPoV29** [comment]
Hello,
No change : Issue still happen : 
After detection and disarmed the system the intrusion state is still "detected" : 
changed_by: null
code_arm_required: true
ui_class: Alarm
widget: MyFoxAlarmController
controllable_name: 'myfox:SomfyProtectAlarmController'
'core:IntrusionState': detected
'core:CloudDeviceStatusState': online
'myfox:AlarmStatusState': disarmed
'myfox:AlertTrespassState': '{"deviceId":"site_alarm","sendAt":"2020-11-09T16:49:11.000000Z"}'
friendly_name: cuisine
supported_features: 30

**Comment by PoVPoV29** [comment]
When I reboot my HA. The status appears correctly in the alarm panel

**Comment by iMicknl** [comment]
What is your polling interval?

**Comment by PoVPoV29** [comment]
60 and I wait those 60 seconds to show you the previous output.

**Comment by PoVPoV29** [comment]
'core:IntrusionState': detected don't change until reboot

**Comment by PoVPoV29** [comment]
Hello,
In the same way the alarm's related automatisations are not working anymore : 
![Auto](https://user-images.githubusercontent.com/69581008/99779116-e407f880-2b14-11eb-854d-1bde6521d4ff.PNG)
My alarm seems never be triggered by HA.
Thanks for your help.
