### ISSUE TITLE
Auto discover Overkiz devices (Somfy TaHoma box, Connexoon)

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#265]
**Is your feature request related to a problem? Please describe.**
To improve discoverability of this integration when it will be in core, it would be good to auto discover based on available Overkiz gateways in the network.

**Describe the solution you'd like**
Implement the autodiscover flow using `ssdp`, `zeroconf` or `discovery`.

**Additional context**
My OverKiz device uses the gateway id in the hostname and the MAC address for Overkiz starts with `[F8811A](https://ouilookup.com/vendor/overkiz)`.

**Hostname**: gateway-xxxx-xxxx-xxxx
**MAC address**: F8:81:1A:xx:xx:xx

**Comment by PoVPoV29** [comment]
Do you need Somfy OUI equipement or help to code ?

**Comment by iMicknl** [comment]
![image](https://user-images.githubusercontent.com/1424596/101221520-263e4780-3688-11eb-9623-c47299f37a5b.png)

I just found out that they broadcast `_kixbox._tcp.`, which we could use perhaps.

**Comment by iMicknl** [comment]
Since we will support Rexel and CozyTouch soon under the TaHoma domain, it would be great to have autodiscover whem moving this integration to core.

If we can not do it based on the tcp, we can have a look at this in the future: https://github.com/home-assistant/core/pull/45087

**Comment by tillstaff** [comment]
I made a check with "avahi-discover" but I didn't find anything with my Cozytouch hub.

But I can confirm that I have the same DHCP specification :
Hostname: gateway-xxxx-xxxx-xxxx
MAC address: F8:81:1A:xx:xx:xx

**Comment by iMicknl** [comment]
Thanks! I believe best way would be to utilise the `zeroconf` and `dhcp` discovery possibilities of Home Assistant.
