### ISSUE TITLE
Tahoma integration doesn't find my awnings

### ISSUE THREAD

**Issue by inconsx** [iMicknl/ha-tahoma#266]
**Issue Description

I've integrated Tahoma to Home Assistant.
All of my covers where found but not my awnings

**To Reproduce**
Delete Integration and redo it.

**Expected behavior**
Every device should be found and migrated to 

**Screenshots**

**Environment (please complete the following information):**

- **ha-tahoma version: 2020.3.4-15
- **Home Assistant version: 0.114.4
- **Platform awnings from brand Markilux (somfy io)

**Device:** (if your problem is related to a specific device)
n/a

- **Model**: [e.g. PositionableScreen, can be gathered from device list in HA]
- **Type**: [e.g. `io:DimmableLightIOComponent`, can be gathered from device page in HA looking at Firmware] `/config/devices/dashboard`]

**Additional context**
n/a

n/a

**Comment by tetienne** [comment]
Can you please give more details? Have you look in the log if any message related to our component? I own myself a Markelux awnings, and I can see it.

**Comment by iMicknl** [comment]
Please have a look at '[Device not supported / working correctly
](https://github.com/iMicknl/ha-tahoma#device-not-supported--working-correctly)' in the readme. It would be helpful if you turn on debug mode and share the log.

Could you share a screenshot of your integrations / devices page as well?

**Comment by inconsx** [comment]
hi,

Unfortunately  can't see anything in the logs related to this integration.
The following are missing:
![awnings](https://user-images.githubusercontent.com/22166678/93447764-13ab4200-f8d3-11ea-97f5-aef759075b94.PNG)

**Comment by vlebourl** [comment]
Have you turned on debug mode for the integration?

**Comment by iMicknl** [comment]
> Have you turned on debug mode for the integration?
> [iMicknl/ha-tahoma#enable-debug-logging](https://github.com/iMicknl/ha-tahoma#enable-debug-logging)

And please share a screenshot of your integrations / devices page in Home Assistant (`/config/devices/dashboard`). How did you install this custom component? I wonder if you are using our version or the default core version..

**Comment by inconsx** [comment]
enabled the debugger.
I've used the oAuth link.

**Comment by vlebourl** [comment]
do you see messages such as those:

```
2020-09-17 10:59:35 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.031 seconds
2020-09-17 10:59:35 DEBUG (MainThread) [custom_components.tahoma] Unsupported TaHoma device detected (io:IORemoteController - RemoteController - RemoteControllerOneWay)
```

**Comment by iMicknl** [comment]
@inconsx you are using the `Somfy` integration, where this is the `Somfy TaHoma` integration. Unfortunately the Somfy integration, which is using the official API, doesn't support all devices. This integration is using the onofficial API used by tahomalink.com and thus supports all devices out of the box.

Please have a look at the [Installation](https://github.com/iMicknl/ha-tahoma#installation) section of the README. I will close this issue for now, feel free to reopen if you still have issues after installing the new integration.

**Comment by inconsx** [comment]
made it and works perfectly now. Thanks
