### ISSUE TITLE
Battery level for Somfy Door sensor / Smoke detectors

### ISSUE THREAD

**Issue by thomasgregg** [iMicknl/ha-tahoma#269]
I have a few door sensor which are used mainly with my Protexial IO system. But they are also visible in my Tahoma and therefore are visible in HA and work great for automations.

Door Sensor --> Protexial --> Tahoma --> HA

The door sensors show a nice battery level in Tahoma

![image](https://user-images.githubusercontent.com/2538782/93516952-06ba3d00-f92b-11ea-8c51-788d7c9ab030.png)

But I can't find the battery level in HA. Is there any way to get this is as well?

![image](https://user-images.githubusercontent.com/2538782/93517137-51d45000-f92b-11ea-91fc-4391f221543e.png)

Same thing for some Somfy smoke detectors I have:

![image](https://user-images.githubusercontent.com/2538782/93517212-69133d80-f92b-11ea-96cf-6bd981d83377.png)

**Comment by tetienne** [comment]
Hi,

Can you please look in the developper tools, if you see more attribute for your device?

For a cover for instance, we have this kind of information:
```
current_position: 0
ui_class: RollerShutter
widget: PositionableRollerShutter
controllable_name: io:RollerShutterGenericIOComponent
rssi_level: 92
core:NameState: Volet baie vitré
core:PriorityLockTimerState: 0
core:StatusState: available
core:DiscreteRSSILevelState: good
core:RSSILevelState: 92
core:ClosureState: 100
core:OpenClosedState: closed
friendly_name: Baie vitrée
supported_features: 527
device_class: shutter
```

**Comment by thomasgregg** [comment]
It just shows me this in the developer tools for the entity:

`ui_class: ContactSensor
widget: ContactSensor
controllable_name: 'rtds:RTDSContactSensor'
'core:PowerSourceType': battery
'core:ContactState': closed
friendly_name: Entrance door
device_class: opening
`

**Comment by iMicknl** [comment]
Is the battery sensor data near real-time? Looking at your device definitions, there is a `core:SensorDefectState` which could output `lowBattery`. I can not find any other indication of battery health in the device definition. (and otherwise, this would have be supported out of the box since we read the battery state if available).

We would need to figure out if tahomalink.com is interpreting `core:SensorDefectState` to show some kind of battery value...

```json
{
	"commands": [],
	"states": [{
		"values": ["closed", "open"],
		"type": "DiscreteState",
		"qualifiedName": "core:ContactState"
	}, {
		"values": ["dead", "lowBattery", "maintenanceRequired", "noDefect"],
		"type": "DiscreteState",
		"qualifiedName": "core:SensorDefectState"
	}],
	"dataProperties": [],
	"widgetName": "ContactSensor",
	"uiClass": "ContactSensor",
	"qualifiedName": "rtds:RTDSContactSensor",
	"type": "SENSOR"
}
```

```json
{
	"commands": [],
	"states": [{
		"values": ["dead", "lowBattery", "maintenanceRequired", "noDefect"],
		"type": "DiscreteState",
		"qualifiedName": "core:SensorDefectState"
	}, {
		"eventBased": true,
		"values": ["detected", "notDetected"],
		"type": "DiscreteState",
		"qualifiedName": "core:SmokeState"
	}],
	"dataProperties": [],
	"widgetName": "SmokeSensor",
	"uiClass": "SmokeSensor",
	"qualifiedName": "rtds:RTDSSmokeSensor",
	"type": "SENSOR"
}
```

**Comment by thomasgregg** [comment]
I can confirm that the battery sensor data in Protexial and Tahoma are very accurate. Protexial even has a possibly to send you a sms if battery is low. Please  let me know if there is anything I can do to test etc.

**Comment by iMicknl** [comment]
> I can confirm that the battery sensor data in Protexial and Tahoma are very accurate. Protexial even has a possibly to send you a sms if battery is low. Please let me know if there is anything I can do to test etc.

It looks like tahomalink.com is getting the battery status from a different endpoint, since it is not included in the device states... 

Could you perhaps have a look at the XHR requests in your browser console, while requesting the battery states? I would like to understand if they leverage a certain endpoint to retrieve those states.

**Comment by thomasgregg** [comment]
I am not sure if this is what you are looking for but I tried. Please let me know if this helps or if you need anything else.

![image](https://user-images.githubusercontent.com/2538782/93743245-fe465880-fbef-11ea-84be-a596f2c685e4.png)

**Comment by iMicknl** [comment]
This is unfortunately not the one I am looking for.

Steps to collect F12 traces:
1. Open the browser and log in:
2. Open Developer Tools ( F12- function key)
3. Go to the network tab
4. Refresh the page and start recording (red button)
5. Reproduce the issue and download the traces in .HAR format and share it with us 

![image](https://user-images.githubusercontent.com/1424596/93812686-46966280-fc52-11ea-9f1f-daae22b89a08.png)

Could you share this .HAR via email with me? (see profile). This file can contain some of your ids (gateway id etc.) that you should not share publicly. 
If you are not comfortable sharing this with me, no problem. In that case we need to figure out if you can figure out in which XHR request they are sending the battery data. (possibly you can search for 'battery' or something)

**Comment by thomasgregg** [comment]
Just sent it to your email.

**Comment by iMicknl** [comment]
Thanks for providing your HAR, @thomasgregg. I had an extensive look and I was not able to find where the information is coming from.. Unfortunately there is no mention of battery state and information in any of the API calls.
