### ISSUE TITLE
Group entities don't work with device specific services (e.g. tahoma.set_cover_position_low_speed)

### ISSUE THREAD

**Issue by llevering** [iMicknl/ha-tahoma#275]
**Describe the bug**
Group entities do not work with tahoma.set_cover_position_low_speed service. Which is a great addition BTW!

**To Reproduce**

1. Create a group of covers
2. From the services-tab execute tahoma.set_cover_position_low_speed service with entity_id: cover.group
3. Nothing happens...
4. In the log you will find: Unable to find referenced entities cover.group

**Expected behavior**
You would expect the function to work with cover groups just as with individual covers. I do understand that might be more easily said than done. I didn't think it would be different from a user perspective, but from a developer perspective I guess it might be a bit more difficult.

**Environment (please complete the following information):**

- **ha-tahoma version:** [e.g. 2.3.1]
- **Home Assistant version:** [e.g. 0.115.2]
- **Platform**: cover

**Comment by iMicknl** [comment]
We did register `set_cover_position_low_speed` as an entity service which should support groups by default. Did you try pass the same group to `cover.set_cover_position` and did it work?

Are you using `cover.group` as a group? Or is this a typo and are you using `group.xxxx`?

**Comment by llevering** [comment]
The actual name is 'cover.boven' I put there as generic example. :)

`cover.set_cover_position` does work as expected (but didn't try, so good to test).  I test with the data:
```
entity_id: cover.boven
position: 29
```
If it helps I would be willing to give you remote access.

**Comment by iMicknl** [comment]
I will have a look upcoming week. Could you please verify that it works with `cover.set_cover_position`? :-). Just to be sure that the entity services do support passing a group.

**Comment by llevering** [comment]
Yes it does, I tried to say that with the earlier post, but I see it was ambiguous. Now I think back: I literally did a search and replace to switch from `cover.set_cover_position` to `tahoma.set_cover_position_low_speed`.

**Comment by iMicknl** [comment]
Are you sure that all entities in the group belong to the `tahoma` integration and the `cover` platform? (+ all of the entities support the low speed movement)

I had a look at the implementation and I couldn't spot the issue. We implement `register_entity_service`, which should take care of groups by default..

**Comment by llevering** [comment]
I've just retested it. And I am absolutely sure. Under the services tab I first tried setting two covers in a group with `tahoma.set_cover_position_low_speed` and when that failed I changed the function `cover.set_cover_position` with same service data and then it immediately worked. The covers are exactly the same types and in a group.

This is the data from the 'States' of the covers and the group. But it is failing for other groups as well:
![image](https://user-images.githubusercontent.com/2834866/95046062-9dd11400-06e3-11eb-8520-ab843c186e6a.png)

**Comment by llevering** [comment]
No change, still not actions on executing the service and still the same error in the log:  '[homeassistant.helpers.service] Unable to find referenced entities cover.kledingkamer'

**Comment by iMicknl** [comment]
@llevering I had a quick look, but I couldn't find the issue unfortunately... We use `async_register_entity_service` which is provided by Home Assistant. The original cover implementation is using the same implementation, where it is working for you.

Could you try the `tahoma.set_cover_my_position` function?

**Comment by llevering** [comment]
That gives the same (lack of) reaction and error in the logs. It is such a strange issue as you mentioned that all call uses the same backend to resolve the group part of the call. It is only a minor so don't invest to much time. I hope more people show up with having the same error so we can find common ground on the core of the issue.

**Comment by mstuij** [comment]
I have the same problem:

`type: button
tap_action:
  action: call-service
  service: tahoma.set_cover_position_low_speed
  service_data:
    entity_id: cover.westkant_cover_group
    position: 100
entity: cover.westkant_cover_group
show_state: true
show_icon: true
`

This doesn't works, it give this error in  the log:

`Logger: homeassistant.helpers.service
Source: helpers/service.py:102
First occurred: 11:21:05 (13 occurrences)
Last logged: 11:35:35

Unable to find referenced entities cover.westkant_cover_group`


When I use cover.set_cover_position it works

**Comment by iMicknl** [comment]
@mstuij does it work for individual entities and could you verify that all items in your group support the low speed movement?

**Comment by mstuij** [comment]
@iMicknl 

Yes for a single entity it works correctly. 
I have 10 x Somfy RS100 IO motors. So they are all the same specifications and have all the low speed.


My group is defined:

```
cover:
  - platform: template
    covers:

      westkant_cover_group:
        friendly_name: "West kant"
        optimistic: false
        open_cover:
          - service: tahoma.set_cover_position_low_speed
            data:
              entity_id: cover.04_computer_kamer, cover.05_hal_1e_etage, cover.06_zijraam
              position: 100
        close_cover:
          - service: tahoma.set_cover_position_low_speed
            data:
              entity_id: cover.04_computer_kamer, cover.05_hal_1e_etage, cover.06_zijraam
              position: 0
        stop_cover:
          - service: cover.stop_cover
            data:
              entity_id: cover.04_computer_kamer, cover.05_hal_1e_etage, cover.06_zijraam
        set_cover_position:
          - service: tahoma.set_cover_position_low_speed
            data:
              entity_id: cover.04_computer_kamer, cover.05_hal_1e_etage, cover.06_zijraam
              position: "{{position}}"
        position_template: "{{ state_attr('cover.04_computer_kamer', 'current_position' ) | int }}"
        icon_template: >-
          {% if is_state('sensor.westkant_cover_group', 'open') %}
            mdi:window-open
          {% else %}
            mdi:window-closed
          {% endif %}



sensor:
  - platform: template
    sensors:
      westkant_cover_group:
        value_template: >-
          {% if is_state('cover.04_computer_kamer', 'open') %}
            open
          {% elif is_state('cover.05_hal_1e_etage', 'open') %}
            open
          {% elif is_state('cover.06_zijraam', 'open') %}
            open
          {% else %}
            closed
          {% endif %}


```

**Comment by iMicknl** [comment]
@llevering @mstuij does the `tahoma.set_cover_my_position` work with groups?

**Comment by mstuij** [comment]
@iMicknl 

No also an error:

Logger: homeassistant.helpers.service
Source: helpers/service.py:102
First occurred: 15:23:05 (2 occurrences)
Last logged: 15:23:29

Unable to find referenced entities cover.westkant_cover_group

**Comment by iMicknl** [comment]
Thanks, at least that one I am able to debug myself locally. Currently my time is limited and the amount of (other) issues / feature requests in this repo is quite high at the moment, thus I won't be able to have a look at this any time soon.

If someone else has some Python / Home Assistant knowledge, feel free to give this issue a look 👍🏻.

**Comment by iMicknl** [comment]
@mstuij does this work with the latest version of ha-tahoma and the latest Home Assistant version? Recently quite a lot changed around services, thus perhaps this works now. :-)

**Comment by mstuij** [comment]
Unfortunately doesn't work it with latest versions. 

What I noticed is that in new Developer tools on the services tab: when you choose the tahoma.set_cover_position_low_speed service you couldn't choose the cover groups.

**Comment by iMicknl** [comment]
Could you give https://github.com/iMicknl/ha-tahoma/archive/refs/heads/enhancement/add-low-speed-switch.zip a try? Extract this file and place `custom_components/tahoma` in your `custom_components` folder.

See https://github.com/iMicknl/ha-tahoma/pull/497 for more context.

**Comment by mstuij** [comment]
I don't know if i do everything right but the covers are not going down. But there is also no error log. This is how I have implemented a button:

`type: custom:button-card
name: West sluiten
tap_action:
  action: call-service
  confirmation:
    text: Westkant alle rolluiken sluiten?
  service: tahoma.set_cover_position_low_speed
  service_data:
    entity_id: cover.westkant_cover_group
    position: 0
entity: cover.westkant_cover_group
show_icon: true
icon: mdi:window-shutter`


Another thing is that I can still not select a cover group in the developers tools when I have selected the tahoma.set_cover_position_low_speed service.

**Comment by iMicknl** [comment]
@mstuij the version that I linked should have a switch per cover, where you can set it to low speed or not. You can than just use the normal cover services. Are you able to see the switch?

**Comment by mstuij** [comment]
@iMicknl 
No I don't see it. I have deleted all original files in the custom_components/tahoma folder and copied the files of your zip (custom_components/tahoma) in this folder. After that I restarted home assistant and I don't see it.

Do I need some configuration?

**Comment by tetienne** [comment]
@mstuij normally no. I have to see why only me see the switch...

**Comment by tetienne** [comment]
@mstuij Can you download again https://github.com/iMicknl/ha-tahoma/archive/refs/heads/enhancement/add-low-speed-switch.zip ? I found my mistake.

**Comment by mstuij** [comment]
@tetienne I still don't see the new option.

**Comment by tetienne** [comment]
@mstuij where did you look? It should be in device page of your cover.

**Comment by mstuij** [comment]
![cover_device](https://user-images.githubusercontent.com/75884924/128590824-ce42b955-aa65-43a8-8a92-d945283039c6.png)

**Comment by tetienne** [comment]
I double checked. I was too tired yesterday night..  I forgot to replace a variable.

**Comment by mstuij** [comment]
Okay no problem. When you give me a new version I will test it directly.

**Comment by tetienne** [comment]
@mstuij It should be ok now. You can retry my branch.

**Comment by mstuij** [comment]
@tetienne 

The switch is now visible:

![cover_device2](https://user-images.githubusercontent.com/75884924/128643212-f34dc269-3f91-461a-add6-21db03b10064.png)

But it seems to be that the covers is always running on slow speed regardless of which lightning button I press

**Comment by tetienne** [comment]
You are well moving your cover from HA?

**Comment by tetienne** [comment]
@mstuij Indeed, don’t know why I didn’t see thit. Should be ok now.

**Comment by nbeernink** [comment]
Works for me now. 👍

**Comment by mstuij** [comment]
@tetienne Now it works also for me (slow and fast speed).

1) I don't see the discrete switch for cover groups?
2) Is it not better to have only feather icon instead of the 2 lightning icons (the tahoma app has also only 1 feather icon: on or off)

**Comment by tetienne** [comment]
@mstuij Perfect !

1. A component cannot do this.
2. I don’t retrieve the state from the Somfy server. They don’t return it. So I declared the switch with an [assumed state](https://developers.home-assistant.io/docs/core/entity/#generic-properties). HA displays assumed state switch using two icons (on and off)

You can create a group with all the low speed switch, to quickly toggle the low mode for all your covers. You can also implement an automation to turn on or off this group at a given time (eg morning and night).

**Comment by mstuij** [comment]
@tetienne Okay so for all my cover groups I should create dummy switches by my self and in the cover template group I have to check the dummy switch.

Then when it is fast speed --> I should set your switches of all covers in this cover group to fast speed and open/close the covers. Then I have to restore your switch (because that is nicer to have the old state to those swicthes)

So isn't it better to keep your slow speed service? Because I don't have to set and restore all the switches for all covers in the group.

**Comment by tetienne** [comment]
Can you tell me you use currently the slow speed service (automation, script) ?

**Comment by mstuij** [comment]
I use:

- Script
- Node-RED
- Cover templates

**Comment by tetienne** [comment]
Can you show me an example of scripts and templates?

**Comment by mstuij** [comment]
Script:

`alle_rolluiken_sluiten_silent:
  alias: Alle rolluiken sluiten silent
  sequence:
  - service: tahoma.set_cover_position_low_speed
    data:
      position: 0
    entity_id: cover.01_master_bedroom, cover.02_voorraam_klein, cover.03_voorraam_groot,
      cover.04_computer_kamer, cover.05_hal_1e_etage, cover.06_zijraam, cover.07_badkamer,
      cover.08_logeerkamer, cover.09_achterdeur, cover.10_achterraam
  mode: single
  icon: hass:window-shutter-open
`

Template:

`cover:
  - platform: template
    covers:
      voorraam_cover_group:
        friendly_name: "Voorraam"
        device_class: shutter
        optimistic: false
        open_cover:
          - service: tahoma.set_cover_position_low_speed
            data:
              entity_id: cover.02_voorraam_klein, cover.03_voorraam_groot
              position: 100
        close_cover:
          - service: tahoma.set_cover_position_low_speed
            data:
              entity_id: cover.02_voorraam_klein, cover.03_voorraam_groot
              position: 0
        stop_cover:
          - service: cover.stop_cover
            data:
              entity_id: cover.02_voorraam_klein, cover.03_voorraam_groot
        set_cover_position:
          - service: tahoma.set_cover_position_low_speed
            data:
              entity_id: cover.02_voorraam_klein, cover.03_voorraam_groot
              position: "{{position}}"
        position_template: "{{ state_attr('cover.03_voorraam_groot', 'current_position' ) | int }}"
        icon_template: >-
          {% if is_state('sensor.voorraam_cover_group', 'open') %}
            mdi:window-shutter-open
          {% else %}
            mdi:window-shutter
          {% endif %}
`

**Comment by mstuij** [comment]
What are the plans of the tahoma.set_cover_position_low_speed service?

I need the slow speed support for a cover template and cover groups.

At the moment the bug is still there, so I can't call the service for the cover template and cover groups. 


Some information about my use case:

I have to use a cover template because I have some "window open" protection with reed switches. So I need to redirect all commands (open, close, stop, position) from the virtual cover to the real cover with all my safety checks between.

@tetienne You say that it is not possible to have slow speed switches for cover template/groups. Is it an idea to just kee the slow speed service and try to solve it for the cover templates/groups?

**Comment by tetienne** [comment]
I would try to see why the service is not working for the group. 
Meanwhile, what about grouping all the low speed switches within a group? In one toggle you will be able to switch all the covers, as downside, you lost the previous configuration.

**Comment by mstuij** [comment]
Okay so for all my cover groups I have to create template switches? 

By the way when you have created a cover group or cover template you could see it in the developer tools.

When selecting cover.open you see the cover groups and cover tenplates listed in the dropdown.

When you choose the tahoma low speed service you don’t see any cover group or cover template listed in the dropdown.

**Comment by tetienne** [comment]
I was talking about a simple group https://www.home-assistant.io/integrations/group 

In your script, you toggle the low speed switches group and then move your cover.

**Comment by tetienne** [comment]
> When you choose the tahoma low speed service you don’t see any cover group or cover template listed in the dropdown.

Good to know.

**Comment by iMicknl** [comment]
Should be fixed now with new cover structure for low speed. Otherwise I open this one again.
