### ISSUE TITLE
Can't cancel action started in Tahoma with HomeAssistant

### ISSUE THREAD

**Issue by thijsdejong** [iMicknl/ha-tahoma#283]
- [x] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**
When my homeassistant instance triggers a Tahoma scene and my covers move, I try to press the stop button in HomeAssistant on one of those covers. Nothing happens. The same goes for manually opening a cover using the tahoma app (not using a scene).

**To Reproduce**

1. Open or close a cover in the Tahoma app
2. Press stop on that cover in HomeAssitant

**Expected behavior**
The cover stops moving.

**What actually happens**
Nothing, the cover keeps moving.

**Environment (please complete the following information):**

- **ha-tahoma version:** 2.3.1
- **Home Assistant version:** 0.115.6
- **Platform**: cover

**Comment by iMicknl** [comment]
Could you give https://github.com/iMicknl/ha-tahoma/pull/263 a try?

**Comment by thijsdejong** [comment]
@iMicknl Both of these have this issue.
```
ui_class: RollerShutter
widget: PositionableRollerShutterWithLowSpeedManagement
controllable_name: io:RollerShutterWithLowSpeedManagementIOComponent
```
```
ui_class: Window
widget: PositionableTiltedWindow
controllable_name: io:WindowOpenerVeluxIOComponent
```

Just tried that PR, works wonderfully, for both devices it's an instant stop. 👍

**Comment by iMicknl** [comment]
Great to hear! The functionality is ready for a while, but I didn't had time yet to clean up the code..
Hopefully I will have some time to simplify the code and to release this fix.

**Comment by iMicknl** [comment]
Great to hear! I just pushed a new version of the code, could you give it a try? Should be merged soon hopefully.

**Comment by thijsdejong** [comment]
@iMicknl fyi, I just tested master(5528c04) and it still works perfectly 👍
