### ISSUE TITLE
Unit_Percentage failure with last home assistant 0.115.6

### ISSUE THREAD

**Issue by oopptt** [iMicknl/ha-tahoma#284]
Hi guys, 

after updating my home assistant I'm getting this error below when starting:

Logger: homeassistant.setup
Source: setup.py:280
First occurred: 3:16:37 (1 occurrences)
Last logged: 3:16:37

Unable to prepare setup for platform tahoma.sensor: Platform not found (cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/const.py)).

Not sure if it's failing something as I have somfy+tahoma both working together, somfy API for covers and tahoma for pergolas and others. Will check further to try to get the unit failing... Any idea of what this error could mean? 

Thanks in advance!

**Comment by vlebourl** [comment]
yes, it's been renamed recently, but I thought we had updated it. let me check

**Comment by vlebourl** [comment]
what version of Tahoma are you using? this was fixed when HA 0.115 went out. be sure to use the last release of the component.

**Comment by iMicknl** [comment]
@oopptt thanks for reporting, make sure you update to `v2.3.1`. As @vlebourl mentioned, we updated this integration to be compatible with 0.115.

If it is not resolved with the latest version of this integration, feel free to reopen this issue.
