### ISSUE TITLE
Invalid auth after reboot

### ISSUE THREAD

**Issue by tomtomdu85** [iMicknl/ha-tahoma#291]
I have logrotate activated.
So, each days (at 7:00am) my home assistant reboot.

After that, I've got an error in the tahoma integration :

```
Logger: custom_components.tahoma
Source: custom_components/tahoma/__init__.py:90
Integration: Somfy TaHoma (documentation, issues)
First occurred: 7:00:49 AM (1 occurrences)
Last logged: 7:00:49 AM

invalid_auth
```

This is my logrotate script :

```
/var/log/home-assistant.log {

    daily
    rotate 4
    compress

    delaycompress
    missingok

    create 777 root root
    postrotate
        /bin/systemctl restart home-assistant.service
    endscript
}
```

If I reboot manually, no problems. Tahoma is OK

Do you have this bug too?

**Comment by iMicknl** [comment]
This is related to https://github.com/iMicknl/ha-tahoma/issues/278. 

The reason why you see `invalid_auth` is since we catch the `BadCredentialsException` on start. Currently the only way to recover is to 'reload' the integration, but we are working on #285 to have this in a nicer way.

**Comment by TheFes** [comment]
How do I reload the integration?

**Comment by vlebourl** [comment]
What version of HA are you using? Starting 0.115 (I think), reload is available in the integration page:
![image](https://user-images.githubusercontent.com/5701372/96420710-1cef3d80-11f6-11eb-8c2f-bf72cb17e177.png)

**Comment by TheFes** [comment]
Must have looked with my nose instead of with my eyes.
The arrow made it very clear ;-)

Thanks!

BTW, don't know if you want to share your e-mail address publicly on the internet.

**Comment by vlebourl** [comment]
> BTW, don't know if you want to share your e-mail address publicly on the internet.

indeed... used my nose as well...

**Comment by iMicknl** [comment]
Let's close this one since it is tracked in https://github.com/iMicknl/ha-tahoma/issues/278.
