### ISSUE TITLE
service "cover/stop_cover". 'dict_items' object is not reversible

### ISSUE THREAD

**Issue by clemalex824** [iMicknl/ha-tahoma#296]
- [x] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

Describe the bug:
Since few days i got : "echec d'appel du service "cover/stop_cover". 'dict_items' object is not reversible" when i call stop service of tahoma. Open/Close are ok.

Environment : 
ha-tahoma version: v2.3.4
Home Assistant 0.116.2
tahomalink: 2020.4.4-18

Device:
current_position: 0
ui_class: RollerShutter
widget: PositionableRollerShutterWithLowSpeedManagement
controllable_name: io:RollerShutterWithLowSpeedManagementIOComponent
rssi_level: 100
core:NameState: volet
core:PriorityLockTimerState: 0
core:StatusState: available
core:DiscreteRSSILevelState: good
core:RSSILevelState: 100
core:ClosureState: 100
core:OpenClosedState: closed
core:Memorized1PositionState: 78
core:TargetClosureState: 100
friendly_name: volet_anais
supported_features: 1551
device_class: shutter

**Comment by iMicknl** [comment]
Thanks, this should be an easy fix. I will have a look at it this week.

Does it happen perhaps when you initiate the cover movement outside Home Assistant? And you receive the error when you cancel the cover movement from HA.

**Comment by clemalex824** [comment]
Service call failed always in HA.

I will test with 'my' button in ha tomorrow.

**Comment by clemalex824** [comment]
tahoma.set_cover_my_position works normally.

**Comment by iMicknl** [comment]
Which Python version are you running? If the service call always fails, I believe your Python version might be out of date.

**Comment by clemalex824** [comment]
python 3.7.3. i will update

**Comment by iMicknl** [comment]
Ok, let me know when this doesn't resolve your issue. Latest Home Assistant (supervised) is currently using python_version 3.8.5.

**Comment by clemalex824** [comment]
I turn the ha core version and I need some time to update my venv. I come back when it's done

**Comment by iMicknl** [comment]
I believe this issue was caused by Python 3.7. Since Home Assistant moved to Python 3.8 as their minimum version, we implemented some features that were only supported in Python 3.8.

If you are using a venv for Home Assistant, it is important that you keep your Python version up to date.

**Comment by clemalex824** [comment]
Is it normal that ha-tahoma uses functions from python 3.8 which makes python 3.7 obsolete while the core only warns for version 0.118 the obsolescence of python 3.7 ?

**Comment by iMicknl** [comment]
@clemalex824 to be honest, I was not aware of Python 3.7 not being obsolete yet in combination with Home Assistant. In order to support Python 3.7, we had to add quite some extra code, which will clutter this integration. Since we target to get this custom_component in core, it makes more sense to target the Python version they use in core and to keep our code as simple as possible.

I will have a better look in the future and will make sure we mention the required Python version in the changelog. :-)

**Comment by clemalex824** [comment]
Thank you for your reply. I totally understand the goal. I just didn't want to find myself in the same situation for python 3.9. If this is present in the changelog it's perfect. Thanks again for this integration which works very well ;-)
