### ISSUE TITLE
Add support for Hitachi Heating System

### ISSUE THREAD

**Issue by Seb0101** [iMicknl/ha-tahoma#298]
Hi,
I have 8 rollers, which work fine with your component (except when Somfy closes http connection, it did yesterday).
I also have 4 air conditioners, today I manage them with homebridge connected to tahoma, and after HA. I think some of my problems come from there.
Is it possible to add them to your component ?
Hitachi Heating System.
Thanks for your answer.
Sébastien

**Comment by vlebourl** [comment]
Hi, at the moment the development of new features is on hold as we are trying to PR into core, and to solve our problem with Somfy regarding server usage (cf #289).

We will still add your request to the TODO list. Could you please open a new issue following and filling out the template here: https://github.com/iMicknl/ha-tahoma/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=

Cheers

**Comment by Seb0101** [comment]
Hi, it’s done.
And thanks for all your work !
Regards

Le 19 oct. 2020 à 10:35, Vincent Le Bourlot <notifications@github.com> a écrit :


Hi, at the moment the development of new features is on hold as we are trying to PR into core, and to solve our problem with Somfy regarding server usage (cf #289 <https://github.com/iMicknl/ha-tahoma/issues/289>).

We will still add your request to the TODO list. Could you please open a new issue following and filling out the template here: https://github.com/iMicknl/ha-tahoma/issues/new?assignees=&labels=enhancement&template=feature_request.md&title= <https://github.com/iMicknl/ha-tahoma/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=>
Cheers
