### ISSUE TITLE
Avoid polling for stateless (RTS) devices

### ISSUE THREAD

**Issue by larsvinc** [iMicknl/ha-tahoma#300]
- [x] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Is your feature request related to a problem? Please describe.**
It is related to https://github.com/iMicknl/ha-tahoma/issues/289

**Describe the solution you'd like**
Since all my devices are stateless, it is my understanding from the issue tracker above that the API usage with Somfy can be greatly simplified, and therefore relieve the traffic on their API. When this is the case, I believe that this is a good solution for all (simplified implementation?, reduced traffic for all).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tetienne** [comment]
Nice idea. We can try to detect if all the devices are stateless and/or add an option to avoid polling!

**Comment by PoVPoV29** [comment]
Can you use that : controllable_name: 'rts:RollerShutterRTSComponent'
RTS is stateless : radio signal in one way
IO is not stateless : radio signal in two way

**Comment by tetienne** [comment]
@PoVPoV29 We don’t have to check the protocol, Somfy returns a states object. We just have to check its presence or not.

**Comment by tetienne** [comment]
@PoVPoV29 @larsvinc If you have RTS devices, can I ask you to test this branch and in particular the stop command?

**Comment by larsvinc** [comment]
Hi,

Tested the branch. No devices were found.
