### ISSUE TITLE
Cannot import name 'CoordinatorEntity'

### ISSUE THREAD

**Issue by barryhartman** [iMicknl/ha-tahoma#320]
- [X] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**
Version 2.3.6 was working correctly with no errors. I've updated to 2.3.7 by removing old 2.3.6 folder and placing new tahoma folder in the custom_components. Rebooted and saw the following error in the log. Running HA version 0.110.7

Got an invalid config error stating: 
The following integrations and platforms could not be set up:
- tahoma.cover

Debug log:
Log Details (ERROR) 
Logger: homeassistant.setup 
Source: setup.py:253 
First occurred: 1:56:58 PM (1 occurrences) 
Last logged: 1:56:58 PM
```
Unable to prepare setup for platform tahoma.cover: Platform not found (cannot import name 'CoordinatorEntity' from 'homeassistant.helpers.update_coordinator' (/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py)).
```

**To Reproduce**
See bug description.

**Expected behavior**
No errors and a working component

**Screenshots**
N/a

**Environment (please complete the following information):**
- **ha-tahoma version:** 2.3.7
- **Home Assistant version:** 0.110.7
- **Platform**:  Somfy covers with a connexoon box 

**Additional context**
When reverting to version 2.3.6 the error is gone.

**Comment by tetienne** [comment]
Indeed CoordinatorEntity was introduced with the 0.115. You will have to update your HA instance. Currently, the latest is 0.119.

**Comment by barryhartman** [comment]
Ah clear. I was already looking for a HA version requirement, but could not find it. 
Thanks for the information.

**Comment by tetienne** [comment]
@barryhartman you can find it [here](https://github.com/iMicknl/ha-tahoma/blob/master/hacs.json) but it was not correct. I will fix it. Thx for the report.
