### ISSUE TITLE
volant.cover shows wrong status

### ISSUE THREAD

**Issue by inconsx** [iMicknl/ha-tahoma#324]
- [x] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**
the volant.cover is moved in but status is shown as open

**To Reproduce**
move in volant.cover

**Expected behavior**
moved in should mean 'close' instead of 'open'.

**Screenshots**
![image](https://user-images.githubusercontent.com/22166678/102080826-6da69f80-3e0f-11eb-827e-e6802b4892fd.png)

**Environment (please complete the following information):**

- **ha-tahoma version:** 2020.6.4-15
- **Home Assistant version:** 2020.12.6
- **Platform**: Awening

**Device:** (if your problem is related to a specific device)

- **Model**: [e.g. PositionableScreen, can be gathered from device list in HA]
- **Type**: io:AwningValanceIOComponent
`/config/devices/dashboard`]

**Additional context**
current_position: 100
ui_class: Awning
widget: AwningValance
controllable_name: 'io:AwningValanceIOComponent'
rssi_level: 14
'core:NameState': Volant
'core:PriorityLockTimerState': 0
'core:StatusState': available
'core:DiscreteRSSILevelState': low
'core:RSSILevelState': 14
'core:ClosureState': 0
'core:OpenClosedState': open
'core:Memorized1PositionState': 105
friendly_name: Volant
supported_features: 527
device_class: awning

**Comment by tetienne** [comment]
Can you please confirm the release number of the component? I don't recognize the one you please provide.

The latest release is 2.3.8.

**Comment by inconsx** [comment]
sorry, yes it's 2.3.8.

**Comment by tetienne** [comment]
@inconsx Can you tell me if at least the open and close command work?

**Comment by iMicknl** [comment]
@inconsx could you give https://github.com/iMicknl/ha-tahoma/archive/fix/awning_valance.zip a try? Extract this file and place `custom_components/tahoma` in your `custom_components` folder. This should solve your issues.

We have had many reports with the same device where their position was reversed, after the change we made for your issue.
