### ISSUE TITLE
Unable to change (tilt)position via automations

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#33]
**Describe the bug**
When you use a `cover` device in your automation, you are not able to set the tilt_position or position as a trigger or action.

**To Reproduce**
1. Go to new automation
2. Create a new action of type 'device' and choose your cover device.
3. Action: Set xxxx tilt position
4. Position is a greyed out field.

**Expected behavior**
A way to set the tilt_position or position via automations.

**Screenshots**
<img width="615" alt="Screenshot 2020-06-07 at 15 27 07" src="https://user-images.githubusercontent.com/1424596/83970016-7ef87780-a8d3-11ea-8deb-1b46e9405ad4.png">

**Environment (please complete the following information):**
 - **Home Assistant version:** 0.111.0.dev0
 - **Platform**: cover

**Comment by vlebourl** [comment]
Covers controlled by Homekit integration, completely independent of tahoma, have the same bug in automation. It's a bug in their side.

**Comment by iMicknl** [comment]
Logged as https://github.com/home-assistant/core/issues/37414

**Comment by iMicknl** [comment]
Closing, since this is a bug in core frontend. 

Logged as: https://github.com/home-assistant/frontend/issues/6329, https://github.com/home-assistant/frontend/issues/6320, https://github.com/home-assistant/frontend/issues/6337
