### ISSUE TITLE
Integration does not show after installing using HACS

### ISSUE THREAD

**Issue by jeroenvanderschoot** [iMicknl/ha-tahoma#330]
- [x] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**
After installing using HACS the integration does not show up in Integrations

**To Reproduce**
1. Open HACS, install Tahoma custom component
2. Restart HA
3. Go the integrations
4. Select Add integration notice Tahoma component is missing

- **ha-tahoma version:** 2.3.8
- **Home Assistant version:** 2020.12.1
- **Platform**: [e.g. cover, sensor, binary_sensor]

**Device:** (if your problem is related to a specific device)

- **Model**: [e.g. PositionableScreen, can be gathered from device list in HA]
- **Type**: [e.g. `io:DimmableLightIOComponent`, can be gathered from device page in HA looking at Firmware] `/config/devices/dashboard`]

**Additional context**

Installing manually in configuration.yaml of HA gives me missing pyhome module error.
After adding the pyhome module using pip install (in docker container) it starts working for me

**Comment by jeroenvanderschoot** [comment]
maybe one thing to add here is that I had another folder tahoma.xxx folder in custom_components folder with a adjusted copy of the original tahoma code of HA

**Comment by iMicknl** [comment]
@jeroenvanderschoot has this been resolved already? Please make sure that you don't have any other `tahoma` components, in your `custom_components` folder.

**Comment by jeroenvanderschoot** [comment]
for me it works now, remove my own custom component

**Comment by iMicknl** [comment]
@jeroenvanderschoot great! Let me know if you have any other feedback / feature requests.
