### ISSUE TITLE
Migrate AtlanticPassAPCDHW (io:AtlanticPassAPCDHWComponent) from Climate to WaterHeater

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#337]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Change the AtlanticPassAPCDHWComponement from the Climate to the WaterHeater domain.

**Describe alternatives you've considered**

**Additional context**

**Comment by iMicknl** [comment]
@jgarec I was looking on implementing another device and I stumbled upon the WaterHeater domain in HA. Do you think it makes sense if I move the `AtlanticPassAPCDHWComponement` to the WaterHeater domain?

It will eventually look like this in HA:

<img width="402" alt="Screen Shot 2021-01-12 at 23 36 27" src="https://user-images.githubusercontent.com/1424596/104382770-045d9d80-552f-11eb-9060-1e862918a305.png">
<img width="382" alt="Screen Shot 2021-01-12 at 23 36 23" src="https://user-images.githubusercontent.com/1424596/104382774-06276100-552f-11eb-85cf-80c849e63594.png">

**Comment by jgarec** [comment]
Hi,

We still have to migrate this component.

**Comment by iMicknl** [comment]
Currently blocked since	`water_heater` domain doesn't support presets..

**Comment by iMicknl** [comment]
Great to see your contributions, @nyroDev! We also have [a Discord server](https://discord.gg/RRXuSVDAzG) which you can join as well, where the other developers are.

Currently ha-tahoma is stale, and we are working on migrating everything to Home Assistant core. When everything is in core, we will archive this repository in favor of core.
