### ISSUE TITLE
myfox:SomfyProtectAlarmController cannot be set in night armed mode and automation do not receive triggers

### ISSUE THREAD

**Issue by tofgun** [iMicknl/ha-tahoma#354]
**Describe the bug**
I have a somfy one camera declared in HA by the tahoma integration component as follow :
MyFoxAlarmController, par Somfy, Firmware: myfox:SomfyProtectAlarmController
1- Clicking the the arm-home does not work. The arm-absent and the disarm buttons/actions work properly. What could be the problem ?
2- I have created some automations triggered by the alarm state (Arming, Armed away, Armed night) but not any one of this state is triggering my automation. For example the following automation test does not work :

alias: Alarme Away ON
description: ‘’
trigger:

    platform: device
    device_id: 0874d314802ed9f218b813a8acf8ebea
    domain: alarm_control_panel
    entity_id: alarm_control_panel.somfy_one_salon
    type: armed_away
    condition: []
    action:
    device_id: 01e8270cf2cc3d50aa26b59f6e20c6c5
    domain: cover
    entity_id: cover.vr_bureau_2
    type: set_position
    position: 65
    mode: single

**To Reproduce**
Click on the arm home button
**Expected behavior**
The alarm should be set in night mode and the automation triggered with the right alarm state
**Screenshots**
![image](https://user-images.githubusercontent.com/77484063/105404160-f0e6bc80-5c29-11eb-9130-4b01b0708ddd.png)

**Environment (please complete the following information):**

- **ha-tahoma version:** Last
- **Home Assistant version:** core-2021.1.4
- **Platform**: alarm_control_panel
- 
MyFoxAlarmController
by Somfy
Firmware: myfox:SomfyProtectAlarmController 

**Additional context**

When requesting the Armed Night state, some logs are coming : 

2021-01-21 21:10:29 DEBUG (MainThread) [custom_components.tahoma.coordinator] EventName.DEVICE_STATE_CHANGED/None (device: ovp://1225-5490-6383/1954068, state: None -> None)
2021-01-21 21:10:29 DEBUG (MainThread) [custom_components.tahoma.coordinator] EventName.DEVICE_STATE_CHANGED/None (device: ovp://1225-5490-6383/4135936, state: None -> None)
2021-01-21 21:10:29 DEBUG (MainThread) [custom_components.tahoma.coordinator] EventName.DEVICE_STATE_CHANGED/None (device: ovp://1225-5490-6383/1954068, state: None -> None)
2021-01-21 21:10:29 DEBUG (MainThread) [custom_components.tahoma.coordinator] EventName.DEVICE_STATE_CHANGED/None (device: ovp://1225-5490-6383/4135936, state: None -> None)
2021-01-21 21:10:29 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.056 seconds

**Comment by tofgun** [comment]
I see that there is a dev tool like in HA. If I call directly the service through the dev tool to launch the alarm night mode, it works : the alarm is set in night mode. 

![image](https://user-images.githubusercontent.com/77484063/105486668-24b7f580-5caf-11eb-9eaf-c729f18ad4be.png)

![image](https://user-images.githubusercontent.com/77484063/105487280-1dddb280-5cb0-11eb-8391-0eeda2781792.png)

**Comment by iMicknl** [comment]
Could you share more about the possibilities you have via Tahoma app / tahomalink.com? (screenshot + details).

What should `arm home` do in your opinion? By the way, it looks like `arm_home` is not even supported for your device in HA, thus it is weird that the LoveLace shows this button.

```
{
	"commands": [{
		"commandName": "arm",
		"nparams": 0
	}, {
		"commandName": "disarm",
		"nparams": 0
	}, {
		"commandName": "getName",
		"nparams": 0
	}, {
		"commandName": "partial",
		"nparams": 0
	}, {
		"commandName": "setName",
		"nparams": 1
	}, {
		"commandName": "refreshAlarmStatus",
		"nparams": 0
	}, {
		"commandName": "setAlarmStatus",
		"nparams": 1
	}],
	"states": [{
		"values": ["offline", "online", "uninstalled"],
		"type": "DiscreteState",
		"qualifiedName": "core:CloudDeviceStatusState"
	}, {
		"values": ["detected", "notDetected"],
		"type": "DiscreteState",
		"qualifiedName": "core:IntrusionState"
	}, {
		"type": "DataState",
		"qualifiedName": "core:NameState"
	}, {
		"values": ["armed", "disarmed", "partial"],
		"type": "DiscreteState",
		"qualifiedName": "myfox:AlarmStatusState"
	}, {
		"type": "DataState",
		"qualifiedName": "myfox:AlertTrespassState"
	}],
	"dataProperties": [],
	"widgetName": "MyFoxAlarmController",
	"uiClass": "Alarm",
	"qualifiedName": "myfox:SomfyProtectAlarmController",
	"type": "ACTUATOR"
}
```

**Comment by tofgun** [comment]
In the tahomalink web app, the somfy protect icon propose 3 modes : Total/Night/Off
![image](https://user-images.githubusercontent.com/77484063/105496524-e118b800-5cbd-11eb-9ee3-dee188471b3e.png)

HA Disarm cmd => myfox:AlarmStatusState: disarmed => Somfy Protect state Off
HA Partial cmd => myfox:AlarmStatusState: partial=> Somfy Protect state Night
HA Arm cmd => myfox:AlarmStatusState: armed => Somfy Protect Total

![image](https://user-images.githubusercontent.com/77484063/105498552-a06e6e00-5cc0-11eb-8ea1-493fcd7a42a6.png)

![image](https://user-images.githubusercontent.com/77484063/105497711-82543e00-5cbf-11eb-8b6e-5d46ead213ce.png)

![image](https://user-images.githubusercontent.com/77484063/105498125-0c9ca200-5cc0-11eb-9941-a269676d6a98.png)


Does it help ?

**Comment by tofgun** [comment]
I just see configuring a new dashboard that the alarm control panel offers 3 possible values instead of 2. It seems that if I use arm-night it works. Then I should use arm-night instead of arm-home ...

![image](https://user-images.githubusercontent.com/77484063/105513200-51313900-5cd2-11eb-9334-3d88fc32d23b.png)

**Comment by tofgun** [comment]
Arm-night and arm-away of alarm_control_panel are working properly with the somfy protect alarm.
My mistake, I choosed the Arm-Home command which has no correspondance with the somfy protect alarm.
