### ISSUE TITLE
Add support for Atlantic heaters gestion

### ISSUE THREAD

**Issue by tomtomdu85** [iMicknl/ha-tahoma#357]
I have 2 heaters area on my tahoma account.

But it's not implemented on Hass.
![image](https://user-images.githubusercontent.com/54668918/105692709-09dbc000-5eff-11eb-80b9-6a56ab1646fa.png)
![image](https://user-images.githubusercontent.com/54668918/105692750-1bbd6300-5eff-11eb-86af-eb83d8774fee.png)

**Comment by vlebourl** [comment]
Well, hello to you too. No problem, let me take some of the little free time I have to make your dream come true...

**Comment by iMicknl** [comment]
@tomtomdu85 please have a look at our [README](https://github.com/iMicknl/ha-tahoma#device-not-supported--working-correctly) regarding not supported devices. 

I will close this issue, feel free to create a new issue using the issue template (which provides us with all required information). Please note that this is a community effort, thus that everyone on this project is doing this on a voluntary basis.

**Comment by tomtomdu85** [comment]
> Well, hello to you too. No problem, let me take some of the little free time I have to make your dream come true...

Hi. Sorry for the formatting. This was just a remark on a missing item, with no further thoughts. I know you do this in your spare time and thank you for that.

**Comment by vlebourl** [comment]
Apology accepted 🙂

**Comment by iMicknl** [comment]
@tomtomdu85 feel free to create a new issue via the issue template. The issue template will ask for some details, which will help us understand more about your device. Adding a screenshot as you did here is great, to understand which features should be supported.

It could be that there is already an open issue, based on your device type. My guess is that someone else did log this same Atlantic heater already :).

**Comment by tomtomdu85** [comment]
@iMicknl you said right. I found the #355 issue. It's the same thing.
So, no more issue is needed. I'll complete the other issue.
