### ISSUE TITLE
Thermis IO sensor - HA shows Unknown when temperature is exactly = 0

### ISSUE THREAD

**Issue by LubikR** [iMicknl/ha-tahoma#358]
- [x] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**
I have two Somfy Thermis WireFree II io. Everything is OK, but when the sensor parameter Core:TemperatureState = 0, then state of sensor is Unknown. It should be exactly = 0. On screeenshot with graph you can see that value is not on graph when it is exactly 0.

**To Reproduce**
1. When the outside temperature is 0 you will see it in Home Assistant GUI

**Expected behavior**
Sensor state shoudl be 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/16385328/105959240-f3a73e80-607b-11eb-9bd9-586c33420617.png)
![image](https://user-images.githubusercontent.com/16385328/105958852-75e33300-607b-11eb-85d8-29bde110ae77.png)

**Environment (please complete the following information):**

- **ha-tahoma version:** 2.4.2
- **Home Assistant version:** Home Assistant 2021.1.5
- **Platform**: sensor
**Device:** Thermis io

- **Model**: TemperatureSensor
- **Type**: Firmware: io:TemperatureIOSystemSensor

**Additional context**

**Comment by iMicknl** [comment]
Thanks for reporting @LubikR, good catch. It seems like `0` is returned as `None`.
This is due to `if 0` expression will result in false.

https://github.com/iMicknl/ha-tahoma/blob/c170fb01ee9e00487c19f288a57c8cd10eb6d9e8/custom_components/tahoma/sensor.py#L137

We need to fix this in an upcoming version.
