### ISSUE TITLE
Hi-Kumo Integration not working

### ISSUE THREAD

**Issue by pmb91917** [iMicknl/ha-tahoma#360]
Hi,

I just installed version 2.4.2 and tested the Hi-Kumo integration. I m not able to log in. A screenshot from the GUI error and debug log entry is attached. I know that this is still in beta mode - I just wanted to provide test details.

![image](https://user-images.githubusercontent.com/64465192/105981858-de8bd900-6096-11eb-9912-b576e64138de.png)

[hi-kumo.txt](https://github.com/iMicknl/ha-tahoma/files/5879672/hi-kumo.txt)

**Comment by iMicknl** [comment]
@pmb91917 thanks for reporting! You are the first user that has a Hi-Kumo box, which is great :-).

Could you try the following version?
https://github.com/iMicknl/ha-tahoma/archive/fix/fix_hi_kumo_integration.zip. After downloading the zip file, please extract the folder. Place the `custom_components/tahoma` in your `custom_components` folder.

**Comment by pmb91917** [comment]
I could now login but the devices are not discovered - debug log attached

[hi-kumo.txt](https://github.com/iMicknl/ha-tahoma/files/5881350/hi-kumo.txt)

**Comment by iMicknl** [comment]
@pmb91917 this is a known issue, tracked via https://github.com/iMicknl/ha-tahoma/issues/299. Hopefully someone will have time to implement that device soon.

Which integration are you currently using for Hi Kumo? (Or aren't you using an integration yet).

**Comment by iMicknl** [comment]
We fixed the login issue and it will be included in the next version. I will let you know (in #299) when it is ready to test.
