### ISSUE TITLE
__init__() missing 2 required keyword-only arguments: 'alive' and 'up_to_date' after update to 2.4.5

### ISSUE THREAD

**Issue by dckiller51** [iMicknl/ha-tahoma#367]
- [ ] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**

Loss of shutters since the last version 2.4.5

```
Logger: custom_components.tahoma
Source: custom_components/tahoma/__init__.py:112
Integration: Somfy TaHoma (documentation, issues)
First occurred: 15:13:41 (1 occurrences)
Last logged: 15:13:41

__init__() missing 2 required keyword-only arguments: 'alive' and 'up_to_date'
Traceback (most recent call last):
  File "/config/custom_components/tahoma/__init__.py", line 112, in async_setup_entry
    gateways = await client.get_gateways()
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 135, in get_gateways
    gateways = [Gateway(**g) for g in humps.decamelize(response)]
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 135, in <listcomp>
    gateways = [Gateway(**g) for g in humps.decamelize(response)]
TypeError: __init__() missing 2 required keyword-only arguments: 'alive' and 'up_to_date'
```

**Environment (please complete the following information):**

- **hub:** Somfy TaHoma
- **ha-tahoma version:** 2.4.5
- **Home Assistant version:** 2021.1.5
- **Platform**: cover

**Device:** (if your problem is related to a specific device)

- **Model**: [e.g. PositionableScreen, can be gathered from device list in HA]
- **Type**: [e.g. `io:DimmableLightIOComponent`, can be gathered from device page in HA looking at Firmware] `/config/devices/dashboard`]

**Additional context**

**Comment by iMicknl** [comment]
Thanks for reporting @dckiller51. For now, I would advise to downgrade to v2.4.3.

Which hub are you using? (Somfy TaHoma, Connexoon, CozyTouch, etc.).

**Comment by iMicknl** [comment]
Could you give https://github.com/iMicknl/ha-tahoma/archive/fix/fix_gateway_params_issues.zip a try? Extract this file and place `custom_components/tahoma` in your `custom_components` folder.

**Comment by dckiller51** [comment]
> 
> 
> Thanks for reporting @dckiller51. For now, I would advise to downgrade to v2.4.3.
> 
> Which hub are you using? (Somfy TaHoma, Connexoon, CozyTouch, etc.).
Somfy Tahoma
Yes downgrade to v2.4.3 works. I'm testing tonight, I'm not at home to send the files

**Comment by iMicknl** [comment]
Thanks @dckiller51. Do you perhaps have the Somfy TaHoma first generation? It is weird how their API is not standardized on all gateways...

**Comment by dckiller51** [comment]
> 
> 
> Thanks @dckiller51. Do you perhaps have the Somfy TaHoma first generation? It is weird how their API is not standardized on all gateways...

This is the Tahoma V2 version 2020.6.4-1 5

**Comment by iMicknl** [comment]
That is weird, I have the same version (2020.6.4-15) and for me this error doesn't occur... 

![image](https://user-images.githubusercontent.com/1424596/106489360-fa3b1900-64b4-11eb-8e44-efb29ee8011b.png)

**Comment by dckiller51** [comment]
> 
> 
> That is weird, I have the same version (2020.6.4-15) and for me this error doesn't occur...
> 
> ![image](https://user-images.githubusercontent.com/1424596/106489360-fa3b1900-64b4-11eb-8e44-efb29ee8011b.png)

I don't have the hub in HA device. The information, I recovered them in the official application.

**Comment by iMicknl** [comment]
@dckiller51 I know, that is the error you are facing in this issue :-). The fixed version should add your hub as an entity in Home Assistant.

**Comment by dckiller51** [comment]
> Pourriez-vous essayer https://github.com/iMicknl/ha-tahoma/archive/fix/fix_gateway_params_issues.zip ? Extrayez ce fichier et placez-le `custom_components/tahoma`dans votre `custom_components`dossier.

This version works. I do have two additional devices. (Tahoma V2 hub and Home Protect System hub). Thank you

**Comment by iMicknl** [comment]
Thanks! Your Home Protect System hub is also a gateway, that is what caused this issue. We will add this to the next version.

**Comment by dckiller51** [comment]
@iMicknl 
Hello, Home Assistant 2021.2.0 updated suite. Mistake
```
Setup failed for tahoma: Requirements for tahoma not found: ['git+https://github.com/iMicknl/python-tahoma-api.git@fix/make_gateway_params_optional#pyhoma==0.5.5'].
```

**Comment by iMicknl** [comment]
@dckiller51, sorry that branch has been removed already. You can download the latest version (v2.4.6) via HACS or via GitHub, where this fix is included.

**Comment by dckiller51** [comment]
@iMicknl 
thank you very much for your speed
