### ISSUE TITLE
Add support for Hitachi RASM3-VNE Heat PumpAirToWaterMainComponent (modbus:YutakiMainComponent)

### ISSUE THREAD

**Issue by stavrosso** [iMicknl/ha-tahoma#370]
- [x] **I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

The device is a Hitachi Heat Pump Model: RASM 3 VNE . It is an air to water heat pump used for heat only. The device is controlled by Hi_Kumo app by Hitachi and powered by moduloTech.

**Device information**

The Hi Ku-Mo App allows remote activation, deactivation of the Heat Pump, temperature setup and weekly timer setup for space heating. Also you can setup the Domestic Hot Water temperature setpoint and activate/deactivate it. Aslo the app shows outside temperature , Set temperature and current hot water and room temperature. These would be nice to be able to be  sensor entities in home assistant. Options for Holiday settings and ECO Mode is also available in the app. App screenshots attached.
![Screenshot_20210201_204124_com hitachi HiKumo](https://user-images.githubusercontent.com/36436860/106507438-b6a3d780-64d3-11eb-8ec6-3249f99e1005.jpg)
![Screenshot_20210201_204132_com hitachi HiKumo](https://user-images.githubusercontent.com/36436860/106507440-b7d50480-64d3-11eb-928d-ebc522417c33.jpg)
![Screenshot_20210201_204141_com hitachi HiKumo](https://user-images.githubusercontent.com/36436860/106507441-b86d9b00-64d3-11eb-845c-64898333a2e4.jpg)
![Screenshot_20210201_204153_com hitachi HiKumo](https://user-images.githubusercontent.com/36436860/106507444-b86d9b00-64d3-11eb-90de-9dd1788b3991.jpg)
![Screenshot_20210201_204200_com hitachi HiKumo](https://user-images.githubusercontent.com/36436860/106507445-b9063180-64d3-11eb-8438-7edf18e5bb2b.jpg)
![Screenshot_20210201_204210_com hitachi HiKumo](https://user-images.githubusercontent.com/36436860/106507446-b9063180-64d3-11eb-9a23-16bd0386f286.jpg)

**Device details**

- **Hub**: Hitachi ATW-TAG-02 Home Automation Gateway and Smart Hi-Box Model: AHP-SMB-01

**Device commands**

Please find attached a word document. This includes the executed commands from the Hi Kumo App ( In RED Color) and the result in the home assistant log file from the tahoma.get_execution_history. Some duplicates exist.
[home assistant hitachi hi-kumo log.docx](https://github.com/iMicknl/ha-tahoma/files/5909309/home.assistant.hitachi.hi-kumo.log.docx)

**Comment by iMicknl** [comment]
Thanks for reporting @stavrosso and great to hear that Hi-Kumo works!

In order to gather more information, you can use the `tahoma.get_execution_history` service in Home Assistant which will print your execution history to the Home Assistant log. 

Run the all available commands via the Hi-Kumo app and write down what you called. Now go to Developer Tools -> Services and execute `tahoma.get_execution_history`. This will print the last execution history in your logbook, which you can paste here.

**Comment by stavrosso** [comment]
Good Morning @iMicknl ,

I have run the commands in the Hi-Kumo App and registered all the log entries in a word document. The actual log file is so long because I was trying command since last night. If you want I can paste it here but IT IS long. I think the word file I uploaded on the bottom of my initial Issue (above) will be more helpful. Please let me know if this is not the case. Thank you

**Comment by iMicknl** [comment]
@stavrosso your Word document is very extensive, thank you. Unfortunately this is not the output which mentions the command name, thus I am not able to use it for the development.

The command history should look like: 
```
2021-02-04 10:45:34 INFO (MainThread) [custom_components.tahoma] 2021-02-02 15:06:10: setVentilationConfigurationMode executed via Android 2.4.8#220 Set device mode : AUTO on io://xxxx-xxxx-xxxx/xxxxxxxxxx#1, with ['comfort'].
```
(see https://github.com/iMicknl/ha-tahoma/issues/376 as an example)

It is possible that this execution history is not supported on Hi-Kumo, but that would be hard to check. If you are willing to share your credentials with me sometime, we can have a chat on [Discord](https://discord.gg/RRXuSVDAzG) -> iMick#1903. You can change your password to a temporary one when I am testing some stuff, and we can work together on retrieving this information. 

Otherwise, we need to see if I can develop a basic version using the device definition, however this can take quite some time.

**Comment by stavrosso** [comment]
Good morning Mick.

Thank you for the message.

I would be happy to share my credentials with you in order to get this sorted out.Just let me know when you want to do that.

I have sent a friend request on Discord . Mine is Stavros#8220. 

Have a nice day.

Regards

Stavros

**Comment by stavrosso** [comment]
Here are some commands I copied from Home assistant log

**Set Room temperature to 21°**

`2021-02-12 18:56:27 INFO (MainThread) [custom_components.tahoma] 2021-02-12 18:55:28: globalControl executed via Room focus : set air to water heat pump state on modbus://0810-9263-3428/5608763/1#2, with ['manu', 'heat', 21].
2021-02-12 18:56:27 INFO (MainThread) [custom_components.tahoma] 2021-02-12 18:55:28: setAutoManuMode executed via Room focus : set air to water heat pump state on modbus://0810-9263-3428/5608763/1#2, with ['manu'].
2021-02-12 18:56:27 INFO (MainThread) [custom_components.tahoma] 2021-02-12 18:55:28: setHolidayMode executed via Room focus : set air to water heat pump state on modbus://0810-9263-3428/5608763/1#2, with ['off'].
`
**Turn OFF Room Heating** 

`2021-02-12 19:02:16 INFO (MainThread) [custom_components.tahoma] 2021-02-12 19:00:58: globalControl executed via devices list : set air to water heat pump to OFF on modbus://0810-9263-3428/5608763/1#2, with ['off', 'heat', 21].
2021-02-12 19:02:16 INFO (MainThread) [custom_components.tahoma] 2021-02-12 19:00:58: setAutoManuMode executed via devices list : set air to water heat pump to OFF on modbus://0810-9263-3428/5608763/1#2, with ['manu'].
2021-02-12 19:02:16 INFO (MainThread) [custom_components.tahoma] 2021-02-12 19:00:58: setHolidayMode executed via devices list : set air to water heat pump to OFF on modbus://0810-9263-3428/5608763/1#2, with ['off'].
`
**Turn ON Room Heating** 

`2021-02-12 19:11:31 INFO (MainThread) [custom_components.tahoma] 2021-02-12 19:10:06: globalControl executed via devices list : set air to water heat pump to ON on modbus://0810-9263-3428/5608763/1#2, with ['manu', 'heat', 20].
2021-02-12 19:11:31 INFO (MainThread) [custom_components.tahoma] 2021-02-12 19:10:06: setAutoManuMode executed via devices list : set air to water heat pump to ON on modbus://0810-9263-3428/5608763/1#2, with ['manu'].
2021-02-12 19:11:31 INFO (MainThread) [custom_components.tahoma] 2021-02-12 19:10:06: setHolidayMode executed via devices list : set air to water heat pump to ON on modbus://0810-9263-3428/5608763/1#2, with ['off'].
`

**Turn On the DHW Switch in the App main Welcome Screen**

`2021-02-12 19:17:19 INFO (MainThread) [custom_components.tahoma] 2021-02-12 19:15:51: setControlDHW executed via devices list : set domestic hot water tank to ON on modbus://0810-9263-3428/5608763/1#4, with ['run'].
2021-02-12 21:01:09 INFO (MainThread) [custom_components.tahoma] 2021-02-12 21:00:38: setControlDHW executed via devices list : set domestic hot water tank to ON on modbus://0810-9263-3428/5608763/1#4, with ['run'].
`

**Turn OFF the DHW Switch in the App main Welcome Screen**

`2021-02-12 20:46:14 INFO (MainThread) [custom_components.tahoma] 2021-02-12 20:09:38: setControlDHW executed via devices list : set domestic hot water tank to OFF on modbus://0810-9263-3428/5608763/1#4, with ['stop'].`

**Turn OFF the DHW via the YUTAKI DHW Screen (Accessible if you click the YUTAKI DHW from the Main Welcome Screen)**

`2021-02-12 20:58:26 INFO (MainThread) [custom_components.tahoma] 2021-02-12 20:56:56: setControlDHW executed via Room focus : set domestic hot water tank state on modbus://0810-9263-3428/5608763/1#4, with ['stop'].`

**Set DHW water temperature to 37 Degrees**

`2021-02-12 20:53:15 INFO (MainThread) [custom_components.tahoma] 2021-02-12 20:52:46: globalControlDHW executed via Room focus : set domestic hot water tank state on modbus://0810-9263-3428/5608763/1#4, with ['run', 'standard', 37].`

**Set Water Temperature to 40 Degrees** 

`2021-02-12 19:20:59 INFO (MainThread) [custom_components.tahoma] 2021-02-12 19:20:21: globalControlDHW executed via Room focus : set domestic hot water tank state on modbus://0810-9263-3428/5608763/1#4, with ['run', 'standard', 40].`

**Set Water Mode to High Demand and 37 Degrees via the YUTAKI DHW Screen (Accessible if you click the YUTAKI DHW from the Main Welcome Screen)**

`2021-02-12 21:02:50 INFO (MainThread) [custom_components.tahoma] 2021-02-12 21:02:25: globalControlDHW executed via Room focus : set domestic hot water tank state on modbus://0810-9263-3428/5608763/1#4, with ['run', 'high demand', 37]`

**Set Water Mode to Standard and 37 Degrees via the YUTAKI DHW Screen (Accessible if you click the YUTAKI DHW from the Main Welcome Screen)**

`2021-02-12 21:04:54 INFO (MainThread) [custom_components.tahoma] 2021-02-12 21:04:18: globalControlDHW executed via Room focus : set domestic hot water tank state on modbus://0810-9263-3428/5608763/1#4, with ['run', 'standard', 37].`

Changed temperature on Weekly Timer Friday  05:30-11:00 from 20 to 21 Degrees
No Record in Log

**Change Room Heating mode from Manual to Weekly Timer** 

`2021-02-12 19:31:30 INFO (MainThread) [custom_components.tahoma] 2021-02-12 19:31:13: globalControl executed via Room focus : set air to water heat pump state on modbus://0810-9263-3428/5608763/1#2, with ['auto', 'heat', 21].
2021-02-12 19:31:30 INFO (MainThread) [custom_components.tahoma] 2021-02-12 19:31:13: setAutoManuMode executed via Room focus : set air to water heat pump state on modbus://0810-9263-3428/5608763/1#2, with ['auto'].
2021-02-12 19:31:30 INFO (MainThread) [custom_components.tahoma] 2021-02-12 19:31:13: setHolidayMode executed via Room focus : set air to water heat pump state on modbus://0810-9263-3428/5608763/1#2, with ['off'].
`
**Change Room Heating mode from Weekly Timer to Manual** 

`2021-02-12 21:17:47 INFO (MainThread) [custom_components.tahoma] 2021-02-12 21:17:29: globalControl executed via Room focus : set air to water heat pump state on modbus://0810-9263-3428/5608763/1#2, with ['manu', 'heat', 21].
2021-02-12 21:17:47 INFO (MainThread) [custom_components.tahoma] 2021-02-12 21:17:29: setAutoManuMode executed via Room focus : set air to water heat pump state on modbus://0810-9263-3428/5608763/1#2, with ['manu'].
2021-02-12 21:17:47 INFO (MainThread) [custom_components.tahoma] 2021-02-12 21:17:29: setHolidayMode executed via Room focus : set air to water heat pump state on modbus://0810-9263-3428/5608763/1#2, with ['off'].
`

Thank you @iMicknl  for your time and hard work. Your help is appreciated

**Comment by iMicknl** [comment]
@stavrosso thanks! Let me know what doesn't work in the latest test version and I will have a look at the commands :).

**Comment by stavrosso** [comment]
Hi Mick,

Here is a list of commands that work normally and others that don't for your reference

**1. THERMOSTAT - Entity id:  climate.modbus_5608763_1_2**

Room Heating temperature (Thermostat) **can’t** be set from home assistant. The value changes if you use the thermostat slider but the app is not updated.

At some point I got this error
```
Logger: custom_components.tahoma.tahoma_device
Source: custom_components/tahoma/tahoma_device.py:163
Integration: Somfy TaHoma (documentation, issues)
First occurred: 4:14:24 PM (1 occurrences)
Last logged: 4:14:24 PM
setRoomAmbientTemperatureControlZone1() : Invalid value for command parameter p1 : expected integer value but got 21.0

```
Is it possible for **Auto** to be renamed to **Weekly Timer** and **Heat** to **Manual**? . This is how they are referred in the app. If it is difficult it is not a big issue as long as the mode change works, which does not.

Trying to change from Auto to Heat (Weekly Timer to Manual in the app) returns the message **Failed to call climate/set_hvac_mode.”heat”** and does not perform the related action in the app. These are the commands if executed from the app:

```
globalControl executed via Room focus : set air to water heat pump state on modbus://0810-9263-3428/5608763/1#2, with ['manu', 'heat', 20].
setAutoManuMode executed via Room focus : set air to water heat pump state on modbus://0810-9263-3428/5608763/1#2, with ['manu'].
setHolidayMode executed via Room focus : set air to water heat pump state on modbus://0810-9263-3428/5608763/1#2, with ['off'].

```

On the other hand changing from Heat to Auto (Manual to Weekly timer) from home assistant, works and the app state is updated.This is the executed command:
```
setAutoManuMode executed via Home Assistant on modbus://0810-9263-3428/5608763/1#2, with ['auto'].
```

2. **PRESET ECO/COMFORT** does not change from Home assistant interface

If you select **ECO** or **COMFORT** from the drop down list in home assistant,  the  state does not change in the app, Something odd that I noticed is that a “circle” animates on the  icon for setting the room temperature  heating in the app (as it is trying to change the set temperature) .

3.  **WATER HEATER (DHW)** **Entity id: water_heater.modbus_5608763_1_4**

**Water heater (DHW) temperature** can’t be set from home assistant. Changing the water heater temperature from home assistant interface does not update the app and reverts back to set Temperature. This is the command when executed from the app:

```
globalControlDHW executed via Room focus : set domestic hot water tank state on modbus://0810-9263-3428/5608763/1#4, with ['run', 'standard', 35].

```

**AWAY MODE** on home assistant works normally and switches the DHW Water OFF/ON in the app. It works fine but the name should be something like DHW (Or Water Heater) ON/OFF if possible of course.

**OPERATION MODE** works normally and changes DHW mode from Standard to High Demand and vice versa in the app.

If you need additional information please let me know.

Thank you

**Comment by iMicknl** [comment]
> Room Heating temperature (Thermostat) **can’t** be set from home assistant. The value changes if you use the thermostat slider but the app is not updated.

Should be fixed in the latest version (updated this afternoon). 

> Is it possible for **Auto** to be renamed to **Weekly Timer** and **Heat** to **Manual**? . This is how they are referred in the app. If it is difficult it is not a big issue as long as the mode change works, which does not.

Unfortunately this is not possible. We can only choose from the following names: https://developers.home-assistant.io/docs/core/entity/climate/#hvac-modes.



> Trying to change from Auto to Heat (Weekly Timer to Manual in the app) returns the message **Failed to call climate/set_hvac_mode.”heat”** and does not perform the related action in the app. These are the commands if executed from the app:

Should be fixed in the latest version (updated this afternoon). 


> If you select **ECO** or **COMFORT** from the drop down list in home assistant, the state does not change in the app, Something odd that I noticed is that a “circle” animates on the icon for setting the room temperature heating in the app (as it is trying to change the set temperature) .

Not sure about this one yet, I would need to do some more research.. The other user also reported that these didn't work.



> **Water heater (DHW) temperature** can’t be set from home assistant. Changing the water heater temperature from home assistant interface does not update the app and reverts back to set Temperature. This is the command when executed from the app:

Ok, let me know via Discord when you have time and we can have a look together at some day. I would like to give it a try myself when developing, but would be good to discuss the moment ;-).

> **AWAY MODE** on home assistant works normally and switches the DHW Water OFF/ON in the app. It works fine but the name should be something like DHW (Or Water Heater) ON/OFF if possible of course.

Unfortunately, water heaters don't support on/off in Home Assistant. I thought best way would be to map it to the away mode, since this is probably when you want to turn it off? :)

**Comment by stavrosso** [comment]
Great , Evrything looks fine. Just let me know a convenient time to talk on discord.

**Comment by stavrosso** [comment]
Good morning Mick,

All works perfectly after the last update. Thank you

Could you possibly add the ON/OFF mode to the Thermostat? (We currently have AUTO and HEAT Operations)

**OFF Command is:**

```
globalControl executed via devices list : set air to water heat pump to OFF on modbus://0810-9263-3428/5608763/1#2, with ['off', 'heat', 19].
setAutoManuMode executed via devices list : set air to water heat pump to OFF on modbus://0810-9263-3428/5608763/1#2, with ['manu'].
setHolidayMode executed via devices list : set air to water heat pump to OFF on modbus://0810-9263-3428/5608763/1#2, with ['off'].

```

**ON Command is:**

```
globalControl executed via devices list : set air to water heat pump to ON on modbus://0810-9263-3428/5608763/1#2, with ['manu', 'heat', 20].
setAutoManuMode executed via devices list : set air to water heat pump to ON on modbus://0810-9263-3428/5608763/1#2, with ['manu'].
setHolidayMode executed via devices list : set air to water heat pump to ON on modbus://0810-9263-3428/5608763/1#2, with ['off'].
```

Thank you

**Comment by iMicknl** [comment]
@stavrosso I will have a look for the on/off, need to have a look if this set via the same device. Not sure how climate front-end shows on/off.

> Also is it possible to have 0.5 steps in thermostat temperature? ( The Hi-Kumo App does not allow 0.5 step changes but the Hitachi controller does. So the room temperature can be set to 19.5 for example on the controller but not in the app).

I understood that this is not supported in the API as well... During implementation I faced errors when passing a float (comma number) instead of an integer. We could have a look, but I am afraid that this is not supported.

**Comment by stavrosso** [comment]
Hi Mick,

If you look at the water heater entity (water_heater.modbus_5608763_1_4) you have enabled 3 modes, standard, high demand and OFF mode , I don't know if the OFF command there could help you figure out how to enable the ON/OFF command on the heating. It seems that the device triggered if I switch the Heating ON or OFF from the app is modbus://0810-9263-3428/5608763/1#2  and the commands appear on my previous post.

I am available anytime you can to try and figure this out.

Thank you again

Stavros

**Comment by iMicknl** [comment]
@stavrosso is this still an issue? In case you are missing any features in the current implementation, feel free to create a new issue.

Have a look here (https://github.com/iMicknl/ha-tahoma#device-not-working-correctly) for more details about what to add and how to receive the commands.
