### ISSUE TITLE
> v2.3.4 missing 1 required keyword-only argument: 'placeoid'

### ISSUE THREAD

**Issue by anlupat** [iMicknl/ha-tahoma#372]
**Describe the bug**
The integration no longer works for my setup.

**To Reproduce**

1. Install v2.3.4 or v2.3.5
2. Watch homeassistant.log
3. See error:

2021-02-02 12:47:21 ERROR (MainThread) [custom_components.tahoma] __init__() missing 1 required keyword-only argument: 'placeoid'
Traceback (most recent call last):
  File "/config/custom_components/tahoma/__init__.py", line 112, in async_setup_entry
    gateways = await client.get_gateways()
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 135, in get_gateways
    gateways = [Gateway(**g) for g in humps.decamelize(response)]
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 135, in <listcomp>
    gateways = [Gateway(**g) for g in humps.decamelize(response)]
TypeError: __init__() missing 1 required keyword-only argument: 'placeoid'

**Expected behavior**
To be able to use the integration

**Reverting back to v2.3.3 solves the issue**

**Environment (please complete the following information):**

- **Hub**: Somfy TaHoma
- **ha-tahoma version:** latest
- **Home Assistant version:** latest
- **Platform**: I think the gateway fails

**Comment by iMicknl** [comment]
Thanks for reporting @anlupat. It is indeed the newly added gateway that expects `placeoid` to be present. We will make this optional, since your gateway doesn't have this value apparently.

**Comment by anlupat** [comment]
@iMicknl It is a really old one, one of the first ever build.

**Comment by iMicknl** [comment]
Haha, we didn't have that one in our test set yet. Apologies for testing in production 😉.

![](https://media2.giphy.com/media/XjlNyeZp5lDri/giphy-downsized-medium.gif)

**Comment by anlupat** [comment]
I don't mind. I'm just happy there is such a great working integration. Since the API of Somfy is kinda, let's try to say it nice, "incomplete".

**Comment by iMicknl** [comment]
Please update to v2.4.6 and it should be fixed!
