### ISSUE TITLE
Cover (AwningValance) not working properly on versions higher than 2.3.8 - AwningValance (io:AwningValanceIOComponent)

### ISSUE THREAD

**Issue by TheFes** [iMicknl/ha-tahoma#373]
- [X] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**
_Short version:_
After version 2.3.8 my cover is not working properly anymore.
The states are reversed (closed is now open, and vice versa), but more importantly, after closing the screen (meaning it is blocking the sun) I can not open it again.

_Long version:_
I have three bedrooms, and all three have vertical covers to block the sun in summer. For some reason the company who placed these covers has used different types of Somfy motors for the rooms:

- **Room 1 - Master bedroom:** 3 windows with separate covers using AwningValance (io:AwningValanceIOComponent)
<img src="https://user-images.githubusercontent.com/28803438/106606631-a5ee7280-6562-11eb-8b9f-f9f5c75d7a83.png" width="150" height="200" /><img src="https://user-images.githubusercontent.com/28803438/106606684-b30b6180-6562-11eb-946e-c2155a999ddd.png" width="150" height="200" /><img src="https://user-images.githubusercontent.com/28803438/106606737-c0c0e700-6562-11eb-9a34-85569a83a71f.png" width="150" height="200" />

- **Room 2 - Bedroom child 1:**  1 (big) window using PositionableHorizontalAwning (io:HorizontalAwningIOComponent) <img src="https://user-images.githubusercontent.com/28803438/106606805-d6361100-6562-11eb-8abe-d72a9a68ff85.png" width="150" height="200" />

- **Room 3 - Bedroom child 2:** 1 (small) window using PositionableScreen (io:VerticalExteriorAwningIOComponent <img src="https://user-images.githubusercontent.com/28803438/106606873-e9e17780-6562-11eb-91c2-95a4b225e083.png" width="150" height="200" />

Shown above is the situation using version 2.3.8. 
Basically the only correct one seems to be Room 3, but using template covers, I had all rooms the way I want them.

After updating to version 2.3.9 I've been having issues with the screens in room 1. The states were reversed, and as I did not had enough time to debug at that moment I reverted back to 2.3.8. 
With each version after that, I checked the changelog to see if these type of covers was mentioned. Until now this was not the case, so I decided to update so I can provide a bug report for the covers. 

So, for room 1 the status after updating to 2.4.5 is this:
<img src="https://user-images.githubusercontent.com/28803438/106608746-15fdf800-6565-11eb-8aea-0b3453c31184.png" width="150" height="200" /><img src="https://user-images.githubusercontent.com/28803438/106608792-1eeec980-6565-11eb-8c60-6d1e0e2561c9.png" width="150" height="200" /><img src="https://user-images.githubusercontent.com/28803438/106608880-36c64d80-6565-11eb-997f-ddfaf356bf37.png" width="150" height="200" />

As you can see from the screenshots, the direction of the arrows has changed, and also the reported position has changes (what was 100, is now 0, and vice versa).
This is not my biggest issue, as I was using a template cover anyway. I can simply change the template cover to reflect this change, and get it the way I want again.

However there seems to be another thing going on, because when I now close the cover anymore after updating.
When I press the up arrow, the icon changes for a second, but nothing happens. The reported position also remains 0.

There are no issues in the logbook.

For now I went back to using 2.3.8 but I would like to update to the latest version.

**Expected behavior**

- Consistent states between versions (for me it is not an issue to revert it myself, but I don't want to have to check this and change it after each update)
- A cover which actually closes and opens when I use the buttons in HA.

**Environment (please complete the following information):**

- **Hub**: [Somfy Connexoon]
- **ha-tahoma version:** [2.4.5]
- **Home Assistant version:** [2021.1.5]
- **Platform**: [cover]

**Device:** 

- **Model**: [AwningValance]
- **Type**: [io:HorizontalAwningIOComponent] `/config/devices/dashboard`]

In case additional information is required, please let me know.

**Comment by iMicknl** [comment]
Thanks for reporting.

Could you give https://github.com/iMicknl/ha-tahoma/archive/fix/awning_valance.zip a try? Extract this file and place `custom_components/tahoma` in your `custom_components` folder. This should solve your issues.

**Comment by TheFes** [comment]
This indeed solved the issue, thanks!
