### ISSUE TITLE
Add support for Hitachi air to air heat pump

### ISSUE THREAD

**Issue by tofgun** [iMicknl/ha-tahoma#377]
Unsupported devices : 

![image](https://user-images.githubusercontent.com/77484063/106960800-e9043d80-673c-11eb-9826-a7a0a9438914.png)
![image](https://user-images.githubusercontent.com/77484063/106961268-9ecf8c00-673d-11eb-8877-6ab70b014ca1.png)
![image](https://user-images.githubusercontent.com/77484063/106961163-7fd0fa00-673d-11eb-9b59-bca66ab2b67e.png)

**Comment by iMicknl** [comment]
Thanks for reporting, @tofgun. We currently have another similar issue (https://github.com/iMicknl/ha-tahoma/issues/299) where we track this feature. I will close this issue, lets keep the discussion in the other one.

For a next issue, please don't remove the issue template with all required information. This helps us gathering all required information.
