### ISSUE TITLE
Execution queue is full on gateway: #1218-0150-5193 (soft limit: 10)

### ISSUE THREAD

**Issue by VoetenK** [iMicknl/ha-tahoma#378]
Server Log:

Logger: custom_components.tahoma.tahoma_device
Source: custom_components/tahoma/tahoma_device.py:163
Integration: Somfy TaHoma (documentation, issues)
First occurred: 3:14:50 PM (483 occurrences)
Last logged: 5:47:09 PM

Execution queue is full on gateway: #1218-0150-5193 (soft limit: 10)
Cannot connect to host tahomalink.com:443 ssl:default [Connect call failed ('178.32.15.131', 443)]

Home Assistant 2021.2.1

Core:
Version
core-2021.2.1

Supervisor:
Version
supervisor-2021.01.7

Host :
Hostname
HomeAssistant
Operating System
Home Assistant OS 5.10

- **Hub**: Somfy TaHoma
- **ha-tahoma version:** 2020.7.4-7

**Comment by iMicknl** [comment]
How many devices do you have? And do you use a automation or group to trigger many commands at the same time?

related to https://github.com/iMicknl/ha-tahoma/issues/261

**Comment by iMicknl** [comment]
Let's keep the discussion in https://github.com/iMicknl/ha-tahoma/issues/261.
