### ISSUE TITLE
Add support for HitachiAirToWaterMainComponent / HitachiHeatingSystem (modbus:YutakiMainComponent) (Yutaki S) 

### ISSUE THREAD

**Issue by xorassistant** [iMicknl/ha-tahoma#382]
- [x] **I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Device information**
There are 4 functions wHICH you can add to the device with the Somfy Tahoma app.
The Holiday function is a function we do not use with the thermostat, because this is a heatpump which is always on.
See the attached screenshots for the Tahoma app features

**1.  auto mode**
> Monday till Sunday (weekdays) 
> From & Untill time
> Possible to set time+temperate value
> OFF function
**2.  manual mode**
> SET manual temperature
**3. off** 

**Device details**

- **Hub**: [Somfy TaHoma]
- WITH the latest version of firmware

```
2021-02-12 06:35:36 DEBUG (MainThread) [custom_components.tahoma] Unsupported device detected (modbus:YutakiMainComponent - HitachiHeatingSystem - HitachiAirToWaterMainComponent - modbus://1233-4770-7251/4002825/1#1)
2021-02-12 06:35:36 DEBUG (MainThread) [custom_components.tahoma] Unsupported device detected (modbus:YutakiV2Zone1Component - HitachiHeatingSystem - HitachiAirToWaterHeatingZone - modbus://1233-4770-7251/4002825/1#2)
2021-02-12 06:35:36 DEBUG (MainThread) [custom_components.tahoma] Unsupported device detected (modbus:YutakiRoomThermostatZone1Component - HeatingSystem - HitachiThermostat - modbus://1233-4770-7251/4002825/1#6)
2021-02-12 06:35:36 DEBUG (MainThread) [custom_components.tahoma] Unsupported device detected (modbus:YutakiRoomThermostatZone2Component - HeatingSystem - HitachiThermostat - modbus://1233-4770-7251/4002825/1#7)
```

**Device commands**

[HITACHI HEAT.zip](https://github.com/iMicknl/ha-tahoma/files/5971120/HITACHI.HEAT.zip)

**Auto**
![AUTO-MODE](https://user-images.githubusercontent.com/1424596/107759270-59582380-6d28-11eb-974f-3dff117a4b1b.png)

**Manual**
![MANUAL-MODE](https://user-images.githubusercontent.com/1424596/107759246-51987f00-6d28-11eb-8a5a-ec1ed72ca8ca.png)

**Off**
![OFF-MODE](https://user-images.githubusercontent.com/1424596/107759256-552c0600-6d28-11eb-9b6a-9b165da73d00.png)

**Settings**
![SETTING-SCREEN](https://user-images.githubusercontent.com/1424596/107759278-5d844100-6d28-11eb-8de5-00fefeef9f01.png)

**Somfy function**
![Somfy function](https://user-images.githubusercontent.com/1424596/107759288-607f3180-6d28-11eb-9d7f-424b62ba4b81.png)

**Tahoma heat**
![tahoma_heat](https://user-images.githubusercontent.com/1424596/107759294-62e18b80-6d28-11eb-93df-dcad36f431ec.png)

**Hitachi products**
![tahoma_hitachi_products](https://user-images.githubusercontent.com/1424596/107759302-65dc7c00-6d28-11eb-980a-7ce675913aea.png)

**Comment by iMicknl** [comment]
Thanks for reporting, @xorassistant! Currently there are [11 open device requests](https://github.com/iMicknl/ha-tahoma/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Anew-device) thus it can take a while before we have time to implement this.

It would help if you are able to call the `tahoma.get_execution_history` in Home Assistant. This will print your history to your log, thus you are able to understand how different commands are executed. A great example of an issue where they used this is https://github.com/iMicknl/ha-tahoma/issues/376.

![image](https://user-images.githubusercontent.com/1424596/107759819-22ced880-6d29-11eb-941c-794058700184.png)

The log should look like:
`2021-02-12 11:56:00 INFO (MainThread) [custom_components.tahoma] 2021-02-05 17:39:47: setIntensity executed via Home Assistant on io://xxxx/xxxx, with [70].`

**Comment by iMicknl** [comment]
@xorassistant apparently, this has the same characteristics as #370.

Could you give https://github.com/iMicknl/ha-tahoma/archive/feature/support_hitachi_PumpAirToWaterMainComponent.zip a try? Extract this file and place `custom_components/tahoma` in your `custom_components` folder.

**Comment by xorassistant** [comment]
@iMicknl 

This version works for reading the temperature of the Hitachi device.
So looks likes this is a good way forward I have put two screenshots in the Hitachi.zip file.
And also some debug logging

[HITACHI.zip](https://github.com/iMicknl/ha-tahoma/files/5980754/HITACHI.zip)

**Comment by iMicknl** [comment]
Thanks @xorassistant. Via the original app, are you able to set values like 23.5? Looking at your logs, it requires a full number (int) instead of a comma number (float).

```
setRoomAmbientTemperatureControlZone1() : Invalid value for command parameter p1 : expected integer value but got 21.0
Cannot connect to host tahomalink.com:443 ssl:default [Connect call failed ('178.32.15.131', 443)]
setRoomAmbientTemperatureControlZone1() : Invalid value for command parameter p1 : expected integer value but got 23.0
setRoomAmbientTemperatureControlZone1() : Invalid value for command parameter p1 : expected integer value but got 24.0
setRoomAmbientTemperatureControlZone1() : Invalid value for command parameter p1 : expected integer value but got 23.5
```

Do the presets / other functions work?

**Comment by xorassistant** [comment]
@iMicknl 

The newest version you send works, only if I set is to value 23.5, Then it shows as "value 23"
![HITACHI-SET-TO-23 5(TAHOMA)](https://user-images.githubusercontent.com/74597098/107934384-46d82700-6f80-11eb-9370-a407288d32e5.png)
![HITACHI-SET-TO-23 5](https://user-images.githubusercontent.com/74597098/107934397-4b9cdb00-6f80-11eb-9bc6-0857e1c049cc.png)

**Comment by iMicknl** [comment]
@xorassistant should be fixed in latest version! https://github.com/iMicknl/ha-tahoma/archive/feature/support_hitachi_PumpAirToWaterMainComponent.zip

Do auto vs heat (manu) work as well? And same for the presets.

**Comment by xorassistant** [comment]
@iMicknl 

The heat function is not working, and also the presets (Auto, Comfort) are not working.
When choose "Comfort", then it's jumping back to "Auto".

[heat-function-error.txt](https://github.com/iMicknl/ha-tahoma/files/5981254/heat-function-error.txt)

**Comment by iMicknl** [comment]
@xorassistant oops, the mapping was reversed... Could you try the latest version? (https://github.com/iMicknl/ha-tahoma/archive/feature/support_hitachi_PumpAirToWaterMainComponent.zip).

It should fix the preset / operation mode, but also use a 1 degree stepping for the temperature.

**Comment by xorassistant** [comment]
> @xorassistant oops, the mapping was reversed... Could you try the latest version? (https://github.com/iMicknl/ha-tahoma/archive/feature/support_hitachi_PumpAirToWaterMainComponent.zip).
> 
> It should fix the preset / operation mode, but also use a 1 degree stepping for the temperature.

@iMicknl yes with this version the Heat functions properly as the "manual" mode.
Also the temperature is now using a 1 degree stepping!
Looks like the Eco/Comfort is not an option for the heatpump type we have, this keeps jumping back to comfort mode.
But it's now possible to adapt the temperature and it's syncing with the Tahoma! awesome!

**Comment by iMicknl** [comment]
Cool! Anything you miss, or can we consider this device implemented correctly? 🥳

**Comment by iMicknl** [comment]
@xorassistant I just pushed a new version, apparently there were some mistakes in the temperature control. Could you give it a try?
