### ISSUE TITLE
CO2 sensor added but no entity created

### ISSUE THREAD

**Issue by tillstaff** [iMicknl/ha-tahoma#390]
**Describe the bug**
I have a CO2 sensor available with my Atlantic Optimocosy device and the sensor is added by the component : 
```
2021-02-17 14:42:18 DEBUG (MainThread) [custom_components.tahoma] Added device (io:CO2IOSystemDeviceSensor - AirSensor - CO2Sensor - io://xxxx-xxxx-xxxx/15021786#2)
```
But I don't have any entity created with this sensor.

**To Reproduce**
I made some investigations and the problem is that the CO2Sensor doesn't have the "CORE_MEASURED_VALUE_TYPE" needed for the select of unit of measurement.
https://github.com/iMicknl/ha-tahoma/blob/3c43f1fc585c62cb7ee547bb23dc47bdcba1f55b/custom_components/tahoma/sensor.py#L135-L140

Here are the attributes of the CO2Sensor : 
```
      {
        "creationTime": 1482935460000,
        "lastUpdateTime": 1482935460000,
        "label": "IO (15021786#2)",
        "deviceURL": "io://xxxx-xxxx-xxxx/15021786#2",
        "shortcut": false,
        "controllableName": "io:CO2IOSystemDeviceSensor",
        "definition": {
          "commands": [],
          "states": [
            {
              "type": "ContinuousState",
              "qualifiedName": "core:CO2ConcentrationState"
            },
            {
              "values": [
                "available",
                "unavailable"
              ],
              "type": "DiscreteState",
              "qualifiedName": "core:StatusState"
            }
          ],
          "dataProperties": [],
          "widgetName": "CO2Sensor",
          "uiClass": "AirSensor",
          "qualifiedName": "io:CO2IOSystemDeviceSensor",
          "type": "SENSOR"
        },
        "states": [
          {
            "name": "core:StatusState",
            "type": 3,
            "value": "available"
          },
          {
            "name": "core:CO2ConcentrationState",
            "type": 1,
            "value": 601
          }
        ],
        "attributes": [
          {
            "name": "core:PowerSourceType",
            "type": 3,
            "value": "mainSupply"
          }
        ],
        "available": true,
        "enabled": true,
        "placeOID": "27c236f2-8df0-49d6-80e8-bcdcae9f9dd4",
        "widget": "CO2Sensor",
        "type": 2,
        "oid": "55288adc-5b26-495c-afeb-615f405afcf8",
        "uiClass": "AirSensor"
      },
```
**Expected behavior**
I made a try to match the unit with the Device_class and now the entity is available.
```
    def unit_of_measurement(self):
        """Return the unit of measurement of this entity, if any."""
        UNITS_CLASS = {
            DEVICE_CLASS_CO2: CONCENTRATION_PARTS_PER_MILLION,
            DEVICE_CLASS_CO: CONCENTRATION_PARTS_PER_MILLION,
        }
        if self.device_class in UNITS_CLASS:
            return UNITS_CLASS.get(self.device_class)

        if self.device.attributes:
            attribute = self.device.attributes[CORE_MEASURED_VALUE_TYPE]
            return UNITS.get(attribute.value)
        return None
```
I don't know if the COSensor have the same problem but it's the same ppm unit so it maybe usefull to add it as exception too.

Although, I find a problem with the icons : 
https://github.com/iMicknl/ha-tahoma/blob/3c43f1fc585c62cb7ee547bb23dc47bdcba1f55b/custom_components/tahoma/sensor.py#L52-L53
For COSensor, the correct one is "mdi:molecule-co", and for CO2Sensor, the correct one is "mdi:molecule-co2"

And the result : 
![Capture d’écran_2021-02-17_15-22-32](https://user-images.githubusercontent.com/11087736/108217701-310b6300-7134-11eb-879f-f9254f0b1f70.png)

**Comment by iMicknl** [comment]
Thanks for your extensive research again, @tillstaff. Perhaps you would like to contribute as well via a pull request? We are looking for more contributors for this project, since there is currently quite a load via all the issues created.

**Comment by tillstaff** [comment]
@iMicknl I don't know so much about Python, but I can try to help.
Here is my first Pull Request #391
