### ISSUE TITLE
Add support for EvoHome - EvoHomeController (ramses:EvoHomeController)

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#403]
**Device information**
![image](https://user-images.githubusercontent.com/1424596/111222714-7ceae400-85dc-11eb-983f-f856caed1f19.png)

Reported by @wzwart76.

**Device details**

- **Hub**: Somfy TaHoma

```
2021-03-15 20:48:52 DEBUG (MainThread) [custom_components.tahoma] Unsupported device detected (ramses:EvoHomeController - EvoHome - EvoHomeController - ramses://xxxx-xxxx-xxxx/xxxxxx/xxx#1)
```

**Device commands**
```
{
	"commands": [{
		"commandName": "setOperatingMode",
		"nparams": 2
	}],
	"states": [{
		"values": ["auto", "eco", "holidays", "off"],
		"type": "DiscreteState",
		"qualifiedName": "ramses:RAMSESOperatingModeState"
	}, {
		"type": "DataState",
		"qualifiedName": "ramses:RAMSESOperatingModeTimeoutState"
	}],
	"dataProperties": [],
	"widgetName": "EvoHomeController",
	"uiClass": "EvoHome",
	"qualifiedName": "ramses:EvoHomeController",
	"type": "ACTUATOR"
}
```

**Comment by iMicknl** [comment]
@wzwart76 if you could give [this version](https://github.com/iMicknl/ha-tahoma/archive/feature/EvoHomeController.zip) a try and report here if it works. Afterwards I will make sure that this functionality is included in the next release.

**Comment by wzwart76** [comment]
Hi Mick,

Just tried the new version and I can set my Evohome to Auto and Off. Is that the correct behavior?

Grtz,

Willem

**Comment by iMicknl** [comment]
It should be possible to set your EvoHome to 'holiday' and 'day-off' as well via presets. Is that not supported?

If so; could you share a screenshot of your climate card in Lovelace.

**Comment by iMicknl** [comment]
@wzwart76 should we merge this, or is it not working yet? :-)
