### ISSUE TITLE
Add support for EvoHome - DHWSetPoint (ramses:EvoHomeDHWSetPoint)

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#404]
**Device information**
Unknown what this device does, it looks like a water heater.

Device owned by @wzwart76.

**Device details**

- **Hub**: Somfy TaHoma

```
2021-03-15 20:48:52 DEBUG (MainThread) [custom_components.tahoma] Unsupported device detected (ramses:EvoHomeDHWSetPoint - EvoHome - DHWSetPoint - ramses://xxxx-xxxx-xxxx/xxxxxx/xxx#1)
```

**Device commands**
```
{
	"commands": [{
		"commandName": "getName",
		"nparams": 0
	}, {
		"commandName": "setTimeProgram",
		"nparams": 1
	}],
	"states": [{
		"type": "DataState",
		"qualifiedName": "core:NameState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "core:TargetDHWTemperatureState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "core:TemperatureState"
	}, {
		"type": "DataState",
		"qualifiedName": "ramses:RAMSESDHWTimeProgramState"
	}],
	"dataProperties": [],
	"widgetName": "DHWSetPoint",
	"uiClass": "EvoHome",
	"qualifiedName": "ramses:EvoHomeDHWSetPoint",
	"type": "ACTUATOR"
}
```

**Comment by tillstaff** [comment]
This device is already integrated with this core component : 
[https://github.com/home-assistant/core/tree/dev/homeassistant/components/evohome](url)

**Comment by iMicknl** [comment]
@tillstaff do you know if the EvoHome integration requires another hub? Or if you just plug the USB receiver in a Raspberry Pi?

@wzwart76 could you maybe tell us a bit more about how you connected your EvoHome system to Somfy TaHoma.

**Comment by wzwart76** [comment]
The Evohome is connected to my Tahoma to a HGI80 interface via USB.
I will try the core component as well, but I remember having issues with it.
