### ISSUE TITLE
Somfy TaHoma Z-Wave USB-Modul 1822492

### ISSUE THREAD

**Issue by sdsmart81** [iMicknl/ha-tahoma#410]
Somfy TaHoma Z-Wave USB-Module

Somfy TaHoma Z-Wave USB-Stick (Somfy No 1822492) seems to be currently not supported under the TaHoma custom components. I would like to use this module to integrate Z-Wave devices also from other brands (e.g. Aeotec Nano Dimmer) into my home assistant environment. Could this be added to the TaHoma custom components?

**Device details**
DEBUG (MainThread) [custom_components.tahoma] Unsupported device detected (zwave:NodeComponent - NetworkComponent - Node - zwave://1202-2738-5532/1#1)

**Comment by vlebourl** [comment]
hi, thank you for your interest in our project. As you may have seen, we have a lot of open tickets in our issue tracker. As ZWave is natively supported by Home Assistant, we don't plan to add it ourselves to this integration. If you want to help us and provide us with the support, feel free to fork the project and open a PR with your proposition. We would be very happy to review it and integrate it. But for now, I'm sorry we can't help you more with this issue. All the best.

**Comment by iMicknl** [comment]
@sdsmart81 just out of interest, what would be a reason to use Z-Wave devices via the Somfy TaHoma hub, instead of directly in Home Assistant? :)

And which Z-Wave devices do you use? The debug details that you included only contain your stick, but no individual device. It could be that some of your devices (like dimmers) are already supported.

**Comment by sdsmart81** [comment]
Hi Mick,

 

Thanks a lot for your reply! I was hoping to connect my new Aeotec Nano Dimmer into my smart home environment using the Somfy TaHoma Z-Wave USB Stick which I already have since I don't have any Z-Wave gateway. Unfortunately Somfy is not supporting the Aeotec Nano Dimmer on their portal. My second hope was that maybe I could connect with help of your TaHoma custom component, which by the way is great and has already helped me a lot integrating my Somfy devices (like sensors) into home assistant, but there I saw that the USB stick is not supported.

 

Any recommendations how you would integrate the Aeotec Nano Dimmer into Home Assistant? I'm using my QNAP T231P NAS with container station to run Home Assistant.

 

Thanks and regards

Stefan

 
 

Gesendet: Samstag, 27. März 2021 um 19:13 Uhr
Von: "Mick Vleeshouwer" ***@***.***>
An: "iMicknl/ha-tahoma" ***@***.***>
Cc: "sdsmart81" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [iMicknl/ha-tahoma] Somfy TaHoma Z-Wave USB-Modul 1822492 (#410)


 

@sdsmart81 just out of interest, what would be a reason to use Z-Wave devices via the Somfy TaHoma hub, instead of directly in Home Assistant? :)

And which Z-Wave devices do you use? The debug details that you included only contain your stick, but no individual device. It could be that some of your devices (like dimmers) are already supported.

**Comment by tetienne** [comment]
@sdsmart81 If you have a ZWave key on your Tahoma box, just remove it and plug on the computer where HA is hosted. Then enable the Zwave-JS integration: https://www.home-assistant.io/integrations/zwave_js/

Zwave on the Tahoma box is really limited.

**Comment by iMicknl** [comment]
@tetienne not sure though if the Z-Wave stick from Somfy TaHoma is supported in Home Assistant, but indeed I would give it a try with the native Z-Wave integration.

@sdsmart81 if the log doesn't show any other unsupported devices than `zwave:NodeComponent`, this integration can't help you either... We depend on the Somfy TaHoma API and if it doesn't show up in tahomalink.com, your device won't be supported via the TaHoma hub.

**Comment by tetienne** [comment]
@iMicknl Mine came from Somfy: https://boutique.somfy.fr/cle-zwave-pour-tahoma.html
It works well with HA.
