### ISSUE TITLE
[UpDownHorizontalAwning] Open and close buttons are reversed

### ISSUE THREAD

**Issue by kassai** [iMicknl/ha-tahoma#411]
**Describe the bug**
The sun blind open and close buttons in Home Assistant are reversed/inverted.

By clicking on the "open" icon, you trigger the blind to be closed.
By clicking on "close", you open the blind.

**To Reproduce**

1. Go to the Home Assistant Lovelace view containing the blind.
2. Click on the "close" icon/button and watch the blind open.
3. Click on the "open" icon/button and watch the blind close.
4. In the "history" section of the device, you will see entries stating that you first have closed the blind and then opened it.

**Expected behavior**
I'd like the "open" icon/button to open the blind.
I'd like the "close" button/icon to close the blind.

**Screenshots**
![image](https://user-images.githubusercontent.com/1950523/112755684-12757300-8fe2-11eb-95f4-9f6410cce2ff.png)

**Environment (please complete the following information):**

- **Hub**: Somfy TaHoma
- **ha-tahoma version:** 2021.1.4-12
- **Home Assistant version:** core-2021.3.4
- **Platform**, **Model**, **Type**: UpDownHorizontalAwning, firmware: rts:HorizontalAwningRTSComponent 

**Device:** (if your problem is related to a specific device)

**Additional context**
This is possibly related to similar reported issues. However, these issues have covered the position of the blinds.

**Comment by iMicknl** [comment]
@kassai thank you for reporting! To be honest, I am not sure if this is an issue we can fix. We just map open to open and close to close...

Could you give the `cover.close_cover` and `cover.open_cover` a try? I wonder if this is working well and if the icons are just confusing. Does it work for you via tahomalink.com?

**Comment by iMicknl** [comment]
As a follow up question, does your awning have a horizontal position or is it a vertical screen? Would be good to understand how it is mounted.

**Comment by kassai** [comment]
Thanks for the reply, @iMicknl. It's horizontal. I'll give it a try with the `cover.close_cover` and `cover.open_cover' as soon as it has stopped raining and I'm at home. It works correctly and as expected using the Tahomalink website.

**Comment by iMicknl** [comment]
And just to be sure, the icons should function like [this](https://github.com/home-assistant/frontend/issues/5513#issuecomment-611700710). I find them highly confusing myself...

**Comment by kassai** [comment]
Reading the other post, I'm a bit confused.

Step-by-step,
1. I push the left button and there is an icon with an arrow pointing upwards showing up to the very left. The arrow indicates that it is closing, which is true. The button that I pushed incorrectly indicates that I'm opening it.
![image](https://user-images.githubusercontent.com/1950523/114617381-5639cf00-9ca8-11eb-9289-76fb02a4b623.png)

2. Looking at the history log, it also incorrectly states that I'm opening it.
![image](https://user-images.githubusercontent.com/1950523/114617736-d06a5380-9ca8-11eb-9c68-358b259fd7a8.png)

So to conclude, the button and the history log indicates that I'm opening it. This is incorrect.
The arrow to the left (that is visible for a short period of time after triggering the action) indicates that I'm closing it. This is correct.

**Comment by tetienne** [comment]
Just to clarify. For HA, the expand button (on the left) means open and the collapse button means close.

That's something we cannot change.

To confirm this, play with the Tahoma interface. Collapse and expand the awning and check the icons are correct.

**Comment by kassai** [comment]
When I press the left button (=expand button to the left), it closes in reality (and is logged as if it is opening). Sorry if I was unclear in my previous comment.

**Comment by tetienne** [comment]
@kassai Can you please define what you mean by close: collapsed or expanded?

**Comment by kassai** [comment]
@tetienne - it collapses/shuts/retracts when I click the expand button.

**Comment by tetienne** [comment]
Waiting for a potential fix, you can use a cover template, to reverse the command of your awning: https://www.home-assistant.io/integrations/cover.template/

**Comment by iMicknl** [comment]
> Waiting for a potential fix, you can use a cover template, to reverse the command of your awning: https://www.home-assistant.io/integrations/cover.template/

I had the same thought, maybe we need to document this one properly. The thing I can't understand yet is why tahomalink.com shows the right result for all users, are we missing something?

**Comment by tetienne** [comment]
@kassai Any chance you can try this branch: https://github.com/iMicknl/ha-tahoma/pull/427? It should solved your issue.

**Comment by kassai** [comment]
I have limited time during the coming days, but will try it out during the weekend.
