### ISSUE TITLE
Add support Somfy outdoor Camera shutter (private life option)

### ISSUE THREAD

**Issue by PoVPoV29** [iMicknl/ha-tahoma#412]
Hello,
I have a Somfy Outdoor Camera and the status of the virtual shutter (virtual is because the camera is filming or not : there is no mechanical shutter) is not updated in HA. : 
cover.allee | unknown | core:CloudDeviceStatusState: online friendly_name: Allée supported_features: 3 device_class: shutter

Thanks for your help.
Regards
Alain

**Comment by iMicknl** [comment]
@PoVPoV29 what is your actual question? Is this device currently not supported?

Please don't remove the bug report template, since it mentions all the information we need. Could you perhaps create a new issue with all the required details? (don't forget to turn on debug mode).
