### ISSUE TITLE
Somfy Doorlock

### ISSUE THREAD

**Issue by RienduPre** [iMicknl/ha-tahoma#413]
I have a question, is the Somfy doorlook also supported by this plugin?

THanks,
Rien

**Comment by vlebourl** [comment]
hi, the old lock is supported as long as you have the wifi bridge with it to connect it to your tahoma box. it's a stateless lock, do you can lock and unlock from HA but no way to know the state of the lock or whether the action succeeded.

**Comment by RienduPre** [comment]
Ok thanks.
Not really what I'm looking for, because it's stateless.

**Comment by iMicknl** [comment]
@RienduPre if there are locks from Somfy that are stateful, they could easily be supported with this integration. But indeed, I don't think they offer stateful locks.

**Comment by vlebourl** [comment]
I think the new one will be stateful. Unfortunately, even on the Tahoma box the current one is stateless... It is strange because the dedicated app knows the state. No idea why they limited it on the Tahoma box...
