### ISSUE TITLE
[awning] Closure & position states are incorrect

### ISSUE THREAD

**Issue by labr3y** [iMicknl/ha-tahoma#419]
- [x] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**
The states are correctly reported for the horizontal awning, but for the vertical awning the following states are reversed :
core:ClosureState
core:OpenClosedState
current_position

When the awning is closed I have the following : 
> **current_position: 100**
> rssi_level: 84
> 'core:NameState': Lambrequin
> 'core:PriorityLockTimerState': 0
> 'core:StatusState': available
> 'core:DiscreteRSSILevelState': good
> 'core:RSSILevelState': 84
> **'core:ClosureState': 0
> 'core:OpenClosedState': open**
> 'core:Memorized1PositionState': 67
> 'io:PriorityLockOriginatorState': null
> 'io:PriorityLockLevelState': null
> friendly_name: Lambrequin
> supported_features: 527
> device_class: awning

When it's opened I have : 
> **current_position: 0**
> rssi_level: 78
> 'core:NameState': Lambrequin
> 'core:PriorityLockTimerState': 0
> 'core:StatusState': available
> 'core:DiscreteRSSILevelState': normal
> 'core:RSSILevelState': 78
> **'core:ClosureState': 100
> 'core:OpenClosedState': closed**
> 'core:Memorized1PositionState': 67
> 'io:PriorityLockOriginatorState': null
> 'io:PriorityLockLevelState': null
> friendly_name: Lambrequin
> supported_features: 527
> device_class: awning

When it's a little bit opened I have:
> **current_position: 80**
> rssi_level: 84
> 'core:NameState': Lambrequin
> 'core:PriorityLockTimerState': 0
> 'core:StatusState': available
> 'core:DiscreteRSSILevelState': good
> 'core:RSSILevelState': 84
>**'core:ClosureState': 20
> 'core:OpenClosedState': open**
> 'core:Memorized1PositionState': 67
> 'io:PriorityLockOriginatorState': null
> 'io:PriorityLockLevelState': null
> friendly_name: Lambrequin
> supported_features: 527
> device_class: awning
There you can see that open/closed state is correctly stated as open (IMO awning should be stated as open as long they are not fully closed).

**To Reproduce**
N/A

**Expected behavior**
core:ClosureState & core:OpenClosedState having the correct values.

**Screenshots**
Status is correctly reported on tahomalink.com
When open:
![image](https://user-images.githubusercontent.com/73796206/114771072-75019980-9d6c-11eb-868b-fe124cdb3217.png)

When closed:
![image](https://user-images.githubusercontent.com/73796206/114771254-a4b0a180-9d6c-11eb-8669-0492449af56b.png)

![image](https://user-images.githubusercontent.com/73796206/114771895-6bc4fc80-9d6d-11eb-8c4e-01c7daaa6d86.png)
Yellow = inverted depending of the version (2.4.7 or 2.4.6), but both are working (meaning it's closing the awning if it's open, and opening if it's closed)
Green = incorrect values

**Environment (please complete the following information):**

- **Hub**: Somfy TaHoma : firmware 2021.1.4-20
- **ha-tahoma version:** 2.4.7 (same on 2.4.6 but the open & close buttons were reversed
- **Home Assistant version:** 2021.4.4
- **Platform**: cover

**Device:**
- **Model**: AwningValance (vertical awning)
- **Type**:  Firmware: io:AwningValanceIOComponent

**Additional context**
Looking at the other part of the sunscreen (horizontal awning), I have the following:

> current_position: 0
> rssi_level: 100
> 'core:NameState': Store banne terr
> 'core:PriorityLockTimerState': 0
> 'core:StatusState': available
> 'core:DiscreteRSSILevelState': good
> 'core:RSSILevelState': 100
> 'core:MovingState': false
> **'core:DeploymentState': 0**
> 'core:OpenClosedState': closed
> 'core:Memorized1PositionState': 105
> 'core:TargetClosureState': 0
> 'io:PriorityLockOriginatorState': null
> 'io:PriorityLockLevelState': null
> friendly_name: Store banne terrasse
> supported_features: 527
> device_class: awning

I'm wondering if core:ClosureState could be replaced by core:DeploymentState' to get the correct value.
Or maybe current_position and ClosureState are inverted.

**Comment by tetienne** [comment]
@labr3y  Any chance you can try this branch: https://github.com/iMicknl/ha-tahoma/pull/427? It should solved your issue.

**Comment by labr3y** [comment]
@tetienne @iMicknl 
I tried. It's still not working.
It's the vertical one that has issues. From what I understood in the modifications in cover.py, it's oriented toward horizontal issues.
I'm available on discord if needed.

developer-tools/state when it's closed :
```
current_position: 100
rssi_level: 68
'core:NameState': Lambrequin
'core:PriorityLockTimerState': 0
'core:StatusState': available
'core:DiscreteRSSILevelState': normal
'core:RSSILevelState': 68
'core:ClosureState': 0
'core:OpenClosedState': open
'core:Memorized1PositionState': 67
'io:PriorityLockOriginatorState': null
'io:PriorityLockLevelState': null
friendly_name: Lambrequin
supported_features: 527
device_class: awning
```

**Comment by tetienne** [comment]
Thx. 

For reference:

```
{
  "commands": [
    {
      "commandName": "advancedRefresh",
      "nparams": 1
    },
    {
      "commandName": "close",
      "nparams": 0
    },
    {
      "commandName": "delayedStopIdentify",
      "nparams": 1
    },
    {
      "commandName": "deploy",
      "nparams": 0
    },
    {
      "commandName": "down",
      "nparams": 0
    },
    {
      "commandName": "getName",
      "nparams": 0
    },
    {
      "commandName": "identify",
      "nparams": 0
    },
    {
      "commandName": "my",
      "nparams": 0
    },
    {
      "commandName": "open",
      "nparams": 0
    },
    {
      "commandName": "refreshMemorized1Position",
      "nparams": 0
    },
    {
      "commandName": "setClosure",
      "nparams": 1
    },
    {
      "commandName": "setDeployment",
      "nparams": 1
    },
    {
      "commandName": "setMemorized1Position",
      "nparams": 1
    },
    {
      "commandName": "setName",
      "nparams": 1
    },
    {
      "commandName": "setPosition",
      "nparams": 1
    },
    {
      "commandName": "setSecuredPosition",
      "nparams": 1
    },
    {
      "commandName": "startIdentify",
      "nparams": 0
    },
    {
      "commandName": "stop",
      "nparams": 0
    },
    {
      "commandName": "stopIdentify",
      "nparams": 0
    },
    {
      "commandName": "undeploy",
      "nparams": 0
    },
    {
      "commandName": "up",
      "nparams": 0
    },
    {
      "commandName": "wink",
      "nparams": 1
    },
    {
      "commandName": "runManufacturerSettingsCommand",
      "nparams": 2
    },
    {
      "commandName": "keepOneWayControllersAndDeleteNode",
      "nparams": 0
    },
    {
      "commandName": "pairOneWayController",
      "nparams": 2
    },
    {
      "commandName": "setConfigState",
      "nparams": 1
    },
    {
      "commandName": "unpairAllOneWayControllersAndDeleteNode",
      "nparams": 0
    },
    {
      "commandName": "unpairAllOneWayControllers",
      "nparams": 0
    },
    {
      "commandName": "unpairOneWayController",
      "nparams": 2
    }
  ],
  "states": [
    {
      "type": "ContinuousState",
      "qualifiedName": "core:DeploymentState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "good",
        "low",
        "normal",
        "verylow"
      ],
      "qualifiedName": "core:DiscreteRSSILevelState"
    },
    {
      "type": "DataState",
      "qualifiedName": "core:ManufacturerSettingsState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:Memorized1PositionState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "false",
        "true"
      ],
      "qualifiedName": "core:MovingState"
    },
    {
      "type": "DataState",
      "qualifiedName": "core:NameState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "closed",
        "open"
      ],
      "qualifiedName": "core:OpenClosedState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:PriorityLockTimerState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:RSSILevelState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:SecuredPositionState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "available",
        "unavailable"
      ],
      "qualifiedName": "core:StatusState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:TargetClosureState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "comfortLevel1",
        "comfortLevel2",
        "comfortLevel3",
        "comfortLevel4",
        "environmentProtection",
        "humanProtection",
        "userLevel1",
        "userLevel2"
      ],
      "qualifiedName": "io:PriorityLockLevelState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "LSC",
        "SAAC",
        "SFC",
        "UPS",
        "externalGateway",
        "localUser",
        "myself",
        "rain",
        "security",
        "temperature",
        "timer",
        "user",
        "wind"
      ],
      "qualifiedName": "io:PriorityLockOriginatorState"
    }
  ],
  "dataProperties": [
    {
      "value": "500",
      "qualifiedName": "core:identifyInterval"
    }
  ],
  "widgetName": "PositionableHorizontalAwning",
  "uiProfiles": [
    "StatefulDeployableAwning",
    "StatefulDeployable",
    "Deployable",
    "DeployUndeploy",
    "StatefulOpenClose",
    "OpenClose"
  ],
  "uiClass": "Awning",
  "qualifiedName": "io:HorizontalAwningIOComponent",
  "type": "ACTUATOR"
}
```

**Comment by jaddel** [comment]
My shades are also reversed using the Connexoon io. 
Is there anything I can provide to be of help?

**Comment by jaddel** [comment]
> > My shades are also reversed using the Connexoon io, latest ha, latest hacs, latest tahoma.
> > Is there anything I can provide to be of help?
> 
> Can you please confirm the firmware and the model of your faulty device. You can find them within _Configuration > Integrations > Tahoma > Your device_.

Firmware: 2021.1.4

**Comment by tetienne** [comment]
@jaddel You missed also the model of your device, should start with *io:* or *rts:*

**Comment by jaddel** [comment]
it's in the previous post connexoon io.

**Comment by tetienne** [comment]
I asked for this 

![image](https://user-images.githubusercontent.com/8216238/117979155-e82e0980-b332-11eb-8af8-ef697f178fdd.jpeg)

**Comment by jaddel** [comment]
ahh sry, here it is: 

Device info
PositionableRollerShutterUno
by Somfy
Firmware: io:RollerShutterUnoIOComponent

**Comment by tetienne** [comment]
@jaddel Looks like a classic roller shutter. When you use the open command within HA, it should deploy the cover, hide the light  It's not the case?

```JSON
{
  "commands": [
    {
      "commandName": "advancedRefresh",
      "nparams": 1
    },
    {
      "commandName": "close",
      "nparams": 0
    },
    {
      "commandName": "delayedStopIdentify",
      "nparams": 1
    },
    {
      "commandName": "down",
      "nparams": 0
    },
    {
      "commandName": "getName",
      "nparams": 0
    },
    {
      "commandName": "identify",
      "nparams": 0
    },
    {
      "commandName": "my",
      "nparams": 0
    },
    {
      "commandName": "open",
      "nparams": 0
    },
    {
      "commandName": "refreshMemorized1Position",
      "nparams": 0
    },
    {
      "commandName": "setClosure",
      "nparams": 1
    },
    {
      "commandName": "setDeployment",
      "nparams": 1
    },
    {
      "commandName": "setMemorized1Position",
      "nparams": 1
    },
    {
      "commandName": "setName",
      "nparams": 1
    },
    {
      "commandName": "setPosition",
      "nparams": 1
    },
    {
      "commandName": "setSecuredPosition",
      "nparams": 1
    },
    {
      "commandName": "startIdentify",
      "nparams": 0
    },
    {
      "commandName": "stop",
      "nparams": 0
    },
    {
      "commandName": "stopIdentify",
      "nparams": 0
    },
    {
      "commandName": "up",
      "nparams": 0
    },
    {
      "commandName": "wink",
      "nparams": 1
    },
    {
      "commandName": "runManufacturerSettingsCommand",
      "nparams": 2
    },
    {
      "commandName": "keepOneWayControllersAndDeleteNode",
      "nparams": 0
    },
    {
      "commandName": "pairOneWayController",
      "nparams": 2
    },
    {
      "commandName": "setConfigState",
      "nparams": 1
    },
    {
      "commandName": "unpairAllOneWayControllersAndDeleteNode",
      "nparams": 0
    },
    {
      "commandName": "unpairAllOneWayControllers",
      "nparams": 0
    },
    {
      "commandName": "unpairOneWayController",
      "nparams": 2
    }
  ],
  "states": [
    {
      "type": "DiscreteState",
      "values": [
        "good",
        "low",
        "normal",
        "verylow"
      ],
      "qualifiedName": "core:DiscreteRSSILevelState"
    },
    {
      "type": "DataState",
      "qualifiedName": "core:ManufacturerSettingsState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:Memorized1PositionState"
    },
    {
      "type": "DataState",
      "qualifiedName": "core:NameState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:PriorityLockTimerState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:RSSILevelState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:SecuredPositionState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "available",
        "unavailable"
      ],
      "qualifiedName": "core:StatusState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:TargetClosureState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "comfortLevel1",
        "comfortLevel2",
        "comfortLevel3",
        "comfortLevel4",
        "environmentProtection",
        "humanProtection",
        "userLevel1",
        "userLevel2"
      ],
      "qualifiedName": "io:PriorityLockLevelState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "LSC",
        "SAAC",
        "SFC",
        "UPS",
        "externalGateway",
        "localUser",
        "myself",
        "rain",
        "security",
        "temperature",
        "timer",
        "user",
        "wind"
      ],
      "qualifiedName": "io:PriorityLockOriginatorState"
    }
  ],
  "dataProperties": [
    {
      "value": "500",
      "qualifiedName": "core:identifyInterval"
    }
  ],
  "widgetName": "PositionableRollerShutterUno",
  "uiProfiles": [
    "CloseableShutter",
    "Closeable",
    "OpenClose"
  ],
  "uiClass": "RollerShutter",
  "qualifiedName": "io:RollerShutterUnoIOComponent",
  "type": "ACTUATOR"
}
```

**Comment by jaddel** [comment]
I'm sry, i just double cheeked and in HA it seems to work correctly except the % positioning is not accurate. 

Since I use homekit to control everything the error must be somewhere there.

**Comment by jaddel** [comment]
I just double checked the full function inside HA. 

If I use the up and down buttons from the HA frontend the cover behaves correct, but as soon as i touch the slider things go wrong. 
I assume that homekit controls the shades  only by setting the position in % and that's why via homekit even open and close dosen't work properly. 

When i mode the slider in HA (click, drag, let go) it jumps to different position afterwards. 

Is there anything else i can provide helping to fix this?

**Comment by tetienne** [comment]
@jaddel please have a try with the current master branch to see if it works as expected. Please also only compare the website Tahomalink.com and Home Assistant to help us to understand the behavior.

**Comment by jaddel** [comment]
is just updated and everything is working finde again. Thank you!
