### ISSUE TITLE
Add support for UpDownHorizontalAwning (rts:HorizontalAwningRTSComponent)

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#42]
_Copied from https://github.com/vlebourl/tahoma_extended/issues/8 by @gieljnssns_

**Device details**
```json
 {
         "creationTime":1541775044000,
         "lastUpdateTime":1541775044000,
         "label":"Zonnetent",
         "deviceURL":"rts://",
         "shortcut":false,
         "controllableName":"rts:HorizontalAwningRTSComponent",
         "definition":{
            "commands":[
               {
                  "commandName":"close",
                  "nparams":0
               },
               {
                  "commandName":"deploy",
                  "nparams":0
               },
               {
                  "commandName":"down",
                  "nparams":0
               },
               {
                  "commandName":"identify",
                  "nparams":0
               },
               {
                  "commandName":"my",
                  "nparams":0
               },
               {
                  "commandName":"open",
                  "nparams":0
               },
               {
                  "commandName":"rest",
                  "nparams":0
               },
               {
                  "commandName":"stop",
                  "nparams":0
               },
               {
                  "commandName":"test",
                  "nparams":0
               },
               {
                  "commandName":"undeploy",
                  "nparams":0
               },
               {
                  "commandName":"up",
                  "nparams":0
               }
            ],
            "states":[

            ],
            "dataProperties":[
               {
                  "value":"0",
                  "qualifiedName":"core:identifyInterval"
               }
            ],
            "widgetName":"UpDownHorizontalAwning",
            "uiClass":"Awning",
            "qualifiedName":"rts:HorizontalAwningRTSComponent",
            "type":"ACTUATOR"
         },
         "attributes":[
            {
               "name":"rts:diy",
               "type":6,
               "value":true
            }
         ],
         "available":true,
         "enabled":true,
         "placeOID":"",
         "widget":"UpDownHorizontalAwning",
         "type":1,
         "oid":"",
         "uiClass":"Awning"
      }
```

**Comment by iMicknl** [comment]
@gieljnssns every Awning should already be supported, could you give it a try using the latest version?

**Comment by gieljnssns** [comment]
<img width="861" alt="Schermafbeelding 2020-06-08 om 10 52 57" src="https://user-images.githubusercontent.com/17234951/84011712-cedc4a80-a976-11ea-8d01-c6a78e8f71cc.png">

I think the service needs to be changed, with the green covering my terrace and the red no longer.
Also the `stop` does not work.

**Comment by iMicknl** [comment]
@dsbaars how is your horizontal cover device mapped? Is the above sample reversed or the same as your situation? 

We reversed the open and close commands for one Horizontal device, however maybe we should do it for all horizontal devices. :-)

**Comment by dsbaars** [comment]
For me it's correct now, so green circled button closed (lift the screen "up" in my case) and red circled button brings the screen down out.

**Comment by iMicknl** [comment]
@gieljnssns could you try the following branch https://github.com/iMicknl/ha-tahoma/tree/fix_44 and see if this fixes your issue?

**Comment by gieljnssns** [comment]
> <img alt="Schermafbeelding 2020-06-08 om 10 52 57" width="861" src="https://user-images.githubusercontent.com/17234951/84011712-cedc4a80-a976-11ea-8d01-c6a78e8f71cc.png">
> 
> I think the service needs to be changed, with the green covering my terrace and the red no longer.
> 
> It also responds very slowly

Sorry it took so long, but it is still the same

**Comment by gieljnssns** [comment]
> It also responds very slowly
It last about 15 a 20 sec in between a click and my awning to respond

**Comment by iMicknl** [comment]
@gieljnssns don't you have this delay when using the Tahoma app? Because I am not sure what could cause the delay, we send the commands directly to the Tahoma API like the old component.

Thanks for testing.

**Comment by dsbaars** [comment]
I do not experience this delay with my (io protocol) awning. 
I only experience some delay seeing the state updated in the position slider. Maybe you could check your HA log for errors from this compnent?

**Comment by gieljnssns** [comment]
I do not have this delay when using https://www.tahomalink.com/enduser-mobile-web/steer-html5-client/tahoma/

deploy awning
```json
{
    "startTime": 1592044728710,
    "owner": "xxxxxxxxxx@me.com",
    "actionGroup": {
        "label": "Zonnetent - Ontplooien - TaHoma PC",
        "shortcut": false,
        "notificationTypeMask": 0,
        "notificationCondition": "NEVER",
        "actions": [
            {
                "deviceURL": "rts://1211-2998-xxxxxxx/16728xxxx",
                "commands": [
                    {
                        "type": 1,
                        "name": "deploy",
                        "parameters": []
                    }
                ]
            }
        ]
    },
    "description": "Execution : Zonnetent - Ontplooien - TaHoma PC",
    "id": "ad42b184-ac10-3401-3e31-xxxxxxxxxxxxxxx",
    "state": "TRANSMITTED",
    "executionType": "Immediate execution",
    "executionSubType": "MANUAL_CONTROL"
}
```
undeploy
```json
{
    "startTime": 1592044875418,
    "owner": "xxxxxxxxx@me.com",
    "actionGroup": {
        "label": "Zonnetent - Sluiten - TaHoma PC",
        "shortcut": false,
        "notificationTypeMask": 0,
        "notificationCondition": "NEVER",
        "actions": [
            {
                "deviceURL": "rts://1211-2998-xxxxxxxx/16728xxxx",
                "commands": [
                    {
                        "type": 1,
                        "name": "undeploy",
                        "parameters": []
                    }
                ]
            }
        ]
    },
    "description": "Execution : Zonnetent - Sluiten - TaHoma PC",
    "id": "ad44ee99-ac10-3401-3e31-xxxxxxxxxxxxx",
    "state": "TRANSMITTED",
    "executionType": "Immediate execution",
    "executionSubType": "MANUAL_CONTROL"
}
```
my-position
```json
{
    "startTime": 1592044984619,
    "owner": "xxxxxxxxx@me.com",
    "actionGroup": {
        "label": "Zonnetent - My positie - TaHoma PC",
        "shortcut": false,
        "notificationTypeMask": 0,
        "notificationCondition": "NEVER",
        "actions": [
            {
                "deviceURL": "rts://1211-2998-xxxxxxxx/16728xxxx",
                "commands": [
                    {
                        "type": 1,
                        "name": "my",
                        "parameters": []
                    }
                ]
            }
        ]
    },
    "description": "Execution : Zonnetent - My positie - TaHoma PC",
    "id": "ad44ee99-ac10-3401-3e31-xxxxxxxxxxxxx",
    "state": "TRANSMITTED",
    "executionType": "Immediate execution",
    "executionSubType": "MANUAL_CONTROL"
}
```

**Comment by iMicknl** [comment]
I am not sure why `deploy` and `undeploy` are being used for your type. In the HA component we use `open` and `close`. Weird that there is a huge delay for open and close, but not for deploy and undeploy.

I will see if we can find some more people with different `rts` devices to understand what would be a global solution. Otherwise I will hardcode the fixes for your model..

**Comment by golles** [comment]
Hi @iMicknl 

I see this issue is auto closed, sadly I have the same issue as @gieljnssns.

When looking at the icons, I find these very confusing, I would have preferred the same icons as in your example: https://raw.githubusercontent.com/iMicknl/ha-tahoma/master/media/tahoma_device_page.png 
This might be more related to HA than this component. After looking to the icons for a while I thought the red one would open the awning and the green one would close. However, it's the other way around, as mentioned before.

![Screenshot 2020-09-08 at 11 13 18](https://user-images.githubusercontent.com/2211503/92458548-d6093380-f1c5-11ea-9d96-f4100aa72747.png)

I've got an RTS awning connected to a TaHoma box in my setup, I'm more than happy to help you test, let me know!
Also thank you so much for picking up the work for this new component!

**Comment by dsbaars** [comment]
I think this is indeed more HA related, since you can change the icon type but not the direction of the arrows, my "Horizontal" IO awning also moves diagonally down when opening so diagonal arrows would be more fitting.

**Comment by iMicknl** [comment]
Unfortunately, this is something in core that is confusing. We map this device to `awning`, which could be confusing with the current Home Assistant core implementation.. You can change the device class to a different value to have up / down arrows for example. [List of available device classes](https://www.home-assistant.io/integrations/cover/).

The screenshot on the main page of this repository is using `tilt_position`, which is only supported for changing the orientation of blinds / pergola slats. You could however create a [cover template](https://www.home-assistant.io/integrations/cover.template/) where you map your cover to use `tilt_position` and show the diagonal arrows.

**Comment by golles** [comment]
I don't really mind which direction the arrows show, I just don't understand the current buttons :-)
`|<-->|` will make the awning go up (not blocking sun)
`->||<-` will make the awning go down (block the sun)
To me, it would make more sense if they work the other way around.

I'll have a look into changing the device class
