### ISSUE TITLE
ha-tahoma V2.4.9: all entities unavailable

### ISSUE THREAD

**Issue by XalaTheShepard** [iMicknl/ha-tahoma#428]
Dear team,

After the update to V2.9.4 all my tahoma entities have become unavailable.
I am using a supported device (Tahoma Box) and the integration is installed on HA supervised in VM.
Untill update V.2.9.3 everything was running fine. 
Also all scenes have become unavailable. 
Furthermore, I have no issues logging in into Tahomalink from the same IP. 

Could you please inform me which steps I can take to have everything working again? 

Many thanks. 

Kind regards, 

Robin

**Comment by iMicknl** [comment]
@XalaTheShepard does it work when you rollback to 2.9.3? Could you please include your log.

**Comment by XalaTheShepard** [comment]
I have to set up samba first to roll back. Also, I will share the logs later as I have discovered a very stranger bug. If I delete the Tahoma integration from both the Integrations page and HACS and reboot, everything works fine again. When I reinstall the Tahoma integration again and reboot, everything is unavailable again... So somehow the Tahoma integration keeps running in the background, even after deleting it, and is only functional if it is not listed in the Integrations page and HACS.

**Comment by XalaTheShepard** [comment]
I got only 1 issue related to the Tahoma integration in the logs:
__init__() missing 1 required keyword-only argument: 'last_update_time'
Traceback (most recent call last):
  File "/config/custom_components/tahoma/__init__.py", line 114, in async_setup_entry
    places = await client.get_places()
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 307, in get_places
    places = Place(**humps.decamelize(response))
  File "/usr/local/lib/python3.8/site-packages/pyhoma/models.py", line 515, in __init__
    self.sub_places = [Place(**p) for p in sub_places] if sub_places else None
  File "/usr/local/lib/python3.8/site-packages/pyhoma/models.py", line 515, in <listcomp>
    self.sub_places = [Place(**p) for p in sub_places] if sub_places else None
TypeError: __init__() missing 1 required keyword-only argument: 'last_update_time'

**Comment by XalaTheShepard** [comment]
I am running the latest firmware of the Tahoma box (2021.1.4-20). It was an update of a day or two ago.

**Comment by XalaTheShepard** [comment]
Many thanks for looking into it. I will try to roll back to a previous version in the meantime. If I somehow can help testing it, please let me know. :)

**Comment by iMicknl** [comment]
Could you give https://github.com/iMicknl/ha-tahoma/archive/refs/heads/fix/428.zip a try? Extract this file and place `custom_components/tahoma` in your `custom_components` folder.

**Comment by XalaTheShepard** [comment]
Sorry for the late response. I will give it a try this evening and inform  you immediately. Many thanks.

**Comment by XalaTheShepard** [comment]
I have tested the fix and now everything works perfectly. Many thanks for the solution.
