### ISSUE TITLE
Actions open,close and stop for IO blind devices

### ISSUE THREAD

**Issue by alexebner** [iMicknl/ha-tahoma#430]
Please add the possibility to configure the action open,close and stop for IO blinds in the visual editor.

IO blinds
![grafik](https://user-images.githubusercontent.com/26386738/115656841-305e9b00-a336-11eb-8e12-37b3afef2c79.png)

RTS blinds
![grafik](https://user-images.githubusercontent.com/26386738/115656778-0dcc8200-a336-11eb-995f-b7a1f4ee839e.png)

It does work when i configure in the yaml editor 
     type: close or open or stop
but the i get in the visual editor unknown action

![grafik](https://user-images.githubusercontent.com/26386738/115657191-c5619400-a336-11eb-956e-c7967d2f2795.png)

![grafik](https://user-images.githubusercontent.com/26386738/115657221-d27e8300-a336-11eb-8910-915d69527145.png)

**Comment by tetienne** [comment]
@alexebner If you select the cover entity (and not the device), you will see the actions you are looking for.

**Comment by alexebner** [comment]
How can i select the entity

![image](https://user-images.githubusercontent.com/26386738/115673347-d2897d80-a34c-11eb-9a22-048670952641.png)

**Comment by tetienne** [comment]
Select `Call service`, then `close/open/stop cover`

**Comment by tetienne** [comment]
@alexebner I double checked your 1st comment, can you give us more details on the device where the open and close actions are not displayed?
Look for it, and show us the attributes here: https://my.home-assistant.io/redirect/developer_states/

**Comment by alexebner** [comment]
Here its showen
![image](https://user-images.githubusercontent.com/26386738/115682770-13d25b00-a356-11eb-893f-a2b43922b8ce.png)

here its not showen
![image](https://user-images.githubusercontent.com/26386738/115682548-dc63ae80-a355-11eb-829d-3504ea4f2679.png)

**Comment by iMicknl** [comment]
I am not sure why this doesn't work though, it seems that this is part of 'device_actions', which is based on the supported features.

There are workarounds for this issue, thus this won't be prioritized, however perhaps someone wants to have a look.

https://github.com/home-assistant/core/blob/dev/homeassistant/components/cover/device_action.py

**Comment by iMicknl** [comment]
This is not an issue of this integration, but 'a feature' in core. If you would like to see this changed, you could see if you (or someone else) would be able to make the changes in core.

The logic is stored here:
https://github.com/home-assistant/core/blob/dev/homeassistant/components/cover/device_action.py#L78
