### ISSUE TITLE
Too many requests, try again later 

### ISSUE THREAD

**Issue by alexebner** [iMicknl/ha-tahoma#435]
I have migrated the automation from my blinds over tahoma to Homassistant. 
Now i get very often "Too many requests, try again later".

I have tryed to take the HA offline over night but in the morning the second action does not work because too many request.

In my last home automation system (Homey) i had never problems with that. I know that i was getting an email fom somfy with the info that they implement a connection limit. Then the developer from the somfy addin makes some changes i his app and the problem never comes up.

I think that the connectionlimits are only for full device syncs with the api.

Here is the Repository from the othe app:
https://github.com/AdyRock/com.somfy.tahoma

I think the fixes of the limit problems are arround 10,Oct,2020

**Comment by iMicknl** [comment]
Could you include a bit more information? Which hub do you use and what is your current configured update interval in Home Assistant?

And do you perhaps run the Homey version next to Home Assistant?

**Comment by alexebner** [comment]
Sorry!

I am using a Somfy Tahoma Premium Device with:
5x IO Venetian blinds
1x IO Shutter
5x RTS Venetian blinds


My update interval is now configured to 300 sec. But also the same problem as bevore.
My last automation is turned off.

My first action in the morning ist to open all the Venetian blinds. Between the open.cover ations i have 1.5sec pause.
My second action 5 minutes later to open the IO Shutter does not work becaue of "Too many requests, try again later"

When i wait soeme time than it work. 


First Action

alias: Alle RAF auf
sequence:
  - service: cover.open_cover
    target:
      entity_id: cover.raffstor_bad
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 500
  - service: cover.open_cover
    target:
      entity_id: cover.raffstor_buro
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 500
  - service: cover.open_cover
    target:
      entity_id: cover.raffstor_kuche
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 500
  - service: cover.open_cover
    target:
      entity_id: cover.raffstor_wc
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 500
  - service: cover.open_cover
    target:
      entity_id: cover.raffstor_wohnzimmer
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 500
  - service: cover.open_cover
    target:
      entity_id: cover.wg_fenster_links
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 500
  - service: cover.open_cover
    target:
      entity_id: cover.wg_fenster_rechts
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 500
  - service: cover.open_cover
    target:
      entity_id: cover.wg_ture_rechts
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 500
  - service: cover.open_cover
    target:
      entity_id: cover.wg_ture_links
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 500
  - service: cover.open_cover
    target:
      entity_id: cover.wg_fenster_vorne
mode: single

**Comment by iMicknl** [comment]
Why do you use a  1.5sec pause in between all automations? I am not sure what is going wrong, but I will give it a look.

And do you perhaps run the Homey version next to Home Assistant? Or is this the only integration you are using?

**Comment by alexebner** [comment]
On homey it was a problem when i sent all action without a pause. Then it was not 100%sure that all blinds are triggered.
I was thinking that this is a problem from tahoma so i have created it same in homeassistant. My Homey ist powerd off since 2 Days becaus that was my firs idea that 2 devices connecting to tahoma make this problem.

**Comment by iMicknl** [comment]
You should not need the pause, so I would start by simplifying it by removing the breaks. `Too many requests, try again later` can indeed happen when you do too many requests, but with one installation where you just execute some actions it should not happen.

Are there any other errors / warnings in your log?

**Comment by tetienne** [comment]
For such cases,I suggest you to create a scenario within Tahomalink.com and the call it from home assistant. It will perform only one request and you are guaranteed all your covers will be opened.

**Comment by alexebner** [comment]
Yes but i also have some logic in another action.

When closing blind and the windows is open then do tilt 50%.
When windows is closed do tilt 100%

**Comment by iMicknl** [comment]
@alexebner do you only have RTS devices? Or do you have at least one IO device as well?

**Comment by alexebner** [comment]
I am using a Somfy Tahoma Premium Device with:
5x IO Venetian blinds
1x IO Shutter
5x RTS Venetian blinds

**Comment by alexebner** [comment]
Now after 8h closed firewall I have opend the firewall for homeassistant.

First i made a "ha core reload" and then i see in the log.


2021-04-28 19:37:35 ERROR (MainThread) [custom_components.tahoma] Unexpected error fetching device events data: Too many requests, try again later : login with ******@*******
Traceback (most recent call last):
  File "/config/custom_components/tahoma/coordinator.py", line 67, in _async_update_data
    events = await self.client.fetch_events()
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 215, in fetch_events
    response = await self.__post(f"events/{self.event_listener_id}/fetch")
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 333, in __post
    await self.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 371, in check_response
    raise NotAuthenticatedException(message)
pyhoma.exceptions.NotAuthenticatedException: Not authenticated

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tahoma/coordinator.py", line 78, in _async_update_data
    await self.client.login()
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 95, in login
    response = await self.__post("login", data=payload)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 333, in __post
    await self.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 363, in check_response
    raise TooManyRequestsException(message)
pyhoma.exceptions.TooManyRequestsException: Too many requests, try again later : login with ******@*******

**Comment by alexebner** [comment]
Can i help you in any way to find the problem?
The problem still exists that the half of the time the blinds are not on the position that they should be.
Sometime it works and sometime not. And in the logs everytime the same entrys.

**Comment by iMicknl** [comment]
@alexebner is this still an issue?

**Comment by alexebner** [comment]
Now with a update interval from 600 it works most of the time. But i have still the same errors in the log.
