### ISSUE TITLE
RTS awning no longer available since last commit

### ISSUE THREAD

**Issue by golles** [iMicknl/ha-tahoma#439]
- [x] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**
RTS awning no longer available since commit 02adec972ec6778d0151402eaf11b82e1594b3eb

**To Reproduce**
I manually install my `custom_components` through `git`, I just updated (`git pull`) and after a restart, I got error logs

**Expected behavior**
Obviously to have the entity available and be able to control the awning.

**Screenshots**
<img width="420" alt="Schermafbeelding 2021-05-09 om 13 21 33" src="https://user-images.githubusercontent.com/2211503/117570220-861e9b80-b0c9-11eb-843a-026504a0b401.png">

**Environment (please complete the following information):**

- **Hub**: TaHoma
- **ha-tahoma version:** 3.18.0 (15078) | 2021.1.4-20
- **Home Assistant version:** 2021.5.1
- **Platform**: cover

**Device:** (if your problem is related to a specific device)

- **Model**: UpDownHorizontalAwning
- **Type**: rts:HorizontalAwningRTSComponent

**Additional context**

Log:
```text
2021-05-09 13:17:28 ERROR (MainThread) [homeassistant.components.cover] Error adding entities for domain cover with platform tahoma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 558, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 581, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _stringify_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 192, in state
    closed = self.is_closed
  File "/config/custom_components/tahoma/cover.py", line 223, in is_closed
    if self.current_cover_position is not None:
  File "/config/custom_components/tahoma/cover.py", line 158, in current_cover_position
    position = 100 - self.select_state(
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

When I checkout 0182388195448c54397d07ff93eec69d4c1cb572, it works fine

```bash
git checkout 0182388195448c54397d07ff93eec69d4c1cb572
dcrestart homeassistant
```
Results into:
<img width="424" alt="Schermafbeelding 2021-05-09 om 13 23 32" src="https://user-images.githubusercontent.com/2211503/117570356-0cd37880-b0ca-11eb-9d01-d769a8002ab6.png">

**Comment by tetienne** [comment]
Sorry, for this. And thx for this issue nicely described. Can you please try https://github.com/iMicknl/ha-tahoma/pull/440/commits?

**Comment by golles** [comment]
> Thx for this issue nicely reported. Can you please try https://github.com/iMicknl/ha-tahoma/pull/440/commits?

It's no longer unavailable so that is good. But the awning takes now 10-30 seconds to respond from the HA UI, Also the UI remains like this:
<img width="353" alt="Schermafbeelding 2021-05-09 om 16 49 17" src="https://user-images.githubusercontent.com/2211503/117576513-91cc8b00-b0e6-11eb-91dd-87984f0e015c.png">
From https://www.tahomalink.com it reacts quite quickly.

No weird errors in the log, but haven't enabled any extra logging for this component.

**Comment by golles** [comment]
Hmm, after a bit more trying it looks like the stop button is not stopping the awning but queueing the action. I remember this was also the case in early versions of this component

**Comment by tetienne** [comment]
> > Thx for this issue nicely reported. Can you please try https://github.com/iMicknl/ha-tahoma/pull/440/commits?
> 
> 
> 
> It's no longer unavailable so that is good. But the awning takes now 10-30 seconds to respond from the HA UI, Also the UI remains like this:
> 
> <img width="353" alt="Schermafbeelding 2021-05-09 om 16 49 17" src="https://user-images.githubusercontent.com/2211503/117576513-91cc8b00-b0e6-11eb-91dd-87984f0e015c.png">
> 
> From https://www.tahomalink.com it reacts quite quickly.
> 
> 
> 
> No weird errors in the log, but haven't enabled any extra logging for this component.

It was the case with the latest version?

**Comment by golles** [comment]
I just did a bit more testing.
When the awning is open and when I press the go-up button in HA, it will close.
When I press the stop button (in HA) while closing, nothing happens and it continues to close. Once fully closed it will open again stop will also go to the prefix location and it looks like that is happening.
When I press the open button and a few seconds later the close button, it won't stop and close.

Not sure if the context is correct, but open is blocking the sun and close is not blocking the sun/retracted.

**Comment by tetienne** [comment]
> Not sure if the context is correct, but open is blocking the sun and close is not blocking the sun/retracted.

That's the expected behavior yes. open = deploy and close = undeploy (for awning only)

It will help me if we split this issue. Can you please confirm that with the PR I linked, you get the same behavior with https://github.com/iMicknl/ha-tahoma/commit/0182388195448c54397d07ff93eec69d4c1cb572?

If yes, I will merge the PR and close this issue. You can then open another issue related to the 2nd issue you described.
If no, it means I introduced a regression.

For the wording, try to use deploy and undeploy to make it clear.

**Comment by tetienne** [comment]
I met the same issue when chaining deploy stop and undeploy with the latest version. So that's not linked to my refactor. I will see what I can do.

**Comment by golles** [comment]
> > Not sure if the context is correct, but open is blocking the sun and close is not blocking the sun/retracted.
> 
> That's the expected behavior yes. open = deploy and close = undeploy (for awning only)
> 
Just wanted to make sure we're talking about the same :-)

> It will help me if we split this issue. Can you please confirm that with the PR I linked, you get the same behavior with [0182388](https://github.com/iMicknl/ha-tahoma/commit/0182388195448c54397d07ff93eec69d4c1cb572)?
> 
I checked out 0182388195448c54397d07ff93eec69d4c1cb572 and the stop button reacts immediately (let's say a second) when the awning is moving. The awning is also available, so this looks good!

**Comment by golles** [comment]
Beside the stop button, #440 Seems t work

**Comment by tetienne** [comment]
@golles There is a typo in your comment?

In the linked PR I didn't touch the Stop button.

Can you compare with the latest available version (not master branch)?

**Comment by golles** [comment]
Sorry to be a bit annoying, but all works fine till https://github.com/iMicknl/ha-tahoma/commit/02adec972ec6778d0151402eaf11b82e1594b3eb, like mentioned in the description.

**Comment by tetienne** [comment]
@golles if only the Stop button does that work, can you please open a new issue?

**Comment by golles** [comment]
Yep, will do that
