### ISSUE TITLE
Cover Offset / Positioning Calibration Tool 

### ISSUE THREAD

**Issue by jaddel** [iMicknl/ha-tahoma#443]
**Is your feature request related to a problem?**

Cover set state doesn't match the real cover state. 

**Describe the solution you'd like**

Perfect would be an ui based offset % variable, one can set individual per cover. 

**Describe alternatives you've considered**

Creating a template cover inside homeassistant for each cover and do the offset manually. 

**Additional context**

I believe the difference between the real and the app / ha / ui set state is related either to the cover design and how the cover has been calibrated during the installation process. 

This is an example how my cover looks when i set it to 50% via homekit or the HA frontend. 

![image](https://user-images.githubusercontent.com/46263124/118487271-d675a900-b71a-11eb-9416-c09f3b52b4e9.png)

**Comment by tetienne** [comment]
If you got the same behavior between HA and the official Somfy Homekit integration, it means we are good.
When you set the cover to 50% you are asking it to be deployed at 50%. It does not mean it will be set at the middle of your windows.
If it was badly calibrated, setting it to 0 or 100 would be wrong too.

**Comment by jaddel** [comment]
I never used the official somefy homekit integration everything is done via the homekit bridge integration. 

I get the same behaviour if i set the shade to 50% via the somfy app on my phone. 

You are right about:

> When you set the cover to 50% you are asking it to be deployed at 50%.

 0 - 100% is calibrated correctly since the relay clicks just in time when the open or close limit is reached. I believe the reason for this that nobody ever thought about the little gaps between the slats / blades of the shutter, in sum they add quite some unwanted offset.
 
One could say the cover has kind of two closed states. One where it its closed with the little gabs between the slats open and one where it is fully closed and no light gets through.

**Comment by iMicknl** [comment]
Looking at your story, it seems that Somfy doesn't offer good ways of calibrating your shutter due to the gaps / offset...

However, this behavior is so specific that I would say that this needs to be in a template cover or even in a separate integration.. A template cover should be the easiest I guess.

**Comment by tillstaff** [comment]
Everything is normal. 
With roller shutter, the auto-calibration will calculate the duration to fully open the roller shutter and the duration to fully close the roller shutter.

If the duration calculated is 20 seconds, so when you set the cover from 100% to 50%, it will activate the motor for 10 seconds. There is no sensor to see the real position of the cover, it's just a question of timing.
