### ISSUE TITLE
Add support for SomfyHeatingTemperatureInterface (ovp:SomfyHeatingTemperatureInterfaceOVPComponent)

### ISSUE THREAD

**Issue by Aeosium** [iMicknl/ha-tahoma#450]
- [x] **I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

*I'd be more than willing to contribute, I am presently looking into the code but as you can imagine I am not sure where to look to be efficient :)*

**Device information**

Somfy Themostat not recognized, this is not the "Smart" thermostat but another version ([vendor link](https://www.somfypro.fr/produits/-/e-cat/2401243/THERMOSTAT_PROGRAMMABLE_FILAIRE_-_CONTACT_SEC))

**Device details**

2021-05-24 22:53:56 DEBUG (MainThread) [custom_components.tahoma] Unsupported device detected (ovp:SomfyHeatingTemperatureInterfaceOVPComponent - HeatingSystem - SomfyHeatingTemperatureInterface - ovp://xxxx-xxxx-xxxx/8920562#1)

**Device commands**

"Unknown error" when trying to run the tahoma.get_execution_history, investigating the issue...

*Retrieved from another source*
```
States
core:BatteryState (full,low,normal,verylow) normal
core:ComfortRoomTemperatureState 20.5
core:EcoRoomTemperatureState 19.5
core:NameState Th Séjour
core:OnOffState (off,on) on
core:SecuredPositionTemperatureState 7
core:StatusState (available,unavailable) available
core:TargetTemperatureState 20.5
core:VersionState v01.01????
ovp:HeatingTemperatureInterfaceActiveModeState (auto,manu) auto
ovp:HeatingTemperatureInterfaceOperatingModeState (both,cooling,heating) heating
ovp:HeatingTemperatureInterfaceSetPointModeState (comfort,eco,free,secured) comfort

Commands
getName
identify
refreshActiveMode
refreshBatteryLevel
refreshComfortTemperature
refreshEcoTemperature
refreshOnOffState
refreshSecuredPositionTemperature
refreshSetPointMode
refreshTargetTemperature
refreshTemperature
setComfortTemperature + 1 parameter
setEcoTemperature + 1 parameter
setName + 1 parameter
setOnOff + 1 parameter
setOperatingMode + 1 parameter
setSecuredPositionTemperature + 1 parameter
setActiveMode + 1 parameter
setManuAndSetPointModes + 1 parameter
```

![image](https://user-images.githubusercontent.com/84744362/119407139-17a22600-bce4-11eb-86a9-c12d9e8bc0a5.png)

**Comment by Aeosium** [comment]
Hello dear bot!

I didn't try a more recent update as I don't think this has been touched yet. I tried to tweak a bit with the source code myself but no success so far, still trying to understand how things are implemented :)

Thanks!

**Comment by iMicknl** [comment]
```
{
	"commands": [{
		"commandName": "getName",
		"nparams": 0
	}, {
		"commandName": "identify",
		"nparams": 0
	}, {
		"commandName": "refreshActiveMode",
		"nparams": 0
	}, {
		"commandName": "refreshBatteryLevel",
		"nparams": 0
	}, {
		"commandName": "refreshComfortTemperature",
		"nparams": 0
	}, {
		"commandName": "refreshEcoTemperature",
		"nparams": 0
	}, {
		"commandName": "refreshOnOffState",
		"nparams": 0
	}, {
		"commandName": "refreshSecuredPositionTemperature",
		"nparams": 0
	}, {
		"commandName": "refreshSetPointMode",
		"nparams": 0
	}, {
		"commandName": "refreshTargetTemperature",
		"nparams": 0
	}, {
		"commandName": "refreshTemperature",
		"nparams": 0
	}, {
		"commandName": "setComfortTemperature",
		"nparams": 1
	}, {
		"commandName": "setEcoTemperature",
		"nparams": 1
	}, {
		"commandName": "setName",
		"nparams": 1
	}, {
		"commandName": "setOnOff",
		"nparams": 1
	}, {
		"commandName": "setOperatingMode",
		"nparams": 1
	}, {
		"commandName": "setSecuredPositionTemperature",
		"nparams": 1
	}, {
		"commandName": "setActiveMode",
		"nparams": 1
	}, {
		"commandName": "setManuAndSetPointModes",
		"nparams": 1
	}],
	"states": [{
		"type": "DiscreteState",
		"values": ["full", "low", "normal", "verylow"],
		"qualifiedName": "core:BatteryState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "core:ComfortRoomTemperatureState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "core:EcoRoomTemperatureState"
	}, {
		"type": "DataState",
		"qualifiedName": "core:NameState"
	}, {
		"type": "DiscreteState",
		"values": ["off", "on"],
		"qualifiedName": "core:OnOffState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "core:SecuredPositionTemperatureState"
	}, {
		"type": "DiscreteState",
		"values": ["available", "unavailable"],
		"qualifiedName": "core:StatusState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "core:TargetTemperatureState"
	}, {
		"type": "ContinuousState",
		"qualifiedName": "core:VersionState"
	}, {
		"type": "DiscreteState",
		"values": ["auto", "manu"],
		"qualifiedName": "ovp:HeatingTemperatureInterfaceActiveModeState"
	}, {
		"type": "DiscreteState",
		"values": ["both", "cooling", "heating"],
		"qualifiedName": "ovp:HeatingTemperatureInterfaceOperatingModeState"
	}, {
		"type": "DiscreteState",
		"values": ["comfort", "eco", "free", "secured"],
		"qualifiedName": "ovp:HeatingTemperatureInterfaceSetPointModeState"
	}],
	"dataProperties": [{
		"value": "500",
		"qualifiedName": "core:identifyInterval"
	}],
	"widgetName": "SomfyHeatingTemperatureInterface",
	"uiProfiles": ["OperatingModeHeating", "ThermostatTargetReader", "OnOffStatus"],
	"uiClass": "HeatingSystem",
	"uiClassifiers": ["generator"],
	"qualifiedName": "ovp:SomfyHeatingTemperatureInterfaceOVPComponent",
	"type": "ACTUATOR"
}
```

Are you able to run `tahoma.get_execution_history`, see https://github.com/iMicknl/ha-tahoma#device-not-working-correctly? This helps us understand which commands to execute, based on what the official app does.

**Comment by Aeosium** [comment]
Thanks for the follow-up, I'll try again to run the command and get back to you asap (it didn't work last time I tried but I'll update everything and try again)!

**Comment by Aeosium** [comment]
Hi there!

I tried running the `tahoma.get_execution_history` but still no luck. This is the error I get in the log if that can help:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/tahoma/__init__.py:313
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 22:59:35 (2 occurrences)
Last logged: 22:59:43

[139745362260848] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 525, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1219, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 728, in admin_handler
    await result
  File "/config/custom_components/tahoma/__init__.py", line 259, in handle_get_execution_history
    await write_execution_history_to_log(tahoma_coordinator.client)
  File "/config/custom_components/tahoma/__init__.py", line 313, in write_execution_history_to_log
    history = await client.get_execution_history()
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyhoma/client.py", line 152, in get_execution_history
    execution_history = [HistoryExecution(**h) for h in humps.decamelize(response)]
  File "/usr/local/lib/python3.9/site-packages/pyhoma/client.py", line 152, in <listcomp>
    execution_history = [HistoryExecution(**h) for h in humps.decamelize(response)]
  File "/usr/local/lib/python3.9/site-packages/pyhoma/models.py", line 480, in __init__
    self.execution_sub_type = ExecutionSubType(execution_sub_type)
  File "/usr/local/lib/python3.9/enum.py", line 360, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 678, in __new__
    raise ve_exc
ValueError: 'DUSK_TRIGGER' is not a valid ExecutionSubType
```

**Comment by iMicknl** [comment]
@Aeosium thanks, this has been fixed in our latest master version.

Do you use HACS? Within HACS, on ha-tahoma card, click on the 3 dots > reinstall > select master > install. Than this command should work :).

**Comment by Aeosium** [comment]
Ok I managed to get the latest master and run the `tahoma.get_execution_history`, thanks for the fix!

I then ran the following command (the screenshot of the somfy app is available on the [previous comment](https://github.com/iMicknl/ha-tahoma/issues/450#issue-900008452)):

- Auto
- Confort
- Eco
- Hors gel
- Auto
- Manual (it selected Confort)
- Off

Which gave this in the log [thermostat.txt](https://github.com/iMicknl/ha-tahoma/files/6919343/thermostat.txt)

It seems that the somfy app runs refresh commands whenever a command is sent by the user.

There was no way to adjust the temperature level, but I know it should be possible as this works on homebridge.

Hope it helps let me know if I can provide more info :)

**Comment by Aeosium** [comment]
Hi !

I didn't try a newer version since last comment. I could try to contribute but I would need an example to see where/how this should be implemented. Is there any reference I can look into ?

Cheers

**Comment by iMicknl** [comment]
@Aeosium sorry for the late replies. Feel free to join our Discord to learn more about how to contribute. We are all there to help you get up to speed.

**Comment by iMicknl** [comment]
@Aeosium I gave it a quick try, not sure if it will work. :D

Could you give https://github.com/iMicknl/ha-tahoma/archive/refs/heads/feature/climate/SomfyHeatingTemperatureInterface.zip a try? Extract this file and place `custom_components/tahoma` in your `custom_components` folder.

**Comment by iMicknl** [comment]
@Aeosium could you try above version? So we can include it with this integration.

**Comment by Aeosium** [comment]
Sorry for the late reply I've had tough times lately so couldn't give a try yet :(
I don't have hands on my setup for a few more days as I am away, but will try as soon as I return!

**Comment by iMicknl** [comment]
@Aeosium no worries, take care! Just reply when you are ready for it.

**Comment by iMicknl** [comment]
@theggz could you give https://github.com/iMicknl/ha-tahoma/archive/refs/heads/feature/climate/SomfyHeatingTemperatureInterface.zip a try? Extract this file and place `custom_components/tahoma` in your `custom_components` folder.

**Comment by theggz** [comment]
Yeah of course, I'm not home for the week-end, but I'll try it right when I get back 🙂

**Comment by theggz** [comment]
@iMicknl I tested it and it works well with my thermostat ! :)
 The only thing that doesn't work is the command to increase / decrease the temperature, but I can't do it with the official Tahoma Android App either.

**Comment by Aeosium** [comment]
Hi gents,

I also managed to test it and I do also see the thermostat! I also have the fact that controls are working to switch confort/eco but not the temperature setting. For me the present status is more than enough as I mostly wanted to be able to log the measured temperature together with the set value to study the sensitivity of my rooms to external weather and programmed heating :) . To make it useable as a real thermostat would maybe require some small addition, but that's probably overkill for now.

Thanks a lot ! Will try to look again into the implementation some day :)

**Comment by iMicknl** [comment]
Great to hear! @Aeosium / @theggz, is there anything in your log when you try to set the temperature?

We can always see if we can work some day [via Discord](https://discord.gg/RRXuSVDAzG) (iMick #1903) so we can speed up the development. Easiest would be if you could temporary change your password and send your credentials, so I can do some live debugging on my machine.
