### ISSUE TITLE
Device is not reporting the status

### ISSUE THREAD

**Issue by blasebast** [iMicknl/ha-tahoma#457]
Hi @iMicknl ,
First, thank you for the great effort putting together this integration. I would like to report an issue I observed just today after upgrading homeassistant and at the same time pulling the latest ha-tahoma:
```
homeassistant       | 2021-06-03 10:26:26 ERROR (MainThread) [custom_components.tahoma] 'UPDATING' is not a valid UpdateBoxStatus
homeassistant       |   File "/config/custom_components/tahoma/__init__.py", line 119, in async_setup_entry
homeassistant       | 2021-06-03 10:26:26 ERROR (MainThread) [custom_components.tahoma] 'UPDATING' is not a valid UpdateBoxStatus
homeassistant       |   File "/config/custom_components/tahoma/__init__.py", line 119, in async_setup_entry
```
controller and cover behind is: Connexoon + CONTROL BOX 3S RTS

**Comment by iMicknl** [comment]
Apparently your box was updating at that specific moment, but this should be a status that we also have in our library. I will add it in the following week, but perhaps your actual issue is already solved after you reload the integration.

**Comment by blasebast** [comment]
Hi, 
Thanks for your reply. I actually reloaded, removed, re-added the integration multiple times after the box's upgrade,
 it looks like on the snapshots and in the log I see stuff mentioned in the issue. I don't think I have something misconfigured, but of course I might be wrong and this specific message looks especially suspicious, maybe this is the underlying cause of issues:
`
homeassistant       | 2021-06-04 15:55:42 ERROR (MainThread) [custom_components.tahoma] Error fetching device events data: Invalid event listener id : xxxxxxxxx-ac10-3e01-5680-b8ebc43edf17
`
![image](https://user-images.githubusercontent.com/25853397/120813775-81c19300-c54e-11eb-9017-fbabf46cf02e.png)
![image](https://user-images.githubusercontent.com/25853397/120813787-86864700-c54e-11eb-8554-ba07a11b3cc9.png)
![image](https://user-images.githubusercontent.com/25853397/120814133-dcf38580-c54e-11eb-9288-dea9b339bcfd.png)

**Comment by rax2m** [comment]
same problem here opening and close states are working fine but as soon it reaches the open or closed state it shows up as unknown I hope you guys fix it because it caused me a headache with Homekit integration . 
I am happy with your work guys thanks I really appreciate it better than the Somfy integration that came with HASS

**Comment by stevehop** [comment]
Same here with my garage door, open and closing using HA shows the status but then becomes unavailable. Also when using my Somfy remotes to open/close it there's no update in HA

**Comment by blasebast** [comment]
Hi, any chance to have it fixed?

**Comment by iMicknl** [comment]
The original reported issue has been solved, however the issues that @rax2m and @stevehop mention doesn't look related. Please create a new issue regarding other issues, not related to the `'UPDATING' is not a valid UpdateBoxStatus` error.

An update with a fix for the UPDATING issue will be go out soo.
