### ISSUE TITLE
Add a second supported box integration

### ISSUE THREAD

**Issue by Alex6fr** [iMicknl/ha-tahoma#461]
Hi,

I allready have my Somfy TaHoma Box well integrated in my Home Assistant with this custom integration. Everythinks work well.

I have an Hitachi PAC Air/Air connected with Hi-Kumo app (SPX-WFG01 gateway) and when I want to add this box integration, I have this message error  (account allready added) : 

![ha-tahoma](https://user-images.githubusercontent.com/53949172/122732370-8095a300-d27c-11eb-8fc7-e63f56dca556.jpg)

Is it possible to add multiple box account in this custom integration ?

Thank's :-)

**Comment by iMicknl** [comment]
Good one! This is already supported in the PR we have for the `core` repository, but I didn't backport it yet.

Will need to see if I can gather some time in the next weeks to do this... Currently we check by email address, so perhaps you could use a different email address for one of the services in the mean time.

**Comment by Alex6fr** [comment]
Yes, It worked ! I've changed my Somfy email account.
Unfortunately my Hitachi PAC is not recognized by the integration :-( 
=>logs :  Unsupported device detected (hlrrwifi:HLinkMainController - HitachiHeatingSystem - HitachiAirToAirHeatPump - hlrrwifi://XXXX-XXXX-XXXX
My model is a RAK-25PSC (HITACHI Shirokuma S)

**Comment by iMicknl** [comment]
Please see https://github.com/iMicknl/ha-tahoma/issues/445 and https://github.com/iMicknl/ha-tahoma/issues/456, where you can follow progress and contribute with more info.
