### ISSUE TITLE
Invalid authentication errors started logging and integration didn't work

### ISSUE THREAD

**Issue by cdeharo** [iMicknl/ha-tahoma#467]
- [x] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**
At some hour of the 2021-07-07 the Tahoma component started to register `Invalid authentication` errors and stopped working with the awning.

Rebooting the HA doesn't solved the problem. 

```
2021-07-08 18:02:29 ERROR (MainThread) [custom_components.tahoma] Invalid authentication.
```

No debug logs found.

Note that managing the awning from the Connexoon Terrace app works fine from the same local network and outside it.

**To Reproduce**
1. Use HA with Tahoma custom component.

**Expected behavior**
Tahoma integration works fine with the supported Somfy appliances.

**Screenshots**

**Environment (please complete the following information):**

- **Hub**: Somfy Connexoon,
- **ha-tahoma version:** 2.4.10
- **Home Assistant version:** 2021.6.6
- **Platform**: cover

**Additional context**

**Comment by cdeharo** [comment]
Same issue as reported in https://github.com/iMicknl/ha-tahoma/issues/466.

**Comment by cdeharo** [comment]
I've just updated the Connexoon firmware from the official app and restarted HA (2021.6.6) and now all works fine. I'll update HA tomorrow, but this seems solved now.

I'll wait two days and close this issue by myself.

**Comment by jcallaghan** [comment]
Similar issue with 2021.7.0. I also went into the TaHoma app and installed the update. Rebooted but still had an issue with the integration loading. Upgrading to 2021.7.1 resolved things for me.

**Comment by iMicknl** [comment]
Thanks for reporting. Let's track the status in #466.
