### ISSUE TITLE
Add support for the new Tahoma Switch box

### ISSUE THREAD

**Issue by TheDaft78** [iMicknl/ha-tahoma#468]
Hi, 

my apologies for not following exactly the issue template, but I recently read about the new Somfy box: [Tahoma Switch](https://boutique.somfy.fr/tahoma-switch.html) and I would like to know if it will be supported by your plugin?

I'm willing to purchase a box to control my rolling shutter and my radiators (Sauter), so I would like to use the most recent version, furthermore since it's less expensive than the 1st version, but I also want to be able to control it from my HA: that's why I would like to know if your plugin will support this new box? I would think so since I read that the OverKiz company is part of Somfy group, but still, if someone could confirm that would be great. I couldn't find any information about this in the existing open issues.

Thanks in advance,
Best Regards.

**Comment by iMicknl** [comment]
Another user, @ahivert, just confimed that the TaHamo Switch works like a charm with this integration.

**Comment by TheDaft78** [comment]
Great, thanks for the feedback!
