### ISSUE TITLE
Add support for Tahoma Scenes

### ISSUE THREAD

**Issue by lindemar** [iMicknl/ha-tahoma#47]
Scenes as defined in the Somfy Tahoma Box are not available with TaHoma integration. Tahoma integration by configuration.yaml supports the scenes defined in Tahoma box.

Device information
Home Assistant 0.110.6
HassOS 4.10
TaHoma integration: https://github.com/iMicknl/ha-tahoma/tree/fix_44

Device details for scenes are not visible by following the instruction

**Comment by iMicknl** [comment]
Thanks @lindemar! I just fixed it and merged it to master.
