### ISSUE TITLE
Looking for contributors!!

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#471]
This project has been started by @tetienne, @vlebourl and me in order to have an alternative to the limited and unstable official Somfy API. However, as you can notice on the issues and activity, all of us are pretty busy and priorities are else where. We are still maintaining the integration, but it is hard to keep up with all the issues and new device requests.

Do you have a basic knowledge of Python and do you want to contribute to this integration? We are actively looking for contributors whom can help us add this integration to Home Assistant core and to handle all the open issues.

Hit me up on Discord (iMick#1903), or reply here. Happy to walk you through the project :).

**Comment by azrael783** [comment]
Hi,

I do have a little basic knowledge of Python and would offer my help here...

**Comment by iMicknl** [comment]
@azrael783 great to hear! Feel free to join us on [Discord](https://discord.gg/RRXuSVDAzG) when you have time. Happy to walk you through it.

**Comment by FelipeGiro** [comment]
I can contribute also. I already joined Discord.

**Comment by iMicknl** [comment]
For anyone that wants to contribute, we are also creating a list with issues that are good to tackle as a first issue :-).

See https://github.com/iMicknl/ha-tahoma/labels/good%20first%20issue
