### ISSUE TITLE
Unexpected error fetching device events data: Too many requests, try again later : login with email - custom_components/tahoma/coordinator.py:78

### ISSUE THREAD

**Issue by Wiggum127** [iMicknl/ha-tahoma#476]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Getting many errors lately which I didn't have before.
The logging claims there have been too many login attempts, for some reason.

Logging on to the Tahoma platform via the Somfy app is not an issue. The user account/credentials are ok.

I've tried lowering the polling interval from the default 30s to 300s and disabled the integration for a while.
After enabling the integration again, I get the same errors back.

An automation I have made for lowering screens at the end of the day no longer works. Interactively lowering a screen works.

### What version of this integration (ha-tahoma) has the issue?

2.5.0

### What version of Home Assistant Core has the issue?

core-2021.7.2

### Which gateway / hub do you use?

Somfy Tahoma

### Device model

PositionableScreen

### Device type

io:VerticalExteriorAwningIOComponent

### Additional information
```
Logger: custom_components.tahoma
Source: custom_components/tahoma/coordinator.py:78
Integration: Somfy TaHoma
First occurred: 27 juni 2021 14:09:22 (471 occurrences)
Last logged: 14:44:50

Unexpected error fetching device events data: Too many requests, try again later : login with email@e.mail
Traceback (most recent call last):
  File "/config/custom_components/tahoma/coordinator.py", line 67, in _async_update_data
    events = await self.client.fetch_events()
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 215, in fetch_events
    response = await self.__post(f"events/{self.event_listener_id}/fetch")
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 333, in __post
    await self.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 371, in check_response
    raise NotAuthenticatedException(message)
pyhoma.exceptions.NotAuthenticatedException: Not authenticated

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tahoma/coordinator.py", line 78, in _async_update_data
    await self.client.login()
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 95, in login
    response = await self.__post("login", data=payload)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 333, in __post
    await self.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 363, in check_response
    raise TooManyRequestsException(message)
pyhoma.exceptions.TooManyRequestsException: Too many requests, try again later : login with email@e.mail
```

**Comment by iMicknl** [comment]
When did this issue first occur? It could be related to the outage on Somfy's side, see https://github.com/iMicknl/ha-tahoma/issues/466#issuecomment-880475153.

**Comment by Wiggum127** [comment]
It started happening around 27/06. The Tahoma integration has been very unstable since. Multiple restarts, enablind/disabling the integration did not change anything. The topic seems to be related to #466. Should I close this one, or do my logs show a different issue compared to 466?

**Comment by Wiggum127** [comment]
FYI. Just upgraded to latest and greatest version of the ha-tahoma and HA 2021.7.2. A few minutes after restarting the container I get the same errors again. Using the Somfy app from my smartphone (same external IP) does not give an error. It doesn't seem to fix the HA error neither. Connecting via 4G via the phone (in theory unlocking the user in some way at Somfy side) also does not change the behaviour.

**Comment by iMicknl** [comment]
@Wiggum127 do you still have these issues? (using our latest version).

**Comment by Wiggum127** [comment]
Yes. Currently still facing the issue, now running HA 2021.7.4 Right after a HA restart, the integration starts spilling the errors.
I'm running the version of the integration which was available on 15/07.

**Comment by Wiggum127** [comment]
Have upgraded to v2.5.1 and v2.5.2 via HACS. The errors persist with the same messages.

**Comment by iMicknl** [comment]
Sorry to hear that you have so many issues, @Wiggum127. Let's see if we can investigate more, however it seems that you are currently the only user who is facing this.

1. Which bridge do you have exactly? Do you have only RTS devices, or also IO devices?
1. Do you run any scripts or automations on Home Assistant, or to the Somfy server via something like HomeBridge?
1. Why did you upgrade to 2.5.2 and not to the latest one? (2.6.1)
1. How do you run Home Assistant?

**Comment by Wiggum127** [comment]
@iMicknl thanks for taking this issue up. I'll try to be as exhaustive as required:

1. Bridge device:
Somfy Connexoon 1811429A, firmware v1.7.9:70

2. Connected devices:
12 screens and 1 terrace sun cover. All RTS devices, I believe

3. Automation scripts
Only via HomeAssistant 2 scripts:
 - lower all screens at end of day, configured 2 x 6 screens with 1min interval to avoid the full queue of 10 actions at Somfy server side.
 - open 2 specific screens at 10h00 every day
 
4. Version
I'm using the version distributed via HACS, currently v2.5.2. I assume this is integrated with the release pushed via Github.

5. HA setup
Using RPI 2B, with a wired ethernet connection, running Raspbian Lite Buster with all latest firmware, kernel and software packages of the official Debian software channels. HA v2021.7.4, running in a docker container.

**Comment by Wiggum127** [comment]
Perhaps a pointer that could help. At around beginning of July, when upgrading to 2021.7, I ran into an issue with the docker image. The dokcer image kept failing to start.

Turned out HA Docker uses Alpine Linux as base image. That is not compatible with Raspbian when:

    Using a version of Docker prior to 19.04 (stock Raspbian Repositories has/had version 18)
    Using an outdated libseccomp2 library

To fix the Docker version problem, I added upstream Debian Bullseye as a low priority repository for software updates. This fixed the problem and everything fired up fine. Perhaps the problem is situated there ?

**Comment by Wiggum127** [comment]
This weekend upgraded HA to latest version (now running 2021.8.8). After reboot HACS indicated a new version of the Tahoma integration. I'm now running the latest 2.6.x instead of 2.5.2.

The errors immediately pop up after reboot. The automations don't work. Ad-hoc individual screen manipulation doesn't respond. The native Somfy app on the smartphone (using the same usr/pwd as the integration) and the physical remote controls work without problem.

Let me know if there is anything I can provide to help you find the root cause.

**Comment by iMicknl** [comment]
@Wiggum127 sorry for the late reply, but I would have no clue as well...

I wonder how it works if you run it on another system, with your credentials. Is that something that you could try out? I am in doubt if it is related to the system you are running on, or related to your Somfy account / configuration.

**Comment by Wiggum127** [comment]
Currently running 2021.9.6 and latest version of the Overkiz integration. It appears the last few days, the integration is a lot more stable. I do get an error from time to time stating "cannot connect to host tahomalink:443 ssl:default [Try again]" but those only appear about 3 times per day.
The integration and automations seem to be working correctly. I guess with the updates of the integration there has been a better exception handling with lost connections or the API is more stable or provides more accurate error codes. 
In any case, seems like we can close this one, for the time being.

**Comment by iMicknl** [comment]
Cool, thanks for the update @Wiggum127! And if you keep debug logging on, you could provide us with more information if it happens a next time. We improved logging a lot.
