### ISSUE TITLE
Volant doesn't move up/close anymore

### ISSUE THREAD

**Issue by inconsx** [iMicknl/ha-tahoma#491]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I can let down my volant but if push/slide for up nothing happens anymore.

### What version of this integration (ha-tahoma) has the issue?

2.5.1.

### What version of Home Assistant Core has the issue?

core-2021.7.3

### Which gateway / hub do you use?

Somfy TaHoma

### Device model

AwningValance

### Device type

io:AwningValanceIOComponent

### Additional information
```
rssi_level: 24
core:SupportedManufacturerSettingsCommands:
  - dead_man_up
  - dead_man_down
  - dead_man_stop
  - dead_man_impulse_up
  - dead_man_impulse_down
  - enter_settings_mode
  - save_upper_end_limit
  - save_lower_end_limit
  - stop_after_save_limit
  - save_settings
  - invert_rotation
  - save_my_position
  - delete_my_position
  - set_dbe_up
  - set_application
  - reset_actuator
  - double_power_cut
  - eject_from_setting_mode
  - enter_back_impulse_setting_mode
  - save_back_impulse_position
  - set_x_time
core:FirmwareRevision: 5118126A10?
core:Manufacturer: Somfy
core:NameState: Volant
core:PriorityLockTimerState: 0
core:StatusState: available
core:DiscreteRSSILevelState: low
core:RSSILevelState: 24
core:ManufacturerSettingsState:
  x_time: 2
  roll_end_limit_state: Auto
  application: 44
  setting_state: User mode
  current_position: 35556
  unroll_end_limit_state: Manual
core:ClosureState: 69
core:OpenClosedState: open
core:Memorized1PositionState: 105
io:PriorityLockOriginatorState: null
io:PriorityLockLevelState: null
friendly_name: Volant
supported_features: 527
device_class: awning
```

**Comment by iMicknl** [comment]
Thanks for reporting, @inconsx! We received a similar issue, thus I will close this one for now. Let's keep track of this issue in #486.

This is a bug on Somfy's side, and for now best is to downgrade our integration.
