### ISSUE TITLE
io:AwningValanceIOComponent not working since v2.4.11 

### ISSUE THREAD

**Issue by jonasjeeliasson** [iMicknl/ha-tahoma#510]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I've run this integration for a year, having two different awnings, the `io:HorizontalAwningIOComponent` and `io:AwningValanceIOComponent`. Since v2.4.11 the `io:AwningValanceIOComponent` stopped working. 

From what I can see is that the `current_position` attribute is missing in the state when comparing the two different awnings, and also comparing with the version v2.4.10. The buttons in Lovelace then stops working and of course showing position doesn't work. The set position service seems to work though.

Nothing in the logs about any problems with the integration. 

### What version of this integration (ha-tahoma) has the issue?

v2.4.11

### What version of Home Assistant Core has the issue?

2021.7.3

### Which gateway / hub do you use?

Somfy Connexoon

### Device model

AwningValance

### Device type

io:AwningValanceIOComponent

**Comment by iMicknl** [comment]
Could you give https://github.com/iMicknl/ha-tahoma/archive/refs/heads/fix/temp_fix_AwningValanceIOComponent.zip a try? Extract this file and place `custom_components/tahoma` in your `custom_components` folder.

**Comment by jonasjeeliasson** [comment]
> Could you give https://github.com/iMicknl/ha-tahoma/archive/refs/heads/fix/temp_fix_AwningValanceIOComponent.zip a try? Extract this file and place `custom_components/tahoma` in your `custom_components` folder.

Works like a charm again :)
