### ISSUE TITLE
Error with 2.6.0

### ISSUE THREAD

**Issue by Supermarco333** [iMicknl/ha-tahoma#514]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I tried to update to the last version to the integration. The integration now refuses to start. Here's the log:

```
2021-08-11 02:41:55 ERROR (MainThread) [homeassistant.config_entries] Error migrating entry email@email.com for tahoma
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/config_entries.py", line 509, in async_migrate
result = await component.async_migrate_entry(hass, self) # type: ignore
File "/home/homeassistant/.homeassistant/custom_components/tahoma/__init__.py", line 111, in async_migrate_entry
old_hub = entry_data[CONF_HUB]
KeyError: 'hub'
```

### What version of this integration (ha-tahoma) has the issue?

2.6.0

### What version of Home Assistant Core has the issue?

core-2021.8.5

### Which gateway / hub do you use?

Connexoon

### Device model

None

### Device type

None

**Comment by tetienne** [comment]
Hi, thx for reporting this. Can you tell me what was the version of this component you were using before performing the update?

I retried a migration from v2.5.2 to v2.6.0 without any issue. The "hub" key is well present. @iMicknl any idea?

**Comment by psicot** [comment]
Hello, same error with Home Assistant `core-2021.8.6`.

**Comment by iMicknl** [comment]
Please update to 2.6.1, which should contain this fix. Thanks!
