### ISSUE TITLE
Add support for Hitachi Yutaki S heat pump (modbus:YutakiMainComponent)

### ISSUE THREAD

**Issue by fredericseiler** [iMicknl/ha-tahoma#519]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### Device information

Hitachi Yutaki S Combi (linked to the Hi-Box via ATW-TAG-02)

### Unsupported device log

Sorry, not sure which log only concerns the heat pump (I also got a HVAC linked via SPX-TAG-01):

```shell
Unsupported device detected (modbus:YutakiMainComponent - HitachiHeatingSystem - HitachiAirToWaterMainComponent - modbus://xxxx-xxxx-xxxx/7292611/1#1)
Added device (modbus:YutakiV2Zone1Component - HitachiHeatingSystem - HitachiAirToWaterHeatingZone - modbus://xxxx-xxxx-xxxx/7292611/1#2)
Added device (modbus:YutakiV2DHWTComponent - HitachiHeatingSystem - HitachiDHW - modbus://xxxx-xxxx-xxxx/7292611/1#4)
Unsupported device detected (modbus:YutakiRoomThermostatZone1Component - HeatingSystem - HitachiThermostat - modbus://xxxx-xxxx-xxxx/7292611/1#6)
Unsupported device detected (modbus:YutakiRoomThermostatZone2Component - HeatingSystem - HitachiThermostat - modbus://xxxx-xxxx-xxxx/7292611/1#7)
Unsupported device detected (ovp:ModbusMainController - Generic - unknown - ovp://xxxx-xxxx-xxxx/10247195)
Added device (ovp:HLinkMainController - HitachiHeatingSystem - HitachiAirToAirHeatPump - ovp://xxxx-xxxx-xxxx/1191539)
Unsupported device detected (ovp:ModbusMainController - Generic - unknown - ovp://xxxx-xxxx-xxxx/7292611)
```

### Device commands

None

### Additional information

Hi, this is not really an unsupported device issue because my heat pump seems to be successfully added to HA, however, I get many "Unsupported device detected" in the logs and nothing in "Device info":

<img width="334" alt="2021-08-11-16-43-13 Google Chrome Configuration - Home Assistant" src="https://user-images.githubusercontent.com/954168/129050290-18912393-2e89-4de6-8768-41ca5dfda7fa.png">

Also, I can switch off the water heating ("Eau chaude"), but not the space heating ("Chauffage"), unlike the Hi-Kumo app.

Water heating:
<img width="414" alt="2021-08-11-16-44-50 Google Chrome Configuration - Home Assistant" src="https://user-images.githubusercontent.com/954168/129050718-95d1fdd0-7b5f-4d83-9787-5d8a94172548.png">

Space heating:
<img width="408" alt="2021-08-11-16-46-48 Google Chrome Configuration - Home Assistant" src="https://user-images.githubusercontent.com/954168/129051009-235603c4-100a-4259-8ae1-83082226ced9.png">

Hi-Kumo app:
<img width="376" alt="2021-08-11-16-49-42 Preview Screenshot_20210811_164754_com hitachi HiKumo jpg" src="https://user-images.githubusercontent.com/954168/129051507-af376079-955b-4430-8b55-bb5dedae8bd8.png">

I suspect that the Hi-Kumo app only set the target temperature to 5°C when "switching off", and there is no real way to switch off only the space heating part, but I'm not sure.

### Relevant log output

None

**Comment by tetienne** [comment]
I don't know what's exactly modbus, but did you try https://www.home-assistant.io/integrations/modbus/ component?

**Comment by fredericseiler** [comment]
Modbus is the protocol used to communicate directly with the heat pump (throught Hitachi H-Link internal bus):

Heat pump > H-Link/Modbus RTU > Gateway (ATW-TAG-02) > io-homecontrol (I suppose) > Hi-Box > TCP/IP > Overkiz cloud

Modbus TCP/RTU interfaces for Hitachi devices are not cheap, and I already got a Hi-Box/gateway combo, so for now, I prefer to stick to the Overkiz way.

**Comment by iMicknl** [comment]
**ovp:ModbusMainController** - Generic - unknown
```
{
	"commands": [{
		"commandName": "getName",
		"nparams": 0
	}, {
		"commandName": "identify",
		"nparams": 0
	}, {
		"commandName": "setName",
		"nparams": 1
	}],
	"states": [{
		"type": "DataState",
		"qualifiedName": "core:NameState"
	}, {
		"type": "DiscreteState",
		"values": ["available", "unavailable"],
		"qualifiedName": "core:StatusState"
	}],
	"dataProperties": [{
		"value": "500",
		"qualifiedName": "core:identifyInterval"
	}],
	"widgetName": "unknown",
	"uiProfiles": ["Specific"],
	"uiClass": "Generic",
	"qualifiedName": "ovp:ModbusMainController",
	"type": "ACTUATOR"
}
```


**modbus:YutakiRoomThermostatZone1Component** - HeatingSystem - HitachiThermostat
```
{
	"commands": [],
	"states": [{
		"type": "DataState",
		"qualifiedName": "modbus:AlarmNumberState"
	}],
	"dataProperties": [],
	"widgetName": "HitachiThermostat",
	"uiProfiles": ["Specific"],
	"uiClass": "HeatingSystem",
	"qualifiedName": "modbus:YutakiRoomThermostatZone1Component",
	"type": "SENSOR"
}
```

**modbus:YutakiRoomThermostatZone2Component** - HeatingSystem - HitachiThermostat
```
{
	"commands": [],
	"states": [{
		"type": "DataState",
		"qualifiedName": "modbus:AlarmNumberState"
	}],
	"dataProperties": [],
	"widgetName": "HitachiThermostat",
	"uiProfiles": ["Specific"],
	"uiClass": "HeatingSystem",
	"qualifiedName": "modbus:YutakiRoomThermostatZone2Component",
	"type": "SENSOR"
}
```

**Comment by iMicknl** [comment]
Looking at the device reference, it doesn't seem that we can control anything of your missing devices. Or would `modbus:AlarmNumberState` perhaps be a value that would be interesting to show as a binary_sensor / sensor in Home Assistant?

**Comment by fredericseiler** [comment]
I have no idea what sort of value the "alarm number state" will provide. Any error code from the heat pump maybe?

Anyway, seems like I can safely ignore those "Unsupported device detected" logs, thanks!

What about the empty "Device info" for the heat pump? Not relevant either? I don't need it at all, just curious...

**Comment by iMicknl** [comment]
> What about the empty "Device info" for the heat pump? Not relevant either? I don't need it at all, just curious...

I am not sure yet, what would be the best solution. Normally we support the first device (which is the 'main' device), however in your case the Modbus controller is not mapped to any device. 

We could see if we can show the device information of the first supported device, however this is quite an edge case.
