### ISSUE TITLE
Door/Windows sensors not working since I updated to latest version

### ISSUE THREAD

**Issue by RienduPre** [iMicknl/ha-tahoma#525]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Since I updated to the new Tahoma version in HACS, it created new devices for all my door/windows sensors. The are now contact sensors and have a different icon. So far so good.
But All sensors remain at the status closed, when I open a door or window.

The Tahoma itself reflects the current open/close status correctly.

If you need more information, please let me know

### What version of this integration (ha-tahoma) has the issue?

2.5

### What version of Home Assistant Core has the issue?

core-2021.8.6

### Which gateway / hub do you use?

Tahoma V2 hub

### Device model

Firmware: 2021.2.4

### Device type

Door/Windows Sensor

**Comment by iMicknl** [comment]
Thanks for reporting, Rien! 

Could you share the states of your sensor when the door is open / closed? Go to Developer Tools -> States and look for your binary_sensor entity. It should show all available states on the right side, could you post them here?

**Comment by RienduPre** [comment]
<img width="1037" alt="Schermafbeelding 2021-08-13 om 10 26 20" src="https://user-images.githubusercontent.com/9009949/129327954-e97ceb7a-3151-4335-9ed7-852510648818.png">

**Comment by iMicknl** [comment]
Fixed in v2.6.3!

**Comment by RienduPre** [comment]
Confirmed !!
Thanx
