### ISSUE TITLE
unit_of_measurement is unsupported after 2021.11

### ISSUE THREAD

**Issue by arjen-w** [iMicknl/ha-tahoma#562]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I do see the following error being logged in the HA logs after a restart of HA:

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:151
Integration: Sensor (documentation, issues)
First occurred: 12 September 2021, 20:27:04 (1 occurrences)
Last logged: 12 September 2021, 20:27:04

custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.

### What version of this integration (ha-tahoma) has the issue?

2.71

### What version of Home Assistant Core has the issue?

2021.9.6

### Which gateway / hub do you use?

Somfy Conexioon

### Device model

PositionableScreen

### Device type

5121525A04?

### Relevant log output

```shell
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:151
Integration: Sensor (documentation, issues)
First occurred: 12 September 2021, 20:27:04 (1 occurrences)
Last logged: 12 September 2021, 20:27:04

custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
```

**Comment by iMicknl** [comment]
Should be fixed in v2.7.2, I just released this change, it was ready but not released.

Thanks for reporting!
