### ISSUE TITLE
Sensor does not work after connection failure

### ISSUE THREAD

**Issue by mingan666** [iMicknl/ha-tahoma#563]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I try to reconnect the component after a connection failure.
This works as expected for my screens, but the sun sensor stays unavailable until a restart home assistant.

### What version of this integration (ha-tahoma) has the issue?

v2.7.1

### What version of Home Assistant Core has the issue?

core-2021.9.5

### Which gateway / hub do you use?

Somfy Tahoma: Tahoma Pro by Somfy Firmware: 2021.2.4

### Device model

LuminanceSensor

### Device type

Firmware: 5126936A15?

### Additional information

Yesterday the component failed. I can see the following in my log:

> This error originated from a custom integration.
> 
> Logger: custom_components.tahoma
> Source: helpers/update_coordinator.py:219
> Integration: Overkiz (by Somfy)
> First occurred: September 13, 2021, 10:35:20 AM (1 occurrences)
> Last logged: September 13, 2021, 10:35:20 AM
> 
> Error fetching device events data: Server is down for maintenance.

I also got the notification that I had to reconnect the component.
I did that a couple of hours later (since I had to wait when I had the connection problems)
Which seems to work fine.

However, as I've seen before, my sun sensor does not come back.
Please check the screenshot taken from home assistant.

![somfy-error](https://user-images.githubusercontent.com/11653241/133204256-972033de-8268-415b-9d46-16da81ee40c7.png)

The sun sensor starts working first after I restart home assistant.

**Comment by iMicknl** [comment]
Thanks for reporting, @mingan666! Great to see that at least our mechanisms are working to recover from maintenance on Somfy's side. Previously many users would be blocked due to Somfy not accepting correct passwords and eventually IP banning users.

We will have a look how we can make sure that sensors can recover as well.
For the other devs, I have seen similar issues related to the `sensor` and `binary_sensor` platform during 'reloading' of the integration. It seems that something isn't correct in our init of these platforms.

**Comment by iMicknl** [comment]
Related to https://github.com/iMicknl/ha-tahoma/issues/560 perhaps.

@mingan666 was there something in your log perhaps, which is similar to the error in #560?

**Comment by mingan666** [comment]
@iMicknl 

I added the relevant log entry, see above under additional information (copied from the ha interface).
Don't think there was anything else relevant to this component.
Don't seem to have the logs anymore and the connection error does not happen that often (I'm happy to say).

**Comment by mingan666** [comment]
@iMicknl 

The problem happend again and once again it seems related to maintenance of the server...
Anyway, I checked the error logs as requested above and it seems you were right and the error might be related to the other issue.

Please see the log entries related with todays problem. I hopes debugging the issue:

```
This error originated from a custom integration.

Logger: custom_components.tahoma
Source: helpers/update_coordinator.py:219
Integration: Overkiz (by Somfy)
First occurred: September 27, 2021, 2:19:45 AM (2 occurrences)
Last logged: 10:02:02 AM

Error fetching device events data: Cannot connect to host tahomalink.com:443 ssl:default [Connect call failed ('178.32.15.131', 443)]
Error fetching device events data: Server is down for maintenance.
```

```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:164
First occurred: 1:59:08 PM (2 occurrences)
Last logged: 1:59:08 PM

Error setting up entry ******** for binary_sensor
Error setting up entry ******** for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 148, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 164, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

**Comment by iMicknl** [comment]
Let's track in https://github.com/iMicknl/ha-tahoma/issues/560, thanks for reporting!

**Comment by mingan666** [comment]
Seems to be fixed! Great work.

I had another connection failure and after reconnecting the plugin the sun sensor worked as expected.
