### ISSUE TITLE
Error fetching device events data

### ISSUE THREAD

**Issue by Supermarco333** [iMicknl/ha-tahoma#565]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Since I updated to 2.7.2, I have this error at each startup of HA

`[custom_components.tahoma] Error fetching device events data: Invalid event listener id : e56842b7-ac10-3e01-7473-4d35038c35f4`

### What version of this integration (ha-tahoma) has the issue?

2.7.2

### What version of Home Assistant Core has the issue?

core-2021.9.5

### Which gateway / hub do you use?

Somfy Connexoon

### Device model

Any

### Device type

Any

### Relevant log output

```shell
[custom_components.tahoma] Error fetching device events data: Invalid event listener id : e56842b7-ac10-3e01-7473-4d35038c35f4
```

**Comment by tetienne** [comment]
Thx for reporting this issue. I will provide a fix with the next release.
