### ISSUE TITLE
Missing "climate class" for heater device

### ISSUE THREAD

**Issue by jugla** [iMicknl/ha-tahoma#569]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The request

My heater are well recognized 👍 

`021-09-18 11:15:29 DEBUG (MainThread) [custom_components.tahoma] Added device (io:AtlanticElectricalHeaterWithAdjustableTemperatureSetpointIOComponent - HeatingSystem - AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint - io://0825-3323-9670/11805187#1)
`

Nevertheless no `climate` entities are created , only `sensor` are created

### Which gateway / hub do you use?

Cozytouch hub

### Device model (optional)

Equateur 3 par Atlantic Group

### Device type (optional)

Firmware: - ÿÿÿ$??

**Comment by iMicknl** [comment]
Can you turn on debug logging (see README) and share your log? I assume there is an entry regarding to the initialization of your climate entity.

**Comment by jugla** [comment]
Thanks for you answer.
I put the logs hereattached
[home-assistant.log](https://github.com/iMicknl/ha-tahoma/files/7192262/home-assistant.log)
Please find also a snapshot on device (sorry in french ;-) )
![image](https://user-images.githubusercontent.com/59493499/133931350-2d5a77f0-abee-4255-824e-3763b0a40206.png)
NB : the inactive sensor is due to the fact that they have been renamed at a version (no issue)

**Comment by jugla** [comment]
I see the heater (radiateur) at the end, I think I was misleading , since I think I will get something with the ID 14821225.
Let me check ;-)

**Comment by jugla** [comment]
Sorry my fault, I mix the climate "generated" by custom component ha-tahoma and the ones generated by custom component "cozy touch".
Both have the same name except a running number.

**Comment by jugla** [comment]
You have made a great job !
