### ISSUE TITLE
Add support for local IP selection in Config Flow

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#576]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The request

@dmaasland did a great job researching how to 'jailbreak' his Somfy Connexoon box. You can read more about this on the [Home Assistant Community Forum](https://community.home-assistant.io/t/somfy-connexoon-tahoma-jailbreak/297076/9).

Currently he is using a modified version of this integration, but it would be good to add support for local IP address selection to the HA Config Flow. I don't think many users will use this, but it is good to have it in.

https://github.com/dmaasland/python-tahoma-api/commit/2d66743d3d92a4e53078342306a4dfe574fe2d79
https://github.com/dmaasland/ha-tahoma/commit/3962777b63f3ce2f07b27dfe7321a3dab924821d

### Which gateway / hub do you use?

n/a

### Additional information

Needs an updated `pyhoma` version.

**Comment by jozg** [comment]
I'm still interested in this feature, so if you please be so kind to implement this feature. thank you.
Regards,

**Comment by iMicknl** [comment]
@jozg did you jailbreak / root your hub?

**Comment by jozg** [comment]
Hello IMicnl, not yet, the day the feature is enabled i'm going to root my hub according the manual of Donny. It makes no sense for me to allready root it, and not being able to control it. thank you for your great word, and thanks to Donny for making the root enable. regards.

**Comment by iMicknl** [comment]
@jozg Donny already has a custom version of this integration where he made the required changes, thus this shouldn't hold you back.

**Comment by jozg** [comment]
ok, i asked him about that, but he mentioned to wait for this final integration, and pointed me to this topic link.

**Comment by tetienne** [comment]
IMO, we should not expose this local entrypoint in the component it will confuse a lot of user and it’s not an "official" stuff. But, hoppefully we can integrate it in our client API.

**Comment by iMicknl** [comment]
> IMO, we should not expose this local entrypoint in the component it will confuse a lot of user and it’s not an "official" stuff. But, hoppefully we can integrate it in our client API.

I am also still in doubt for this one, we can also just keep it in the custom integration (when we move to core). But having a hub named 'Local' which will open a new dialog where users can add their IP would be sufficient for me as well. We can add more information in that new dialog, about that this is only for advanced users that rooted their bridge.

**Comment by jozg** [comment]
Issue still not resolved completly

**Comment by rjlee** [comment]
Would having someone with a local api enabled hub help with testing ?  I'd be happy to enable mine if that would help, just let me know.

**Comment by iMicknl** [comment]
@rjlee that would help eventually, however didn't prioritize the work yet. See https://github.com/iMicknl/ha-tahoma/issues/697 for our roadmap.
