### ISSUE TITLE
Overkiz.event logger throws error when failure_type_code is not an Enum

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#609]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

In some situations, self.failure_type_code is not an enum but just an int. We don't check for this.

https://github.com/iMicknl/python-tahoma-api/blob/d4572c27dd098db9171c307232b1e7a5530774f8/pyhoma/models.py#L294

Not sure if we should tackle this here, or if we should just get rid of this ugly and confusing code in pyhoma.

### What version of this integration (ha-tahoma) has the issue?

latest

### What version of Home Assistant Core has the issue?

n/a

### Which gateway / hub do you use?

n/a

### Home Assistant log

```
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/config/custom_components/tahoma/coordinator.py", line 110, in _async_update_data
"failure_type_code": event.failure_type_code.value,
AttributeError: 'int' object has no attribute 'value'
```

**Comment by tetienne** [comment]
It also means that's a failure type we don't know.
