### ISSUE TITLE
Use STEP_ID constants in config flow

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#634]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The request

https://github.com/home-assistant/core/pull/58696/files

### Which gateway / hub do you use?

n/a

**Comment by tetienne** [comment]
Not relevant anymore: https://github.com/home-assistant/architecture/discussions/660
