### ISSUE TITLE
Rewrite Cover entity to use EntityDescription

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#640]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The request

As discussed with @tetienne, it would be great to move our cover entity to use the new entity description structure as well.

This would maybe allow us to add support for this kind of specific features as well; https://github.com/jcallaghan/home-assistant-config/issues/277#issuecomment-787449118.

### Which gateway / hub do you use?

n/a

**Comment by tetienne** [comment]
About this one, I was thinking having a list of device url map to a cover entity description... kind of the legacy integration. But it will avoid to switch between widget, uiClasses deviceurl, etc.
