### ISSUE TITLE
Thermor brand of Atlantic is also supported

### ISSUE THREAD

**Issue by St4n** [iMicknl/ha-tahoma#648]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The request

Hi,

Just to notify you that Thermor brand heaters are also supported via atlantic api.

If I'm not wrong, Thermor is the same group that Atlantic.

Would be good if you can note that Thermor brand is supported in the Readme :)

Thanks,
Stephane

### Which gateway / hub do you use?

Cozytouch

### Device model (optional)

Heaters

**Comment by vlebourl** [comment]
Indeed same brand, and internally all devices are called `Atlantic`-something. But +1 for mentioning Thermor.
