### ISSUE TITLE
Authentication works, but "Failed to set up" due to "7 is not a valid ProductType"

### ISSUE THREAD

**Issue by ProLoser** [iMicknl/ha-tahoma#652]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I tried to enable advanced debugging but I don't see any difference in the output logs. The integration appeared to authenticated with Tahoma North America but it does not appear to complete the setup process.

### What version of this integration (ha-tahoma) has the issue?

2.9.3

### What version of Home Assistant Core has the issue?

core-2021.11.1

### Which gateway / hub do you use?

Somfy Tahoma

### Device model

Cover (blinds)

### Home Assistant log

```shell
7 is not a valid ProductType
Traceback (most recent call last):
  File "/config/custom_components/tahoma/__init__.py", line 141, in async_setup_entry
    devices, scenarios, gateways, places = await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyhoma/client.py", line 243, in get_devices
    devices = [Device(**d) for d in humps.decamelize(response)]
  File "/usr/local/lib/python3.9/site-packages/pyhoma/client.py", line 243, in <listcomp>
    devices = [Device(**d) for d in humps.decamelize(response)]
  File "/usr/local/lib/python3.9/site-packages/pyhoma/models.py", line 79, in __init__
    self.type = ProductType(type)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 7 is not a valid ProductType
```

**Comment by iMicknl** [comment]
@ProLoser thanks for reporting! We need to fix this in the underlying library, but you are the first user with this ProductType.

Would you be willing to work with me [via Discord](https://discord.gg/gDSNf8MKf7) (iMick #1903) sometime? It would be great to add your setup definition (anonymized) to our test suite, so that these bugs don't happen again.

**Comment by ProLoser** [comment]
It says invite expired.

**Comment by ProLoser** [comment]
@iMicknl I'm happy to help but that discord invite link does not work

**Comment by iMicknl** [comment]
The chat link in the README is up to date.
https://github.com/iMicknl/ha-tahoma

**Comment by ProLoser** [comment]
Confirmed everything works in the latest release!

**Comment by ProLoser** [comment]
@iMicknl thank you so much for fixing this! Do you have a sponsor or buy-me-a-beer or preferred OSS I can donate to in thanks?
