### ISSUE TITLE
Somfy integration with Home Assistant not working

### ISSUE THREAD

**Issue by nil-ghosh** [iMicknl/ha-tahoma#660]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

When configuring Somfy within Home Assistant it takes me to Somfy Developer portal. However, entering the credentials I keep on getting an error - An error has occurred. Please try again. 

However, if I login to the Somfy developer portal separately, I can log in and see my app listed. 

Any help will be much appreciated. 

### What version of this integration (ha-tahoma) has the issue?

Not available

### What version of Home Assistant Core has the issue?

core-2021.11.5

### Which gateway / hub do you use?

Somfy

### Device model

RTS Blinds

**Comment by iMicknl** [comment]
This seems like a bug with the Somfy integration from Home Assistant core. Please report bugs [here](https://github.com/home-assistant/core/issues).

This integration is named Overkiz (by Somfy) and works for Somfy as well, thus you could give this a try. See our main page for more information; https://github.com/iMicknl/ha-tahoma.

**Comment by tetienne** [comment]
@nil-ghosh And to avoid to open another issue, see https://github.com/tetienne/somfy-open-api/issues/182

**Comment by nil-ghosh** [comment]
> This seems like a bug with the Somfy integration from Home Assistant core. Please report bugs [here](https://github.com/home-assistant/core/issues).
> 
> This integration is named Overkiz (by Somfy) and works for Somfy as well, thus you could give this a try. See our main page for more information; https://github.com/iMicknl/ha-tahoma.

Thanks @iMicknl - It works for me. Much appreciated.
