### ISSUE TITLE
Screens working only once, with using the local api and connexoon root.

### ISSUE THREAD

**Issue by jozg** [iMicknl/ha-tahoma#671]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Hello Mick,
I've succeeded in rooting my connexoon, and the local api is working, big thanks to Donny.
Because there is no official local api integration yet, i'm using a branch from Donny.
With this custom version of your integration i can control my screens, but only once.

Let'say:
I push the 'up' button in Home Assistant, the screens are going up by the local API.
Then after that the up and down button's are greyed out, and i can see the following error in the logviewer:
: 2021-12-08 08:26:38 ERROR (MainThread) [custom_components.tahoma] Error fetching device events data: __init__() missing 1 required positional argument: 'timestamp'
And only if 1 restart (herlaad) the plugin, or complete restart the home assistant server, i can again once control the screens, before the error is again presented, and the buttons greyed out.

Thank you for your great work!.

At this moment i have an hybrid situation. In my poroduction Home Assistant i;'m using your official integration wich is using the cloud solution. In my test enviroment i;m using the local API.

### What version of this integration (ha-tahoma) has the issue?

https://github.com/dmaasland/ha-tahoma/commit/3962777b63f3ce2f07b27dfe7321a3dab924821d

### What version of Home Assistant Core has the issue?

core-2021.11.5

### Which gateway / hub do you use?

Connexoon (rooted)

### Device model

OXIMO io screens

### Home Assistant log

```shell
: 2021-12-08 08:26:38 ERROR (MainThread) [custom_components.tahoma] Error fetching device events data: __init__() missing 1 required positional argument: 'timestamp'
```

### Additional information

Great work of you and Donny. And i'm happy to test anything to get an working local API.

**Comment by iMicknl** [comment]
Thanks for reporting @jozg. We will take this into account when we work on adding Donny's work to this integration.

**Comment by iMicknl** [comment]
@jozg , would you be able to work with me [via Discord](https://discord.gg/gDSNf8MKf7) (iMick #1903) so we can speed up the development? I would need some API responses, so that I can add this to our test suite again.

**Comment by iMicknl** [comment]
Let's close this one for now, and track it via #576. We will make sure we support this as well, when we add official support.
