### ISSUE TITLE
device_info name overflows card

### ISSUE THREAD

**Issue by Mariusthvdb** [iMicknl/ha-tahoma#680]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

<img width="404" alt="Schermafbeelding 2021-12-15 om 16 38 06" src="https://user-images.githubusercontent.com/33354141/146216961-2092eba1-af6b-4b7d-911b-7b361e51a999.png">

### What version of this integration (ha-tahoma) has the issue?

2.10.1 fix 665

### What version of Home Assistant Core has the issue?

2022.1.0dev

### Which gateway / hub do you use?

Somfy  Tahoma

**Comment by iMicknl** [comment]
Not a `ha-tahoma` issue, please report in front-end.

See https://github.com/home-assistant/frontend/issues/8615 for a similar issue.

**Comment by Mariusthvdb** [comment]
right, but that issue was closed, and apparently unjustly so..... will do though, sorry for your trouble

**Comment by iMicknl** [comment]
That issue has been closed, because I fixed the problem with a PR. Your issue is related to the model name, where my issue was related to the firmware.

That's why I said **similar** issue. 😉

**Comment by Mariusthvdb** [comment]
aww, I hope we dont have to file an issue for every possible element that can need word-wrap.....

anyways: https://github.com/home-assistant/frontend/issues/10934

**Comment by spacegaier** [comment]
> aww, I hope we dont have to file an issue for every possible element that can need word-wrap.....
> 

Well you do, since we are not adding word wrapping to any random element if not required 😉. PR created.

**Comment by Mariusthvdb** [comment]
Thanks Philip, appreciated.

Not meant as a rant... sorry if I came across like that
