### ISSUE TITLE
Ineed to enter the password again

### ISSUE THREAD

**Issue by Acey-yo** [iMicknl/ha-tahoma#681]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Hi there,

I have the problem that he irregularly requests the password and I cannot use the control until I have re-entered the password and he has reconnected.
Can someone help me there?

### What version of this integration (ha-tahoma) has the issue?

 v2.10.1

### What version of Home Assistant Core has the issue?

2021.12.1

### Which gateway / hub do you use?

somfy connexoon

**Comment by iMicknl** [comment]
Please see the pinned issue. https://github.com/iMicknl/ha-tahoma/issues/599. This is a known issue.
