### ISSUE TITLE
After upgrading to 2.10.2 both my sirene entities are unavailable

### ISSUE THREAD

**Issue by RienduPre** [iMicknl/ha-tahoma#689]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

After upgrading to v2.10.2 from v2.9.4 my two sirene entities are unavailable
<img width="663" alt="Schermafbeelding 2021-12-22 om 11 30 35" src="https://user-images.githubusercontent.com/9009949/147078770-8e2f3258-249e-47c2-858b-ad02531965b3.png">
<img width="666" alt="Schermafbeelding 2021-12-22 om 11 30 11" src="https://user-images.githubusercontent.com/9009949/147078779-ef7e6e96-b478-490b-8172-7a466745117c.png">

### What version of this integration (ha-tahoma) has the issue?

2.10.2

### What version of Home Assistant Core has the issue?

core-2021.12.4

### Which gateway / hub do you use?

Somfy Tahoma V2

### Device model

Tahoma Short Channel door Somfy Firmware: 2021.5.4

### Home Assistant log

```shell
2021-12-22 11:13:33 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.meterkast_sirene

Is the only line I could find in the logging
```

**Comment by iMicknl** [comment]
There was a breaking change related to the change from switch entities to the new siren entity. Do the new siren entities work? 
(or do you see anything in the log).

**Comment by RienduPre** [comment]
I don’t see any new sirene entities

**Comment by iMicknl** [comment]
What are those entities on your screenshot? Is there anything in your log related to the integration?

**Comment by RienduPre** [comment]
The screenshot are the disabled sirene entities which were working and enabled before the upgrade. 
should there be new sirene entities or devices in the list of the integration?

**Comment by iMicknl** [comment]
@RienduPre , would you be able to work with me [via Discord](https://discord.gg/gDSNf8MKf7) (iMick #1903) so we can speed up the development? Easiest would be if you could temporary change your password and send your credentials, so I can do some live debugging on my machine.

Siren is a hard platform to debug for me, since I don't own them.

**Comment by RienduPre** [comment]
Hi,
What happens to my entities when I change my password or userid? Can I just re-logon to my current integration or do I have to setup a new integration, the last option would recreate al my devices and is not what I want to do.

I sent you an invite via discord already.

Thanks,
Rien
