### ISSUE TITLE
Cancel via Home Assistant not working for awning device

### ISSUE THREAD

**Issue by Ivan86NL** [iMicknl/ha-tahoma#701]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

The same issue as mentioned in #283 and #263 is also present for an awning. I have an awning with a screen attached. This are two devices in Tahoma and Home Assistant. The attached screen is functioning correctly when I cancel it via Home Assistant. The awning is nog canceling correctly and behaving the same as mentioned by thijsdejong in #283.

Screenshot from Home Automation:
![image](https://user-images.githubusercontent.com/60283791/148639838-0bf30f0a-d8c5-45e3-96a3-f7c291dae69c.png)
So to keep things clear; the "Volant" (UpDownExteriorScreen) is working fine with the stop/cancel function, the "Zonnescherm" (UpDownHorizontalAwning) does not cancel/stop when it's opening or closing (same issue as thijsdejong mentioned in #283). 

Is it possible to create the same fix for the awning device as well? Thanks it advance! 

### What version of this integration (ha-tahoma) has the issue?

2.10.2

### What version of Home Assistant Core has the issue?

2021.12.7

### Which gateway / hub do you use?

Somfy TaHoma

### Device model

UpDownExteriorScreen, UpDownHorizontalAwning

**Comment by iMicknl** [comment]
Thanks for reporting!

>Is it possible to create the same fix for the awning device as well? Thanks it advance!

Unfortunately not, since this is a different issue. Does the `stop` button work when the action is executed via Home Assistant? And how does it behave when you start the action outside HA?

**Comment by Ivan86NL** [comment]
I've tested it to be sure, but the stop button also does not work when the action is executed from within Home Assistant. 
When I trigger it via the Tahoma app or webpage I can trigger the awning and stop it immediately also.
I hope this is information you can use.
