### ISSUE TITLE
Unable to change tilt position on io:BioclimaticPergolaIOComponent

### ISSUE THREAD

**Issue by jurgen272** [iMicknl/ha-tahoma#74]
The device io:BioclimaticPergolaIOComponent is visible in HA, but I can't change position.
Buttons and slider aren't responding.

**Expected behavior**
io:BioclimaticPergolaIOComponent is responding to bottons and slider

**Environment (please complete the following information):**
 - **Home Assistant version**: 0.111.4
 - Using latest beta version for Somfy Tahoma integration

**Device:** (if your problem is related to a specific device)
 - **Model**: Pergola
 - **Type**: io:BioclimaticPergolaIOComponent

**Comment by iMicknl** [comment]
Could you share your device info, like you did in your other issue? I would like to make sure our devices have the same commands available. This weekend I will give the latest beta a try with my Pergola device and see which changes we need to make.

**Comment by jurgen272** [comment]
{
         "creationTime":1590504461000,
         "lastUpdateTime":1590504461000,
         "label":"PERGOLA TILT IO",
         "deviceURL":"io://xxxxxx",
         "shortcut":false,
         "controllableName":"io:BioclimaticPergolaIOComponent",
         "definition":{
            "commands":[
               {
                  "commandName":"closeSlats",
                  "nparams":0
               },
               {
                  "commandName":"delayedStopIdentify",
                  "nparams":1
               },
               {
                  "commandName":"getName",
                  "nparams":0
               },
               {
                  "commandName":"identify",
                  "nparams":0
               },
               {
                  "commandName":"openSlats",
                  "nparams":0
               },
               {
                  "commandName":"refreshMemorized1Orientation",
                  "nparams":0
               },
               {
                  "commandName":"setMemorized1Orientation",
                  "nparams":1
               },
               {
                  "commandName":"setName",
                  "nparams":1
               },
               {
                  "commandName":"setSecuredOrientation",
                  "nparams":1
               },
               {
                  "commandName":"setOrientation",
                  "nparams":1
               },
               {
                  "commandName":"setSlatsOrientationWithSpeed",
                  "nparams":2
               },
               {
                  "commandName":"startIdentify",
                  "nparams":0
               },
               {
                  "commandName":"stop",
                  "nparams":0
               },
               {
                  "commandName":"stopIdentify",
                  "nparams":0
               },
               {
                  "commandName":"wink",
                  "nparams":1
               }
            ],
            "states":[
               {
                  "type":"ContinuousState",
                  "qualifiedName":"core:Memorized1OrientationState"
               },
               {
                  "type":"DataState",
                  "qualifiedName":"core:NameState"
               },
               {
                  "type":"ContinuousState",
                  "qualifiedName":"core:PriorityLockTimerState"
               },
               {
                  "type":"ContinuousState",
                  "qualifiedName":"core:RSSILevelState"
               },
               {
                  "type":"ContinuousState",
                  "qualifiedName":"core:SecuredOrientationState"
               },
               {
                  "values":[
                     "closed",
                     "open"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"core:SlatsOpenClosedState"
               },
               {
                  "type":"ContinuousState",
                  "qualifiedName":"core:SlatsOrientationState"
               },
               {
                  "values":[
                     "available",
                     "unavailable"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"core:StatusState"
               },
               {
                  "values":[
                     "comfortLevel1",
                     "comfortLevel2",
                     "comfortLevel3",
                     "comfortLevel4",
                     "environmentProtection",
                     "humanProtection",
                     "userLevel1",
                     "userLevel2"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"io:PriorityLockLevelState"
               },
               {
                  "values":[
                     "LSC",
                     "SAAC",
                     "SFC",
                     "UPS",
                     "externalGateway",
                     "localUser",
                     "myself",
                     "rain",
                     "security",
                     "temperature",
                     "timer",
                     "user",
                     "wind"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"io:PriorityLockOriginatorState"
               }
            ],
            "dataProperties":[
               {
                  "value":"500",
                  "qualifiedName":"core:identifyInterval"
               }
            ],
            "widgetName":"BioclimaticPergola",
            "uiClass":"Pergola",
            "qualifiedName":"io:BioclimaticPergolaIOComponent",
            "type":"ACTUATOR"
         },
         "states":[
            {
               "name":"core:NameState",
               "type":3,
               "value":"PERGOLA TILT IO"
            },
            {
               "name":"core:PriorityLockTimerState",
               "type":1,
               "value":0
            },
            {
               "name":"core:StatusState",
               "type":3,
               "value":"available"
            },
            {
               "name":"core:RSSILevelState",
               "type":2,
               "value":18.0
            },
            {
               "name":"core:SlatsOpenClosedState",
               "type":3,
               "value":"open"
            },
            {
               "name":"core:SlatsOrientationState",
               "type":1,
               "value":73
            },
            {
               "name":"core:SecuredOrientationState",
               "type":1,
               "value":105
            }
         ],
         "attributes":[

         ],
         "available":true,
         "enabled":true,
         "placeOID":"xxxxxx",
         "widget":"BioclimaticPergola",
         "type":1,
         "oid":"xxxxxx",
         "uiClass":"Pergola"
      }

**Comment by iMicknl** [comment]
@jurgen272 I can confirm that the integration is broking for pergola's, since we moved away from position to tilt_position for the slats.

**Comment by flhoest** [comment]
Hi there, I'm actually also working on this. I've found a way to mimic the setPosition behavior.
Start moving the slate, ready the actual position and stop when you reach what you are looking for. This is what I'm going to implement.

**Comment by iMicknl** [comment]
@flhoest you are responding to a very old issue, which has been resolved for ages. Not sure what you are working on, but good to check if the Overkiz integration in core doesn’t support it already.

**Comment by flhoest** [comment]
I'm trying to use the setPosition of my roof slats. The API returns a activity id like if it will be working but nothing happens. I using the OverKiz endpoint.

**Comment by iMicknl** [comment]
@flhoest this is the repository for the (old and deprecated) Home Assistant integration. Seems you are not using Home Assistant?

If you are using our Python API wrapper, please create an issue on https://github.com/iMicknl/python-overkiz-api.

If you face issues with the API, please contact Somfy support or https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode.

**Comment by flhoest** [comment]
You are right, I'm coding my own code and I'm using Domoticz. So, I'm totally out of context. Sorry.
