### ISSUE TITLE
Setup failure with Cozytouch

### ISSUE THREAD

**Issue by Hankey71** [iMicknl/ha-tahoma#752]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Overkiz integration has stopped working since 8:30 today. All of my connected devices no longer work: radiators and water heaters.

### What version of this integration (ha-tahoma) has the issue?

2.12.1

### What version of Home Assistant Core has the issue?

core-2022.2.1

### Which gateway / hub do you use?

Cozytouch

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Added device (Device...".
```

</details>

### Additional information

Cette erreur provient d'une intégration personnalisée

Logger: homeassistant.config_entries
Source: custom_components/tahoma/__init__.py:218
Integration: Overkiz (by Somfy) - Custom component
First occurred: 16:44:14 (1 occurrences)
Last logged: 16:44:14

Error setting up entry XX@XX.XX for tahoma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tahoma/__init__.py", line 51, in async_setup_entry
    if await _block_if_core_is_configured(hass, entry):
  File "/config/custom_components/tahoma/__init__.py", line 218, in _block_if_core_is_configured
    entry.data[CONF_USERNAME] == overkiz_entry.data[CONF_USERNAME]
KeyError: 'username'

**Comment by iMicknl** [comment]
Please update to v2.12.2 to see if this fixes your issue.

Your issue is not related to a specific time, but related to your 2022.2 update.

**Comment by Hankey71** [comment]
Thank you ! it works
