### ISSUE TITLE
You cannot use Overkiz from core and custom component at the same time.

### ISSUE THREAD

**Issue by arandax** [iMicknl/ha-tahoma#753]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Configuring Overkiz core integration, does not allow to configure ha-tahoma too.

### What version of this integration (ha-tahoma) has the issue?

2.12.2

### What version of Home Assistant Core has the issue?

2022.2.2

### Which gateway / hub do you use?

Tahoma

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Added device (Device...".
```

</details>

**Comment by tetienne** [comment]
Hello, that's on purpose. Otherwise you will be ban by Overkiz.

**Comment by arandax** [comment]
Thank you!
