### ISSUE TITLE
Sauter Ipala and Guella

### ISSUE THREAD

**Issue by cob94440** [iMicknl/ha-tahoma#761]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### Device information

I have two Ipala.
The integration see température and consuption but they are not view as climate.
My water heater sauter Guelma let me see how many shower left but non boost option nor eco mode.
They're connected via cozytouch

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Added device (Device...".
```

</details>

### Device commands

<details><summary>Commands logs</summary>

```
Copy/paste your execution history here.
```

</details>
Non logs

### Additional information

None

**Comment by tetienne** [comment]
Please, enable debug log, and update your comment: https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced
We haven’t enough information to help you.

**Comment by vlebourl** [comment]
Be aware that master version is not fully stable release and might break existing functionalities.

**Comment by cob94440** [comment]
I'm on 2.12.2.
Is it ahead of master

**Comment by vlebourl** [comment]
No it's behind.

**Comment by cob94440** [comment]
![Screenshot_2022-02-11-18-59-32-38_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/62489067/153644680-f2c4741a-3e95-44e6-aea8-4aba04697e9c.jpg)
![Screenshot_2022-02-11-18-59-42-72_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/62489067/153644701-8f7fe8f4-d8a4-46c1-8ffc-4012d2ed7d37.jpg)
This is what i have

**Comment by cob94440** [comment]
I Guess Guelma IS ok
As you Can see Ipala are not Seen as climate

**Comment by iMicknl** [comment]
Weird, the AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint should be supported as a climate entity already.

Can you download the diagnostics information and attach your JSON file here? (just drag and drop it in here). You can find the diagnostics button on the integrations page, when you click the dots at the integration.
