### ISSUE TITLE
Error message when I change HVAC_mode with my heaters (type NoneType doesn't define __round__ method)

### ISSUE THREAD

**Issue by tillstaff** [iMicknl/ha-tahoma#762]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Since the last update I do, I have some problems to set hvac_mode on my heaters. 
There is an error which interrupt all my automation tasks : 
```
Error: type NoneType doesn't define __round__ method
```
According to the logs, the problem has start with the fix #523 .
When I comment the following line, all is working well.
https://github.com/iMicknl/ha-tahoma/blob/88bff1c15ec2c48160c0e1da85c4c6155b8a5c26/custom_components/tahoma/sensor.py#L249

I think that is my "Cozytouch Interface" which cause the problem.
It's like a heater for Cozytouch but it doesn't have a temperature sensor.

![image](https://user-images.githubusercontent.com/11087736/153638912-6c1e52c2-c687-430f-9c27-1476d784d459.png)

### What version of this integration (ha-tahoma) has the issue?

2.12.2

### What version of Home Assistant Core has the issue?

2022.2.5

### Which gateway / hub do you use?

Cozytouch

### Device model

AtlanticElectricalHeater

### Home Assistant log

<details><summary>Logs</summary>

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 536, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 569, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 542, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/tahoma/sensor.py", line 394, in state
    return self.entity_description.native_value(state.value)
  File "/config/custom_components/tahoma/sensor.py", line 234, in <lambda>
    native_value=lambda value: round(value, 2),
TypeError: type NoneType doesn't define __round__ method
```

</details>

**Comment by iMicknl** [comment]
What was the last working version for you? Or did you just update it?

Since you link to a change from [Aug 12, 2021](https://github.com/iMicknl/ha-tahoma/pull/523#issue-969202076).

**Comment by tillstaff** [comment]
Yes I just update it and I didn't get too much care on the logs after that.

But my wife was complaining about the heater not working in the morning and I finally catch this error.

**Comment by iMicknl** [comment]
Can you include your diagnostic information?

**Comment by tillstaff** [comment]
Hi @iMicknl 
I can't reproduce the problem with the latest release 2.13.0.
I think the PR #768 has solved my issue.
`native_value=lambda value: round(cast(float, value), 2)`
Thanks for you help
