### ISSUE TITLE
Moving from [Overkiz (by Somfy) - Custom component] to [https://www.home-assistant.io/integrations/overkiz] missing posizion

### ISSUE THREAD

**Issue by xefil** [iMicknl/ha-tahoma#786]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Hi all,
I was a happy user of the HACS integration for my pergola using Somfy TaHoma. I had to create a script to revert the move of the devices, but apart from this all was working well.
AFAIK the core integration is the furure, right? So I have disabled the HACS component and installed the integration from HA. What I'm missing now is the position of the `current_position` attribute. So if I open the device, I have the position bar, and if I slide it to, i.e. 50%, it goes at 50%, but then the position is not reported to HA, so if I reopen the device again, the position is at 100%, because the `current_position` is missing. The cover / awning remains correctly at 50%.
Is this feature missing for any cause?
It's the right place to ask?
Thanks, Simon

### What version of this integration (ha-tahoma) has the issue?

latest with 2022.2.1

### What version of Home Assistant Core has the issue?

2022.2.1

### Which gateway / hub do you use?

Somfy Tahoma V2

### Device model

io:HorizontalAwningIOComponent + io:PergolaRailGuidedAwningIOComponent

### Home Assistant log

<details><summary>Logs</summary>

```
N/A
```

</details>

### Additional information

---

**Comment by tetienne** [comment]
Hi, as this an issue related to the Core, it should be reported within Core repository.

Anyway, about Cover platform we fully backport everything. There is no missing features. 

Can you please move your awning to 40%, wait 30 seconds and report the diagnostic information?

**Comment by iMicknl** [comment]
Indeed, as @tetienne mentioned; if you face an issue with Overkiz integration in core, please create an issues there.

**Comment by xefil** [comment]
Hi, ok @iMicknl and @tetienne , I can open the case there.... where ? :-)

**Comment by xefil** [comment]
Thanks @iMicknl as always ;)

**Comment by xefil** [comment]
Done:

https://github.com/home-assistant/core/issues/67766

Thanks @iMicknl and @tetienne  ;-)

Simon
