### ISSUE TITLE
select entity broken since update v2.13.0

### ISSUE THREAD

**Issue by NicoLeOca** [iMicknl/ha-tahoma#787]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Hi,

Since the last update, the select entity is broken and can't action any of the status for my gate.

here is the log I get in debug:
```
[custom_components.tahoma] Managed action group is invalid : Too many command parameters : expected at most 0 but got 1
```

Could have a look at it please?

### What version of this integration (ha-tahoma) has the issue?

2.13.0

### What version of Home Assistant Core has the issue?

2022.2.9

### Which gateway / hub do you use?

Tahoma Short Channel (Somfy Tahoma v1)

### Device model

io:DiscreteGateOpenerIOComponent

### Home Assistant log

<details><summary>Logs</summary>

```
[custom_components.tahoma] Managed action group is invalid : Too many command parameters : expected at most 0 but got 1
```

</details>

**Comment by iMicknl** [comment]
Which select entity do you use? (could you maybe add a screenshot?). What is the latest version of ha-tahoma where it does work for you? Can you double check this for me?

Is there a reason why you don't use the Overkiz integration in core by the way, I think most of these features are already ported.

**Comment by NicoLeOca** [comment]
Hi @iMicknl 
<img width="847" alt="Capture d’écran 2022-03-06 à 20 26 54" src="https://user-images.githubusercontent.com/9487685/156938964-dedd83dc-9de6-4a3d-bf07-754f1e251b80.png">

<img width="475" alt="Capture d’écran 2022-03-06 à 20 28 17" src="https://user-images.githubusercontent.com/9487685/156938981-f543f6d3-6626-49ba-b3e6-6622f0e55e43.png">

I think v2.12.2 was ok, i usually keep everything up to date.
I did not move to the core integration because I didn't see the point. On the contrary, I suspect that the core will not be updated as dynamically as the HACS version, because of the HA process.

**Comment by iMicknl** [comment]
Could you try another version and see which version still works? This will for sure speed up the fix :-). I wonder if this is caused by an update on our side, or on Overkiz side.

To be honest, currently core is even further in terms of code, we focus on core and improvements made to core will eventually end up here. In the end, we hope to sunset this integration.

**Comment by NicoLeOca** [comment]
@iMicknl 
I do confirm that v2.12.2 works properly

**Comment by iMicknl** [comment]
@NicoLeOca could you perhaps check the version in core? Does that have the same issue?

Our efforts are now mainly focused on core, thus if you can move, it would be great :-).

**Comment by NicoLeOca** [comment]
@iMicknl 
Done
Not really a success so far; the select does not appear at all
I open an issue in HA and close this one
