### ISSUE TITLE
Add support for Somfy Tahoma Alarm

### ISSUE THREAD

**Issue by ryoshi87** [iMicknl/ha-tahoma#793]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The request

Hi,

I'm not sure if this is already supported, but my integration does not find the built-in alarm of the Somfy Tahoma.
I have some motion and window closure sensors and want to arm and disarm the alarm from HA. Hope you know what I mean.
A month ago I tried the addin of openhab and they use the same Overkiz API and the alarm was detected, so the API should support that. But I really want to use HA instead of openhab.

Should the integration discover the alarm, or is this unsupported?
Thank you for your time and help.

Greetings

### Which gateway / hub do you use?

Somfy Tahoma

**Comment by iMicknl** [comment]
Please include your diagnostics information. You can download this via the integrations page, 3 dots and than select download diagnostics.

**Comment by ryoshi87** [comment]
Hi,
thank you for having a look.
I see, that there is a alarm detected, but it does not show in the device list. I am a HA newbie, so I might miss something.
[config_entry-overkiz-c7a5b52daea1a27726ebf43bea363277.json.txt](https://github.com/iMicknl/ha-tahoma/files/8356235/config_entry-overkiz-c7a5b52daea1a27726ebf43bea363277.json.txt)

**Comment by iMicknl** [comment]
It seems that your alarm control panel is already supported in ha-tahoma (not in core!). If you go to the integrations page and look up the devices of this integration, do you see 'Alarm' in the list?

There should be a disabled alarm control panel entity, that you can enable.

**Comment by ryoshi87** [comment]
I searched through all devices and entities within the settings filtered by the integration. There is no alarm, partial* or anything. I am only seeing my rooms, sensors, shutters etc. Maybe I am not on the right page? Sorry for my little knowledge. I am trying to evaluate HA.

Is the settings view, the page you mean?

**Comment by iMicknl** [comment]
If you go to `/config/integrations` and than click on "x devices" at the Overkiz integration. Can you send me a screenshot of that page?

**Comment by ryoshi87** [comment]
Hi,
this was the page I was referring to. On this page there are following entries:
All of my ContactSensor, PositionableRollerShutterWithLowSpeedManagement, SmokeSensor, OccupancySensor and 1 entry with Model: Tahoma Pro.
The list is long, so I think the Model Column is what you wanted to know. If not, please let me know.

On each device page I can do, what I am expecting to do: Roller Shutters can move, ContactSensors let me know their state, etc.
On the Tahoma Pro page, there is only a Device Info (not much info), Diagnose with an HomeKit code and 3 Boxes for automation, Scenes and scripts. 

Thank you again for taking your time.

**Comment by ryoshi87** [comment]
Hi, sadly I am pretty sure.
I sorted after Model and if the name should be the same it should appear between Tahoma Pro and my SmokeSensor, but it does not.
![ScreenshotOverkizDevices](https://user-images.githubusercontent.com/8654662/160472521-5fc60a3c-f72a-45b9-95ca-e5444124c47c.png)

I browsed the diagnostics and I can see there is a TSKAlarmController listed, but I can't see it anywhere in the UI. Sadly I don't speak Python. I tried to add an Alarm Panel on the dashboard, but it says there is no entity to add. Dunno if this is supported.

I tries to reinstall, tried to switch the alarm via the app to get it detected. No success.

Is there any way to add it manually via a configuration file?
Thank you for helping me out.

**Comment by iMicknl** [comment]
@ryoshi87 , would you be able to work with me [via Discord](https://discord.gg/RRXuSVDAzG) (iMick #1903) so we can speed up the development? Easiest would be if you could temporary change your password and send your credentials, so I can do some live debugging on my machine.

**Comment by ryoshi87** [comment]
As said in discord. Seemed to had a setup error on my side. Its working with the latest dev core. Closing this.
