### ISSUE TITLE
Expose auto/manual switch of Somfy remote (io)

### ISSUE THREAD

**Issue by neuhausf** [iMicknl/ha-tahoma#794]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The request

I’m trying to use the little A/M switch on the somfy remote as a sensor in my automations. But I can’t figure how (or if) the switch is represented by this integration.
![image](https://user-images.githubusercontent.com/7963239/161229944-679f95bf-c1a7-4e79-b6a3-075378edb58c.png)
See also https://community.home-assistant.io/t/overkiz-api-and-somfy-api/61448/1769?u=neuhausf

### Which gateway / hub do you use?

Somfy TaHoma V2, Firmware: 2021.6.4

### Device model (optional)

PositionableExteriorVenetianBlind (or probably TaHoma Short Channel)

### Device type (optional)

io:ExteriorVenetianBlindIOComponent

### Additional information

diagnostics of TaHoma V2 from HA
[config_entry-overkiz-91796d4b3b8434e80fa9ccd21a2481e9-tahoma.json.txt](https://github.com/iMicknl/ha-tahoma/files/8396261/config_entry-overkiz-91796d4b3b8434e80fa9ccd21a2481e9-tahoma.json.txt)

**Comment by iMicknl** [comment]
@neuhausf can you change the value of your remote and generate your diagnostics again? It would be good to have a diff to easily spot what changed.

**Comment by neuhausf** [comment]
(2): remote on "auto"
-> switch auto to manual
(3): remote on "manual"
[config_entry-overkiz-91796d4b3b8434e80fa9ccd21a2481e9.json (2).txt](https://github.com/iMicknl/ha-tahoma/files/8396418/config_entry-overkiz-91796d4b3b8434e80fa9ccd21a2481e9.json.2.txt)
[config_entry-overkiz-91796d4b3b8434e80fa9ccd21a2481e9.json (3).txt](https://github.com/iMicknl/ha-tahoma/files/8396419/config_entry-overkiz-91796d4b3b8434e80fa9ccd21a2481e9.json.3.txt)

I don't see any difference... All registered blinds on the remote move a little bit (same as identify). Not only the blind on the selected channel.

**Comment by neuhausf** [comment]
@iMicknl as for the remote I guess it's the basic TaHoma Remote, which came with the box:
https://elektro-zollinger.ch/Shop/Somfy/RF-Handsender-Somfy-TaHoma-Serenity-2-RTS-ws-gu-204012039?sort=rating&order=ASC&page=9
I'm interested in the state of the Somfy Situo 5 Variation A/M remote:
https://www.somfy.ch/de-ch/produkte/1811636/situo-5-variation-a-m-io-pure-ii
Shouldn't the remote store the auto/manual state on the blind or on the box?

**Comment by iMicknl** [comment]
What does the remote do? But it doesn't seem like this is exposed unfortunately. If you cannot see it on tahomalink.com or in the official app, it is probably not available.

**Comment by neuhausf** [comment]
The Situo remote closes/opens the blind. It has 5 channels to control 5 blinds.
The auto/manual switch is to enable/disable automations running on the TaHoma box. The switch state is reflected in Tahomalink:
![image](https://user-images.githubusercontent.com/7963239/161236981-a03c6153-bc2f-4e1d-98ac-8a9a643c7b62.png)
So it should be retrievable by the API I guess?

**Comment by neuhausfhacs** [comment]
I guess I found it. It's the priority lock originator sensor, which is disabled by default.
![image](https://user-images.githubusercontent.com/101320210/161252614-cc3b192b-0961-4d3a-a981-5182f7bef6f4.png)
![image](https://user-images.githubusercontent.com/101320210/161252792-def12bc5-c6ba-44a1-b17d-2b87ae341fb3.png)
"Benutzer" (user) means in this case, that the manual control is activated. "Unbekannt" means it's on "auto".

Only issue: The value doesn't update itself. Only if I open the TaHoma App on the phone or refresh Tahomalink. @iMicknl can you poll this sensor from time to time? Or expose a service to do so. I don't need "realtime" data - every 5 to 10 minutes would be enough.

**Comment by iMicknl** [comment]
@neuhausf we won't fix this on short term. We already poll every 30 seconds for updates on the event listener, but apparently this state is not broadcasted. Opening the TaHoma app (or tahomalink.com) will call an endpoint to refresh all states, which we should not call every 5 minutes.

We looked into this in the past: https://github.com/iMicknl/ha-tahoma/pull/271, however we couldn't settle yet on a good decision. Somfy's infrastructure is just not built for this...

**Comment by neuhausfhacs** [comment]
@iMicknl I see. It's a pitty that I can't use this switch without polling.
Probably you can reconsider #271 in a different approach: Expose a service which refreshes the state of (one) device. Implement some rate limiting: Only x requests per hour/day. Something like HACS does with the github API.

In my case I just need about three updates a day: Auto opening/closing blinds in the morning/during the day/evening. So the update will occur before making a decision in terms of automation (in my case with AppDaemon, [hass-blinds](https://github.com/wogri/hass-blinds)).

**Comment by tetienne** [comment]
@neuhausf Within the Tahoma website, when you switch the mode, do you see an instant update of UI? If yes it means there is an event we don't read.

**Comment by neuhausf** [comment]
@tetienne No and yes...
1. I open tahomalink.com, navigate to "product" view
2. Change auto to manual on the remote
3. Wait... even after 3mins the state is not reflected in tahomalink
4. Open Tahoma Classic on iPhone
5. Do nothing but wait a few seconds
6. On the *web interface* tahomalink.com, the state is now updated. The same is true for the home-assistant sensor.

The following happens in the web interface *after* opening the iPhone app:
![image](https://user-images.githubusercontent.com/7963239/161418663-c5ae8b8e-4686-4953-ad14-2170f79c0315.png)
![image](https://user-images.githubusercontent.com/7963239/161418688-c247a6f8-36d8-4a96-aa1d-d017a38d13c5.png)
![image](https://user-images.githubusercontent.com/7963239/161418713-5158b177-1860-4cee-a085-d1b7443e8842.png)
![image](https://user-images.githubusercontent.com/7963239/161418734-8796c558-48ca-44ce-86b2-7816eb471ca8.png)

**Comment by tetienne** [comment]
Thx for clear debug session :) So indeed even Somfy cannot trigger a live update within calling this `RefreshAllDevicesStatesCompletedEvent`.

**Comment by neuhausf** [comment]
@tetienne
Just another detail: I activated manual mode on 20:30 -> state was not reflected in HA until 7:00 the next day. At this time, a Somfy automation ran. So I guess that the Tahoma box must refresh all device states before running an automation.

Hopefully we can refresh the states more often with https://github.com/iMicknl/ha-tahoma/issues/796
So I'm closing this for now, so can all focus on implementing the local API (which will be awesome 😉 )!
