### ISSUE TITLE
Implement Somfy TaHoma local API

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#796]
Finally Somfy implemented a local API! We hope to implement it in core for the next month release, let's see if that is feasible.

> *Eligible TaHoma Boxes: TaHoma V2, TaHoma switch, TaHoma DIN-Rail v1 & v2

<details><summary>Full Announcement</summary>

> Dear customer,
>  
> We are glad to contact you today for the release of a new service we call Developer Mode, available for the different types of TaHoma boxes*.
> 
> This new service allows to activate a local API on your TaHoma box and finally connect third-party software to your equipment. A complete documentation of the service is available on [GitHub](https://somfy.us17.list-manage.com/track/click?u=2969767755c736684ad240968&id=acdead4d39&e=cc7b34f13b). In a nutshell, the API allows to monitor and control the devices which are paired locally with your TaHoma box without the constraint of going through our servers. Thanks to the new Developer Mode, you can easily integrate your Somfy equipment with third-party home automation softwares.
> 
> **Support**
> Our support teams are available for any problems or questions regarding the use or operation of the TaHoma system.
> However, for questions related to the development of third party software using the API, please refer to the page mentioned above for further details.
> Finally, for problems or questions concerning the use of said software, it is necessary to contact the supplier or developer of the chosen solution directly for assistance.
> 
> **Warning**
> The applications proposed by Somfy to use its boxes and connected solutions employ a certain number of rules designed to preserve the integrity of your equipment. Please be careful when using the API so as not to damage them. Somfy declines all responsibility for inappropriate use. Similarly, the use of the TaHoma application in conjunction with the API may cause conflicts or contrary actions for which Somfy cannot be held responsible. Also, to ensure the proper functioning of your box, be sure to limit the demands on it.
> 
> **Sunsetting Somfy Open API**
> It is always hard to say goodbye but Developer Mode is so much better ! Its release therefore announces the depreciation of the Somfy Open API (cloud-based) as the new service will provide a larger number of features (scenarios and group commands being included) but also a larger number of supported devices. Finally, the Developer Mode, by its local nature, avoid any downtime issue or traffic limitation.
> 
> If you are a Somfy Open API customer, from the entire Somfy team, we’d like to apologize for any inconvenience this may cause you. We’re committed to making the transition as smooth as possible and that’s why we’ll continue to support this API until June 21st 2022.
> 
> Thank you for your understanding and we hope you will enjoy this new service.
> 
> *Eligible TaHoma Boxes: TaHoma V2, TaHoma switch, TaHoma DIN-Rail v1 & v2
> 

</details>

https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode

**Comment by NicoLeOca** [comment]
That rocks!
It would even make me move to a supported version of the Tahoma and get rid of my v1.

**Comment by NicoLeOca** [comment]
> That rocks! It would even make me move to a supported version of the Tahoma and get rid of my v1.

Done !

**Comment by Archcry** [comment]
It would be nice to add local support for connexoon as well. There's no official way to enable the local API on connexoon but it's possible to jailbreak the connexoon and enable local API that way ([source](https://blog.unauthorizedaccess.nl/2021/04/07/no-clouds-just-sunshine.html)).

**Comment by iMicknl** [comment]
We will look into that as well, however our first goal is to work on the Somfy TaHoma integration. I am in contact with Donny and we will see what changes need to be made to support both of them.

See https://github.com/home-assistant/core/issues/69558.

**Comment by tetienne** [comment]
The deprecated API is the one used by the Somfy component not the one used by this component.

**Comment by EDelsman** [comment]
Thanks, that is reassuring. The release notes and Somfy deprecation message suggested the local api would be the solution.
