### ISSUE TITLE
Electricity Meter

### ISSUE THREAD

**Issue by lseufer** [iMicknl/ha-tahoma#80]
Describe the bug:
Data isn't pulled from my meters

Expected behavior:
Nothing is reported. Only "unknown" 

Environment:
 - Home Assistant version: 0.111
 - **Platform**: sensor

Device:
 - Model: 'io:TotalElectricalEnergyConsumptionIOSystemSensor'
 - Type: CumulativeElectricPowerConsumptionSensor

**Comment by vlebourl** [comment]
Hi, thank you for the report, can you please follow instructions provided [here](https://github.com/iMicknl/ha-tahoma/blob/7d8a780b9a3d0ac6b07e76967dbe3d8b36beb49b/.github/ISSUE_TEMPLATE/bug_report.md) to add device details, namely state definitions and command definitions?

**Comment by lseufer** [comment]
Here you go!


`creationTime":1564688966000,
         "lastUpdateTime":1564688966000,
         "label":"Compteur",
         "deviceURL":"",
         "shortcut":false,
         "controllableName":"io:TotalElectricalEnergyConsumptionIOSystemSensor",
         "definition":{
            "commands":[

            ],
            "states":[
               {
                  "type":"ContinuousState",
                  "qualifiedName":"core:ElectricEnergyConsumptionState"
               },
               {
                  "type":"ContinuousState",
                  "qualifiedName":"core:RSSILevelState"
               },
               {
                  "values":[
                     "dead",
                     "lowBattery",
                     "maintenanceRequired",
                     "noDefect"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"core:SensorDefectState"
               },
               {
                  "values":[
                     "available",
                     "unavailable"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"core:StatusState"
               }
            ],
            "dataProperties":[

            ],
            "widgetName":"CumulativeElectricPowerConsumptionSensor",
            "uiClass":"ElectricitySensor",
            "qualifiedName":"io:TotalElectricalEnergyConsumptionIOSystemSensor",
            "type":"SENSOR"
         },
         "states":[
            {
               "name":"core:StatusState",
               "type":3,
               "value":"available"
            },
            {
               "name":"core:ElectricEnergyConsumptionState",
               "type":1,
               "value":21744148
            }
         ],
         "attributes":[
            {
               "name":"core:MeasurementCategory",
               "type":3,
               "value":"electric/overall"
            },
            {
               "name":"core:PowerSourceType",
               "type":3,
               "value":"mainSupply"
            },
            {
               "name":"core:MeasuredValueType",
               "type":3,
               "value":"core:ElectricalEnergyInWh"
            }
         ],
         "available":true,
         "enabled":true,
         "placeOID":"c9594cac-f5e2-4e26-9688-5926954443d3",
         "widget":"CumulativeElectricPowerConsumptionSensor",
         "measurementCategory":"ELECTRIC_OVERALL",
         "type":2,
         "oid":"4ff9b811-1bd8-4edc-afb6-422ac7b87b45",
         "uiClass":"ElectricitySensor"`

**Comment by vlebourl** [comment]
could you checkout this branch instead of your HACS install of the component and try it out?

https://github.com/iMicknl/ha-tahoma/tree/fix_electrical_energy_sensor

**Comment by lseufer** [comment]
Excellent! This works. You can merge it.

**Comment by vlebourl** [comment]
thanks!
