### ISSUE TITLE
Unable to change temperature on altantic thermostats

### ISSUE THREAD

**Issue by YomoShitsu** [iMicknl/ha-tahoma#805]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Hello, 

I have an Atlantic installation in my home with a bridge cozytouch. 
With Overkiz integration, I am able to switch on/off all climates in my house. 
But now I can't change temperature with this integration

### What version of this integration (ha-tahoma) has the issue?

2.13.0

### What version of Home Assistant Core has the issue?

core-2022.5.3

### Which gateway / hub do you use?

Cozytouch

### Home Assistant log

<details><summary>Logs</summary>

```
2022-05-10 07:07:18 DEBUG (MainThread) [custom_components.tahoma] Finished fetching device events data in 0.098 seconds (success: True)
2022-05-10 07:07:48 DEBUG (MainThread) [custom_components.tahoma] Finished fetching device events data in 0.100 seconds (success: True)
2022-05-10 07:08:18 DEBUG (MainThread) [custom_components.tahoma] Finished fetching device events data in 0.102 seconds (success: True)
2022-05-10 07:08:48 DEBUG (MainThread) [custom_components.tahoma] Finished fetching device events data in 0.098 seconds (success: True)
2022-05-10 07:09:18 DEBUG (MainThread) [custom_components.tahoma] Finished fetching device events data in 0.097 seconds (success: True)
```

</details>

**Comment by iMicknl** [comment]
Can you download your diagnostics information (from the device page of the device that doesn't work) and than drag and drop it here in a new comment.

**Comment by YomoShitsu** [comment]
![image](https://user-images.githubusercontent.com/58432074/168284832-2a3cd6c9-4054-4057-b79e-adb55dfb9482.png)

![image](https://user-images.githubusercontent.com/58432074/168284889-00c290c6-dc23-4f51-bf8b-b355c20dbb28.png)

![image](https://user-images.githubusercontent.com/58432074/168285069-82d5c550-10ec-41f7-a1b5-e61ce0b48114.png)

![image](https://user-images.githubusercontent.com/58432074/168285149-5f780fb4-2f3d-4649-9bdb-80d6941f46a2.png)

**Comment by iMicknl** [comment]
@YomoShitsu and for which one can't you set the temperature? I see a lot of climate entities, which one  is 'broken'?

**Comment by YomoShitsu** [comment]
All are broken. I can't set temperature for all...
But I can switch off/on all of them

**Comment by iMicknl** [comment]
What is the error you get? Or is it just not available? Can you add a screenshot of the climate card in the dashboard + pop-up.

**Comment by YomoShitsu** [comment]
I don't see any error or pop up... 
when I changed temperature with my iOS Cozytouch app it doesn't sent information to home assistant. But when I switch off my climate since iOS app, it switch off it on home assistant. 

![image](https://user-images.githubusercontent.com/58432074/168292115-de406838-d2e5-4dd2-9ac7-05dac3f1b98f.png)

**Comment by YomoShitsu** [comment]
And I have only two days of logbook...

**Comment by YomoShitsu** [comment]
Hi @iMicknl did you get some news about my issue ?
Regards

**Comment by YomoShitsu** [comment]
Hi guys ! 
Does anyone got some news about my issue ? 
Ni answers since 14 days...

**Comment by tetienne** [comment]
Sorry, our free time currently is limited, and we are focused on backported (slowly) this custom component to HA directly.
About https://github.com/iMicknl/ha-tahoma/issues/805#issuecomment-1126046645, if you restart your HA instance do you see the states refreshed?

**Comment by YomoShitsu** [comment]
Hello sorry for later answer...
No it doesn't work anymore

**Comment by YomoShitsu** [comment]
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.tahoma
Source: helpers/update_coordinator.py:151
Integration: Overkiz (by Somfy) - Custom component
First occurred: 13:20:09 (1 occurrences)
Last logged: 13:20:09

Error fetching device events data: Too many requests, try again later.

**Comment by YomoShitsu** [comment]
Hi guys !
Any news about my issue ?

**Comment by YomoShitsu** [comment]
I saw a new thing : 

If my Zone Control is in heat mode your extension works like a charm. But when I put it in fresh mode, it doesn't works. 

Any idea ?

**Comment by YomoShitsu** [comment]
Last version of Kubernetes up to date
Same issue with cool mode
But integration works with heat mode

**Comment by iMicknl** [comment]
@YomoShitsu please update to 2022.12 in core (public beta now, or release in a few days). This will include the `AtlanticPassAPCZoneControl`. You can now use the core integration and report a bug in https://github.com/home-assistant/core/issues, when you still face issues.
