### ISSUE TITLE
Invert Cover state

### ISSUE THREAD

**Issue by svh1985** [iMicknl/ha-tahoma#806]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The request

Hi there,

I want to check if it's possible to invert the incorrect state of my io:HorizontalAwningIOComponent, which is actually installed in my house as a 4,5 mtr wide vertical awning. I have 3 other awning's which are reported as io:VerticalExteriorAwningIOComponent, these are showing the correct state, see image below.

The rflink platform as an option to invert the state of an device, is this also possible with ha-tahoma?

```
cover:
  - platform: rflink
    devices:
      YOUR_ACTUAL_DEVICE_ID:
        ... /... 
        type: inverted
```

<img width="679" alt="image" src="https://user-images.githubusercontent.com/5213210/170037175-68f2b259-a7bd-47bd-848f-d2a314c5124c.png">

Thanks!

### Which gateway / hub do you use?

Tahoma Switch

### Device model (optional)

PositionableHorizontalAwning

### Device type (optional)

io:HorizontalAwningIOComponent

**Comment by tetienne** [comment]
Hi,

Components are not allowed anymore to add option within the yaml, and there is currently no way to add easily an option through the UI.
For your use case, you will have to create a [template cover](https://www.home-assistant.io/integrations/cover.template/) to reverse the logic.
