### ISSUE TITLE
use of deprecated 'async_get_registry', use async_get instead...

### ISSUE THREAD

**Issue by browetd** [iMicknl/ha-tahoma#809]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

At startup and since the last release of HA (2022.6), I have the following errors while ha-tahoma is starting:

`2022-06-05 09:27:15 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for tahoma using this method at custom_components/tahoma/__init__.py, line 141: device_registry = await dr.async_get_registry(hass)
2022-06-05 09:27:15 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for tahoma using this method at custom_components/tahoma/climate_devices/atlantic_electrical_heater_with_adjustable_temperature_setpoint.py, line 109: entity_registry = await self.hass.helpers.entity_registry.async_get_registry()`

### What version of this integration (ha-tahoma) has the issue?

V2.13.0

### What version of Home Assistant Core has the issue?

2022.6.2

### Which gateway / hub do you use?

Cozytouch

### Device model

Equateur 3

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Added device (Device...".
```

</details>
See problem description...

**Comment by tetienne** [comment]
Hi, thx for reporting this. Depending of the HA reviewer, your device will be soon available directly from the Overkiz integration and so you will no need to use this custom component: https://github.com/home-assistant/core/pull/72790

**Comment by roofburner** [comment]
Still present:
2022-07-06 12:50:29 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for tahoma using this method at custom_components/tahoma/__init__.py, line 141: device_registry = await dr.async_get_registry(hass)

**Comment by browetd** [comment]
@tetienne I am using Overkiz Integration (latest release) and the issue is still present.  There is two references to async_get_registry in __init__.py at lines 141 and 158 of the current code.

**Comment by tetienne** [comment]
@browetd what is the device you need we implement within Core to leave this custom component?

**Comment by browetd** [comment]
@tetienne I am using three "Equateur 3" heaters from Atlantic...  Is it already supported by Core ? I have seen that a PR has been issued recently but have not seen any mention of that in the last release of HA 2022.7.0 (I am still using 2022.6.7 due to the amount of potential problems generated by the move to Python 3.10)...

**Comment by browetd** [comment]
Is the Equateur 3 devices (Brand: Thermor using Cozytouch)  are supported by the integration in core Home assistant ?  If not, I still have the issue...

**Comment by iMicknl** [comment]
@browetd this still depends on https://github.com/home-assistant/core/pull/72790. Which is not merged yet.

**Comment by roofburner** [comment]
Still present: 2022-09-28 22:20:53.763 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom integration author for tahoma using this method at custom_components/tahoma/__init__.py, line 141: device_registry = await dr.async_get_registry(hass)

**Comment by iMicknl** [comment]
Does this block the integration / home assistant from functioning? We are aware of this issue and hope to have the components migrated as soon as possible.

**Comment by browetd** [comment]
@iMicknl As far as I know, this is not blocking the integration to work... Just warning messages...  Thank you for your hard work on this integration.  I appreciate

**Comment by roofburner** [comment]
All works well, for now...Op 7 okt. 2022 18:21 schreef Mick Vleeshouwer ***@***.***>:
Does this block the integration / home assistant from functioning? We are aware of this issue and hope to have the components migrated as soon as possible.

**Comment by iMicknl** [comment]
Fixed in latest version. Thanks for your patience @browetd ;-).
