### ISSUE TITLE
Add support for ModelName EOLIS WIREFREE io

### ISSUE THREAD

**Issue by dannycb1987** [iMicknl/ha-tahoma#812]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### Device information

I have a Eolis Wirefree windsensor ( https://www.somfy.nl/producten/1816084/eolis-wirefree-io) but the app does not show the windsensor. I hooked it up directly on the motors (only way it seems) that is working correctly, but I would love to get the sensor working in HA so I can automate more stuff based on wind speed. Is this possible?

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Added device (Device...".
```

</details>

### Device commands

<details><summary>Commands logs</summary>

```
No log available
```

</details>

**Comment by tetienne** [comment]
Hi, please enable the debug logging https://github.com/iMicknl/ha-tahoma/blob/master/README.md#enable-debug-logging
Restart and report the log related to this component.
