### ISSUE TITLE
Unable to move blind to 'my' position

### ISSUE THREAD

**Issue by boutch** [iMicknl/ha-tahoma#814]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Hello,

I am using the latest version of the custom component via the Mini Tahoma box. I can control my RTS 

blinds correctly but can't get the my position to work. If I use the Tahoma app on my phone, it works fine.

I've tried:
- calling the service cover.stop_cover
- using the service tahoma.set_cover_my_position as per the documentation but it is not listed
![msedge_qJ6KC3xRfB](https://user-images.githubusercontent.com/6465289/178484156-b1425b4e-e880-461e-80d2-cc649edcf8ab.png)

What am I missing?

Thank you

### What version of this integration (ha-tahoma) has the issue?

2.13.0

### What version of Home Assistant Core has the issue?

2022.7.2

### Which gateway / hub do you use?

Tahoma Mini

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Added device (Device...".
```

</details>

**Comment by iMicknl** [comment]
@boutch is there a reason why you use the custom component, instead of the Overkiz integration from core? (remove the custom component first).

The my functionality is not exposed via a service anymore, but via a button. You should see this button on your integrations page.

**Comment by boutch** [comment]
Thank you @iMicknl. I've tried both Overkiz as a custom component and also in HA core. I can't see any button in the integration. 
![msedge_b8YaAc5Afh](https://user-images.githubusercontent.com/6465289/178509771-5c3c663c-b3e1-4adc-97f3-75159c68ed78.png)

**Comment by boutch** [comment]
Thank you.

That's done, please refer to https://github.com/home-assistant/core/issues/75067
