### ISSUE TITLE
Atlantic Cozytouch : Invalid authentication

### ISSUE THREAD

**Issue by sylvaindd** [iMicknl/ha-tahoma#816]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I can't get to connect to my Cozytouch account, I get the error : Invalid authentication
It's working fine on the Cozytouch Android application.
I tried changing my password to one without special characters, didn't change anything.

I enabled the debug logs, but I don't get any logs.

### What version of this integration (ha-tahoma) has the issue?

v2.13.0

### What version of Home Assistant Core has the issue?

2022.7.5

### Which gateway / hub do you use?

Cozytouch

### Home Assistant log

2022-07-16 17:49:39 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tahoma which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by iMicknl** [comment]
Let's track this in https://github.com/home-assistant/core/issues/75394.

Please switch to the core integration, if you are able to switch.
