### ISSUE TITLE
Add support for DomesticHotWaterProduction (modbuslink:AtlanticDomesticHotWaterProductionMBLComponent)

### ISSUE THREAD

**Issue by mlkjp161** [iMicknl/ha-tahoma#817]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### Device information

thermor malicio 3

atlantic agilia

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Added device (Device...".
```

</details>

### Device commands

turn off and turn on

**Comment by iMicknl** [comment]
Can you add your diagnostics information?

**Comment by mlkjp161** [comment]
[overkiz-6871a79ca8297748fc9e79df2804c325-MALICIO-2e96cf78f877bf6941e8ad70f7db3390.json.txt](https://github.com/iMicknl/ha-tahoma/files/9229463/overkiz-6871a79ca8297748fc9e79df2804c325-MALICIO-2e96cf78f877bf6941e8ad70f7db3390.json.txt)

thank you for your answer, the first one is the thermor malicio 3.

[overkiz-6871a79ca8297748fc9e79df2804c325-Cozytouch Sauter-707833dd6ace35d3244969b8eea044da.json.txt](https://github.com/iMicknl/ha-tahoma/files/9229468/overkiz-6871a79ca8297748fc9e79df2804c325-Cozytouch.Sauter-707833dd6ace35d3244969b8eea044da.json.txt)

the second one is the atlantic agilia.

I would like to turn them off, to control the temperature would be a plus.

cheers

**Comment by iMicknl** [comment]
Thanks @mlkjp161, your first device is DomesticHotWaterProduction (modbuslink:AtlanticDomesticHotWaterProductionMBLComponent) and your second device is the hub? So I am not sure what your 'Atlantic Agilia' is?

Can you describe your second device and a screenshot of the CozyTouch app?

**Comment by mlkjp161** [comment]
The Atlantic Agilia work fine!
But not the thermor malicio 3. I still can't turn it off.
I attach a sreenshot below:

![Screenshot_2022-09-04-18-34-45-1675058157](https://user-images.githubusercontent.com/78966928/188324813-cffa9413-149e-426e-85e1-1edf49b08aba.png)
