### ISSUE TITLE
SIlence mode via activateOption

### ISSUE THREAD

**Issue by steeve** [iMicknl/ha-tahoma#818]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The request

It is possible to enable/disable the "Discreet" mode that's available in the TaHoma app via the following:

```
           "commands": [
            {
              "commandName": "activateOption",
              "nparams": 1
            },
            {
              "commandName": "deactivateOption",
              "nparams": 1
            },
            
            
          {
            "name": "core:SupportedOptions",
            "type": 10,
            "value": [
              "silence"
            ]
          }
```

Enabling/disabling the silence mode
```
activateOption("silence")
deactivateOption("silence")
```

Getting the current state:
```
          {
            "name": "core:ActivatedOptionsState",
            "type": 10,
            "value": [
              "silence"
            ]
          }
```

I managed to make it work via the `tahoma.execute_command` service from HA, but I'd wager it'd be nicer to have a binary switch available.

Wdyt?

### Which gateway / hub do you use?

Somfy TaHoma Mini (connectivity kit)

### Device model (optional)

DynamicShutter

### Device type (optional)

ogp:Shutter

**Comment by tetienne** [comment]
Hi, thx you for your detailed issue.

Can you please open your issue directly on the main Home assistant repository https://github.com/home-assistant/core ?

We don't support new features here.
