### ISSUE TITLE
Can't get On/Off switch 

### ISSUE THREAD

**Issue by Desaydrone** [iMicknl/ha-tahoma#819]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I use this integration to connected all my heater from cozytouch hub, it seems to retrieve lot of information, but i didn't have On/Off switch that i can use on my automation. 

I got :

- 2 Atlantic Oniris io P
- 3 Atlantic Oniris io H
- 2 Atlantic Agilia H

I got the climate entities but no switch,  and don't find how to have them, if of course some have to be create

### What version of this integration (ha-tahoma) has the issue?

2.13.0

### What version of Home Assistant Core has the issue?

2022.9.7

### Which gateway / hub do you use?

Atlantic Cozytouch

### Device model

Oniris io P / Oniris io H / Agilia H

**Comment by iMicknl** [comment]
What is your device? Please include your 'Model' and 'Hardware' which you can see on the integrations page.

Is this already supported in the Home Assistant core integration?

**Comment by Desaydrone** [comment]
Hope is that you need :) 

**The list :** 
![image](https://user-images.githubusercontent.com/15471688/193433307-71d64887-c48e-4fb8-8417-bf4296dc4e50.png)

**Oniris io P**
![image](https://user-images.githubusercontent.com/15471688/193433222-3bf6579c-5661-4746-9bfe-48ae924f7804.png)

**Oniris io H**
![image](https://user-images.githubusercontent.com/15471688/193433232-134d158c-daa2-468e-aa21-19521c4766cd.png)

**Agilia H**
![image](https://user-images.githubusercontent.com/15471688/193433241-0d74312a-08af-4968-9c84-6fa460bd6410.png)

**Comment by iMicknl** [comment]
We are actually working to bring your `AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint` to core in https://github.com/home-assistant/core/pull/72790.

What if you set the HVAC mode to off? Doesn't this turn off your device?

**Comment by Desaydrone** [comment]
Hi,
Yes i can turn off when setting hvac mode, no problem, but when i use some integration they need an On/Off possibility, they can't use HVAC mode :'(

**Comment by iMicknl** [comment]
@Desaydrone the HVAC mode is the supported mode, thus I will see this as a feature request and not a bug.

You could use a template or script as a workaround where you call `climate.set_hvac_mode()`.
