### ISSUE TITLE
Bug when connected with Cozytouch ID

### ISSUE THREAD

**Issue by Biorgland** [iMicknl/ha-tahoma#821]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Hi,
When I try to connect to my Cozytouch account through Overkiz, there's always the same issue "wrong mail or password".
Even with master version of Tahoma or all solutions seen on the other threads, I cannot connect

### What version of this integration (ha-tahoma) has the issue?

master

### What version of Home Assistant Core has the issue?

22.10.1

### Which gateway / hub do you use?

Cozytouch

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Added device (Device...".
```

</details>

**Comment by iMicknl** [comment]
Which hardware do you have? Do you have a Navilink / Naviclim device by any chance? See https://github.com/home-assistant/core/issues/75394.

Please note that this integration is not maintained anymore, please try the core integration.

**Comment by Biorgland** [comment]
Ah I have not seen the other subjects on it. And Indeed I have a Navilink system so not compatible with the current solution.
Thanks
