### ISSUE TITLE
Hvac hitachi issue (error migration łafter update component and not recognized  oversik ha core

### ISSUE THREAD

**Issue by seblang** [iMicknl/ha-tahoma#827]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Hi Imicknl,

I have just upgrade may HA to the last version and the TAHOMA is not supported any more!
I have added the OVERKIZ intégration but unfortunatly I just acces to the room temperature!
It's not possible to set up a temperature or switch on/off etc.....like previously!
Can I copy past some file from the old intégration to solve my issue?

If I update previous integration I ha a migration issue! 

![Screenshot 2022-11-04 23 01 09](https://user-images.githubusercontent.com/11487773/200081982-d42eefcb-bc75-4f84-99c1-34fdc702056b.png)
![Screenshot 2022-11-04 23 01 24](https://user-images.githubusercontent.com/11487773/200081993-19073033-2c96-4ccd-b55a-cfa39a50d76f.png)

previously :

![Screenshot 2022-11-04 23 02 36](https://user-images.githubusercontent.com/11487773/200081954-4786ace3-4567-424e-ad1a-a25ed37bdab5.png)

see old issue
[Add support for AC RAK-50RXD - HitachiAirToAirHeatPump (hlrrwifi:HLinkMainController)](https://github.com/iMicknl/ha-tahoma/issues/445#top)
#445
[seblang](https://github.com/seblang) opened this issue on 18 May 2021 · 17 comments · Fixed by https://github.com/iMicknl/ha-tahoma/pull/364

### What version of this integration (ha-tahoma) has the issue?

2.XX

### What version of Home Assistant Core has the issue?

2.11.1

### Which gateway / hub do you use?

HI-KUMO

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Added device (Device...".
```

</details>

**Comment by seblang** [comment]
I have update the custom component to the last version..... And the integration say issue at configuration!

Logs:
Assistant
2022-11-05 13:34:19.063 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=tahoma>
2022-11-05 13:34:32.506 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=update.overkiz_by_somfy_custom_component_update, old_state=None, new_state=<state update.overkiz_by_somfy_custom_component_update=off; auto_update=False, installed_version=v2.13.1, in_progress=False, latest_version=v2.13.1, release_summary=None, release_url=https://github.com/iMicknl/ha-tahoma/releases/v2.13.1, skipped_version=None, title=None, entity_picture=https://brands.home-assistant.io/_/tahoma/icon.png, friendly_name=Overkiz (by Somfy) - Custom component update, supported_features=21 @ 2022-11-05T13:34:32.506277+01:00>>

**Comment by iMicknl** [comment]
@seblang did you update the custom component already?

**Comment by seblang** [comment]
Yes I am in v2.13.

Last year you have send me some file to add my  hvac (see https://github.com/iMicknl/ha-tahoma/pull/364). 
It was working until I upgrade to HA v2022. 11...... I have update custom components but I message migration issue with log I have shared with you previously. 
Thank you

**Comment by iMicknl** [comment]
@seblang please include your full log, the log above does not contain any errors. Just make sure you run the latest version of the ha-tahoma component, since there were some breaking changes in core.

**Comment by seblang** [comment]
Hello

juste done the update to V14 but issue stay

![Screenshot 2022-11-05 17 04 50](https://user-images.githubusercontent.com/11487773/200129416-341b76e0-edcd-4bb2-9389-f8001441c744.png)

sorry but there is no other log about tahoma in logs
![Screenshot 2022-11-05 17 07 33](https://user-images.githubusercontent.com/11487773/200129444-e4d6eb70-e6a3-4e1f-baa3-54daa1f385e7.png)

I have checked in my config.yaml the debug is activated.

In core overkiz, I see my HVAC but only the temperature . Enclose de file
[config_entry-overkiz-15727ac0f31600885e74331a1c9d201e.json.txt](https://github.com/iMicknl/ha-tahoma/files/9944245/config_entry-overkiz-15727ac0f31600885e74331a1c9d201e.json.txt)

**Comment by seblang** [comment]
@iMicknl 

Issue solved!
I have un-installed overkiz, un-installer Tahoma, restarted HA
Do a new installation of Tahoma and log in and it's work again
thank you for your help
