### ISSUE TITLE
Climate no more supported for CozyTouch in core Overkiz?

### ISSUE THREAD

**Issue by waazdakka** [iMicknl/ha-tahoma#828]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### Device information

Cozytouch bridge and electric heaters.

### Home Assistant log

Hello,
I understood we are forced to move to the core Overkiz integration (I assume this one ? https://www.home-assistant.io/integrations/overkiz) since 2022.11 HASS but now i read climate is not supported (yet?). 
I can't understand why this integration has been deprecated / deactivated by force while the core one has not the same abilities and entities.
I just can't understand why it's a repeating pattern with Home Assistant: when you're almost sure to have a stable system, there always is something to be broken for no reason... And it's really not WAF approved.
What are we supposed to do now? Going back to constructor app to manage our heaters? 🙄

**Comment by iMicknl** [comment]
@waazdakka thanks for your constructive feedback…

If your device is not supported in the core component yet, you can still use the custom component. I don’t see the issue here? Just update to the latest version of the custom component if you face issues with 2022.11.

**Comment by iMicknl** [comment]
Please include your diagnostics as well, so I have an idea which hardware you have and which hardware is not supported in core yet.

**Comment by eichenlauba** [comment]
Hi! Same problem here.. my Cosytouch pass is the only item supported by the core integration. My other heaters (Atlantic Calissia) seems not fully supported yet (sensors are present but no climate controls)
Have you an idea of when this type of heater gonna be supported? 
thanks for your help 🙏

**Comment by eichenlauba** [comment]
@iMicknl is it enough? 
![56DA78D3-1A5D-4A0D-8238-2218C4132B14](https://user-images.githubusercontent.com/6337122/200763579-1618da54-64d3-4800-81c7-c39c9985ab80.jpeg)

**Comment by tetienne** [comment]
Please click on "Télécharger les journaux". That’s the file we want.

**Comment by eichenlauba** [comment]
@iMicknl @tetienne here it is
[overkiz-77b846e3d159c694dc2fb89dc9cb2962-Radiateur-5da9e9c5939c04159f322ac6136217ca.json.txt](https://github.com/iMicknl/ha-tahoma/files/9968869/overkiz-77b846e3d159c694dc2fb89dc9cb2962-Radiateur-5da9e9c5939c04159f322ac6136217ca.json.txt)

**Comment by iMicknl** [comment]
@eichenlauba your `io:AtlanticElectricalHeaterWithAdjustableTemperatureSetpointIOComponent` is already merged into core and will be released with the next release (2022.12).

**Comment by waazdakka** [comment]
Hello @tetienne and @iMicknl, 

I assume you were a bit ironic 😅 It wasn't to criticize you and your work, it's just frustrating and incomprehensible when everything is working well then... decide to work no more :'( 

Thanks for your answer, so here are my logs :
[logs_cozytouch.zip](https://github.com/iMicknl/ha-tahoma/files/9968914/logs_cozytouch.zip)

I just miss the climate entities for the heaters, allowing me to control theme (power / temp etc.)...

Thanks for you for your work and your help!

**Comment by eichenlauba** [comment]
@iMicknl thanks for your help!

**Comment by iMicknl** [comment]
@waazdakka you have the same device. (`io:AtlanticElectricalHeaterWithAdjustableTemperatureSetpointIOComponent`), so the message above applies to you as well.

Regarding your feedback, you could just stay on ha-tahoma and you can still control your heaters, nothing changed. There was a breaking change in 2022.11, but this was fixed a day after the update. 

If you want to have your system as stable as possible, just wait a week until you update your Home Assistant and make sure you update all your custom components to the latest version.

**Comment by eichenlauba** [comment]
@iMicknl on custom integration, the fix work well but when an automation change my heaters preset mode, for some reason they are becoming unavailable.

After the preset change : 
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/6337122/200794816-6a40ce02-efc3-4b2c-b172-1344a1f638f8.png">
As you can see, my control is unavailable, but the informations about temperature, and others sensor are good.
