### ISSUE TITLE
Add current heating state as `hvac_action` for AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint

### ISSUE THREAD

**Issue by waazdakka** [iMicknl/ha-tahoma#829]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The request

I wonder if the heating state could be fetched from the server like the Cozytouch app is able?
First, I find that the integrated thermometers are not very accurate compared to the sensors that can be placed in the rooms. Then, if I want to manage the heaters completely by Home Assistant and no longer use the programming from the application, it could be interesting to know if the radiator is heating up or not in order to force the heating mode (by increasing the temperature target).
Is this data provided by when you retrieve the data from the server?
![heating_state](https://user-images.githubusercontent.com/9380081/202016784-ce2387f0-0908-43b4-9d3e-6a81b17ce233.jpeg)

Thanks!!

### Which gateway / hub do you use?

Cozytouch

### Device model (optional)

Bolero Auto B

**Comment by waazdakka** [comment]
@iMicknl Is that the logs you need?
[config_entry-tahoma-15e7d1b36f7cf6b7c4c3d84c1c6a8852.json.txt](https://github.com/iMicknl/ha-tahoma/files/10020603/config_entry-tahoma-15e7d1b36f7cf6b7c4c3d84c1c6a8852.json.txt)
Yes I submitted it here because I'm not sure of where to post on the core git

**Comment by waazdakka** [comment]
Maybe I'm missing something but I don't see anything related to the state (the colomn "state" displays the hvac mode but not the heating-or-not state)

<img width="1289" alt="Capture d’écran 2022-11-16 à 12 47 50" src="https://user-images.githubusercontent.com/9380081/202172761-09f5538c-52d1-4592-893c-5bedaad7838d.png">

I will follow the integration to the core of course! :D

**Comment by iMicknl** [comment]
@waazdakka please try the core integration. From this Wednesday, the public beta of 2022.12 will support your device.

If your hvac_action is not exposed and you miss this functionality, please create an issue in core adding your diagnostic log (from core).

**Comment by iMicknl** [comment]
You can create an issue at https://github.com/home-assistant/core/issues, if you still face issues with 2022.12.
