### ISSUE TITLE
Can't change settings on Tahoma/Hitachi AC

### ISSUE THREAD

**Issue by BOSSoNe0013** [iMicknl/ha-tahoma#831]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Each times i try to change some settings of my air conditioner (temperature, mode, etc...) i've got an error with the fan speed

### What version of this integration (ha-tahoma) has the issue?

2.14.0

### What version of Home Assistant Core has the issue?

core-2022-11-4

### Which gateway / hub do you use?

Somfy TaHoma

### Device model

HitachiAirToAirHeatPump

### Home Assistant log

<details><summary>Logs</summary>

```
Logger: custom_components.tahoma
Source: custom_components/tahoma/executor.py:73
Integration: Overkiz (by Somfy) - Custom component
First occurred: 13:42:40 (3 occurrences) Last logged: 13:51:10
globalControl() : Invalid value for command parameter p3 : expected string value (auto, hi, med, lo, silent) but got low (String)
```

</details>

**Comment by iMicknl** [comment]
Thanks for reporting @BOSSoNe0013. We will need to look into this when we are porting this device to core, however I won't be able to do that this year anymore due to my holidays.

**Comment by BOSSoNe0013** [comment]
Problem still present in 2023.1.6

**Comment by BOSSoNe0013** [comment]
Problem still present in 2023.2.5

**Comment by iMicknl** [comment]
@BOSSoNe0013 can you add me on Discord? (iMick#1903). Let's have a look.

**Comment by BOSSoNe0013** [comment]
> @BOSSoNe0013 can you add me on Discord? (iMick#1903). Let's have a look.

done :)
