### ISSUE TITLE
Atlantic Explorer v4 Cozytouch bridge away mode don't work

### ISSUE THREAD

**Issue by Step-han** [iMicknl/ha-tahoma#833]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I've got 2 entities to control the explorer v4.

Boost mode & away mode.

Boost mode works fine, but the away mode does nothing. With the cold weather I want to control the pump with boost mode and away mode. Set is to away 'always' and let HA set it to boost to heat the water to a target level and set it back to away again after the temp is reached.

![image](https://user-images.githubusercontent.com/54219681/205347775-ae9500a6-9ce7-4fed-a117-04064f61e945.png)

The slider don't work and I see no error or something in the logs. 

If i set it to 1 it goes automatic back to 0

![image](https://user-images.githubusercontent.com/54219681/205348202-251389d6-3689-4823-acff-cc021fc426ad.png)

### What version of this integration (ha-tahoma) has the issue?

2.14.0

### What version of Home Assistant Core has the issue?

2022.11.2

### Which gateway / hub do you use?

Cozytouch

### Device model

AtlanticDomesticHotWaterProductionV2_CV4E_IOComponent

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Added device (Device...".
```

</details>

**Comment by iMicknl** [comment]
@Step-han could you try the Overkiz integration from core? If you face the same issue, you can create an issue there and include your diagnostics information. This integration does not receive many updates anymore, we mainly focus on the core integration at the moment.

**Comment by Step-han** [comment]
@iMicknl thanks for your reply

I have deleted the intergration from /config/custom_componens, rebooted HA and installed the cozytouch core intergration (via Overkiz). Same behavior.

Where do I need to make a new issue?

**Comment by iMicknl** [comment]
Here https://github.com/home-assistant/core/issues
