### ISSUE TITLE
Authentification non valide with Cozytouch

### ISSUE THREAD

**Issue by nicog2** [iMicknl/ha-tahoma#834]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

After an update from Thermor, Atlantic, Sauter on Cozytouch, the authentification does not work for new user. 

I have the help service at phone, and he said to me: "We migrated accounts from one database to another and improved connection security"

### What version of this integration (ha-tahoma) has the issue?

Home Assistant 2022.11.5

### What version of Home Assistant Core has the issue?

Supervisor 2022.11.2

### Which gateway / hub do you use?

Cozytouch

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Added device (Device...".
```

</details>

**Comment by iMicknl** [comment]
We have already migrated to this new authentication server in Overkiz in core. Please upgrade to 2022.12 (public beta) or wait for the release of 2022.12. 

This ha-tahoma integration is currently less maintained since we are working on migrating all the bits to core.
