### ISSUE TITLE
Atlantic doesn't switch to unavailable state

### ISSUE THREAD

**Issue by merlin-zaraza** [iMicknl/ha-tahoma#835]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

When Atlantic boiler became unavailable (e.g. connection lost, power off) there is no indication of this state in device and sensors.

### What version of this integration (ha-tahoma) has the issue?

2.14.0

### What version of Home Assistant Core has the issue?

2023.1.2

### Which gateway / hub do you use?

Cozytouch Sauter

### Device model

Atlantic

**Comment by iMicknl** [comment]
Are you sure that this is supported by the official vendor app? (e.g. CozyTouch). We already implement this for devices that support this.

By the way; we don’t maintain this integration anymore, best would be to try the component in core (remove the custom component first).

**Comment by merlin-zaraza** [comment]
All I know that CozyTouch app can tell me that my device is offline, so I hope device support it. Anyway, will try core component. Any recommendations on migration? Thanks

**Comment by iMicknl** [comment]
@merlin-zaraza please remove the integration manually on your integrations page + remove the custom components/tahoma folder. Reboot and select CozyTouch (or Overkiz).

If this issue still occurs, please create an issue on the Home Assistant core repo and add your diagnostics logs when a device is unavailable in the app (+ screenshot), but not in HA.
