### ISSUE TITLE
Failed to set up (probably) since core 2023.5

### ISSUE THREAD

**Issue by r-jean-pierre** [iMicknl/ha-tahoma#843]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Did not noticed at first sigh but (maybe) since core 2023.5b1 to today core 2023.5b5 the integration failed to setup and throw

File "/config/custom_components/tahoma/__init__.py", line 140, in async_setup_entry

entities are still there but with no data

### What version of this integration (ha-tahoma) has the issue?

v2.14.0

### What version of Home Assistant Core has the issue?

2023.5.0b5

### Which gateway / hub do you use?

Cozytouch

### Home Assistant log

<details><summary>Logs</summary>

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tahoma/__init__.py", line 140, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, SUPPORTED_PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

</details>

**Comment by iMicknl** [comment]
@r-jean-pierre is there a reason why you can't upgrade to the core component yet?

It seems there has been a breaking change which we would need to fix in the custom component.

**Comment by r-jean-pierre** [comment]
> @r-jean-pierre is there a reason why you can't upgrade to the core component yet?
> 
> It seems there has been a breaking change which we would need to fix in the custom component.

Hi,

Well, for me, with my best motivation, i cannot got the "all-in-one-entity" which controls the heater by using the core component.
For example, there is a custom lovelace "custom:simple-thermostat" which creates this:
![image](https://user-images.githubusercontent.com/9727894/235850676-3fc28d61-4ed1-4e42-b021-df47e959bbc0.png)

Based on a "climate-xxxxxx" entity 
This entity is present in the custom integration but not in the core

![image](https://user-images.githubusercontent.com/9727894/235851424-3a4bbc56-55af-469d-a5c1-9de00869a1ef.png)
To resume, the "Controls" is missing in the core

I gave some trials with the new way of doing it, at a certain period it was even possible to have both working at the same time, but definitively, I always had better success with the custom rather than the "official" one

**Comment by iMicknl** [comment]
If the controls is missing in core, that means your device is not fully supported yet. Which device do you have and does it fully work in custom? (before this update)

**Comment by r-jean-pierre** [comment]
I have 3 heaters "IPALA H BLC" by Sauter (from Atlantic Group) connected via Cozytouch
and 1 towel dryer+heater "ASAMA Connect" also Sauter/Atlantic

The 4 of them worked in any previous version of HA core with the custom-integration, never had problems

**Comment by yllar** [comment]
+1 
My device is exposed to custom component as io:AtlanticPassAPCHeatPumpMainComponent  (Atlantic Alfea Excellia A.I TRI 16)

**Comment by vlebourl** [comment]
Not sure if it's related but the async_setup_entries function has been deprecated preventing the custom component to load...

**Comment by theggz** [comment]
Hi ! Same behavior here since the upgrade (2023.5.1) :

```
Logger: homeassistant.config_entries
Source: custom_components/tahoma/__init__.py:140
Integration: Overkiz (by Somfy) - Custom component
First occurred: 08:16:03 (2 occurrences)
Last logged: 08:19:01

Error setting up entry guillaume.scheidt@gmail.com for tahoma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tahoma/__init__.py", line 140, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, SUPPORTED_PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

I keep the custom integration because my thermostat is not yet fully supported in the core integration (ovp:SomfyHeatingTemperatureInterfaceOVPComponent).

**Comment by Jejebond** [comment]
Hi ! Same here, but i'm missing Somfy Thermostat V2 and Somfy Valve Heating controls on Core components, i've created an issue about this.

```
[homeassistant.config_entries] Error setting up entry xxxxxxxxxx@gmail.com for tahoma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tahoma/__init__.py", line 140, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, SUPPORTED_PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by iMicknl** [comment]
@r-jean-pierre both of your devices should be fully supported in Home Assistant core. Upgrade to the latest version and create an issue on core GitHub if your device is not supported.

@yllar you can follow https://github.com/home-assistant/core/issues/89537 for AtlanticPassAPCHeatPump (io:AtlanticPassAPCHeatPumpMainComponent).

@theggz you can create a new issue on GitHub core for SomfyHeatingTemperatureInterfaceOVPComponent, so we can track it there.
