### ISSUE TITLE
Integration broken after latest App update of Cozytouch

### ISSUE THREAD

**Issue by thundergreen** [iMicknl/ha-tahoma#847]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Integration setup  fails with error:

Translation Error: The intl string context  .....

unfortunately it is not in debug when trying to setup the integration.

### What version of this integration (ha-tahoma) has the issue?

2.15.0

### What version of Home Assistant Core has the issue?

2023.6.2

### Which gateway / hub do you use?

Cozytouch

### Home Assistant log

<details><summary>Logs</summary>

```
Translation Error: The intl string context  .....

```

</details>

**Comment by iMicknl** [comment]
Please add the full error log, this is too short to give any context.

Can't you use the core integration yet? I don't seen an issue in core open under your name anymore.

**Comment by thundergreen** [comment]
The crazy thing is I don't see any error message in logs even with debug
enabled

Mick Vleeshouwer ***@***.***> schrieb am Fr., 16. Juni 2023,
16:05:

**Comment by iMicknl** [comment]
@thundergreen in that case copy the full error you get in the Config Flow (when you set it up). You only copied like 4 words, which makes it hard to debug...

Which language do you use in HA?
Why don't you use the core component (see question in previous message).

**Comment by MindFreeze** [comment]
I had the same strange error and got "Invalid authentication" when I tried to reconfigure. Tried switching to the ha-core component and now the error is "Your CozyTouch hardware is not supported by this integration.".

It worked fine a couple of days ago but broke with a recent update. Tried Overkiz v2.14.0 and still get "Invalid authentication"

**Comment by MindFreeze** [comment]
Related link to hardware support request in core https://github.com/home-assistant/core/issues/94544

**Comment by iMicknl** [comment]
Please reopen / create a new issue if this hasn't been fixed with the latest ha-tahoma update.
