### ISSUE TITLE
Support multiple types of boxes with different API endpoints.

### ISSUE THREAD

**Issue by vlebourl** [iMicknl/ha-tahoma#85]
**Is your feature request related to a problem? Please describe.**

RTS Connexoon box isn't compatible with this integration so far.

**Describe the solution you'd like**

Add support for multiple API endpoints like in https://github.com/dubocr/homebridge-tahoma/blob/master/overkiz-api.js

**Comment by iMicknl** [comment]
@vlebourl it looks like the Connexoon boxes are compatible nowadays? Looks like the urls mentioned here are the old API platforms.

Shall we close this one?

**Comment by vlebourl** [comment]
let's close it for now, we'll reopen if needed.
