### ISSUE TITLE
Add support for ModelName (io:SomfySensorName)

### ISSUE THREAD

**Issue by ferhke** [iMicknl/ha-tahoma#852]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### Device information

Event(name=<EventName.DEVICE_STATE_CHANGED: 'DeviceStateChangedEvent'>, timestamp=1695304340557, setupoid=_CountingAttr(counter=325, _default=None, repr=<function obfuscate_id at 0xffff6c21e700>, eq=True, order=True, hash=None, init=True, on_setattr=None, alias=None, metadata={}), owner_key=None, type=None, sub_type=None, time_to_next_state=None, failed_commands=None, failure_type_code=None, failure_type=None, condition_groupoid=None, place_oid=None, label=None, metadata=None, camera_id=None, deleted_raw_devices_count=None, protocol_type=None, gateway_id=None, exec_id=None, device_url=internal://****-****-3567/uPodNetwork/0, device_states=[EventState(name='core:RSSILevelState', type=<DataType.INTEGER: 1>, value=-42)], old_state=None, new_state=None)

### Home Assistant log

Event(name=<EventName.DEVICE_STATE_CHANGED: 'DeviceStateChangedEvent'>, timestamp=1695304340557, setupoid=_CountingAttr(counter=325, _default=None, repr=<function obfuscate_id at 0xffff6c21e700>, eq=True, order=True, hash=None, init=True, on_setattr=None, alias=None, metadata={}), owner_key=None, type=None, sub_type=None, time_to_next_state=None, failed_commands=None, failure_type_code=None, failure_type=None, condition_groupoid=None, place_oid=None, label=None, metadata=None, camera_id=None, deleted_raw_devices_count=None, protocol_type=None, gateway_id=None, exec_id=None, device_url=internal://****-****-3567/uPodNetwork/0, device_states=[EventState(name='core:RSSILevelState', type=<DataType.INTEGER: 1>, value=-42)], old_state=None, new_state=None)

### Device commands

Event(name=<EventName.DEVICE_STATE_CHANGED: 'DeviceStateChangedEvent'>, timestamp=1695304340557, setupoid=_CountingAttr(counter=325, _default=None, repr=<function obfuscate_id at 0xffff6c21e700>, eq=True, order=True, hash=None, init=True, on_setattr=None, alias=None, metadata={}), owner_key=None, type=None, sub_type=None, time_to_next_state=None, failed_commands=None, failure_type_code=None, failure_type=None, condition_groupoid=None, place_oid=None, label=None, metadata=None, camera_id=None, deleted_raw_devices_count=None, protocol_type=None, gateway_id=None, exec_id=None, device_url=internal://****-****-3567/uPodNetwork/0, device_states=[EventState(name='core:RSSILevelState', type=<DataType.INTEGER: 1>, value=-42)], old_state=None, new_state=None)

**Comment by iMicknl** [comment]
@ferhke what is your request? There is just log information in your issue, which doesn't tell us much.

Have you tried using Overkiz integration from core?
