### ISSUE TITLE
Set step to 0.5 instead of 1 (Hitachi Hi-Kumo)

### ISSUE THREAD

**Issue by SeeDborg** [iMicknl/ha-tahoma#855]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The request

I still use this integration because the official one does not provide a climate entity for my Hitachi Heat Pump...
I would like to have a step of 0.5°C instead of 1°C to set the temperature, would it be possible please ?

### Which gateway / hub do you use?

Hi Box

### Device type (optional)

Micrologiciel : 2022.6.4

**Comment by iMicknl** [comment]
@SeeDborg did you create an issue for this on the core repository? Happy to see if we can merge this to core and fix your issue.

The device (https://github.com/iMicknl/ha-tahoma/blob/master/custom_components/tahoma/water_heater_devices/hitachi_dhw.py#L36) looks fairly simple.

**Comment by SeeDborg** [comment]
No I did not

**Comment by SeeDborg** [comment]
I see that many issues have been created on the core repository but I'm not sure you can see them.

I'm now desperate because with the latest version of HA, I can't use this version, and the new Overkiz component in main does not create any useful entities for my Heatpump... (Hi-Kumo Europe here)

**Comment by iMicknl** [comment]
Happy to have a look after my holidays (in 4 weeks). Please remind me afterwards and I can see if I can prioritize this device.

**Comment by SeeDborg** [comment]
OK, thank you so much, I'll get in touch in 4 weeks !
I'll try to summarize all the issues with the device. I'll be available to help, if needed.
Enjoy your holiday :)

**Comment by SeeDborg** [comment]
Since you updates the component, maybe are you available now ?
In the new Overkiz component, there is no useful entity created when I connect Hi-Kumo (only empty ones)

And here are the things that are not working with my Hi-Kumo Hitachi heatpump, with old ha-tahoma component :

- I can't increase the temperature by 0.5°C, only by 1°C. Increasing by 0.5 is possible on the heatpump and in Hi-Kumo so I assume it's possible with the Overkiz component too.
- The room temperature is always indicated as the next round number. For example if the room temperature indicated by the Heatpump is 19.8°C, the component in HA indicated 20°C.
- It's not possible to have the instant or the daily energy consumption. Only the total of energy since the component was installed.

I let you tell me how I can be of any help :)

**Comment by iMicknl** [comment]
@SeeDborg can you contact me via Discord? This component is already present in Home Assistant core... So not sure what your issue is?

**Comment by SeeDborg** [comment]
The official component in assistant core creates no entity, only empty ones...
I'll contact you via Discord.
