### ISSUE TITLE
Can't install on 2024.11.0

### ISSUE THREAD

**Issue by SeeDborg** [iMicknl/ha-tahoma#856]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I got this message error :
![image](https://github.com/user-attachments/assets/69891c8c-2b3e-4c51-82c3-8d6bf20d1747)

### What version of this integration (ha-tahoma) has the issue?

latest

### What version of Home Assistant Core has the issue?

2024.11.0

### Which gateway / hub do you use?

Hi Kumo

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Added device (Device...".
```

</details>

**Comment by nicomillerioux18** [comment]
même problème ici...

**Comment by SeeDborg** [comment]
And I can't use the new official integration because it does not provide any useful entities for my HeatPump... 😭

**Comment by iMicknl** [comment]
This is a known issue indeed and this won't be fixed unfortunately. When we have migrated all entities from this repository, we will archive this repository as well.

I am aware of your open issues on core, but the only option would be to wait until this has been added to core unfortunately.
