### ISSUE TITLE
Make assumed_state for RTS configurable via option flow

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#9]
Current behaviour is that `assumed_state` is `True` for all rts devices, since RTS doesn't have a feedback function.

However, when you are only controlling your RTS devices via Home Assistant, some people don't want to have this optimistic mode.

**Comment by iMicknl** [comment]
A setting is not needed, can be tweaked already via core. https://www.home-assistant.io/docs/configuration/customizing-devices/#assumed_state

**Comment by vlebourl** [comment]
Tested and works as expected with `customize.yaml`.

**Comment by iMicknl** [comment]
@vlebourl great! We need to add it to the README at some point, same for the device class that could be changes via customize.yaml.

**Comment by vlebourl** [comment]
We can add it to the README, although it's a standard feature of HA, every entity can be customized. Not sure whether we should be that thorough in our README.
