### ISSUE TITLE
Covers move step by step and can't be stopped while moving

### ISSUE THREAD

**Issue by rabesocke** [iMicknl/ha-tahoma#90]
**Describe the bug**
I have two problems with version 1.4. At the moment I switched back to version 1.3.

- The covers can't be stopped while they are moving. They move all the way down and don't respond to the stop button.
- By activating a scene with several covers all covers move one by one. The first cover moves and when that one is finished the next cover moves. Until version 1.3 all covers moves all together.

**To Reproduce**
1. Move a cover and click the stop button - the cover do not respond to that click

or

1. Create a scene with several covers.
2. Activate the scene

**Expected behavior**
- The cover stops by clicking the stop button while moving
- All covers should move together (and not one by one)

**Screenshots**
No screenshot

**Environment (please complete the following information):**
 - **Home Assistant version:** 0.111.4
 - **Platform**: cover

**Device:** (if your problem is related to a specific device)
 - **Model**: PositionableRollerShutter
 - **Type**: io:RollerShutterGenericIOComponent
 - **Device details**
no further details

**Additional context**
No additional context necessary

**Comment by vlebourl** [comment]
thank you for your report. we'll have a look rapidly. 
@Mick regarding the second issue, I think this is related to the addition of the wait to the apply_action. could an async function allow to keep the wait while sending several commands without waiting for the previous ones to finish?

**Comment by vlebourl** [comment]
small comment, it would be preferable to open 2 separate issues. Thanks a lot :)
