### ISSUE TITLE
custom_components.tahoma.config_flow - Unexpected exception - ValueError: No ui Class

### ISSUE THREAD

**Issue by jensihnow** [iMicknl/ha-tahoma#99]
**Describe the bug**

Found this custom integration while searching for issues related to https://github.com/home-assistant/core/issues/37291.
Anyways, haven't used it before and running into a config_flow issue after submitting my credentials: 

> [%key:common::config_flow::error::unknown%]

**To Reproduce**
1. Go to Integrations and add the integration
2. Click on submit after inserting credentials
3. See error

**Expected behavior**

With this error I'm unable to activate/configure the component. 

**Screenshots**

![grafik](https://user-images.githubusercontent.com/1306057/86389753-1ebce180-bc97-11ea-92e4-a4dc3e1a8dc5.png)

**Environment (please complete the following information):**
 - **Home Assistant version:** 0.112.0
 - **Platform**: -

**Device:** -
 - **Model**: -
 - **Type**: zwave:ZWaveOccupancySensor

 - **Device details**
_Please follow the instructions here: https://github.com/totalimmersion/com.somfy.tahoma/files/2755935/Instructions.for.the.TaHoma.devices.pdf to gather more details of the device and post them below_

```json
("No ui Class: " + debug_output)
ValueError: No ui Class: {
"creationTime": 1472213846000, 
"lastUpdateTime": 1472213846000, 
"label": "ZWAVE (2#1)", 
"deviceURL": "zwave://xxxx-xxxx-xxxx/2#1", 
"shortcut": false, 
"controllableName": "zwave:ZWaveOccupancySensor", 
"definition": {"commands": [], "states": [], "dataProperties": [], "qualifiedName": "zwave:ZWaveOccupancySensor", "type": "UNKNOWN"},
"available": false, "enabled": true, "placeOID": "xxx", "type": 0, "oid": "xxx-xxx-xxx-xxx-xxx"}
```

**Additional context**

Exception:

```2020-07-02 18:58:04 ERROR (MainThread) [custom_components.tahoma.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/tahoma/config_flow.py", line 92, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/tahoma/config_flow.py", line 48, in validate_input
    await hass.async_add_executor_job(controller.get_setup)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tahoma/tahoma_api.py", line 238, in get_setup
    self._get_setup(result)
  File "/config/custom_components/tahoma/tahoma_api.py", line 248, in _get_setup
    device = Device(self, device_data)
  File "/config/custom_components/tahoma/tahoma_api.py", line 615, in __init__
    raise ValueError("No ui Class: " + debug_output)
ValueError: No ui Class: {
"creationTime": 1472213846000, 
"lastUpdateTime": 1472213846000, 
"label": "ZWAVE (2#1)", 
"deviceURL": "zwave://xxxx-xxxx-xxxx/2#1", 
"shortcut": false, 
"controllableName": "zwave:ZWaveOccupancySensor", 
"definition": {"commands": [], "states": [], "dataProperties": [], "qualifiedName": "zwave:ZWaveOccupancySensor", "type": "UNKNOWN"},
"available": false, "enabled": true, "placeOID": "xxx", "type": 0, "oid": "xxx-xxx-xxx-xxx-xxx"}```

**Comment by vlebourl** [comment]
Thanks for the report, I'll have a look tomorrow!

**Comment by vlebourl** [comment]
We actually weren't planning on supporting zwave devices as there is a native zWave integration in HA. But I guess it could change.

**Comment by jensihnow** [comment]
I actually don’t care about the zWave support, it just broke my setup of the integration. Thanks!

**Comment by iMicknl** [comment]
@vlebourl this issue is probably introduced by adding climate to the config flow. Would be good to check there loosely for `uiclass`. Didn't know that uiclass could be empty.

**Comment by vlebourl** [comment]
Sorry if I got misunderstood. I was not implying I wouldn't fix it. IMHO, this is a misbehaving of the API that should raise exception at that stage.

**Comment by vlebourl** [comment]
can you try branch [fix-99](https://github.com/iMicknl/ha-tahoma/archive/fix-99.zip)?

**Comment by jensihnow** [comment]
Just to confirm, switched over to your custom integration without any issues a few minutes ago. Minor piece was io:SomfyContactIOSystemSensor sensor switching from sensor to binary_sensor. Guess this is a breaking change when this one will be released.

**Comment by iMicknl** [comment]
> Just to confirm, switched over to your custom integration without any issues a few minutes ago. Minor piece was io:SomfyContactIOSystemSensor sensor switching from sensor to binary_sensor. Guess this is a breaking change when this one will be released.

Great to hear! Indeed that is marked as a change in our changelog, when it will be published to core, we will list the breaking changes for sure. :)
